import{it,expect,vi}from'vitest';import{checkpointWordJobs,pendingWordIds,resumeWordCheckpoint}from'./local_index_resume';
import{createWordResumeRunner}from'./local_index_resume';
it('defers reads during input and preserves the checkpoint for later resume',async()=>{const s=storage();checkpointWordJobs(s,'user:A',[job]);const getBook=vi.fn(async(id:string)=>({id,title:'Word'})),enqueue=vi.fn();let allowed=false;const options={storage:s,scope:()=> 'user:A',getBook,isWord:()=>true,ready:async()=>false,enqueue,canRun:()=>allowed};await resumeWordCheckpoint(options);expect(getBook).not.toHaveBeenCalled();expect(pendingWordIds(s,'user:A')).toEqual(['word1']);allowed=true;await resumeWordCheckpoint(options);expect(getBook).toHaveBeenCalledOnce();expect(enqueue).toHaveBeenCalledOnce()});
it('runs B after pending A and does not lose a same-scope invalidation',async()=>{let scope='A',release!:()=>void;const seen:string[]=[];const run=vi.fn(async(owner:string)=>{seen.push(owner);if(seen.length===1)await new Promise<void>(r=>release=r)});const resume=createWordResumeRunner({scope:()=>scope,run});const a=resume();scope='B';const b=resume();release();await Promise.all([a,b]);expect(seen).toEqual(['A','B']);let finish!:()=>void;let count=0;const same=createWordResumeRunner({scope:()=>scope,run:async()=>{count++;if(count===1)await new Promise<void>(r=>finish=r)}});const first=same();same();finish();await first;expect(count).toBe(2)});
function storage(){const data=new Map<string,string>();return{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v)},removeItem:(k:string)=>{data.delete(k)}}}
const job={bookId:'word1',title:'Private title not persisted',ownerScope:'user:A',state:'running' as const,etaMs:null,completedUnits:0,totalUnits:1 as const};
it('reload resumes pending IDs only and drops already fingerprint-ready entries',async()=>{const s=storage();checkpointWordJobs(s,'user:A',[job]);const enqueue=vi.fn();expect(pendingWordIds(s,'user:A')).toEqual(['word1']);await resumeWordCheckpoint({storage:s,scope:()=> 'user:A',getBook:async id=>({id,title:'Word',originalSha256:'revision1'}),isWord:()=>true,ready:async()=>false,enqueue});expect(enqueue).toHaveBeenCalledWith('word1','Word','user:A','revision1');await resumeWordCheckpoint({storage:s,scope:()=> 'user:A',getBook:async id=>({id,title:'Word'}),isWord:()=>true,ready:async()=>true,enqueue});expect(pendingWordIds(s,'user:A')).toEqual([])});
it('capacity error preserves the previous checkpoint without truncating it',()=>{const s=storage();checkpointWordJobs(s,'user:A',[job]);expect(()=>checkpointWordJobs(s,'user:A',Array.from({length:4097},(_,i)=>({...job,bookId:`extra${i}`})))).toThrow('local_index_checkpoint_capacity');expect(pendingWordIds(s,'user:A')).toEqual(['word1'])});
it('does not read A checkpoint as B and stops after identity changes during await',async()=>{const s=storage();checkpointWordJobs(s,'user:A',[job]);expect(pendingWordIds(s,'user:B')).toEqual([]);let scope='user:A';const enqueue=vi.fn();await resumeWordCheckpoint({storage:s,scope:()=>scope,getBook:async id=>{scope='user:B';return{id,title:'Private A'}},isWord:()=>true,ready:async()=>false,enqueue});expect(enqueue).not.toHaveBeenCalled();expect(pendingWordIds(s,'user:A')).toEqual(['word1'])});
