import{it,expect,vi}from'vitest';import{LocalIndexJobs}from'./local_index_jobs';
const tick=()=>new Promise(r=>setTimeout(r,15));
it('does not enqueue a late import under the newly selected identity',()=>{const jobs=new LocalIndexJobs({scope:()=> 'user:B',run:vi.fn()});jobs.enqueue('a','A private title','user:A');expect(jobs.snapshot()).toEqual([])});
it('queues without delaying reading and completes with honest unknown ETA',async()=>{let finish!:()=>void;const run=vi.fn(()=>new Promise<void>(r=>finish=r));const jobs=new LocalIndexJobs({scope:()=> 'account:a',run});jobs.enqueue('book','Title');expect(jobs.snapshot()[0]?.state).toBe('queued');expect(run).not.toHaveBeenCalled();await tick();expect(jobs.snapshot()[0]?.state).toBe('running');expect(jobs.snapshot()[0]?.etaMs).toBeNull();finish();await tick();expect(jobs.snapshot()[0]?.state).toBe('complete')});
it('isolates identical IDs across accounts and suppresses late completion',async()=>{let scope='account:a',finish!:()=>void;const done=vi.fn();const jobs=new LocalIndexJobs({scope:()=>scope,run:()=>new Promise<void>(r=>finish=r),completed:done});jobs.enqueue('same','Private A');await tick();scope='guest:b';jobs.identityChanged();expect(jobs.snapshot()).toEqual([]);finish();await tick();expect(done).not.toHaveBeenCalled();jobs.dispose()});
it('records failure without raw errors and allows retry',async()=>{const run=vi.fn().mockRejectedValueOnce(Error('private secret raw')).mockResolvedValue(undefined);const jobs=new LocalIndexJobs({scope:()=> 'guest:a',run});jobs.enqueue('b','B');await tick();expect(jobs.snapshot()[0]?.state).toBe('failed');expect(JSON.stringify(jobs.snapshot())).not.toContain('secret');jobs.enqueue('b','B');await tick();expect(jobs.snapshot()[0]?.state).toBe('complete')});
it('cancels a stalled task by deadline without declaring completion',async()=>{const jobs=new LocalIndexJobs({scope:()=> 'guest:a',run:()=>new Promise(()=>{}),timeoutMs:5});jobs.enqueue('b','B');await vi.waitFor(()=>expect(jobs.snapshot()[0]?.state).toBe('failed'));jobs.dispose()});

it('holds queued work while input is active and resumes without losing the job',async()=>{const run=vi.fn(async()=>{}),jobs=new LocalIndexJobs({scope:()=> 'guest:a',run});jobs.setPaused(true);jobs.enqueue('b','B');await tick();expect(run).not.toHaveBeenCalled();expect(jobs.snapshot()[0]?.state).toBe('queued');jobs.setPaused(false);await tick();expect(run).toHaveBeenCalledOnce();expect(jobs.snapshot()[0]?.state).toBe('complete');jobs.dispose()});
it('aborts active work and requeues even if the dialog closes before the abort settles',async()=>{const run=vi.fn().mockImplementationOnce(()=>new Promise(()=>{})).mockResolvedValue(undefined),done=vi.fn(),jobs=new LocalIndexJobs({scope:()=> 'guest:a',run,completed:done});jobs.enqueue('b','B');await tick();jobs.setPaused(true);jobs.setPaused(false);await vi.waitFor(()=>expect(jobs.snapshot()[0]?.state).toBe('complete'));expect(run).toHaveBeenCalledTimes(2);expect(done).toHaveBeenCalledOnce();jobs.dispose()});
