export interface LocalIndexJob {bookId:string;title:string;ownerScope:string;state:'queued'|'running'|'complete'|'failed';etaMs:null;completedUnits:number;totalUnits:1;revision?:string}
/** Session-local queue; search content stays in the existing owner-scoped index. */
export class LocalIndexJobs {
 private jobs=new Map<string,LocalIndexJob>();private listeners=new Set<()=>void>();private running=false;private controller:AbortController|undefined;private disposed=false;
 constructor(private options:{scope:()=>string;run:(bookId:string,signal:AbortSignal)=>Promise<unknown>;completed?:(job:LocalIndexJob)=>void;timeoutMs?:number}){}
 snapshot():LocalIndexJob[]{const scope=this.options.scope();return [...this.jobs.values()].filter(j=>j.ownerScope===scope).map(j=>({...j}))}
 subscribe(fn:()=>void):()=>void{this.listeners.add(fn);return()=>{this.listeners.delete(fn)}}
 private emit(){for(const fn of this.listeners)fn()}
 enqueue(bookId:string,title:string,expectedScope=this.options.scope(),options:{revision?:string;recheck?:boolean}={}):void{if(this.disposed||expectedScope!==this.options.scope())return;const ownerScope=expectedScope,key=JSON.stringify([ownerScope,bookId]),old=this.jobs.get(key);if(old&&old.state!=='failed'&&old.revision===options.revision&&!(options.recheck&&old.state==='complete'))return;if(old?.state==='running')this.controller?.abort();this.jobs.set(key,{bookId,title,ownerScope,state:'queued',etaMs:null,completedUnits:0,totalUnits:1,...(options.revision?{revision:options.revision}:{})});this.emit();setTimeout(()=>void this.pump(),0)}
 identityChanged():void{this.controller?.abort();for(const job of this.jobs.values())if(job.ownerScope!==this.options.scope()&&(job.state==='queued'||job.state==='running'))job.state='failed';this.emit()}
 dispose():void{this.disposed=true;this.controller?.abort();this.listeners.clear()}
 private async pump(){if(this.running||this.disposed)return;this.running=true;try{for(;;){const job=[...this.jobs.values()].find(j=>j.ownerScope===this.options.scope()&&j.state==='queued');if(!job||this.disposed)break;const controller=new AbortController();this.controller=controller;job.state='running';this.emit();let timer:ReturnType<typeof setTimeout>|undefined;let abort:()=>void=()=>{};try{const interrupted=new Promise<never>((_,reject)=>{abort=()=>reject(new DOMException('Index cancelled','AbortError'));controller.signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>controller.abort(),this.options.timeoutMs??180_000)});await Promise.race([Promise.resolve().then(()=>this.options.run(job.bookId,controller.signal)),interrupted]);if(controller.signal.aborted||job.ownerScope!==this.options.scope()||this.disposed)throw Error('invalidated');job.state='complete';job.completedUnits=1;this.options.completed?.({...job})}catch{job.state='failed'}finally{if(timer)clearTimeout(timer);controller.signal.removeEventListener('abort',abort);this.controller=undefined;this.emit()}await new Promise(r=>setTimeout(r,0))}}finally{this.running=false}}
}
