# تدقيق التصميم — الجزء 01: الدستور، الهيكل العام، القارئ والروابط

> النطاق المقروء كاملًا: `01-design-constitution.md`، و`1- الخزانة - الهيكل العام (مستقل).html`، و`2+3+4- الخزانة - القارئ والروابط (مستقل).html`.  
> الأصل عند التعارض: التطبيق الحالي في `app/`. هذا الملف سجل فجوات، وليس تفويضًا لتغيير سلوك قائم.  
> الحالة: **منفذ** = مسار فعلي قابل للاستخدام، **جزئي** = أصل موجود لكن العقد التصميمي غير مكتمل، **غير منفذ** = لا يوجد مسار منتج مطابق، **قرار مفتوح** = يحتاج حسم منتج/بيانات.

## خلاصة تنفيذية

- القشرة الفعلية تملك Header، بحثًا حيًا، BottomNav بثلاث بوابات، سمات، اتصالًا، حالات عامة، RTL وإتاحة جيدة؛ لكن Header المكتب يخالف حصر المستوى الأعلى في البوابات الثلاث إذ يعرض ست وجهات مستقلة.
- القارئ الفعلي أقوى من النموذج في تحميل صيغ متعددة، الفهرس، البحث داخل الكتاب، التظليل والملاحظات والنسخ الموثق، الفواصل، وضع السكينة، واستعادة الصفحات. لذلك تُحفظ هذه القدرات بوصفها الأصل.
- أكبر الفجوات المستقلة: توحيد عقد السمات/التسمية، GotoDialog، تبويبات لوحة الفهرس، شريط تقدم ذكي بوقت متبقٍ، إعدادات عرض القارئ، وكثافة الروابط.
- أكبر الفجوات التابعة للبيانات/المحرك: البلوكات الدلالية الثمانية، بطاقات الآية/الحديث/العَلَم/المكان/الغريب/الإحالة، العرض المتقابل للمتن والشروح، والصورة الأصلية التفاعلية مع OCR.

## سجل الدستور والهيكل

| القسم | الميزة أو التصور | حالة التنفيذ الحالية | الفجوة | ملفات التنفيذ المحتملة | الاختبارات المطلوبة | الأولوية والتبعيات | حالة الإنجاز |
|---|---|---|---|---|---|---|---|
| الدستور §1–4 | شخصية ورقية دافئة وTokens للألوان والمسافات والزوايا والظلال | `tokens.css` واسع، والواجهات تستخدم المتغيرات بكثافة | توجد قيم قديمة/مكررة وتسميات موازية، وبعض الأبيض/الأسود الصريح في السمات؛ لا يوجد مصدر JSON مولد وحيد | `app/src/styles/tokens.css`، `app/src/styles/base.css`، أداة توليد tokens جديدة | عقد يمنع الألوان الصلبة خارج قائمة سماح؛ snapshot للقيم القانونية | P1؛ يسبق أي توسع بصري واسع | جزئي |
| الدستور §3 | Amiri للعناوين والمتن وIBM Plex Sans Arabic للواجهة | التطبيق يستخدم عائلات Thmanyah وخطوطًا محلية متعددة؛ متن المستند يحترم خطوط الكتاب المضمّنة | تعارض صريح؛ الأصل الحالي يحفظ دقة الكتاب، لكن هوية الواجهة تحتاج قرارًا موثقًا بدل استبدال أعمى | `app/src/styles/tokens.css`، `app/public/fonts/` | فحص تحميل الخطوط، fallback عربي، وعدم انحدار مطابقة Word | P2؛ قرار هوية + عدم المساس بخطوط المستند | قرار مفتوح |
| الدستور §5 | حاوية 1120، قارئ 1280، متن 680، نقاط 640/1024 | الـtokens والحاويات موجودة، واستجابة واسعة في CSS | يلزم توحيد نقاط التحول وإثبات 375/768/1280 لكل شاشة رئيسية | `app/src/styles/tokens.css`، `components.css`، `screens.css` | visual/responsive contract للعرض الثلاثي، وعدم overflow | P1؛ مستقل | جزئي |
| الدستور §5 و§10 | ثلاث بوابات فقط: اقرأ/اكتشف/أنا | BottomNav مطابق بثلاث بوابات | Header المكتب يعرض الرئيسية/القرآن/السنة/مكتبتي/المؤلفون/بحث؛ يخالف العقد الأعلى | `app/src/shell.ts`، `app/src/router.ts`، `components.css` | navigation contract: ثلاث بوابات فقط مع بقاء الوصول لكل المسارات داخلها | P0؛ يحتاج خريطة معلومات وانتقال محافظ للروابط العميقة | جزئي |
| الهيكل SHL-02 | Header لاصق: شعار، بوابات، بحث، حساب | Header فعلي غني وبحث Ctrl/⌘K وحساب/إعدادات/ترجمة/سمة | إعادة تركيب الوجهات داخل البوابات؛ ضبط sticky/blur حرفيًا؛ عدم ازدحام التابلت | `app/src/shell.ts`، `components.css` | keyboard/focus، sticky، responsive، aria-current | P0؛ تابع للبند السابق | جزئي |
| الهيكل SHL-02 | شريط جوال علوي مصغر + BottomNav، ويختفيان في القارئ | BottomNav موجود خارج القارئ؛ القارئ لا يضيفه، لكنه يضيف Header المكتب العام | يلزم ReaderHeader مصغر مستقل بدل Header العام المزدحم على الجوال | `app/src/screens/reader.ts`، `app/src/shell.ts`، `components.css` | mobile reader contract: لا BottomNav، لا overflow، أهداف 44px | P0؛ مستقل نسبيًا | جزئي |
| الهيكل SHL-01 | لوحة اليوم للمستخدم العائد: ترحيب، متابعة، ورد، كنوز، اقتباس، سؤال، جديد | `home.ts` يملك بوابات ومحتوى رئيسيًا وميزات قراءة متفرقة في وحدات أخرى | مطابقة تركيب «لوحة اليوم» وسياق المستخدم العائد غير مكتملة | `app/src/screens/home.ts`، `reading_data.ts`، `activity_store.ts`، `spaced_review.ts` | حالتا عائد/جديد؛ ثبات البيانات؛ mobile/desktop | P1؛ يعتمد تجميع بيانات النشاط | جزئي |
| الهيكل SHL-01 | بداية المستخدم الجديد الهادئة: بحث + ثلاث أفعال + مقترحات | توجد شاشة ترحيب وبحث رئيسي وبيانات منشورة | لا توجد حالة موحدة مبنية على غياب النشاط/المكتبة كما في التصميم | `app/src/screens/home.ts`، `welcome.ts`، `published_library_seed.ts` | empty-account state، الانتقال بعد أول كتاب، عدم وميض الحالة | P1؛ يعتمد هوية الجلسة وحالة المكتبة | جزئي |
| الهيكل SHL-01 | الورد اليومي وسلسلة الأيام | توجد `reading_plan.ts` و`reading_data.ts` وواجهات خطط | بطاقة لوحة اليوم والسلسلة بالتكوين المحدد ليست مؤكدة مكتملة | `app/src/screens/home.ts`، `reading_plan.ts`، `reading_insights.ts` | حساب الدقائق/السلسلة، timezone، empty state | P2؛ يعتمد بيانات نشاط موثوقة | جزئي |
| الهيكل SHL-01 | «من كنوز قراءاتك» ومراجعة مقتطفات | ملاحظات/اقتباسات/مراجعة متباعدة موجودة | دمجها في الرئيسية كبطاقات موضعية وفعل رجوع مباشر | `home.ts`، `spaced_review.ts`، `quote_store.ts`، `annotation_store.ts` | اختيار العناصر، deep link، الخصوصية | P2؛ تابع للتعليقات والاقتباسات | جزئي |
| الهيكل SHL-01 | اقتباس اليوم وسؤال اليوم وجديد يهمك | توصيات واقتباسات وبيانات كتب موجودة | سؤال اليوم وتوثيق مصدره وحالة عدم توفره؛ ضبط التحفيز وإيقافه | `home.ts`، `recommendation_preferences.ts`، `reading_recommendations.ts` | opt-out، مصدر الاقتباس، عدم توليد نص داخل الكتاب | P2؛ تفضيلات + corpus | جزئي |
| الدستور §6 | مكونات BookCover/BookCard/ContinueCard/CategoryCard/SearchResult | مكونات فعلية وأنماط واختبارات بطاقات/أغلفة/بحث | يلزم جرد API موحد ومنع نسخ هندسية متباينة بين الشاشات | `app/src/components.ts`، `book_cover.ts`، CSS | component contract ولقطات في RTL/LTR | P2؛ مستقل | جزئي |
| الدستور §8 | خمس حالات: ممتلئة/فارغة/تحميل/خطأ/دون اتصال | `stateView`، Skeleton، connectivity/offline policy موجودة | ليست كل شاشة تطبق الحالات الخمس؛ يحتاج matrix تغطية | `app/src/state_view.ts`، `connectivity.ts`، كل `screens/*` | اختبار تعاقدي لكل شاشة وحالة؛ reduced-motion للسكلتون | P1؛ مستقل وقابل للدفعات | جزئي |
| الدستور §9 | تباين، لمس 44px، تكبير 200%، لوحة مفاتيح وقارئ شاشة | اختبارات إتاحة متعددة وforced-colors وskip link وaria | لا يوجد إثبات شامل 200%/375px لكل القارئ والـSheets؛ بعض أزرار القارئ بلا aria-label صريح | `navigation_accessibility.ts`، `components.css`، `reader.ts` | axe/keyboard، 200% reflow، touch targets، aria names | P0؛ مستقل | جزئي |
| الدستور §4 | reduced-motion للحركة والتمرير | `motion_preference.ts` وmedia query وإصلاح تمرير القارئ موجودة | تدقيق كل transitions/skeleton/lightbox/sheets المستقبلية | `motion_preference.ts`، `tokens.css`، CSS المكونات | preference contract: smooth→auto وإيقاف shimmer/animations | P1؛ مستقل | منفذ جزئيًا |
| الدستور §11 | مصدر حقيقة `tokens.json` وتصدير آلي | CSS هو المصدر الواقعي الحالي | `tokens.json` والمولد غير موجودين؛ Flutter خارج نطاق هذا المحرك | ملف token source + script توليد + `tokens.css` | idempotent generation، schema، drift check | P2؛ قرار تنسيق وبناء | غير منفذ |
| الدستور §13 | اسم/شعار/خط مصحف/سمات داكنة وتباين عالٍ | الاسم والشعار وسمات app متعددة وخط حفص محلي موجودة | ما زالت قرارات المصحف والهوية معلنة مفتوحة؛ لا تعتمد ضمنيًا من asset | `brand.ts`، `settings_store.ts`، `quran.ts`، `tokens.css` | brand assets، Quran font fallback، theme contrast | P2؛ حسم منتج/شرعي/خط | قرار مفتوح |

## سجل القارئ وأنماط العرض

| القسم | الميزة أو التصور | حالة التنفيذ الحالية | الفجوة | ملفات التنفيذ المحتملة | الاختبارات المطلوبة | الأولوية والتبعيات | حالة الإنجاز |
|---|---|---|---|---|---|---|---|
| القارئ الأساسي | ReaderHeader: رجوع، فهرس، عنوان مركزي، بحث، أدوات | Header التطبيق + toolbar والفهرس والبحث موجودة؛ توجد دالة ReaderHeader أخرى غير المسار الرئيسي | توحيد رأس قارئ واحد فعلي، عنوان مركزي، أدوات خلف درج، ومنع ازدحام الجوال | `app/src/screens/reader.ts`، `components.css` | desktop/mobile header، aria، لا overflow، route back | P0؛ مستقل مع حفظ الأفعال الحالية | جزئي |
| القارئ الأساسي | TOC Aside مكتب وDrawer/Sheet جوال | فهرس فعلي قابل للبحث، مستويات وروابط bookmarks، وفتح جوال | لا Backdrop/Sheet موحد؛ لا تبويبات الفهرس/الفواصل/التظليلات | `reader.ts`، `components.css`، `annotation_store.ts` | فلترة عربية، keyboard trap، mobile backdrop، tabs counts | P0؛ بيانات موجودة | جزئي |
| القارئ الأساسي | شريط أدوات سفلي responsive ونقطة توسع ToolCard | toolbar غني جدًا وقابل للتمرير/الضغط | الأفعال كثيرة مباشرة، خلاف قاعدة «الخدمة الجديدة داخل درج أدوات»؛ يلزم تجميع محافظ | `reader.ts`، `components.css` | كل الأفعال تبقى قابلة للوصول؛ لا تمرير أفقي جوال؛ focus restore | P0؛ يعتمد تصميم drawer | جزئي |
| الجلسة 2 | النمط الانسيابي بالأنواع الثمانية | نمط `flow` موجود كتخطيط قراءة، لكن النص يعرض فقرات عامة | لا نموذج دلالي ثابت للفقرة/آية/حديث/أثر/شعر/نقل/فائدة/غريب | `ooxml-model`/مصدر Shamela، `scene`, `paint`, `reader.ts` | fixtures لكل نوع، عدم تغيير النص، theme snapshots | P0؛ يعتمد تحويل بيانات دلالي موثوق | غير منفذ وظيفيًا |
| الجلسة 2 | الآية تحافظ على التشكيل؛ إزالة التشكيل لبقية النص | توجد إعدادات/خدمات قرآن، لكن عقد القارئ العام غير مكتمل | تمييز الآيات بنيويًا قبل أي strip؛ منع regex التخمين المحفوف | نموذج بيانات الكتاب + `reader.ts` | property tests لعلامات التشكيل والآيات | P1؛ تابع للبلوكات الدلالية | غير منفذ |
| الجلسة 2 | شارات المصدر ودرجة الحديث داخل المتن | شاشة السنة وبيانات حديث مستقلة موجودة | الربط بالموضع داخل كتب الشاملة ونسبة الحكم غير مكتمل | `sunnah_domain.ts`، registry، تحويل Shamela، `reader.ts` | attribution دائم، درجات متعددة، no-unattributed badge | P0؛ corpus وربط كيانات | غير منفذ في القارئ العام |
| الجلسة 2 | SmartProgress: نسبة + وقت متبقٍ حسب سرعة القراءة | تقدم صفحة/عدد صفحات وreading insights موجودان | لا يظهر وقت متبقٍ موثوق في القارئ العام | `reader_navigation.ts`، `reading_insights.ts`، `reader.ts` | حساب سرعة robust، unknown state، تحديث بلا thrash | P1؛ بيانات تقدم متاحة | جزئي |
| الجلسة 2 | تقليب scroll/pages ووضع تركيز | `reading_mode.ts` يبدل flow/pages، و«سكينة» تخفي الأدوات | وضع التركيز الذي يخفت البلوكات غير موجود؛ تسمية/عقد النمطين يحتاج توحيد | `reading_mode.ts`، `reader.ts`، CSS | persistence، keyboard، focus mode، reduced-motion | P1؛ التركيز يعتمد البلوكات | جزئي |
| الجلسة 2 | النمط المطابق للمطبوع مع صفحة ورقية وحواشٍ | العرض الهندسي وصفحات Word وحواشي نصية/Markdown/PDF موجودة، وهو الأصل الأدق | شارة «موافق للمطبوع»، تفريق متن/شرح، ونافذة الحاشية التفاعلية ليست عامة | `paint`, `scene`, `reader.ts`, `components.css` | corpus Word/PDF/BOK، footnote navigation، page authority | P0؛ لا ترقيع بصري، مرتبط بالمحرك | جزئي متقدم |
| الجلسة 2 | GotoDialog: جزء/صفحة/بداية/فهرس/آخر موضع | page jump والتنقل العميق موجودان بأشكال متعددة | لا Dialog موحد ولا أزرار سريعة كاملة ولا تحقق نطاق للأجزاء | `reader.ts`، `reader_navigation.ts`، `reader_page_authority.ts` | page/part bounds، last position، focus trap، mobile sheet | P1؛ مستقل نسبيًا | جزئي |
| الجلسة 2 | إعدادات العرض: حجم/سطر/عرض/محاذاة/تشكيل/أسانيد/سمات/كثافة روابط | سمات القراءة، app themes، reading mode وبعض إعدادات عامة موجودة | لوحة قارئ متكاملة ومعاينة/persistence وخصائص block-specific غير مكتملة | `settings_store.ts`، `reader.ts`، `tokens.css` | persistence/migration، theme isolation، 200%، defaults | P0؛ بعض البنود تعتمد الدلالات | جزئي |
| الجلسة 2 | ثلاث سمات قراءة مستقلة: day/sepiya/night | tokens و`data-reading-theme` موجودان؛ spelling الفعلي `sepiya` يخالف التصميم `sepia` | توحيد الاسم بترحيل backward-compatible؛ فصلها بوضوح عن app theme | `tokens.css`، `settings_store.ts`، `reader_theme_control_contract.test.ts` | migration، values exact، عدم تسرب سمة التطبيق | P1؛ مستقل | منفذ مع فجوة تسمية |
| الجلسة 3 | الصفحة الأصلية التفاعلية: صورة مسح ثابتة + hit regions | PDF reader ومعاينة الأصل بجانب النص موجودان | لا نموذج صفحة ممسوحة ببلوكات OCR قابلة للنقر/تحديد مع إحداثيات | PDF/OCR build pipeline، `reader.ts`، `paint/interact` | coordinate mapping/zoom، OCR confidence، search hit | P0؛ يعتمد حزمة OCR/خرائط بلوكات | غير منفذ |
| الجلسة 3 | BlockPopover فوق الصورة: نص مستخرج، 6 أفعال، دقة وإبلاغ | تحديد/نسخ/ملاحظة/بحث/ترجمة موجودة للنص DOM | لا popover مرتبط ببلوك صورة ولا confidence/report | `reader.ts`، report store جديد، OCR artifacts | popover/sheet، confidence label، report payload | P1؛ تابع للصفحة الأصلية | غير منفذ |
| الجلسة 3 | Lightbox للصور: تكبير/مشاركة/حفظ/وصف مولد موسوم | صور الكتب تُرسم؛ لا مسار عام واضح مطابق | بناء lightbox قابل للوصول؛ الوصف المولد لا يدخل المتن ويُوسم | `paint/quickHtml.ts`، `reader.ts`، component/CSS | zoom/pan، escape/focus trap، download، AI label | P1؛ استخراج الصور أولًا | غير منفذ/غير مثبت |
| الجلسة 3 | SelectionMenu: نسخ موثق، 4 ألوان، ملاحظة، بطاقة، اسأل | نسخ عادي/غني موثق، تظليل بألوان، ملاحظة، Google، ترجمة موجودة | لا «بطاقة» و«اسأل» بالمعنى المصمم؛ القائمة تتجاوز قاعدة 5 بدل More؛ labels/colors تحتاج مطابقة | `reader.ts`، `rich_clipboard.ts`، `quote_card.ts` | actions ≤5 + more، mobile bar، citation toast، range persistence | P0؛ معظم البنية موجودة | جزئي متقدم |
| الجلسة 3 | ملاحظات هامشية وبطاقة ملاحظة | التخزين ولوحة الملاحظات والقفز موجود | علامة هامش بجانب السطر وبطاقة موضعية غير مكتملتين | `reader.ts`، `annotation_store.ts`، interact geometry | anchor stability بعد إعادة layout، delete/edit، a11y | P1؛ يحتاج مراسي مستقرة | جزئي |
| الجلسة 3 | BookmarkCard بأربعة ألوان واسم اختياري | bookmark على مستوى الصفحة موجود | لا لون/اسم/بطاقة؛ نموذج التخزين أضيق | `annotation_store.ts`، `reader_bookmark_mapping.ts`، `reader.ts` | migration، rename/colors، deep link | P1؛ migration تخزين | جزئي |
| الجلسة 3 | لوحة ثلاثية: الفهرس/الفواصل/تظليلاتي | فهرس ولوحة annotations منفصلان | دمجهما في لوحة واحدة responsive مع حفظ التبويب | `reader.ts`، `components.css` | tabs/ARIA، counts، filter، mobile sheet | P0؛ كل البيانات موجودة | غير منفذ كتركيب |
| الجلسة 4 | بطاقات سريعة للآية والحديث، ≤4 أفعال + صفحة كاملة | صفحات قرآن وسنة وخدمات منفصلة غنية | لا اكتشاف/بطاقة موضعية في القارئ العام ولا ReturnBar حقيقي يحفظ الموضع | `quran.ts`، `sunnah.ts`، `reader.ts`، entity linker | attribution، card placement، return stack، mobile sheet | P0؛ ربط كيانات ومصادر | غير منفذ في القارئ العام |
| الجلسة 4 | بطاقات العَلَم/المكان/الغريب/الإحالة | شاشات مؤلفين وبيانات معجمية/بحثية جزئية | لا entity links موضعية ولا خرائط/تعريفات منسوبة | catalog metadata، author screens، dictionary/place datasets، `reader.ts` | ambiguity/disambiguation، sources، offline | P1؛ يعتمد إثراء بيانات | غير منفذ |
| الجلسة 4 | ReturnBar «عودة إلى موضعك» في كل خروج | توجد دالة `returnBar` ثابتة المثال، والتنقل العميق متفرق | الموضع/الكتاب/الصفحة ثابتة في الدالة وغير مربوطة بمكدس رحلة عام | `router.ts`، `reader_navigation.ts`، `reader.ts`، pages الخدمية | nested journeys، refresh persistence، correct page/book | P0؛ مطلوب قبل البطاقات الكاملة | جزئي شكلي |
| الجلسة 4 | كثافة الروابط: هادئ/قياسي/باحث + عداد | لا عقد عام؛ توجد روابط القرآن/الفهرس/الكتب | إعداد + سياسة أنواع + عداد + عدم إغراق المتن | settings/entity-link model/`reader.ts` | matrix الأنواع × المستويات، persistence، count accuracy | P0؛ يعتمد entity linking | غير منفذ |
| الجلسة 4 | المتن والشروح: زر جانبي، قائمة، عرض متقابل، شرح مستقل | بيانات سلاسل/كتب وعرض PDF بجوار النص موجودة، لكنها ليست شروحًا متزامنة | نموذج علاقة شرح↔متن، مرساة الحديث، مزامنة الموضع، UI responsive | `book_series.ts`/metadata graph، `reader.ts`، scene anchors | switch sharh retains anchor، mobile sheet، missing relation | P0؛ يعتمد تحويل العلاقات والفهارس | غير منفذ |
| الدستور §6 | FootnotePopover | الحواشي في الصفحة/Markdown وروابط رجوع موجودة | popover/Sheet موحد قرب العلامة مع fallback للصفحة | `reader.ts`، `markdown_render.ts`، `paint/quickHtml.ts` | keyboard/hover/touch، multi-paragraph notes، escape | P1؛ بيانات الحاشية موجودة | جزئي |
| الدستور §6 | وضع القراءة الصافية بنقرة على المتن | زر «سكينة» فعلي يخفي أجزاء الواجهة | التفعيل بنقرة آمنة على فراغ المتن، وعدم التفعيل عند التحديد/الرابط | `reader.ts`، `components.css` | pointer guards، keyboard equivalent، persistence decision | P2؛ مستقل | جزئي |
| الدستور §6 | جودة الكتاب: المصدر/الدقة/التدقيق/اكتمال الربط لا تُخفى | توجد إشعارات fidelity ومصدر وبيانات جودة وشاشة data quality | QualityBar موحد ودائم داخل القارئ غير مكتمل | `library_data_quality.ts`، `reader.ts`، `source_sync_ui.ts` | status mapping، always visible، offline، log link | P0؛ يعتمد metadata تحويل موحد | جزئي |

## دفعات تنفيذ مقترحة بلا تعارض ملفات

1. **قشرة وتنقل (P0):** `shell.ts` وCSS القشرة فقط؛ إعادة Header إلى البوابات الثلاث مع الحفاظ على الروابط العميقة، ثم ReaderHeader جوال مستقل.
2. **قابلية استخدام القارئ (P0/P1):** لوحة جانبية موحدة (فهرس/فواصل/تظليلات)، GotoDialog، وتجميع أدوات القارئ. هذه الدفعة تمس `reader.ts` بقوة، فلا تتوازى مع أي وكيل آخر في الملف نفسه.
3. **إعدادات وتقدم (P1):** ترحيل `sepia/sepiya`، لوحة إعدادات القراءة، وقت متبقٍ، واختبارات persistence؛ يمكن فصل منطق الحساب في وحدات مستقلة ثم دمجه لاحقًا.
4. **نموذج الدلالات (P0):** عقد بيانات للبلوكات والكيانات والروابط قبل أي واجهة. يجب أن يمر عبر حدود `SPEC.md` ويمتنع عن تغيير نص الكتاب.
5. **واجهات الدلالات (P0/P1):** البطاقات السريعة وReturnBar وكثافة الروابط ثم الشروح المتقابلة، بعد توفر بيانات قابلة للاختبار.
6. **الأصل المصور (P0 طويل):** artifact خرائط OCR، hit testing، BlockPopover وLightbox. لا يبدأ كتعديل CSS للقارئ.

## معايير قبول مشتركة

- لا يُحذف أو يُضعف أي مسار فعلي قائم للصيغ Word/PDF/BOK/EPUB/Markdown أو للفهرس والنسخ والتعليقات.
- كل إضافة لها حالات ممتلئة/فارغة/تحميل/خطأ/دون اتصال بحسب قابليتها، واختبار 375/768/1280 وتكبير 200%.
- كل زر أيقوني باسم عربي قابل للوصول، وكل Sheet/Modal يحبس التركيز ويعيده، وEscape يغلقه.
- `prefers-reduced-motion` يلغي الحركة والتمرير الناعم غير الضروري.
- لا يُنشأ رابط دلالي أو حكم حديث أو وصف آلي بلا مصدر/وسم واضح، ولا يُدرج محتوى مولد في متن الكتاب.
- أي عمل يمس تخطيط Word يثبت باختبار آلي/Corpus وفق تعليمات المحرك، لا بلقطة «تبدو صحيحة».
