import { createHash } from "node:crypto";
import type { DerivedArtifact } from "@library/source-sync";
import type { BuildJob, DerivedArtifactBuilder } from "../../source-sync-server/src/index.js";
import type { DerivedArtifactSink, ImmutableRevisionSource } from "./node-derived-builders.js";

export class PdfServiceBuildError extends Error { constructor(readonly code:string,readonly retryable:boolean,message=code,readonly retryAfterMs:number|null=null){super(message);this.name="PdfServiceBuildError"} }
export interface PdfServiceBuilderOptions { endpoint:string|URL; accessToken?:()=>Promise<string>; timeoutMs:number; maxSourceBytes:number; maxPdfBytes:number; engineVersion:string; fetchImpl?:typeof fetch }
export function createPdfServiceBuilder(source:ImmutableRevisionSource,sink:DerivedArtifactSink,options:PdfServiceBuilderOptions):DerivedArtifactBuilder{
 const fetchImpl=options.fetchImpl??fetch;
 return {async build({job}){const docx=await source.readRevisionBytes(job.sourceRevisionId);if(docx.byteLength>options.maxSourceBytes)throw new PdfServiceBuildError("source_too_large",false);const form=new FormData();form.append("source",new Blob([docx],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),`${job.sourceRevisionId}.docx`);form.append("bookId",job.bookId);form.append("sourceRevisionId",job.sourceRevisionId);
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeoutMs);try{const headers:Record<string,string>={};const token=await options.accessToken?.();if(token){if(!token.trim())throw new PdfServiceBuildError("unauthenticated",false);headers.authorization=`Bearer ${token}`;}let response:Response;try{response=await fetchImpl(options.endpoint,{method:"POST",headers,body:form,signal:controller.signal});}catch(error){if(error instanceof PdfServiceBuildError)throw error;throw new PdfServiceBuildError(controller.signal.aborted?"pdf_timeout":"pdf_transport",true);}
   if(!response.ok)throw new PdfServiceBuildError(`pdf_http_${response.status}`,response.status===408||response.status===429||response.status>=500,undefined,parseRetryAfter(response.headers.get("retry-after")));const type=response.headers.get("content-type")?.split(";")[0]?.trim();if(type!=="application/pdf")throw new PdfServiceBuildError("invalid_pdf_content_type",false);const length=Number(response.headers.get("content-length"));if(Number.isFinite(length)&&length>options.maxPdfBytes)throw new PdfServiceBuildError("pdf_too_large",false);const pdf=new Uint8Array(await response.arrayBuffer());if(pdf.byteLength>options.maxPdfBytes)throw new PdfServiceBuildError("pdf_too_large",false);if(pdf.byteLength<5||new TextDecoder("ascii").decode(pdf.subarray(0,5))!=="%PDF-")throw new PdfServiceBuildError("invalid_pdf_signature",false);
   const hex=createHash("sha256").update(pdf).digest("hex"),objectKey=`artifacts/${job.bookId}/${job.buildId}/pdf/${hex}.pdf`;await sink.putImmutable({objectKey,bytes:pdf,contentType:"application/pdf"});return{artifactId:`${job.buildId}:pdf`,kind:"pdf",bookId:job.bookId,sourceRevisionId:job.sourceRevisionId,buildId:job.buildId,status:"ready",fingerprint:{algorithm:"sha256",hex,byteLength:pdf.byteLength},objectKey,engineVersion:response.headers.get("x-pdf-engine")||options.engineVersion} satisfies DerivedArtifact;
  }finally{clearTimeout(timer);}}
 };
}
function parseRetryAfter(value:string|null){if(value===null)return null;const seconds=Number(value);if(Number.isFinite(seconds)&&seconds>=0)return Math.round(seconds*1000);const at=Date.parse(value);return Number.isFinite(at)?Math.max(0,at-Date.now()):null}
