import type { BookSourceRevision, SourceFingerprint } from "@library/source-sync";
import type { SourceRevisionAuthorityStore, SourceRevisionAuthorityTransaction, StagedSourceUpload } from "../../source-sync-server/src/index.js";
import type { D1DatabaseBinding } from "./bindings.js";

export class D1SourceRevisionAuthorityStore implements SourceRevisionAuthorityStore {
  constructor(private readonly db: D1DatabaseBinding,private readonly quota?:QuotaConfig) {}
  transaction<T>(work: (tx: SourceRevisionAuthorityTransaction) => Promise<T>): Promise<T> {
    // Correctness is enforced by unique constraints and conditional mutations;
    // no read result alone grants authority to overwrite an existing row.
    return work(new D1AuthorityTransaction(this.db,this.quota));
  }
}
class D1AuthorityTransaction implements SourceRevisionAuthorityTransaction {
  constructor(private readonly db: D1DatabaseBinding,private readonly quota?:QuotaConfig) {}
  async isBookOwner(bookId: string, userId: string) { return (await this.db.prepare("SELECT 1 AS owned FROM books WHERE id = ?1 AND owner_id = ?2").bind(bookId, userId).first()) !== null; }
  async getRevisionByOperation(bookId: string, operationId: string) { return revision(await this.db.prepare("SELECT * FROM book_source_revisions WHERE book_id = ?1 AND operation_id = ?2").bind(bookId, operationId).first<Row>()); }
  async getRevisionByFingerprint(bookId: string, fp: SourceFingerprint) { return revision(await this.db.prepare("SELECT * FROM book_source_revisions WHERE book_id = ?1 AND sha256 = ?2 AND byte_length = ?3").bind(bookId, fp.hex, fp.byteLength).first<Row>()); }
  async getActiveRevisionId(bookId: string) { const row = await this.db.prepare("SELECT active_source_revision_id AS id FROM books WHERE id = ?1").bind(bookId).first<{ id: string | null }>(); return row?.id ?? null; }
  async getUpload(id: string) { return upload(await this.db.prepare("SELECT * FROM source_uploads WHERE id = ?1").bind(id).first<UploadRow>()); }
  async getUploadByOperation(bookId: string, operationId: string) { return upload(await this.db.prepare("SELECT * FROM source_uploads WHERE book_id = ?1 AND operation_id = ?2").bind(bookId, operationId).first<UploadRow>()); }
  async createUpload(item: StagedSourceUpload) { return changed(await this.db.prepare("INSERT OR IGNORE INTO source_uploads (id,operation_id,owner_id,book_id,object_key,sha256,byte_length,base_revision_id,source_name,device_id,expires_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)").bind(item.uploadId,item.operationId,item.ownerId,item.bookId,item.objectKey,item.expectedFingerprint.hex,item.expectedFingerprint.byteLength,item.baseRevisionId,item.sourceName,item.deviceId,item.expiresAt).run()); }
  async createRevision(item: BookSourceRevision, key: string) { return changed(await this.db.prepare("INSERT OR IGNORE INTO book_source_revisions (id,book_id,operation_id,base_revision_id,sha256,byte_length,source_name,created_at,created_by_device_id,status,immutable_object_key) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)").bind(item.revisionId,item.bookId,item.operationId,item.baseRevisionId,item.fingerprint.hex,item.fingerprint.byteLength,item.sourceName,item.createdAt,item.createdByDeviceId,item.status,key).run()); }
  async enqueueBuildForRevision(item: BookSourceRevision) { if(item.status==="conflicted")return;const buildId=`build:${item.revisionId}`;const manifest={buildId,bookId:item.bookId,sourceRevisionId:item.revisionId,status:"processing",artifacts:[],createdAt:item.createdAt};await this.db.prepare("INSERT OR IGNORE INTO book_builds (id,book_id,source_revision_id,status,manifest_json,created_at) VALUES (?1,?2,?3,'processing',?4,?5)").bind(buildId,item.bookId,item.revisionId,JSON.stringify(manifest),item.createdAt).run();for(const kind of ["reader","pdf","search","toc","cover"])await this.db.prepare("INSERT OR IGNORE INTO build_jobs (id,build_id,book_id,source_revision_id,kind,state,next_attempt_at_ms) VALUES (?1,?2,?3,?4,?5,'pending',0)").bind(`${buildId}:${kind}`,buildId,item.bookId,item.revisionId,kind).run(); }
  async markUploadFinalized(id: string, revisionId: string) { return changed(await this.db.prepare("UPDATE source_uploads SET finalized_revision_id = ?2 WHERE id = ?1 AND finalized_revision_id IS NULL").bind(id,revisionId).run()); }
  async reserveUsage(i:{userId:string;bookId:string;operationId:string;uploadId:string;byteLength:number;expiresAt:string}){if(!this.quota)return"reserved" as const;if(i.byteLength>this.quota.maxSourceBytes)return"quota_exceeded" as const;await this.db.prepare("INSERT OR IGNORE INTO account_quotas (principal_sub,max_source_bytes,max_book_revisions,max_account_storage_bytes,max_requests_per_window,rate_window_seconds) VALUES (?1,?2,?3,?4,?5,?6)").bind(i.userId,this.quota.maxSourceBytes,this.quota.maxBookRevisions,this.quota.maxAccountStorageBytes,this.quota.maxRequestsPerWindow,this.quota.rateWindowSeconds).run();await this.db.prepare("INSERT OR IGNORE INTO account_usage (principal_sub) VALUES (?1)").bind(i.userId).run();const lock=await this.db.prepare("INSERT OR IGNORE INTO usage_reservations (principal_sub,book_id,operation_id,upload_id,byte_length,status,expires_at) VALUES (?1,?2,?3,?4,?5,'reserved',?6)").bind(i.userId,i.bookId,i.operationId,i.uploadId,i.byteLength,i.expiresAt).run();if((lock.meta?.changes??0)!==1)return"replay" as const;const now=Math.floor(Date.now()/1000),used=await this.db.prepare("UPDATE account_usage SET reserved_bytes=reserved_bytes+?2,window_started_at=CASE WHEN window_started_at+?3<=?4 THEN ?4 ELSE window_started_at END,window_requests=CASE WHEN window_started_at+?3<=?4 THEN 1 ELSE window_requests+1 END,record_version=record_version+1 WHERE principal_sub=?1 AND committed_bytes+reserved_bytes+?2<=?5 AND (CASE WHEN window_started_at+?3<=?4 THEN 1 ELSE window_requests+1 END)<=?6 AND (SELECT COUNT(*) FROM book_source_revisions WHERE book_id=?7)<?8").bind(i.userId,i.byteLength,this.quota.rateWindowSeconds,now,this.quota.maxAccountStorageBytes,this.quota.maxRequestsPerWindow,i.bookId,this.quota.maxBookRevisions).run();if((used.meta?.changes??0)!==1){await this.db.prepare("UPDATE usage_reservations SET status='released' WHERE upload_id=?1 AND status='reserved'").bind(i.uploadId).run();return"quota_exceeded" as const}return"reserved" as const}
  async commitUsage(id:string){const r=await this.db.prepare("UPDATE usage_reservations SET status='committed' WHERE upload_id=?1 AND status='reserved' RETURNING principal_sub,byte_length").bind(id).first<{principal_sub:string;byte_length:number}>();if(!r)return;await this.db.prepare("UPDATE account_usage SET reserved_bytes=reserved_bytes-?2,committed_bytes=committed_bytes+?2,record_version=record_version+1 WHERE principal_sub=?1").bind(r.principal_sub,r.byte_length).run();await this.db.prepare("INSERT INTO audit_events (principal_sub,event_type,book_id,device_id,operation_id,outcome) SELECT owner_id,'source_upload',book_id,device_id,operation_id,'committed' FROM source_uploads WHERE id=?1").bind(id).run()}
  async releaseUsage(id:string){const r=await this.db.prepare("UPDATE usage_reservations SET status='released' WHERE upload_id=?1 AND status='reserved' RETURNING principal_sub,byte_length").bind(id).first<{principal_sub:string;byte_length:number}>();if(r)await this.db.prepare("UPDATE account_usage SET reserved_bytes=MAX(0,reserved_bytes-?2),record_version=record_version+1 WHERE principal_sub=?1").bind(r.principal_sub,r.byte_length).run()}
  async releaseExpiredUsage(){const rows=await this.db.prepare("SELECT upload_id,principal_sub,byte_length FROM usage_reservations WHERE status='reserved' AND expires_at<CURRENT_TIMESTAMP").all<{upload_id:string;principal_sub:string;byte_length:number}>();for(const r of rows.results??[]){const changedRow=await this.db.prepare("UPDATE usage_reservations SET status='released' WHERE upload_id=?1 AND status='reserved'").bind(r.upload_id).run();if((changedRow.meta?.changes??0)===1)await this.db.prepare("UPDATE account_usage SET reserved_bytes=MAX(0,reserved_bytes-?2),record_version=record_version+1 WHERE principal_sub=?1").bind(r.principal_sub,r.byte_length).run()}}
  async recordQuarantine(i:{uploadId:string;ownerId:string;bookId:string;operationId:string;deviceId:string;reason:string}){await this.db.prepare("INSERT OR IGNORE INTO source_quarantines (id,upload_id,owner_id,book_id,operation_id,device_id,reason_code,status) VALUES (?1,?2,?3,?4,?5,?6,?7,'pending')").bind(`quarantine:${i.uploadId}`,i.uploadId,i.ownerId,i.bookId,i.operationId,i.deviceId,i.reason).run();await this.db.prepare("INSERT INTO audit_events (principal_sub,event_type,book_id,device_id,operation_id,outcome) VALUES (?1,'docx_quarantine',?2,?3,?4,?5)").bind(i.ownerId,i.bookId,i.deviceId,i.operationId,i.reason).run()}
  async quarantineDecision(id:string){const r=await this.db.prepare("SELECT status FROM source_quarantines WHERE upload_id=?1").bind(id).first<{status:"pending"|"allowed"|"rejected"}>();return r?.status??null}
  async reconcileCompletedUpload(bookId:string,operationId:string,revisionId:string){const row=await this.db.prepare("SELECT id FROM source_uploads WHERE book_id=?1 AND operation_id=?2").bind(bookId,operationId).first<{id:string}>();if(!row)return;await this.db.prepare("UPDATE source_uploads SET finalized_revision_id=COALESCE(finalized_revision_id,?2) WHERE id=?1").bind(row.id,revisionId).run();await this.commitUsage(row.id);const completed=revision(await this.db.prepare("SELECT * FROM book_source_revisions WHERE id=?1 AND book_id=?2 AND operation_id=?3").bind(revisionId,bookId,operationId).first<Row>());if(completed)await this.enqueueBuildForRevision(completed)}
}
export interface QuotaConfig{maxSourceBytes:number;maxBookRevisions:number;maxAccountStorageBytes:number;maxRequestsPerWindow:number;rateWindowSeconds:number}
type Row = Record<string, unknown>; type UploadRow = Row;
function revision(r: Row | null): BookSourceRevision | null { if (!r) return null; return { revisionId:String(r.id),bookId:String(r.book_id),operationId:String(r.operation_id),baseRevisionId:r.base_revision_id===null?null:String(r.base_revision_id),fingerprint:{algorithm:"sha256",hex:String(r.sha256),byteLength:Number(r.byte_length)},sourceName:String(r.source_name),createdAt:String(r.created_at),createdByDeviceId:String(r.created_by_device_id),status:String(r.status) as BookSourceRevision["status"] }; }
function upload(r: UploadRow | null): StagedSourceUpload | null { if (!r) return null; return { uploadId:String(r.id),operationId:String(r.operation_id),ownerId:String(r.owner_id),bookId:String(r.book_id),objectKey:String(r.object_key),expectedFingerprint:{algorithm:"sha256",hex:String(r.sha256),byteLength:Number(r.byte_length)},baseRevisionId:r.base_revision_id===null?null:String(r.base_revision_id),sourceName:String(r.source_name),deviceId:String(r.device_id),expiresAt:String(r.expires_at) }; }
function changed(result: { success: boolean; meta?: { changes?: number } }) { return result.success && (result.meta?.changes ?? 0) === 1; }
