import type { EditionAttachmentIntent, ImmutableSourceEdition, LogicalWork, SourceFormat, WorkSourceAuthority } from "@library/source-sync";
import type { SourceEditionPersistence, StoredEditionAttachment } from "../../source-sync-server/src/index.js";
import type { D1DatabaseBinding } from "./bindings.js";
type Row=Record<string,unknown>;
export class D1SourceEditionPersistence implements SourceEditionPersistence{
 constructor(private readonly db:D1DatabaseBinding){}
 async isOwner(workId:string,userId:string){return await this.db.prepare("SELECT 1 FROM logical_works WHERE id=?1 AND owner_id=?2").bind(workId,userId).first()!==null}
 async isActiveDevice(userId:string,deviceId:string){return await this.db.prepare("SELECT 1 FROM devices WHERE principal_sub=?1 AND device_id=?2 AND revoked_at IS NULL").bind(userId,deviceId).first()!==null}
 async getWork(workId:string){const r=await this.db.prepare("SELECT * FROM logical_works WHERE id=?1").bind(workId).first<Row>();return r?work(r):null}
 async findAttachment(workId:string,operationId:string){const r=await this.db.prepare("SELECT o.*,w.title,o.result_authority_kind AS authority_kind,o.result_authority_edition_id AS authority_edition_id,o.result_authority_format AS authority_format,o.result_work_version AS record_version FROM source_edition_operations o JOIN logical_works w ON w.id=o.work_id WHERE o.work_id=?1 AND o.operation_id=?2").bind(workId,operationId).first<Row>();if(!r)return null;return{operationId:String(r.operation_id),workId:String(r.work_id),editionId:String(r.edition_id),intent:String(r.intent)as EditionAttachmentIntent,expectedWorkVersion:Number(r.expected_work_version),result:work(r)} satisfies StoredEditionAttachment}
 async commit(i:{userId:string;deviceId:string;edition:ImmutableSourceEdition;intent:EditionAttachmentIntent;expectedWorkVersion:number;nextWork:LogicalWork}){if(!this.db.batch)throw Error("d1_batch_required");const e=i.edition,statements=[this.db.prepare("INSERT INTO source_editions(id,operation_id,work_id,format,role,object_key,sha256,byte_length,media_type,source_name,created_at,created_by_device_id) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)").bind(e.editionId,e.operationId,e.workId,e.format,e.role,e.objectKey,e.fingerprint.hex,e.fingerprint.byteLength,e.mediaType,e.sourceName,e.createdAt,e.createdByDeviceId),this.db.prepare("INSERT INTO source_edition_operations(work_id,operation_id,edition_id,intent,requested_by_user_id,requested_by_device_id,expected_work_version,result_work_version,result_authority_kind,result_authority_edition_id,result_authority_format) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)").bind(e.workId,e.operationId,e.editionId,i.intent,i.userId,i.deviceId,i.expectedWorkVersion,i.nextWork.recordVersion,i.nextWork.authority?.kind??null,i.nextWork.authority?.editionId??null,i.nextWork.authority?.format??null)];if(i.intent!=="attach-alternate"){statements.push(this.db.prepare("UPDATE logical_works SET authority_kind=?2,authority_edition_id=?3,authority_format=?4,record_version=record_version+1 WHERE id=?1 AND record_version=?5").bind(e.workId,i.nextWork.authority!.kind,i.nextWork.authority!.editionId,i.nextWork.authority!.format,i.expectedWorkVersion))}statements.push(this.db.prepare("INSERT INTO audit_events(principal_sub,event_type,book_id,device_id,operation_id,outcome) VALUES (?1,'source_edition_attach',?2,?3,?4,?5)").bind(i.userId,e.workId,i.deviceId,e.operationId,i.intent));const result=await this.db.batch(statements);return result.every(x=>x.success&&(x.meta?.changes??1)>0)}
}
function work(r:Row):LogicalWork{const kind=r.authority_kind==null?null:String(r.authority_kind);let authority:WorkSourceAuthority|null=null;if(kind==="word-live")authority={kind,editionId:String(r.authority_edition_id),format:"docx"};else if(kind==="immutable-edition")authority={kind,editionId:String(r.authority_edition_id),format:String(r.authority_format)as Exclude<SourceFormat,"docx">};return{workId:String(r.work_id??r.id),title:String(r.title),authority,recordVersion:Number(r.record_version)}}
