# Search index contract

- The index is generated by Alkhizana from its portable book packages; an external
  absolute path is never part of an index or manifest.
- Arabic folding is for lookup only. Original text remains authoritative and is
  returned for snippets/highlighting.
- A shard is independently buildable, replaceable, serializable and searchable.
  Shard identity is a logical portable id such as a package/book bucket.
- Queries return a stable total plus a bounded page. They never materialize all
  result objects merely to render the first page.
- Index building and querying use structured-clone-safe values so the same API can
  run in a Web Worker. Durable OPFS/IndexedDB storage belongs to the adapter, not
  this dependency-free core.
- Lucene files from Shamela are an import-source optimization only if a separate
  converter can prove its schema/analyzer/version. They are not a runtime format.
