# سجل التصميم الحي

> المصدر الجامع الحاكم لتتبع تصميم «الخزانة». كل معرف ثابت ولا يعاد استخدامه عند حذف/دمج بند؛ تسجل التغييرات بتحديث الحالة والملفات والاختبارات، مع بقاء تقارير الأجزاء مراجع منشأ.
> أُنشئ هذا الإصدار من جميع صفوف التقارير الثلاثة دون إسقاط، ويظل عدد البنود فحص سلامة إلزاميًا عند أي دمج لاحق.

- آخر دمج: 2026-08-10
- المصادر: `part-01-shell-reader.md`، `part-02-quran-sunnah-search.md`، `part-03-discovery-library-account.md`
- عدد البنود: **113**

| المعرف الثابت | المصدر | قسم التقرير | القسم / المرجع | الميزة أو التصور | الحالة الحالية | الفجوة | ملفات التنفيذ المحتملة | الاختبارات المطلوبة | الأولوية | التبعيات | الإنجاز |
|---|---|---|---|---|---|---|---|---|---|---|---|
| DSG-01-001 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §1–4 | شخصية ورقية دافئة وTokens للألوان والمسافات والزوايا والظلال | `tokens.css` واسع، والواجهات تستخدم المتغيرات بكثافة | توجد قيم قديمة/مكررة وتسميات موازية، وبعض الأبيض/الأسود الصريح في السمات؛ لا يوجد مصدر JSON مولد وحيد | `app/src/styles/tokens.css`، `app/src/styles/base.css`، أداة توليد tokens جديدة | عقد يمنع الألوان الصلبة خارج قائمة سماح؛ snapshot للقيم القانونية | P1 | يسبق أي توسع بصري واسع | جزئي |
| DSG-01-002 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §3 | Amiri للعناوين والمتن وIBM Plex Sans Arabic للواجهة | التطبيق يستخدم عائلات Thmanyah وخطوطًا محلية متعددة؛ متن المستند يحترم خطوط الكتاب المضمّنة | تعارض صريح؛ الأصل الحالي يحفظ دقة الكتاب، لكن هوية الواجهة تحتاج قرارًا موثقًا بدل استبدال أعمى | `app/src/styles/tokens.css`، `app/public/fonts/` | فحص تحميل الخطوط، fallback عربي، وعدم انحدار مطابقة Word | P2 | قرار هوية + عدم المساس بخطوط المستند | قرار مفتوح |
| DSG-01-003 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §5 | حاوية 1120، قارئ 1280، متن 680، نقاط 640/1024 | الـtokens والحاويات موجودة، واستجابة واسعة في CSS | يلزم توحيد نقاط التحول وإثبات 375/768/1280 لكل شاشة رئيسية | `app/src/styles/tokens.css`، `components.css`، `screens.css` | visual/responsive contract للعرض الثلاثي، وعدم overflow | P1 | مستقل | جزئي |
| DSG-01-004 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §5 و§10 | ثلاث بوابات فقط: اقرأ/اكتشف/أنا | BottomNav مطابق بثلاث بوابات | Header المكتب يعرض الرئيسية/القرآن/السنة/مكتبتي/المؤلفون/بحث؛ يخالف العقد الأعلى | `app/src/shell.ts`، `app/src/router.ts`، `components.css` | navigation contract: ثلاث بوابات فقط مع بقاء الوصول لكل المسارات داخلها | P0 | يحتاج خريطة معلومات وانتقال محافظ للروابط العميقة | جزئي |
| DSG-01-005 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-02 | Header لاصق: شعار، بوابات، بحث، حساب | Header فعلي غني وبحث Ctrl/⌘K وحساب/إعدادات/ترجمة/سمة | إعادة تركيب الوجهات داخل البوابات؛ ضبط sticky/blur حرفيًا؛ عدم ازدحام التابلت | `app/src/shell.ts`، `components.css` | keyboard/focus، sticky، responsive، aria-current | P0 | تابع للبند السابق | جزئي |
| DSG-01-006 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-02 | شريط جوال علوي مصغر + BottomNav، ويختفيان في القارئ | BottomNav موجود خارج القارئ؛ القارئ لا يضيفه، لكنه يضيف Header المكتب العام | يلزم ReaderHeader مصغر مستقل بدل Header العام المزدحم على الجوال | `app/src/screens/reader.ts`، `app/src/shell.ts`، `components.css` | mobile reader contract: لا BottomNav، لا overflow، أهداف 44px | P0 | مستقل نسبيًا | جزئي |
| DSG-01-007 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-01 | لوحة اليوم للمستخدم العائد: ترحيب، متابعة، ورد، كنوز، اقتباس، سؤال، جديد | `home.ts` يملك بوابات ومحتوى رئيسيًا وميزات قراءة متفرقة في وحدات أخرى | مطابقة تركيب «لوحة اليوم» وسياق المستخدم العائد غير مكتملة | `app/src/screens/home.ts`، `reading_data.ts`، `activity_store.ts`، `spaced_review.ts` | حالتا عائد/جديد؛ ثبات البيانات؛ mobile/desktop | P1 | يعتمد تجميع بيانات النشاط | جزئي |
| DSG-01-008 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-01 | بداية المستخدم الجديد الهادئة: بحث + ثلاث أفعال + مقترحات | توجد شاشة ترحيب وبحث رئيسي وبيانات منشورة | لا توجد حالة موحدة مبنية على غياب النشاط/المكتبة كما في التصميم | `app/src/screens/home.ts`، `welcome.ts`، `published_library_seed.ts` | empty-account state، الانتقال بعد أول كتاب، عدم وميض الحالة | P1 | يعتمد هوية الجلسة وحالة المكتبة | جزئي |
| DSG-01-009 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-01 | الورد اليومي وسلسلة الأيام | توجد `reading_plan.ts` و`reading_data.ts` وواجهات خطط | بطاقة لوحة اليوم والسلسلة بالتكوين المحدد ليست مؤكدة مكتملة | `app/src/screens/home.ts`، `reading_plan.ts`، `reading_insights.ts` | حساب الدقائق/السلسلة، timezone، empty state | P2 | يعتمد بيانات نشاط موثوقة | جزئي |
| DSG-01-010 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-01 | «من كنوز قراءاتك» ومراجعة مقتطفات | ملاحظات/اقتباسات/مراجعة متباعدة موجودة | دمجها في الرئيسية كبطاقات موضعية وفعل رجوع مباشر | `home.ts`، `spaced_review.ts`، `quote_store.ts`، `annotation_store.ts` | اختيار العناصر، deep link، الخصوصية | P2 | تابع للتعليقات والاقتباسات | جزئي |
| DSG-01-011 | part-01-shell-reader.md | سجل الدستور والهيكل | الهيكل SHL-01 | اقتباس اليوم وسؤال اليوم وجديد يهمك | توصيات واقتباسات وبيانات كتب موجودة | سؤال اليوم وتوثيق مصدره وحالة عدم توفره؛ ضبط التحفيز وإيقافه | `home.ts`، `recommendation_preferences.ts`، `reading_recommendations.ts` | opt-out، مصدر الاقتباس، عدم توليد نص داخل الكتاب | P2 | تفضيلات + corpus | جزئي |
| DSG-01-012 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §6 | مكونات BookCover/BookCard/ContinueCard/CategoryCard/SearchResult | مكونات فعلية وأنماط واختبارات بطاقات/أغلفة/بحث | يلزم جرد API موحد ومنع نسخ هندسية متباينة بين الشاشات | `app/src/components.ts`، `book_cover.ts`، CSS | component contract ولقطات في RTL/LTR | P2 | مستقل | جزئي |
| DSG-01-013 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §8 | خمس حالات: ممتلئة/فارغة/تحميل/خطأ/دون اتصال | `stateView`، Skeleton، connectivity/offline policy موجودة | ليست كل شاشة تطبق الحالات الخمس؛ يحتاج matrix تغطية | `app/src/state_view.ts`، `connectivity.ts`، كل `screens/*` | اختبار تعاقدي لكل شاشة وحالة؛ reduced-motion للسكلتون | P1 | مستقل وقابل للدفعات | جزئي |
| DSG-01-014 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §9 | تباين، لمس 44px، تكبير 200%، لوحة مفاتيح وقارئ شاشة | اختبارات إتاحة متعددة وforced-colors وskip link وaria | لا يوجد إثبات شامل 200%/375px لكل القارئ والـSheets؛ بعض أزرار القارئ بلا aria-label صريح | `navigation_accessibility.ts`، `components.css`، `reader.ts` | axe/keyboard، 200% reflow، touch targets، aria names | P0 | مستقل | جزئي |
| DSG-01-015 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §4 | reduced-motion للحركة والتمرير | `motion_preference.ts` وmedia query وإصلاح تمرير القارئ موجودة | تدقيق كل transitions/skeleton/lightbox/sheets المستقبلية | `motion_preference.ts`، `tokens.css`، CSS المكونات | preference contract: smooth→auto وإيقاف shimmer/animations | P1 | مستقل | منفذ جزئيًا |
| DSG-01-016 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §11 | مصدر حقيقة `tokens.json` وتصدير آلي | CSS هو المصدر الواقعي الحالي | `tokens.json` والمولد غير موجودين؛ Flutter خارج نطاق هذا المحرك | ملف token source + script توليد + `tokens.css` | idempotent generation، schema، drift check | P2 | قرار تنسيق وبناء | غير منفذ |
| DSG-01-017 | part-01-shell-reader.md | سجل الدستور والهيكل | الدستور §13 | اسم/شعار/خط مصحف/سمات داكنة وتباين عالٍ | الاسم والشعار وسمات app متعددة وخط حفص محلي موجودة | ما زالت قرارات المصحف والهوية معلنة مفتوحة؛ لا تعتمد ضمنيًا من asset | `brand.ts`، `settings_store.ts`، `quran.ts`، `tokens.css` | brand assets، Quran font fallback، theme contrast | P2 | حسم منتج/شرعي/خط | قرار مفتوح |
| DSG-01-018 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | القارئ الأساسي | ReaderHeader: رجوع، فهرس، عنوان مركزي، بحث، أدوات | Header التطبيق + toolbar والفهرس والبحث موجودة؛ توجد دالة ReaderHeader أخرى غير المسار الرئيسي | توحيد رأس قارئ واحد فعلي، عنوان مركزي، أدوات خلف درج، ومنع ازدحام الجوال | `app/src/screens/reader.ts`، `components.css` | desktop/mobile header، aria، لا overflow، route back | P0 | مستقل مع حفظ الأفعال الحالية | جزئي |
| DSG-01-019 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | القارئ الأساسي | TOC Aside مكتب وDrawer/Sheet جوال | فهرس فعلي قابل للبحث، مستويات وروابط bookmarks، وفتح جوال | لا Backdrop/Sheet موحد؛ لا تبويبات الفهرس/الفواصل/التظليلات | `reader.ts`، `components.css`، `annotation_store.ts` | فلترة عربية، keyboard trap، mobile backdrop، tabs counts | P0 | بيانات موجودة | جزئي |
| DSG-01-020 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | القارئ الأساسي | شريط أدوات سفلي responsive ونقطة توسع ToolCard | toolbar غني جدًا وقابل للتمرير/الضغط | الأفعال كثيرة مباشرة، خلاف قاعدة «الخدمة الجديدة داخل درج أدوات»؛ يلزم تجميع محافظ | `reader.ts`، `components.css` | كل الأفعال تبقى قابلة للوصول؛ لا تمرير أفقي جوال؛ focus restore | P0 | يعتمد تصميم drawer | جزئي |
| DSG-01-021 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | النمط الانسيابي بالأنواع الثمانية | نمط `flow` موجود كتخطيط قراءة، لكن النص يعرض فقرات عامة | لا نموذج دلالي ثابت للفقرة/آية/حديث/أثر/شعر/نقل/فائدة/غريب | `ooxml-model`/مصدر Shamela، `scene`, `paint`, `reader.ts` | fixtures لكل نوع، عدم تغيير النص، theme snapshots | P0 | يعتمد تحويل بيانات دلالي موثوق | غير منفذ وظيفيًا |
| DSG-01-022 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | الآية تحافظ على التشكيل؛ إزالة التشكيل لبقية النص | توجد إعدادات/خدمات قرآن، لكن عقد القارئ العام غير مكتمل | تمييز الآيات بنيويًا قبل أي strip؛ منع regex التخمين المحفوف | نموذج بيانات الكتاب + `reader.ts` | property tests لعلامات التشكيل والآيات | P1 | تابع للبلوكات الدلالية | غير منفذ |
| DSG-01-023 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | شارات المصدر ودرجة الحديث داخل المتن | شاشة السنة وبيانات حديث مستقلة موجودة | الربط بالموضع داخل كتب الشاملة ونسبة الحكم غير مكتمل | `sunnah_domain.ts`، registry، تحويل Shamela، `reader.ts` | attribution دائم، درجات متعددة، no-unattributed badge | P0 | corpus وربط كيانات | غير منفذ في القارئ العام |
| DSG-01-024 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | SmartProgress: نسبة + وقت متبقٍ حسب سرعة القراءة | تقدم صفحة/عدد صفحات وreading insights موجودان | لا يظهر وقت متبقٍ موثوق في القارئ العام | `reader_navigation.ts`، `reading_insights.ts`، `reader.ts` | حساب سرعة robust، unknown state، تحديث بلا thrash | P1 | بيانات تقدم متاحة | جزئي |
| DSG-01-025 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | تقليب scroll/pages ووضع تركيز | `reading_mode.ts` يبدل flow/pages، و«سكينة» تخفي الأدوات | وضع التركيز الذي يخفت البلوكات غير موجود؛ تسمية/عقد النمطين يحتاج توحيد | `reading_mode.ts`، `reader.ts`، CSS | persistence، keyboard، focus mode، reduced-motion | P1 | التركيز يعتمد البلوكات | جزئي |
| DSG-01-026 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | النمط المطابق للمطبوع مع صفحة ورقية وحواشٍ | العرض الهندسي وصفحات Word وحواشي نصية/Markdown/PDF موجودة، وهو الأصل الأدق | شارة «موافق للمطبوع»، تفريق متن/شرح، ونافذة الحاشية التفاعلية ليست عامة | `paint`, `scene`, `reader.ts`, `components.css` | corpus Word/PDF/BOK، footnote navigation، page authority | P0 | لا ترقيع بصري، مرتبط بالمحرك | جزئي متقدم |
| DSG-01-027 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | GotoDialog: جزء/صفحة/بداية/فهرس/آخر موضع | page jump والتنقل العميق موجودان بأشكال متعددة | لا Dialog موحد ولا أزرار سريعة كاملة ولا تحقق نطاق للأجزاء | `reader.ts`، `reader_navigation.ts`، `reader_page_authority.ts` | page/part bounds، last position، focus trap، mobile sheet | P1 | مستقل نسبيًا | جزئي |
| DSG-01-028 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | إعدادات العرض: حجم/سطر/عرض/محاذاة/تشكيل/أسانيد/سمات/كثافة روابط | سمات القراءة، app themes، reading mode وبعض إعدادات عامة موجودة | لوحة قارئ متكاملة ومعاينة/persistence وخصائص block-specific غير مكتملة | `settings_store.ts`، `reader.ts`، `tokens.css` | persistence/migration، theme isolation، 200%، defaults | P0 | بعض البنود تعتمد الدلالات | جزئي |
| DSG-01-029 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 2 | ثلاث سمات قراءة مستقلة: day/sepiya/night | tokens و`data-reading-theme` موجودان؛ spelling الفعلي `sepiya` يخالف التصميم `sepia` | توحيد الاسم بترحيل backward-compatible؛ فصلها بوضوح عن app theme | `tokens.css`، `settings_store.ts`، `reader_theme_control_contract.test.ts` | migration، values exact، عدم تسرب سمة التطبيق | P1 | مستقل | منفذ مع فجوة تسمية |
| DSG-01-030 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | الصفحة الأصلية التفاعلية: صورة مسح ثابتة + hit regions | PDF reader ومعاينة الأصل بجانب النص موجودان | لا نموذج صفحة ممسوحة ببلوكات OCR قابلة للنقر/تحديد مع إحداثيات | PDF/OCR build pipeline، `reader.ts`، `paint/interact` | coordinate mapping/zoom، OCR confidence، search hit | P0 | يعتمد حزمة OCR/خرائط بلوكات | غير منفذ |
| DSG-01-031 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | BlockPopover فوق الصورة: نص مستخرج، 6 أفعال، دقة وإبلاغ | تحديد/نسخ/ملاحظة/بحث/ترجمة موجودة للنص DOM | لا popover مرتبط ببلوك صورة ولا confidence/report | `reader.ts`، report store جديد، OCR artifacts | popover/sheet، confidence label، report payload | P1 | تابع للصفحة الأصلية | غير منفذ |
| DSG-01-032 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | Lightbox للصور: تكبير/مشاركة/حفظ/وصف مولد موسوم | صور الكتب تُرسم؛ لا مسار عام واضح مطابق | بناء lightbox قابل للوصول؛ الوصف المولد لا يدخل المتن ويُوسم | `paint/quickHtml.ts`، `reader.ts`، component/CSS | zoom/pan، escape/focus trap، download، AI label | P1 | استخراج الصور أولًا | غير منفذ/غير مثبت |
| DSG-01-033 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | SelectionMenu: نسخ موثق، 4 ألوان، ملاحظة، بطاقة، اسأل | نسخ عادي/غني موثق، تظليل بألوان، ملاحظة، Google، ترجمة موجودة | لا «بطاقة» و«اسأل» بالمعنى المصمم؛ القائمة تتجاوز قاعدة 5 بدل More؛ labels/colors تحتاج مطابقة | `reader.ts`، `rich_clipboard.ts`، `quote_card.ts` | actions ≤5 + more، mobile bar، citation toast، range persistence | P0 | معظم البنية موجودة | جزئي متقدم |
| DSG-01-034 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | ملاحظات هامشية وبطاقة ملاحظة | التخزين ولوحة الملاحظات والقفز موجود | علامة هامش بجانب السطر وبطاقة موضعية غير مكتملتين | `reader.ts`، `annotation_store.ts`، interact geometry | anchor stability بعد إعادة layout، delete/edit، a11y | P1 | يحتاج مراسي مستقرة | جزئي |
| DSG-01-035 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | BookmarkCard بأربعة ألوان واسم اختياري | bookmark على مستوى الصفحة موجود | لا لون/اسم/بطاقة؛ نموذج التخزين أضيق | `annotation_store.ts`، `reader_bookmark_mapping.ts`، `reader.ts` | migration، rename/colors، deep link | P1 | migration تخزين | جزئي |
| DSG-01-036 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 3 | لوحة ثلاثية: الفهرس/الفواصل/تظليلاتي | فهرس ولوحة annotations منفصلان | دمجهما في لوحة واحدة responsive مع حفظ التبويب | `reader.ts`، `components.css` | tabs/ARIA، counts، filter، mobile sheet | P0 | كل البيانات موجودة | غير منفذ كتركيب |
| DSG-01-037 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 4 | بطاقات سريعة للآية والحديث، ≤4 أفعال + صفحة كاملة | صفحات قرآن وسنة وخدمات منفصلة غنية | لا اكتشاف/بطاقة موضعية في القارئ العام ولا ReturnBar حقيقي يحفظ الموضع | `quran.ts`، `sunnah.ts`، `reader.ts`، entity linker | attribution، card placement، return stack، mobile sheet | P0 | ربط كيانات ومصادر | غير منفذ في القارئ العام |
| DSG-01-038 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 4 | بطاقات العَلَم/المكان/الغريب/الإحالة | شاشات مؤلفين وبيانات معجمية/بحثية جزئية | لا entity links موضعية ولا خرائط/تعريفات منسوبة | catalog metadata، author screens، dictionary/place datasets، `reader.ts` | ambiguity/disambiguation، sources، offline | P1 | يعتمد إثراء بيانات | غير منفذ |
| DSG-01-039 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 4 | ReturnBar «عودة إلى موضعك» في كل خروج | توجد دالة `returnBar` ثابتة المثال، والتنقل العميق متفرق | الموضع/الكتاب/الصفحة ثابتة في الدالة وغير مربوطة بمكدس رحلة عام | `router.ts`، `reader_navigation.ts`، `reader.ts`، pages الخدمية | nested journeys، refresh persistence، correct page/book | P0 | مطلوب قبل البطاقات الكاملة | جزئي شكلي |
| DSG-01-040 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 4 | كثافة الروابط: هادئ/قياسي/باحث + عداد | لا عقد عام؛ توجد روابط القرآن/الفهرس/الكتب | إعداد + سياسة أنواع + عداد + عدم إغراق المتن | settings/entity-link model/`reader.ts` | matrix الأنواع × المستويات، persistence، count accuracy | P0 | يعتمد entity linking | غير منفذ |
| DSG-01-041 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الجلسة 4 | المتن والشروح: زر جانبي، قائمة، عرض متقابل، شرح مستقل | بيانات سلاسل/كتب وعرض PDF بجوار النص موجودة، لكنها ليست شروحًا متزامنة | نموذج علاقة شرح↔متن، مرساة الحديث، مزامنة الموضع، UI responsive | `book_series.ts`/metadata graph، `reader.ts`، scene anchors | switch sharh retains anchor، mobile sheet، missing relation | P0 | يعتمد تحويل العلاقات والفهارس | غير منفذ |
| DSG-01-042 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الدستور §6 | FootnotePopover | الحواشي في الصفحة/Markdown وروابط رجوع موجودة | popover/Sheet موحد قرب العلامة مع fallback للصفحة | `reader.ts`، `markdown_render.ts`، `paint/quickHtml.ts` | keyboard/hover/touch، multi-paragraph notes، escape | P1 | بيانات الحاشية موجودة | جزئي |
| DSG-01-043 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الدستور §6 | وضع القراءة الصافية بنقرة على المتن | زر «سكينة» فعلي يخفي أجزاء الواجهة | التفعيل بنقرة آمنة على فراغ المتن، وعدم التفعيل عند التحديد/الرابط | `reader.ts`، `components.css` | pointer guards، keyboard equivalent، persistence decision | P2 | مستقل | جزئي |
| DSG-01-044 | part-01-shell-reader.md | سجل القارئ وأنماط العرض | الدستور §6 | جودة الكتاب: المصدر/الدقة/التدقيق/اكتمال الربط لا تُخفى | توجد إشعارات fidelity ومصدر وبيانات جودة وشاشة data quality | QualityBar موحد ودائم داخل القارئ غير مكتمل | `library_data_quality.ts`، `reader.ts`، `source_sync_ui.ts` | status mapping، always visible، offline، log link | P0 | يعتمد metadata تحويل موحد | جزئي |
| DSG-02-001 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-01 المصحف | مصحف وقور بصفحات حقيقية، إطار مزدوج، علامات الآي والبسملة، نهاري/ليلي، واستجابة للجوال | `screens/quran.ts` يعرض الحزمة الكاملة؛ أصول 114 سورة JSON/SVG وخط `hafs-uthmani.ttf`؛ أوضاع قراءة محفوظة واختبارات responsive/Q0/Q1 | مطابقة التصميم البصرية ليست مكتملة؛ لا إطار المصحف المزدوج الموصوف ولا تحقق بصري شامل لكل الصفحات/المقاسات | `app/src/screens/quran.ts`, `app/src/styles/screens.css`, `app/public/quran/mushaf/hafs/*`, `app/src/quran_view_preferences.ts` | لقطات مرجعية desktop/mobile/day/night؛ خصائص تغطية 604 صفحات؛ تنقل لوحة المفاتيح وقارئ الشاشة | P1 | ثبات أصول المصحف وترخيصها، دستور التصميم | جزئي |
| DSG-02-002 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-01 المصحف | التجويد الملوّن ومفتاح ألوان قابل للطي | لا يظهر مسار بيانات أو rendering للتجويد في التنفيذ المقروء | مطلوب dataset موثق لمد/غنة/قلقلة/إخفاء، تمثيل spans لا يغيّر النص، مفتاح، تعطيل كامل، وألوان مناسبة لعمى الألوان | `quran_domain.ts`, `quran_resource_pack.ts`, `screens/quran.ts`, `styles/screens.css`, أصول `public/quran/resources` | صحة حدود المقاطع مقابل عينة ذهبية؛ بقاء النسخ والنص دون محارف إضافية؛ contrast وreduced-motion | P1 | مصدر تجويد مرخّص، محاذاة مواضع الكلمات/الحروف | غير منفذ |
| DSG-02-003 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-01 المصحف | الروايات (حفص، ورش، قالون) والرسم المدني/الهندي | العقد يدعم `qiraa/riwaya/mushafEdition`، والواجهة/البيانات الفعلية الحالية لحفص؛ لا corpus فعلي لورش/قالون | تحميل انتقائي حسب الرواية، فروق النص والرسم والعدّ، منع إيهام المستخدم بتوفر غير الموجود | `quran_domain.ts`, `quran_full_pack.ts`, `quran_local_pack.ts`, `screens/quran.ts` | manifests/provenance لكل رواية؛ تبديل يحفظ الموضع؛ عينات فروق معتمدة؛ fallback واضح | P2 | بيانات موثقة وترخيص؛ هوية آية عابرة للروايات | نواة عقد فقط |
| DSG-02-004 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-01 المصحف | نافذة انتقال: سورة/جزء وحزب/صفحة + بداية/فهرس/آخر موضع | يوجد تنقل سوري/آياتي وحفظ مواضع في بعض المسارات | لا توجد نافذة موحدة بفهارس الجزء والحزب والصفحة والأزرار السريعة كما في التصميم | `screens/quran.ts`, بيانات page spans، `quran_view_preferences.ts` | جميع الحدود (114 سورة/30 جزءًا/60 حزبًا/604 صفحات)؛ استعادة آخر موضع؛ mobile focus trap | P1 | خريطة مصحف موثوقة | جزئي |
| DSG-02-005 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-02 صفحة الآية | صفحة آية كاملة بتبويبات: تفاسير، كلمة بكلمة، إعراب، قراءات، أسباب نزول، متشابهات، أحكام، تأملاتي | inspector يعرض الآية/الكلمة؛ تفسير محلي؛ خدمات الغريب والقراءات والتصريف والإعراب؛ تحديد ونسخ وتعليقات مقيدة | لا route موسوعي مستقل ولا بقية التبويبات/حالاتها؛ الموارد الحالية تعرض كخدمة منفردة لا تجربة مترابطة | `screens/quran.ts`, `quran_resource_pack.ts`, `quran_domain.ts`, `annotation_store.ts`, `router.ts` | deep-link لكل تبويب وآية؛ provenance؛ loading/error/empty؛ الجوال؛ عدم خلط بيانات آيتين عند التنقل السريع | P0 | حزم أسباب النزول/المتشابهات/الأحكام، عقود موحدة للمصادر | جزئي |
| DSG-02-006 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-02 التفاسير | مقارنة متوازية لعدة تفاسير + «أضف تفسيرًا» | selector لتفسير واحد، تحميل محلي وكاش، فتح التفسير ككتاب، تغيير الحجم | اختيار متعدد، أعمدة متوازية/بطاقات جوال، مزامنة التمرير، ترتيب وحفظ التفضيل | `screens/quran.ts`, `quran_full_pack.ts`, `styles/screens.css` | 1–4 تفاسير؛ responsive؛ فشل مصدر واحد لا يسقط البقية؛ حفظ الاختيارات | P1 | إتاحة عدة حزم تفسير وربطها بهوية الآية | جزئي |
| DSG-02-007 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-02 كلمة بكلمة | الكلمة، المعنى، الجذر، الصرف، وعدد/مواضع الجذر | تحديد الكلمة، التصريف/الغريب، وفهرس جذور بوقائع مواضع | لا جدول كلمة بكلمة موحد، ولا معنى/جذر/صرف في بطاقة واحدة، ولا انتقال مواضع الجذر من السياق | `quran_selection.ts`, `quran_root_search.ts`, `quran_resource_pack.ts`, `screens/quran.ts` | محاذاة token مع النص العثماني؛ كلمات ملتصقة/وقف؛ دقة الجذر؛ انتقال النتيجة | P1 | word-token map موثق ومتوافق مع الرسم | جزئي |
| DSG-02-008 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-02 الآية في التراث | استشهاد عكسي في الكتب مع الفن/القرن/الأهمية وفتح الموضع | يمكن إرسال نص محدد للبحث العام؛ لا فهرس استشهادات آيات | فهرسة إحالات الآيات الصريحة والاقتباسات، درجات ثقة، facets، وفتح موضع الشاملة | `packages/search`, `app/src/engine/search_store.ts`, `screens/quran.ts`, pipeline حزم الشاملة | precision/recall على عينة ذهبية؛ filters؛ 10k pagination؛ deep-link للموضع | P0 | تحويل كتب الشاملة، فهرس Worker المجزأ، كاش معرفات الآيات | غير منفذ |
| DSG-02-009 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-03 التلاوات | مشغل ملازم، تظليل الكلمة المنطوقة، اختيار قارئ مع بيانات التسجيل | catalog وصوت lazy، اختيار/تصفية القارئ، حفظ الاختيار، تشغيل/تقديم/سرعة | لا مشغل ملازم/مصغر، لا timings للكلمات، ولا بيانات عرض القارئ/سنة التسجيل بالهيئة المطلوبة | `screens/quran.ts`, `quran_audio_filter.ts`, `quran_domain.ts`, `audio_core.ts`, styles | تبديل الآيات/القارئ؛ تعذر الشبكة؛ عدم التنزيل قبل التشغيل؛ sync word timing؛ mobile mini-player | P1 | audio timing manifests، مصادر صوت وشروطها | جزئي |
| DSG-02-010 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-03 الحفظ | تكرار الآية ×1/3/7/∞، تكرار مقطع، السرعة، مؤقت النوم | السرعة متاحة فقط | state machine للتكرار والمقطع، حدود الانتقال، timer، استئناف/إيقاف آمن بالخلفية | `screens/quran.ts`, `audio_core.ts`, `quran_view_preferences.ts` | تكرار دقيق بلا تخطي؛ إلغاء timer؛ تغيير السورة؛ media lifecycle | P1 | تلاوات مجزأة أو timestamps دقيقة | غير منفذ غالبًا |
| DSG-02-011 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-05 البحث القرآني | باللفظ/الجذر/الموضوع/الرسم، اقتراح إملائي، عدادات وتجميع بالسورة والمشتقات | بحث لفظي مع عبارة/تشكيل، ترتيب قرآني، root index، واجهة نتائج | لا بحث موضوعي أو بالرسم كمسارين واضحين؛ لا fuzzy suggestion؛ لا facets/عداد مشتقات مكتملة أو pagination كبيرة | `quran_search_contract.ts`, `quran_root_search.ts`, `screens/quran.ts`, `packages/search` | corpus 6236 آية؛ حساسية الرسم/الهمزات؛ اقتراحات غير مضللة؛ تجميع وعد صحيح؛ زمن <1s | P0 | فهارس موضوع/رسم موثقة؛ عقد Worker | جزئي |
| DSG-02-012 | part-02-quran-sunnah-search.md | 5 — مركز القرآن | QUR-08 المشاركة | بطاقة آية بثلاثة قوالب وترجمة اختيارية ومعاينة/تصدير | نسخ موثق فقط؛ توجد بنية عامة `quote_card.ts` قد يعاد استخدامها | composer خاص بالآية، خطوط/اتجاه، ترجمة مرخصة، PNG/SVG، metadata ومصدر ثابت | `quote_card.ts`, `screens/quran.ts`, `quran_domain.ts`, styles/assets | snapshot للقوالب؛ النص الطويل؛ الترجمة RTL/LTR؛ تنزيل فعلي؛ المصدر لا يسقط | P2 | dataset ترجمة وترخيص؛ خط عثماني قابل للتضمين | غير منفذ |
| DSG-02-013 | part-02-quran-sunnah-search.md | 6 — مركز السنة | أساس المركز | corpus موحّد موثق للشواهد والأحكام والشروح والترجمات | `sunnah_domain.ts` يعرّف وحدات الحديث والشواهد والرواة والأحكام والمصادر ويفرض provenance؛ registry وعينة ذهبية؛ بوابة مصادر | العقود ليست متصلة بعد بقاعدة واسعة محولة؛ corpus العينة لا يكفي لتجارب التصميم | `sunnah_domain.ts`, `sunnah_source_registry.ts`, pipeline بيانات السنة، حزم الموقع | validation لكل سجل؛ dedupe/identity؛ provenance/license gates؛ عينات مشتركة بين المصادر | P0 | اكتساب/تحويل كتب الشاملة ومصادر حديث مرخصة | نواة فقط |
| DSG-02-014 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-01 صفحة الحديث | صفحة حديث كاملة مع المتن، مصادره، تبويبات الحكم/التخريج/الروايات/الشروح/الغريب/الرواة/الشواهد/الفوائد/الترجمة/التراث | شاشة السنة تفهرس كتب السنة وتبحث في متن corpus عينة؛ لا route حديث كامل | بناء هوية حديث وربط الشواهد، route deep-link، تبويبات وحالات بيانات ناقصة، نسخ موثق واستماع/حفظ | `screens/sunnah.ts`, `sunnah_domain.ts`, `router.ts`, `annotation_store.ts`, styles | فتح معرف ثابت؛ attribution لكل معلومة؛ mobile tabs؛ race/error/empty؛ accessibility | P0 | corpus موحد وعلاقات الحديث | غير منفذ |
| DSG-02-015 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-01 الحكم | أحكام المتقدمين/المعاصرين، كل قول منسوب بمصدره، شارة الدرجة | عقد `ScholarVerdict` وحقول grade/source/provenance | لا تجميع زمني ولا UI ولا تعارض أحكام/درجة مركبة | `sunnah_domain.ts`, `screens/sunnah.ts`, `components.ts` | لا حكم بلا مصدر؛ اختلاف الأحكام ظاهر؛ ألوان ليست الوسيلة الوحيدة؛ ترتيب زمني | P0 | بيانات أحكام موثقة وهوية عالم | عقد فقط |
| DSG-02-016 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-01 التخريج | إجمالي/متوسط/تفصيلي: المواضع، الكتاب والباب والمدار، اختلافات الإسناد والمتن والعلل | الشاهد يحمل مرجع كتاب ورقمًا ورواة؛ validator لترتيب الرواة | لا تجميع طرق ولا مقارنة ألفاظ ولا علل أو مستويات عرض | نماذج جديدة قرب `sunnah_domain.ts`, `screens/sunnah.ts`, pipeline | golden hadith متعدد الطرق؛ مقارنة لفظ؛ صحة المراجع؛ انتقال المستوى يحفظ السياق | P0 | استخراج أسانيد/أبواب/علل من مصادر موثقة | غير منفذ |
| DSG-02-017 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-01 الحديث في التراث | استشهاد عكسي مع مرشحي الفن والقرن | لا فهرس إحالات خاص؛ البحث العام ممكن نصيًا فقط | كشف الاقتباس/الإحالة وربط الحديث المرجعي بدرجة ثقة وfacets | `packages/search`, `search_store.ts`, `screens/sunnah.ts`, pipeline | precision/recall؛ منع خلط الأحاديث المتشابهة؛ pagination وفتح الموضع | P1 | فهرس كتب الشاملة + هوية الحديث | غير منفذ |
| DSG-02-018 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-02 شجرة الإسناد | رسم الطرق، تمييز المدار، علل على الحواف، تقرير مولد، pan/zoom وتصدير | بيانات `NarratorRef` خطية اختيارية فقط؛ توجد علاقات مؤلفين لا إسناد | نموذج graph، layout حتمي RTL، edge annotations، interaction/export، عدم ضغط الجوال | ملف domain/graph جديد، `screens/sunnah.ts`, styles، أداة export | graph cycles/broken links؛ layout snapshot؛ keyboard navigation؛ pan/zoom mobile؛ تقرير يطابق graph | P1 | أسانيد محللة وهوية راوٍ موحدة؛ مكتبة رسم خفيفة | غير منفذ |
| DSG-02-019 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-03 بطاقة الراوي | بطاقة كاملة: الطبقة/الوفاة/الرتبة، أقوال النقاد المنسوبة، الشيوخ والتلاميذ والمصادر | `NarratorRef` يحتوي الاسم/الموضع/صيغة الأداء فقط | كيان راوٍ مستقل وعلاقاته وأقوال الجرح والتعديل وroute/panel | `sunnah_domain.ts`, ملف narrator store جديد، `screens/sunnah.ts`, `router.ts` | attribution؛ دمج الأسماء المتشابهة؛ علاقة عكسية؛ panel desktop/page mobile | P1 | authority file للرواة ومصادر تراجم | غير منفذ |
| DSG-02-020 | part-02-quran-sunnah-search.md | 6 — مركز السنة | HAD-06 المشاركة | ثلاثة قوالب؛ المصدر والدرجة ثابتان؛ خيار إظهار الراوي | لا composer حديث؛ يوجد `quote_card.ts` عام | قالب موثق يمنع إخفاء المصدر/الدرجة، تصدير صورة، معالجة النص الطويل | `quote_card.ts`, `screens/sunnah.ts`, styles/assets | invariant المصدر والدرجة؛ اختلاف القوالب؛ long text؛ download/share fallback | P2 | صفحة الحديث وبيانات الدرجة الموثقة | غير منفذ |
| DSG-02-021 | part-02-quran-sunnah-search.md | 6 — مركز السنة | بوابة السنة | بحث كتب السنة + تصفية الفن + بحث متن corpus | منفذ في `screens/sunnah.ts` و`sunnah_corpus_search.ts` مع اختبارات screen/corpus/domain/source | البحث خطي في عينة ومفصول عن نواة البحث؛ لا pagination أو highlights/facets واسعة | `screens/sunnah.ts`, `sunnah_corpus_search.ts`, `packages/search` | benchmark corpus واقعي؛ Worker؛ pagination؛ تشكيل/همزات؛ إلغاء طلب سابق | P0 | حزم corpus وفهرس مجزأ | جزئي |
| DSG-02-022 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-01 البحث الفوري | overlay من أي مكان؛ فارغ يعرض الشائع والسجل والمتقدم؛ نتائج بعد 3 أحرف | `live_search.ts` يحول الإدخال إلى صفحة البحث عند Enter؛ shell يملك بوابة مركزية | لا overlay واقتراحات لحظية أو سجل/شائع ولا إدارة focus/escape كاملة | `live_search.ts`, `shell.ts`, مكوّن overlay جديد، `router.ts`, styles | debounce/cancel؛ أول نتيجة <1s؛ keyboard/escape/focus trap؛ mobile fullscreen؛ سجل محلي ومسحه | P0 | فهرس متعدد الكيانات Worker | غير منفذ |
| DSG-02-023 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-01 متعدد الكيانات | مؤلفون وكتب وإكمال وأحاديث بدرجتها وآيات ونصوص موثقة | البحث العام يفهرس نصوص الكتب وmetadata؛ روابط تصنيف/مؤلف؛ القرآن والسنة منفصلان | index/result union موحد وترتيب أقسام وتوثيق badges؛ منع مزج أنواع بلا هوية | `packages/search`, `engine/search_store.ts`, `live_search.ts`, `search_author_metadata.ts`, domains القرآن/السنة | ranking fixture؛ نوع وsource لكل hit؛ فتح صحيح؛ نتائج أول 3 أحرف | P0 | حزم books/authors/quran/hadith موحدة | جزئي منخفض |
| DSG-02-024 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-02 صفحة النتائج | قائمة مسطحة، highlight، عداد، فتح الموضع، تحميل/لا نتائج/جوال | منفذ بدرجة جيدة: highlights، metadata، open anchor، loading/no-results، virtualization ودفعات 40 | التنفيذ يجمع كل النتائج من البحث القديم قبل العرض؛ لا pagination مصدرية ولا ربط `packages/search` | `screens/search.ts`, `engine/search_store.ts`, `packages/search`, Worker entry جديد | 10k results؛ pagination stable؛ first paint <1s؛ عدم حجب UI؛ cancellation؛ responsive | P0 | فهرس الشاملة المجزأ وحزم الموقع | جزئي |
| DSG-02-025 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-02 «افتح بنمط» | انسيابي/مطابق للمطبوع/الصفحة الأصلية | قارئات متعددة للصيغ لكن بطاقة البحث تفتح نمطًا واحدًا بحسب الكتاب | menu لكل نتيجة مع capability detection وروابط mode مستقرة | `screens/search.ts`, `screens/reader.ts`, `book_format.ts`, `router.ts` | ظهور الأنماط المتاحة فقط؛ روابط مباشرة؛ PDF/Word/BOK/EPUB | P1 | عقود قدرات القارئ | غير منفذ |
| DSG-02-026 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-02 التجميع | مسطح/بالكتاب/بالمؤلف/بالقرن/بالفن | يوجد ترتيب وتجميع بالكتاب ووظائف ترتيب وفاة؛ مرشحات metadata | لا كل التجميعات التفاعلية ولا عدادات مجموعات/طيها، والتجميع الحالي بعد جلب النتائج | `screens/search.ts`, `search_result_order.ts`, `packages/search` | totals ثابتة؛ تبديل بلا فقد position؛ مجموعات 10k؛ empty groups | P1 | metadata مؤلف/قرن/فن مكتملة في الحزم | جزئي |
| DSG-02-027 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-02 مرشحات البلوكات | أحاديث فقط، آيات، شعر، حواشٍ، فوائد | البحث الحالي يرشح body/heading/tag/card وbook/author/category/century | لا semantic block types لأن ingestion لا ينتجها | schema حزم الشاملة، `packages/search`, `engine/search_store.ts`, `screens/search.ts` | تصنيف block golden set؛ multi-select؛ counts؛ fallback للنص غير المصنف | P1 | محول صفحات الشاملة إلى blocks | غير منفذ |
| DSG-02-028 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-03 المتقدم | عبارة تامة/أي كلمات/استبعاد/تقارب/wildcards؛ تجاهل تشكيل وهمزات؛ جذر/مشتقات | exact/morphological/root تقريبي؛ تطبيع عربي؛ metadata scopes | parser وعقد query حقيقي غير موجود؛ الاشتقاق والجذر موصوفان تجريبيين؛ لا proximity/exclude/wildcard | `packages/search`, `search_presentation.ts`, `screens/search.ts`, tests parser | grammar/property tests؛ escaping/ReDoS؛ exact/proximity fixtures؛ URL round-trip | P0 | قرار محلل عربي موثق؛ إصدار schema index | جزئي |
| DSG-02-029 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-03 نطاق زمني وحقول | قرن/مدى وفاة، كتب/مؤلفون/تصنيفات، حقول متن/عناوين/وسوم/بطاقة | منفذ في `screens/search.ts` و`search_store.ts` مع hash query واختبارات metadata | يلزم نقله إلى query على الفهرس المجزأ بدل filter/scan، وإظهار chips قابلة للحذف | `packages/search`, `screens/search.ts`, `hash_query_state.ts`, metadata pipeline | URL persistence؛ حذف chip؛ intersect filters؛ مجهول الوفاة؛ أداء | P0 | metadata كاملة في shard descriptors | جزئي متقدم |
| DSG-02-030 | part-02-quran-sunnah-search.md | 7 — البحث | SRC-03 جودة المصدر | نص محقق/OCR بنسبة/مصوّر فقط + شريط التدقيق والربط | توجد شاشة جودة بيانات للمكتبة وبعض metadata، لا facets جودة في نتيجة البحث | quality schema لكل document/hit وفلترة/عرض شفاف | `library_data_quality.ts`, schema الحزم, `packages/search`, `screens/search.ts` | لا ادعاء نسبة بلا مصدر؛ filter combinations؛ missing quality | P1 | pipeline الاكتساب والتحويل وقياسات OCR/ربط | غير منفذ |
| DSG-02-031 | part-02-quran-sunnah-search.md | 7 — البحث | نواة البحث | فهرس معكوس مجزأ، phrase verification، pagination، serialize/restore، Worker | منفذ في `packages/search/src/index.ts` واختباره يشمل 20k وثيقة/10k مطابقات؛ limit حتى 500 | العقد handler موجود لكن لا Worker runtime/bundling في app، لا تحميل shards من manifests، لا بحث متعدد shards/merge/ranking/cancel | `packages/search/src/index.ts`, worker entry في app، `engine/search_store.ts`, manifests تحت `public/library` | worker integration؛ shard corruption/version؛ multi-shard merge؛ cancel/drop؛ cold/warm benchmark | P0 | مولد shards من حزم الشاملة | نواة منفذة، دمج غير منفذ |
| DSG-02-032 | part-02-quran-sunnah-search.md | 7 — البحث | الأداء والعرض | أول النتائج <1s، 10k نتيجة مع pagination والعرض الافتراضي | virtualization في UI واختبار أداء نواة سريع؛ الجدولة القديمة تعاونية 16ms | المسار المنتج ما زال `searchAllBooks` يفهرس/يمر على الكتب ويعيد مصفوفة كاملة؛ لا SLO end-to-end على بيانات الشاملة | `engine/search_store.ts`, `search_yield.ts`, `screens/search.ts`, `packages/search`, أدوات benchmark | e2e 10k؛ cold load؛ memory budget؛ long tasks؛ mobile baseline؛ pagination correctness | P0 | اكتمال ingestion والشاردات وWorker | غير محقق طرفيًا |
| DSG-02-033 | part-02-quran-sunnah-search.md | 7 — البحث | LIB-03 ضمن تصميم البحث | استكمال صفحة الكتاب: الجودة، عائلة الكتاب، الاقتباس، التقييمات، المعاينة، الاستشهاد/الوقف | توجد صفحات كتاب/طبعات/سلاسل وتقييم جودة متناثرة، وبيانات علاقات/مكتبة | توحيدها في صفحة الكتاب، علاقات شروح/مختصرات/منظومات، استشهادات عكسية ومؤشرات وقف | `screens/book.ts`, `edition_groups.ts`, `book_series.ts`, `library_data_quality.ts`, search index | العلاقات واتجاهاتها؛ provenance؛ 3 حالات جودة؛ mobile | P2 | metadata وعلاقات كتب مستخرجة | جزئي |
| DSG-02-034 | part-02-quran-sunnah-search.md | 7 — البحث | LIB-04 ضمن تصميم البحث | استكمال صفحة المؤلف: شيوخه/تلاميذه/من نقل عنه | توجد علاقات مؤلفين وgraph واختبارات لها | عرض التصور الكامل وربط «من نقل عنه» بنتائج استشهاد عكسي | `author_relations.ts`, `author_relation_graph.ts`, شاشة المؤلف/التصفح | cycles؛ unknown dates؛ deep links؛ citation counts | P2 | authority data وفهرس الاستشهادات | جزئي |
| DSG-02-035 | part-02-quran-sunnah-search.md | 7 — البحث | LIB-02 ضمن تصميم البحث | شجرة علمية للأقسام والفرع الحالي | taxonomy links وبعض تصنيفات؛ لا شجرة علمية تفاعلية كاملة | نموذج هرمي/شبكي، counts، breadcrumb، current branch، responsive | `taxonomy_links.ts`, `screens/browse.ts`, styles، catalog pipeline | tree integrity/no orphans؛ counts؛ keyboard tree semantics؛ mobile | P2 | taxonomy موحدة لحزم الشاملة | غير منفذ/جزئي منخفض |
| DSG-03-001 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | DSC-01 شبكة الأقسام | 24 قسمًا علميًا ببطاقات، أعداد كتب، وصول من بوابة «اكتشف»، واستجابة للجوال | `screens/browse.ts` يعرض «رفوفك» من كتب الجهاز؛ `shell.ts` يثبت بوابات اقرأ/اكتشف/أنا؛ توجد روابط تصنيف ومرشحات في المكتبة | الاستكشاف الحالي شخصي لا كتالوجي؛ لا شجرة 24 قسمًا ولا أعداد منشورة ولا صفحة قسم | `screens/browse.ts`, `taxonomy_links.ts`, `data.ts`, `shamela_catalog.ts`, `ui.ts` | عقد الأقسام، صحة الأعداد، روابط عميقة، حالات فارغ/تحميل/خطأ، responsive + keyboard | P0 | يعتمد على حزم التصنيفات والكتب المنشورة وهوية تصنيف مستقرة | جزئي |
| DSG-03-002 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | DSC-01 داخل القسم | صفحة «الحديث» بمرشح القرن/المحقق/الناشر وترتيب وأوسمة الطبعات | `screens/library.ts` يدعم بحثًا ومرشحات محلية وبيانات مؤلف/تصنيف/وسوم؛ `search_metadata_filters_contract.test.ts` يغطي بعض المرشحات | لا مسار قسم مستقل، ولا مرشح قرن/محقق/ناشر متكامل على الكتالوج المنشور، ولا تعداد نتائج موثوق | `screens/browse.ts`, `screens/library.ts`, `book_format.ts`, `data.ts`, `router.ts` | property tests للمرشحات المركبة، ثبات URL، pagination، الأداء على كتالوج كبير | P0 | بعد تطبيع metadata للشاملة | جزئي |
| DSG-03-003 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | DSC-02 البحث الشامل الأساسي | ستة نطاقات: الكل، العناوين، الأعلام، نصوص الكتب، الآيات، الأحاديث؛ نتائج مجمعة ومرشحات جانبية و«افتح بـ…» | `screens/search.ts` و`live_search.ts` وبوابة بحث مركزية؛ نواة `packages/search`؛ بحث قرآن وسنة مستقل؛ بيانات مؤلف | لا تجميع موحد فعلي للأنواع الستة في استجابة واحدة، ولا عقد facet موحد أو انتقال دقيق من كل نتيجة | `screens/search.ts`, `central_search_gateway_contract.test.ts`, `live_search.ts`, `packages/search/src/index.ts`, `quran_search_contract.ts`, `sunnah_corpus_search.ts` | دمج الأنواع، ترتيب ثابت، highlighting آمن، pagination 10k، أول نتيجة <1s، worker cancellation | P0 | يعتمد على حزم فهارس الشاملة وهوية block/موضع | جزئي |
| DSG-03-004 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | DSC-03 صفحة الكتاب | بطاقة ثرية: وصف، فهرس متوسع، طبعة ومحقق وأجزاء/صفحات، قراءة/تنزيل/إضافة، طبعات أخرى، كتب مشابهة | `screens/book.ts` يقدم بيانات أساسية، معاينة أجزاء، خطة قراءة، ورفوف؛ `editions.ts` يجمع الطبعات؛ حساب الصفحات واختبارات الهوية موجودة | لا فهرس هرمي كامل داخل البطاقة، لا تنزيل مُدار، لا جودة/موافقة للمطبوع، لا إحصاءات البلوكات/تقييمات/QR، ولا «مشابه» مدمج | `screens/book.ts`, `reader_toc.ts`, `editions.ts`, `book_series.ts`, `reading_recommendations.ts`, `offline_policy.ts` | بطاقة ذهبية من SQLite، فهرس عميق، طبعات ومعتمدة، روابط مواضع، توصيات شفافة، a11y | P0 | للبيانات والفهرس؛ P1 للتوصيات؛ المجتمع/التقييم P3 | جزئي |
| DSG-03-005 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | DSC-04 صفحة المؤلف | ترجمة، خط زمني هجري، مصنفات بحسب الفن، شيوخ/تلاميذ، وتأثير/استشهاد عكسي | `authorsScreen` و`authorBooksScreen` يعرضان السجل والعصر والكتب؛ `author_relations.ts` و`author_relation_graph.ts` وعلاقات علمية مدققة | لا خط زمني أو تجميع مصنفات بالفن/التاريخ، ولا «كل ما نُقل عنه» من corpus، وعرض العلاقات أقل ثراءً من التصميم | `screens/library.ts`, `author_relations.ts`, `author_relation_graph.ts`, `search_author_metadata.ts`, `data.ts` | بيانات ذهبية لمؤلفين متعددين، علاقات تبادلية، chronology، تجميع فنون، empty/unknown metadata | P1 | يعتمد على حزمة المؤلفين/العلاقات واستشهادات النص | جزئي |
| DSG-03-006 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | الرؤية 1.4 التصنيف الشجري | تصنيف كامل متعدد المستويات لا قائمة مسطحة فقط | تصنيف نصي وروابط taxonomy في عدة شاشات | لا نموذج أب/أبناء ولا breadcrumbs أو استيراد مضبوط للشجرة | `taxonomy_links.ts`, `shamela_catalog.ts`, `screens/browse.ts`, `screens/library.ts` | دورات/عقد يتيمة، breadcrumb، انتقال وتصنيف متعدد | P0 | أساس DSC-01 والبحث | جزئي |
| DSG-03-007 | part-03-discovery-library-account.md | 7ج — الاستكشاف الجزئي | الرؤية 13.181–190 الاستكشاف الذكي | توصيات مفسرة، مزاج/حاجة، مختارات يومية، مسارات، «ماذا بعده؟» | `reading_recommendations.ts` يرتب كتبًا غير مقروءة ويعطي سببًا؛ `recommendation_preferences.ts` يحفظ الرفض؛ خطط قراءة أساسية | لا persona/مستوى/هدف، لا قوائم تحريرية أو مزاج، لا «اقترح غيره» متكامل، ولا مسارات أهل العلم | `reading_recommendations.ts`, `screens/home.ts`, `screens/browse.ts`, `reading_plan.ts`, `reading_journeys.ts` | شفافية السبب، عدم اقتراح المقروء/المرفوض، cold start، وضع السكينة، خطط قابلة للاستئناف | P1 | /P2؛ يعتمد على التهيئة وبيانات النشاط؛ الذكاء M2 | جزئي |
| DSG-03-008 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | QLT-01 أبلغ عن مشكلة | من الموضع بنقرتين، ستة أنواع، التقاط الكتاب/الجزء/الصفحة/النص وقصاصة المطبوع، تصحيح اختياري، رقم بلاغ | توجد شاشة `data_quality.ts` لتدقيق metadata محليًا، وبنية source-sync/quarantine على مستوى المصادر | لا فعل قارئ لبلاغ المستخدم، لا نموذج/مخزن بلاغ، لا التقاط موضع أو قصاصة، ولا outbox محلي | `screens/reader.ts`, ملف جديد `quality_report_store.ts`, `packages/source-sync/src/outbox.ts`, `source-sync_ui.ts` | التقاط الموضع، نقرتان، offline outbox، idempotency، الخصوصية، رفض payload كبير، a11y | P1 | يحتاج هوية موضع مستقرة وعقد خادم قبل المزامنة | غير منفذ |
| DSG-03-009 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | QLT-02 بلاغاتي | قائمة حالات، نقاط مساهمة، قبل/بعد، سبب رفض، حالة فارغة | لا شاشة/route مخصصة؛ توجد عقود خادم للمراجعات والسجل والحجر لكنها إدارية | ينقص نموذج حالة مستخدم وواجهة مزامنة وإشعارات النتيجة؛ نقاط المساهمة غير موجودة | `router.ts`, شاشة جديدة `screens/reports.ts`, `packages/source-sync-server/src/revision-history.ts`, `source-sync_ui.ts` | state machine، صلاحية صاحب البلاغ، before/after، empty/error، offline reconciliation | P2 | بعد QLT-01 وخدمة مصادقة اختيارية | غير منفذ |
| DSG-03-010 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | LIB-05 الشجرة العلمية | أصل وشروح وحواشٍ ومختصرات ومنظومات عبر القرون، مرشح وتصفح أفقي | `book_series.ts`, `edition_groups.ts`, `screens/series.ts` وشاشة مركز السلاسل موجودة | العرض الحالي تجميعي أولي؛ لا graph زمني غني ولا أنواع علاقات كاملة أو تصفح من صفحة الكتاب | `screens/series.ts`, `book_series.ts`, `screens/book.ts`, `ui.ts` | graph بلا دورات، ترتيب هجري، filtering، keyboard pan/zoom، mobile overflow | P1 | يعتمد على استيراد علاقات الكتب | جزئي |
| DSG-03-011 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | LIB-06 رفوفي | رفوف نظام وشخصية، اسم/لون/خصوصية، مشاركة، تقدم، مكتمل، شبكة/قائمة، إعادة ترتيب بالسحب | `shelf_store.ts` يوفر create/list/remove/set membership؛ `screens/shelves.ts` ودمج الرفوف بصفحة الكتاب والمكتبة | لا لون/خصوصية/مشاركة، لا رفوف نظام، لا ترتيب كتاب/رف، ولا عرض شبكة/قائمة غني؛ التخزين localStorage وغير scoped بملف | `shelf_store.ts`, `screens/shelves.ts`, `screens/library.ts`, `screens/book.ts`, `session_identity.ts` | migration للتخزين، CRUD، ترتيب DnD ولوحة مفاتيح، privacy defaults، profile isolation | P0 | قبل الحساب المتعدد يجب إصدار schema وهوية scope | جزئي |
| DSG-03-012 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | LIB-07 التنزيلات | مساحة مخصصة، نص/صور/صوت، تقدم/انتظار Wi‑Fi، حذف/تحديث، توفير بيانات، تنزيل مجموعات بشجرة ثلاثية الحالة | service worker و`offline_policy.ts` وملفات منشورة محلية؛ حالة offline في الإعدادات | لا download manager أو quota/resume، ولا تفصيل مكونات الكتاب أو سياسة Wi‑Fi/90 يومًا، ولا تنزيل جماعي | ملفات جديدة `download_store.ts`, `screens/downloads.ts`; `offline_policy.ts`, `reader_cache.ts`, `public/sw.js`, `artifact_download.ts` | quota/eviction، resume/CRC، فشل وسط التنزيل، tri-state، no duplicate fetch، mobile storage pressure | P0 | لكتب الشاملة الفعلية؛ يعتمد على manifest الحزم وأحجامها | غير منفذ كرحلة؛ أساس تقني جزئي |
| DSG-03-013 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | LIB-08 جديد المكتبة | أسبوعي: أضيف/حُدّث، مصدر، عدد الطلبات، اشتراك إشعارات، سجل تغييرات يذكر البلاغ | `published_library_seed.ts` وmanifest منشور، وسجل مراجعات في source-sync server | لا feed زمني للمستخدم ولا تبويبان/اشتراك، ولا ربط changelog بالكتاب أو بلاغ المستخدم | شاشة جديدة `screens/library_updates.ts`, `published_library_seed.ts`, `packages/source-sync-server/src/revision-history.ts` | delta manifests، timezone/week grouping، dedupe، deep links، changelog provenance | P1 | يعتمد على publication revisions؛ الإشعار بعد مركز الإشعارات | غير منفذ |
| DSG-03-014 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | الرؤية 1.13 طلب كتاب | طلب عام مع تتبع وتصويت | لا مقابل ظاهر | نموذج طلب/تصويت/مكافحة إساءة وخدمة | شاشة ومخزن جديدان + عقود `source-sync-server` | dedupe، تصويت واحد، حالات، rate limits، guest policy | P3 | خدمة خارجية وصلاحيات | غير منفذ |
| DSG-03-015 | part-03-discovery-library-account.md | 8 — المكتبة الشخصية والجودة | الرؤية 15.206–207 سجل الجودة | سجل علني ومقياس جودة لكل كتاب | `data_quality.ts` يفحص نواقص محلية؛ revision history خلفي موجود | لا مقياس مستخدم موحد أو provenance منشور على بطاقة الكتاب | `screens/book.ts`, `screens/data_quality.ts`, source revision contracts | حساب الدرجة، عدم الادعاء عند نقص البيانات، changelog integrity | P1 | بعد حزم metadata والمراجعات | جزئي |
| DSG-03-016 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | NOT-01 دفتر الكتاب | تجميع حسب أبواب الكتاب، أربعة ألوان، ملاحظات وتأملات، مشاركة وتصدير Word/PDF/Markdown | `annotation_store.ts` يدعم 4 ألوان وملاحظات/تظليلات؛ قارئ يعرض محفوظات الكتاب؛ `notes.ts` يجمعها عالميًا | لا صفحة دفتر كتاب مستقلة أو تجميع TOC، لا تأملات/وسوم، ولا تصدير الأنواع الثلاثة أو مشاركة | `screens/reader.ts`, `screens/notes.ts`, `annotation_store.ts`, `reader_toc.ts`, `annotations_markdown.ts`, `research_project_docx.ts` | grouping بالموضع، ألوان، export round-trip، RTL Word/PDF، حذف/استعادة، a11y | P0 | يستلزم schema موحدًا للمحفوظات وهوية موضع | جزئي |
| DSG-03-017 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | NOT-02 الدفتر العام | كل الكتب، بحث، وسوم حرة، مرشحات كتاب/لون/نوع/تاريخ، حالات فارغة | `screens/notes.ts` يبحث ويصفي أنواعًا (ومنها مراجعات مجدولة) ويعرض اسم الكتاب والعودة للموضع | لا وسوم حرة ولا مرشحات كاملة/URL state ولا فصل التأملات؛ نموذج الملاحظة نصي بسيط | `screens/notes.ts`, `annotation_store.ts`, `hash_query_state.ts`, `spaced_review.ts` | facets مركبة، tags Unicode، URL restore، آلاف العناصر، اسم كتاب دائم | P0 | بعد ترقية schema | جزئي |
| DSG-03-018 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | NOT-03 محرر الملاحظة | نص/صوت/صورة، وسوم، تأمل موسع، خصوصية خاصة افتراضيًا ونشر بعد الإجازة | `addNote` نص فقط؛ نموذج داخل القارئ؛ ملفات audio core تخص مصادر/تشغيل وليست ملاحظات مسجلة | لا مرفقات/تسجيل/وسوم/تأملات/سياسة نشر؛ يلزم تخزين blobs وحدود حجم | `annotation_store.ts`, `screens/reader.ts`, `screens/notes.ts`, ملفات جديدة للمرفقات/التأمل | إذن الميكروفون، إلغاء التسجيل، quota، MIME validation، privacy default، XSS في markdown | P1 | للنص+وسوم؛ P2 للمرفقات؛ النشر P3 | جزئي جدًا |
| DSG-03-019 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | NOT-08 القاموس والمفردات | ضغط مطول، معجمان بمصدرهما، إضافة كلمة وسياقها، دفتر وبطاقات مراجعة M2 | لا قاموس/مخزن مفردات ظاهر؛ توجد مراجعة متباعدة للمحفوظات لا الكلمات | كامل الرحلة ومصادر البيانات والتراخيص؛ البطاقات صريحة M2 | `screens/reader.ts`, ملفات `dictionary.ts`, `vocabulary_store.ts`, شاشة دفتر؛ `spaced_review.ts` | صرف الكلمة/التشكيل، attribution، offline lookup، context position، keyboard/touch | P2 | يعتمد على حزم معاجم مرخصة؛ flashcards M2 | غير منفذ |
| DSG-03-020 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | NOT-06 مصمم الاقتباس | 3 قوالب، نسب وأحجام واسم اختياري، توثيق وشعار ثابتان، تنزيل/مشاركة/نسخ، واقتباس قصاصة المطبوع | `quote_card.ts` يولد SVG بثلاث سمات وتوثيق كتاب/مؤلف/صفحة؛ `notes.ts` ينزله؛ `rich_clipboard.ts` والنسخ الموثق موجودان | لا شاشة مصمم أو نسب/حجم/اسم، ولا تحقق شعار ثابت، ولا قصاصة PDF موثقة؛ بيانات الطبعة/الرابط ناقصة | `quote_card.ts`, `screens/notes.ts`, `screens/reader.ts`, `rich_clipboard.ts`, `pdf` preview helpers | snapshot SVG، bidi/escaping، ratios، high-DPI download، citation completeness، crop bounds | P1 | قصاصة الصورة تعتمد على page mapping/PDF | جزئي |
| DSG-03-021 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | «أثر القراءة» | استعادة المحفوظات أو قراءة نظيفة تخفيها دون حذفها | موضع القراءة والأنشطة محفوظان؛ المحفوظات مستقلة في store | لا session-level visibility mode ولا بطاقة إعادة الفتح/استعادة | `screens/book.ts`, `screens/reader.ts`, `reading_data.ts`, `annotation_store.ts` | clean mode لا يحذف، restore، تعدد الكتب/الملفات، reload persistence | P1 | بعد scope الملف الشخصي | غير منفذ |
| DSG-03-022 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | SHL-03 التهيئة الأولى | 4 خطوات قابلة للتخطي: اللغة، persona، الاهتمامات، الورد، ثم ختام | `welcome.ts` للبدء/الاستيراد؛ إعدادات وورد/خطط وتوصيات منفصلة | لا wizard أو تخزين persona/interests، ولا أثر مشروح على كثافة الواجهة | `screens/welcome.ts`, `settings_store.ts`, `recommendation_preferences.ts`, `reading_plan.ts`, `router.ts` | skip/return، migration، RTL/لغة، persona effect، no forced account | P1 | مدخل للتوصيات لا مانع لاستخدام التطبيق | غير منفذ |
| DSG-03-023 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | SHL-04 الإشعارات | مركز، سحب للإخفاء، فئات مستقلة، ساعات هدوء، لا تسويق | لا مركز إشعارات؛ توجد بيانات مراجعة/خطط يمكن أن تولد أحداثًا | نموذج notification محلي، permissions، scheduler، quiet hours، deep links، إعداد لكل فئة | ملفات `notification_store.ts`, `screens/notifications.ts`; `reading_plan.ts`, `spaced_review.ts`, PWA service worker | timezone/DST، quiet hours، permission denied، dedupe، deep link، swipe + keyboard | P2 | تطبيق ويب قد يقيد الجدولة؛ لا push خارجي دون إذن | غير منفذ |
| DSG-03-024 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | ACC-01 حساب اختياري/ضيف | بريد أو هاتف مع «تابع دون حساب» متساوي البروز؛ كل المحلي يعمل للضيف؛ التسجيل يضيف المزامنة | `session_identity.ts` يعرّف guest/device identity؛ `settings.ts` يصرح أن الحساب اختياري ولا يرفع دون مزود؛ عقود هوية/أجهزة في source-sync | لا شاشة دخول أو provider فعلي أو ترقية ضيف لحساب؛ الهوية في shell ضيف ثابت | `session_identity.ts`, `screens/welcome.ts`, شاشة login، `source_sync_ui.ts`, حزم source-sync server/cloudflare | guest parity، upgrade merge، token expiry، logout keeps/clears choice، no upload before consent | P1 | عقد محلي؛ التفعيل الخارجي يحتاج إذن ومزود | جزئي بنيويًا |
| DSG-03-025 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | ACC-02 تعدد الملفات | ملفات مستقلة للرفوف والورد والإحصاءات مع تبديل سريع | `identityScope` موجود لكن stores الحالية (رفوف/ملاحظات/إعدادات) مفاتيح عامة؛ لا UI profiles | نموذج profile محلي وترحيل/scoping لكل بيانات المستخدم وتبديل ذري | `session_identity.ts`, `shelf_store.ts`, `annotation_store.ts`, `reading_data.ts`, `settings_store.ts`, `shell.ts`, `screens/me.ts` | migration بلا فقد، isolation، switch أثناء القراءة، حذف/تصدير ملف، default profile | P0 | قبل توسيع بيانات المستخدم؛ تغيير عابر للحزم يحتاج خطة migration | غير منفذ |
| DSG-03-026 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | SET-01 الإعدادات/وضع السكينة | السكينة أولًا؛ المظهر/القراءة/اللغة/البيانات/الخصوصية؛ AI موسوم M2 | `screens/settings.ts` و`settings_store.ts`: السمات، حجم واجهة وقارئ، التباين، تقليل الحركة، تصدير/استيراد، offline، حساب ومزامنة اختيارية | لا وضع سكينة مستقل، لا لغة/تنسيقات أو إعدادات إشعار، ولا قسم خصوصية شامل؛ الحفظ محلي لا حسابي | `screens/settings.ts`, `settings_store.ts`, `motion_preference.ts`, `ui_translations.ts`, `screens/home.ts`, `screens/me.ts` | effect contracts لكل toggle، live persistence، reset، export/import، reduced motion | P0 | للسكينة والخصوصية؛ P1 للغة؛ مزامنة بعد الحساب | جزئي قوي |
| DSG-03-027 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | SET-02 إمكانية الوصول | حتى 200%، تباين، عسر قراءة، وضع أساسي، قارئ شاشة، معاينة حية | حجم واجهة/قارئ وتباين وتقليل حركة مطبقة؛ اختبارات forced colors/navigation/motion موجودة | لا dyslexia mode ولا basic mode أو preview؛ لا حد 200% موحد مثبت، ولا لوحة اختصارات/تحكم خارجي | `screens/settings.ts`, `settings_store.ts`, `ui.ts`, `navigation_accessibility.ts`, CSS | 200% reflow، WCAG keyboard/screen reader، live preview، basic-mode route guard، forced colors | P0 | للـreflow/basic؛ P1 لعسر القراءة بعد اختيار خط صالح | جزئي |
| DSG-03-028 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | الرؤية 11.162–167 المزامنة والملكية | مزامنة لحظية، offline كامل، استيراد خارجي، تصدير مفتوح، خصوصية | source-sync متعدد الحزم وعقود outbox/revisions/devices؛ أرشيف ZIP/JSON محلي؛ التطبيق يعمل محليًا | مزامنة بيانات المستخدم غير موصولة نهائيًا؛ لا Kindle/Goodreads؛ لا سياسة تعارض UI؛ بعض exports لا تشمل كل كيانات المستقبل | `source_sync_ui.ts`, `packages/source-sync*`, `library_archive.ts`, كل stores | offline edits/conflicts، encryption/authz، export completeness، account deletion، recovery | P1 | /P2؛ يحتاج ACC-01/02 وموافقة على البنية الخارجية | جزئي بنيويًا |
| DSG-03-029 | part-03-discovery-library-account.md | 9 — معرفتي، الحساب، الإعدادات | الرؤية 18.224–228 بوابة «أنا» | لوحة هادئة: استكمال، ورد، مراجعة، اقتباس، جديد؛ تنقل ثلاثي وبحث دائم | `screens/me.ts` يلخص القراءة ووصولًا سريعًا وإيقاع 4 أسابيع؛ `home.ts` غني؛ البوابات الثلاث ثابتة | مركز «أنا» لا يطابق كل وحدات اليوم؛ البحث ليس مثبتًا حرفيًا في كل شاشة؛ الإشعارات/الجديد ناقصان | `screens/me.ts`, `screens/home.ts`, `shell.ts`, `live_search.ts` | presence عبر routes، وضع السكينة، empty states، mobile bottom nav | P1 | بعد الإشعارات/الجديد؛ التنقل مكتمل | جزئي |
| DSG-03-030 | part-03-discovery-library-account.md | متطلبات عابرة مستخرجة من وثيقة الرؤية وREADME | README — سلطة الملفات | `7ج` قاعدة الاستكشاف فقط، و`7` الرسمي استكمال إلزامي؛ `8` و`9` مستقلان؛ النموذج التأسيسي متجاوز | قاعدة عابرة ملزمة مستخرجة من المرجع؛ يلزم التحقق منها في كل دفعة. | تطبيق القاعدة على جميع الأعمال ذات الصلة وإثباتها آليًا. | بحسب الميزة المرتبطة؛ يحدد قبل بدء الدفعة مع منع تعارض الملكية. | بوابة تعاقدية تثبت الالتزام بالقاعدة وعدم الانحدار. | P0 | لا تبعيات إضافية موثقة. | مفتوح |
| DSG-03-031 | part-03-discovery-library-account.md | متطلبات عابرة مستخرجة من وثيقة الرؤية وREADME | README — M1 مكتمل تصميميًا | الجلسة 9 تقول إن M1 اكتمل تصميميًا، لا برمجيًا | قاعدة عابرة ملزمة مستخرجة من المرجع؛ يلزم التحقق منها في كل دفعة. | تطبيق القاعدة على جميع الأعمال ذات الصلة وإثباتها آليًا. | بحسب الميزة المرتبطة؛ يحدد قبل بدء الدفعة مع منع تعارض الملكية. | بوابة تعاقدية تثبت الالتزام بالقاعدة وعدم الانحدار. | P1 | لا تبعيات إضافية موثقة. | واضح/غير مكتمل برمجيًا |
| DSG-03-032 | part-03-discovery-library-account.md | متطلبات عابرة مستخرجة من وثيقة الرؤية وREADME | الرؤية — الكتاب الحي | هوية block وأنواع دلالية هي أساس الروابط والدفاتر والاستشهاد | قاعدة عابرة ملزمة مستخرجة من المرجع؛ يلزم التحقق منها في كل دفعة. | تطبيق القاعدة على جميع الأعمال ذات الصلة وإثباتها آليًا. | بحسب الميزة المرتبطة؛ يحدد قبل بدء الدفعة مع منع تعارض الملكية. | بوابة تعاقدية تثبت الالتزام بالقاعدة وعدم الانحدار. | P1 | لا تبعيات إضافية موثقة. | جزئي |
| DSG-03-033 | part-03-discovery-library-account.md | متطلبات عابرة مستخرجة من وثيقة الرؤية وREADME | الرؤية — المحلية أولًا | الضيف والقراءة الأساسية دون حساب، والبيانات ملك المستخدم | قاعدة عابرة ملزمة مستخرجة من المرجع؛ يلزم التحقق منها في كل دفعة. | تطبيق القاعدة على جميع الأعمال ذات الصلة وإثباتها آليًا. | بحسب الميزة المرتبطة؛ يحدد قبل بدء الدفعة مع منع تعارض الملكية. | بوابة تعاقدية تثبت الالتزام بالقاعدة وعدم الانحدار. | P0 | لا تبعيات إضافية موثقة. | متحقق أساسًا |
| DSG-03-034 | part-03-discovery-library-account.md | متطلبات عابرة مستخرجة من وثيقة الرؤية وREADME | الرؤية — مراحل المنتج | M1: المكتبة/القارئ/الربط/المراكز/البحث/أدوات القارئ؛ M2: الذكاء والعادة والتوصيات؛ M3: الباحث والجودة والمجتمع | قاعدة عابرة ملزمة مستخرجة من المرجع؛ يلزم التحقق منها في كل دفعة. | تطبيق القاعدة على جميع الأعمال ذات الصلة وإثباتها آليًا. | بحسب الميزة المرتبطة؛ يحدد قبل بدء الدفعة مع منع تعارض الملكية. | بوابة تعاقدية تثبت الالتزام بالقاعدة وعدم الانحدار. | P1 | لا تبعيات إضافية موثقة. | جارٍ |

## قواعد التحديث

- لا يغيّر المعرف الثابت بعد إنشائه.
- بعد كل دفعة: تحدّث الحالة الحالية والفجوة والملفات والاختبارات والإنجاز، ثم تحدّث المرحلة المطابقة في `DESIGN_PHASE_PLAN.md`.
- لا تصبح بيانات العرض التجريبية حقائق إنتاجية دون مصدر وترخيص واختبار.
- التنفيذ الحالي هو الأصل عند التعارض، والتصورات الإضافية تبقى متطلبات حتى توسم «مكتمل» بدليل اختبار.
