export interface PackProvenance{provider:string;sourceUrl:string;retrievedAt:string;version:string;checksumSha256:string;license:string|null}
export interface AudioMediaVariant{variantId:string;mimeType:"audio/mpeg"|"audio/ogg"|"audio/mp4";url:string;byteLength:number|null;checksumSha256:string|null;byteRanges:boolean}
export interface AudioSegment{segmentId:string;chapterId:string;startMs:number;endMs:number;title:string;ayahRef?:{surah:number;ayah:number};transcriptRef?:string}
export interface AudioChapter{chapterId:string;title:string;index:number;segments:readonly AudioSegment[]}
export interface AudioWorkPack{schemaVersion:1;workId:string;kind:"recitation"|"audiobook"|"lecture";title:string;speaker:string;reciter?:string;riwaya?:string;durationMs:number;chapters:readonly AudioChapter[];variants:readonly AudioMediaVariant[];provenance:PackProvenance;offline:{cachePolicy:"explicit";resume:true;eviction:"lru-unpinned"}}
export interface SearchPackContract{schemaVersion:1;normalization:{ignoreArabicDiacriticsByDefault:true;diacriticSensitiveOptIn:true};ranking:readonly["exact","prefix","all-terms","broad"]}
export interface AudioCatalogSource{sourceId:string;workId:string;kind:"recitation"|"audiobook"|"lecture";title:string;speaker:string|null;reciter?:string|null;riwaya?:string|null;chapterIds:readonly string[];segmentation:"chapter"|"segment";mediaBaseUrl:string;timingManifestUrl:string|null;durationMs:null;checksumSha256:null}
export interface AudioSourceCatalog{schemaVersion:1;catalogId:string;entries:readonly AudioCatalogSource[];provenance:PackProvenance;offline:{metadataOnly:true;mediaDownload:"explicit"}}
export const DEFAULT_SEARCH_PACK_CONTRACT:SearchPackContract={schemaVersion:1,normalization:{ignoreArabicDiacriticsByDefault:true,diacriticSensitiveOptIn:true},ranking:["exact","prefix","all-terms","broad"]};
export function validateAudioWorkPack(p:AudioWorkPack){if(p.schemaVersion!==1||!p.workId||!p.title||!p.speaker||!Number.isSafeInteger(p.durationMs)||p.durationMs<0)throw Error("audio_pack_invalid");for(const c of p.chapters){if(!c.chapterId||!Number.isSafeInteger(c.index)||c.index<0)throw Error("audio_chapter_invalid");for(const s of c.segments){if(s.chapterId!==c.chapterId||s.startMs<0||s.endMs<=s.startMs||s.endMs>p.durationMs)throw Error("audio_segment_invalid");if(s.ayahRef&&(!Number.isSafeInteger(s.ayahRef.surah)||s.ayahRef.surah<1||s.ayahRef.surah>114||!Number.isSafeInteger(s.ayahRef.ayah)||s.ayahRef.ayah<1))throw Error("audio_ayah_ref_invalid")}}for(const v of p.variants){const u=new URL(v.url);if(u.protocol!=="https:"||v.byteLength!==null&&(!Number.isSafeInteger(v.byteLength)||v.byteLength<0)||v.checksumSha256!==null&&!/^[0-9a-f]{64}$/.test(v.checksumSha256))throw Error("audio_variant_invalid")}return p}
export function validateAudioSourceCatalog(c:AudioSourceCatalog){if(c.schemaVersion!==1||!c.catalogId||c.offline.metadataOnly!==true||c.offline.mediaDownload!=="explicit")throw Error("audio_catalog_invalid");const ids=new Set<string>();for(const e of c.entries){if(!e.sourceId||!e.workId||!e.title||ids.has(e.sourceId)||e.durationMs!==null||e.checksumSha256!==null)throw Error("audio_catalog_entry_invalid");ids.add(e.sourceId);const media=new URL(e.mediaBaseUrl);if(media.protocol!=="https:")throw Error("audio_catalog_url_invalid");if(e.timingManifestUrl!==null&&new URL(e.timingManifestUrl).protocol!=="https:")throw Error("audio_catalog_url_invalid");if(e.chapterIds.some(id=>!/^\d{1,3}$/.test(id)))throw Error("audio_catalog_chapter_invalid")}return c}
