import { isAbsolute } from "node:path";
export type ServicePlatform = "win32" | "darwin" | "linux";
export interface ServiceDescriptorOptions { name:string; executablePath:string; configPath:string; stdoutPath:string; stderrPath:string; restartSeconds:number }
export interface ServiceInstallPlan { platform:ServicePlatform; operation:"install"|"uninstall"; requiresExplicitConfirmation:true; commands:readonly { executable:string; args:readonly string[] }[]; rollbackCommands:readonly { executable:string; args:readonly string[] }[]; descriptor?:string }
function valid(o:ServiceDescriptorOptions){if(!/^[A-Za-z0-9_.-]+$/.test(o.name))throw Error("invalid service name");for(const [k,v] of Object.entries({executablePath:o.executablePath,configPath:o.configPath,stdoutPath:o.stdoutPath,stderrPath:o.stderrPath}))if(!isAbsolute(v))throw Error(`${k} must be absolute`);if(!Number.isInteger(o.restartSeconds)||o.restartSeconds<1)throw Error("restartSeconds must be a positive integer");return o}
const xml=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");
const unit=(s:string)=>`"${s.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/%/g,"%%")}"`;
export function renderWindowsTaskContract(input:ServiceDescriptorOptions){const o=valid(input);return `<?xml version="1.0" encoding="UTF-16"?>\n<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"><RegistrationInfo><Description>Khizana source sync; stdout=${xml(o.stdoutPath)}; stderr=${xml(o.stderrPath)}; secrets resolved by process only</Description></RegistrationInfo><Triggers><LogonTrigger><Enabled>true</Enabled></LogonTrigger></Triggers><Principals><Principal id="CurrentUser"><LogonType>InteractiveToken</LogonType><RunLevel>LeastPrivilege</RunLevel></Principal></Principals><Settings><MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy><RestartOnFailure><Interval>PT${o.restartSeconds}S</Interval><Count>999</Count></RestartOnFailure><ExecutionTimeLimit>PT0S</ExecutionTimeLimit></Settings><Actions Context="CurrentUser"><Exec><Command>${xml(o.executablePath)}</Command><Arguments>run --config &quot;${xml(o.configPath)}&quot;</Arguments></Exec></Actions></Task>\n`}
export function renderLaunchdPlist(input:ServiceDescriptorOptions){const o=valid(input);return `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict>\n<key>Label</key><string>${xml(o.name)}</string>\n<key>ProgramArguments</key><array><string>${xml(o.executablePath)}</string><string>run</string><string>--config</string><string>${xml(o.configPath)}</string></array>\n<key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>ThrottleInterval</key><integer>${o.restartSeconds}</integer>\n<key>StandardOutPath</key><string>${xml(o.stdoutPath)}</string><key>StandardErrorPath</key><string>${xml(o.stderrPath)}</string>\n</dict></plist>\n`}
export function renderSystemdUserUnit(input:ServiceDescriptorOptions){const o=valid(input);return `[Unit]\nDescription=Khizana Word source sync (${o.name})\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nExecStart=${unit(o.executablePath)} run --config ${unit(o.configPath)}\nRestart=on-failure\nRestartSec=${o.restartSeconds}\nStandardOutput=append:${unit(o.stdoutPath)}\nStandardError=append:${unit(o.stderrPath)}\n\n[Install]\nWantedBy=default.target\n`}
export function createServiceInstallPlan(platform:ServicePlatform,operation:"install"|"uninstall",o:ServiceDescriptorOptions):ServiceInstallPlan{valid(o);if(platform==="win32")return{platform,operation,requiresExplicitConfirmation:true,commands:[{executable:"schtasks.exe",args:operation==="install"?["/Create","/TN",o.name,"/XML","<descriptor-path>","/F"]:["/Delete","/TN",o.name,"/F"]}],rollbackCommands:operation==="install"?[{executable:"schtasks.exe",args:["/Delete","/TN",o.name,"/F"]}]:[],...(operation==="install"?{descriptor:renderWindowsTaskContract(o)}:{})};if(platform==="darwin")return{platform,operation,requiresExplicitConfirmation:true,commands:[{executable:"launchctl",args:operation==="install"?["bootstrap","gui/<uid>","<descriptor-path>"]:["bootout","gui/<uid>","<descriptor-path>"]}],rollbackCommands:operation==="install"?[{executable:"launchctl",args:["bootout","gui/<uid>","<descriptor-path>"]}]:[],...(operation==="install"?{descriptor:renderLaunchdPlist(o)}:{})};return{platform,operation,requiresExplicitConfirmation:true,commands:operation==="install"?[{executable:"systemctl",args:["--user","daemon-reload"]},{executable:"systemctl",args:["--user","enable","--now",`${o.name}.service`]}]:[{executable:"systemctl",args:["--user","disable","--now",`${o.name}.service`]},{executable:"systemctl",args:["--user","daemon-reload"]}],rollbackCommands:operation==="install"?[{executable:"systemctl",args:["--user","disable","--now",`${o.name}.service`]},{executable:"systemctl",args:["--user","daemon-reload"]}]:[],...(operation==="install"?{descriptor:renderSystemdUserUnit(o)}:{})}}
export function guardServicePlatform(requested:ServicePlatform,actual:NodeJS.Platform=process.platform){if(requested!==actual)throw Error(`platform mismatch: requested ${requested}, actual ${actual}`)}
