import type{SourceSyncPhase,SourceSyncViewState}from"./session-state.js";
export type SyncMessageKey=`sync.${SourceSyncPhase}`;
export type SyncAction="signIn"|"continueLocal"|"upgradeAccount"|"chooseManagedFolder"|"cancelConnection"|"refresh"|"viewRevisions"|"retryConnection"|"viewPending"|"retryPending"|"cancelPending"|"keepLocal"|"keepRemote"|"createCopy"|"viewQuarantine";
export interface SyncActionPolicy{messageKey:SyncMessageKey;actions:readonly SyncAction[];mutatingActions:readonly SyncAction[];uploadAllowed:boolean}
const BASE:Record<SourceSyncPhase,{messageKey:SyncMessageKey;actions:readonly SyncAction[]}>={signedOut:{messageKey:"sync.signedOut",actions:["signIn","continueLocal"]},guest:{messageKey:"sync.guest",actions:["continueLocal","upgradeAccount"]},localOnly:{messageKey:"sync.localOnly",actions:["chooseManagedFolder","upgradeAccount"]},connecting:{messageKey:"sync.connecting",actions:["cancelConnection"]},synced:{messageKey:"sync.synced",actions:["refresh","viewRevisions"]},offline:{messageKey:"sync.offline",actions:["retryConnection","continueLocal"]},pending:{messageKey:"sync.pending",actions:["viewPending","retryPending","cancelPending"]},conflict:{messageKey:"sync.conflict",actions:["keepLocal","keepRemote","createCopy","viewRevisions"]},quarantined:{messageKey:"sync.quarantined",actions:["viewQuarantine"]},error:{messageKey:"sync.error",actions:["retryConnection","continueLocal"]}};
const MUTATING=new Set<SyncAction>(["retryPending","cancelPending","keepLocal","keepRemote","createCopy"]);
export function syncActionPolicy(state:SourceSyncViewState,context:{pendingRetryable?:boolean;pendingCancelable?:boolean}={}):SyncActionPolicy{let actions=[...BASE[state.phase].actions];if(state.phase==="pending"){if(!context.pendingRetryable)actions=actions.filter(x=>x!=="retryPending");if(!context.pendingCancelable)actions=actions.filter(x=>x!=="cancelPending")}if((state.phase==="guest"||state.phase==="signedOut")&&state.uploadAllowed)throw Error("guest_or_signed_out_upload_invariant");return{messageKey:BASE[state.phase].messageKey,actions,mutatingActions:actions.filter(x=>MUTATING.has(x)),uploadAllowed:state.uploadAllowed}}
export type ConflictResolution="keepLocal"|"keepRemote"|"createCopy";
export interface ConflictResolutionIntent{kind:"resolveConflict";operationId:string;bookId:string;deviceId:string;conflictingRevisionId:string;expectedPublicationVersion:number;resolution:ConflictResolution}
export interface PendingOperationIntent{kind:"retryPending"|"cancelPending";operationId:string;bookId:string;deviceId:string;pendingOperationId:string;expectedOperationVersion:number}
export function conflictResolutionIntent(state:SourceSyncViewState,input:Omit<ConflictResolutionIntent,"kind">):ConflictResolutionIntent{if(state.phase!=="conflict"||!state.activeDevice||state.activeDevice.deviceId!==input.deviceId||!input.operationId.trim()||input.expectedPublicationVersion<0)throw Error("conflict_intent_not_allowed");return{kind:"resolveConflict",...input}}
export function pendingOperationIntent(state:SourceSyncViewState,input:Omit<PendingOperationIntent,"kind">&{action:"retryPending"|"cancelPending"},constraints:{retryable:boolean;cancelable:boolean}):PendingOperationIntent{if(state.phase!=="pending"||!state.activeDevice||state.activeDevice.deviceId!==input.deviceId||!input.operationId.trim()||input.expectedOperationVersion<0||input.action==="retryPending"&&!constraints.retryable||input.action==="cancelPending"&&!constraints.cancelable)throw Error("pending_intent_not_allowed");const{action,...rest}=input;return{kind:action,...rest}}
export const conflictResolutionIntentSchema={type:"object",additionalProperties:false,required:["kind","operationId","bookId","deviceId","conflictingRevisionId","expectedPublicationVersion","resolution"],properties:{kind:{const:"resolveConflict"},operationId:{type:"string",minLength:1},bookId:{type:"string",minLength:1},deviceId:{type:"string",minLength:1},conflictingRevisionId:{type:"string",minLength:1},expectedPublicationVersion:{type:"integer",minimum:0},resolution:{enum:["keepLocal","keepRemote","createCopy"]}}}as const;
