import { REQUIRED_DERIVED_ARTIFACTS, type BookBuildManifest } from "@library/source-sync";
import type { BuildJob, BuildJobStore } from "../../source-sync-server/src/index.js";
import type { D1DatabaseBinding } from "./bindings.js";

export class D1BuildJobStore implements BuildJobStore {
 constructor(private readonly db:D1DatabaseBinding){}
 async ensureBuildJobs(m:BookBuildManifest){await this.db.prepare("INSERT OR IGNORE INTO book_builds (id,book_id,source_revision_id,status,manifest_json,created_at) VALUES (?1,?2,?3,?4,?5,?6)").bind(m.buildId,m.bookId,m.sourceRevisionId,m.status,JSON.stringify(m),m.createdAt).run();for(const kind of REQUIRED_DERIVED_ARTIFACTS)await this.db.prepare("INSERT OR IGNORE INTO build_jobs (id,build_id,book_id,source_revision_id,kind,state,next_attempt_at_ms) VALUES (?1,?2,?3,?4,?5,'pending',0)").bind(`${m.buildId}:${kind}`,m.buildId,m.bookId,m.sourceRevisionId,kind).run();}
 async claim(now:number,lease:string,leaseMs:number,limit:number){const rows=(await this.db.prepare("SELECT * FROM (SELECT build_jobs.*,ROW_NUMBER() OVER (PARTITION BY book_id ORDER BY next_attempt_at_ms,id) AS fair_rank FROM build_jobs WHERE ((state IN ('pending','retryable') AND next_attempt_at_ms <= ?1) OR (state='in-flight' AND lease_until_ms <= ?1))) ORDER BY fair_rank,next_attempt_at_ms,id LIMIT ?2").bind(now,limit).all<Row>()).results??[];const out:BuildJob[]=[];for(const r of rows){const j=job(r);const result=await this.db.prepare("UPDATE build_jobs SET state='in-flight',attempt=attempt+1,lease_id=?2,lease_until_ms=?3,record_version=record_version+1,last_error=NULL WHERE id=?1 AND record_version=?4").bind(j.jobId,lease,now+leaseMs,j.recordVersion).run();if(changed(result))out.push({...j,state:"in-flight",attempt:j.attempt+1,leaseId:lease,leaseUntilMs:now+leaseMs,recordVersion:j.recordVersion+1});}return out;}
 async complete(j:BuildJob,a:BookBuildManifest["artifacts"][number]){const m=await this.getManifest(j.buildId);m.artifacts=[...m.artifacts.filter(x=>x.kind!==a.kind),a];if(m.artifacts.length===REQUIRED_DERIVED_ARTIFACTS.length)m.status="ready";if(!this.db.batch)throw new Error("D1 transactional batch is required for artifact completion");const statements=[this.db.prepare("UPDATE book_builds SET manifest_json=?2,status=?3,record_version=record_version+1 WHERE id=?1 AND EXISTS (SELECT 1 FROM build_jobs WHERE id=?4 AND record_version=?5 AND state='in-flight')").bind(j.buildId,JSON.stringify(m),m.status,j.jobId,j.recordVersion),this.db.prepare("UPDATE build_jobs SET state='succeeded',lease_id=NULL,lease_until_ms=NULL,record_version=record_version+1 WHERE id=?1 AND record_version=?2 AND state='in-flight'").bind(j.jobId,j.recordVersion)];const [b,q]=await this.db.batch(statements);return changed(b!)&&changed(q!);}
 retry(j:BuildJob,n:number,c:string){return this.transition(j,"retryable",n,c);} fail(j:BuildJob,c:string){return this.transition(j,"failed",0,c);}
 private async transition(j:BuildJob,state:string,next:number,code:string){return changed(await this.db.prepare("UPDATE build_jobs SET state=?2,next_attempt_at_ms=?3,last_error=?4,lease_id=NULL,lease_until_ms=NULL,record_version=record_version+1 WHERE id=?1 AND record_version=?5 AND state='in-flight'").bind(j.jobId,state,next,code,j.recordVersion).run());}
 async getManifest(id:string){const r=await this.db.prepare("SELECT manifest_json FROM book_builds WHERE id=?1").bind(id).first<{manifest_json:string}>();if(!r)throw new Error("Build missing");return JSON.parse(r.manifest_json) as BookBuildManifest;}
 async getActiveBuildId(book:string){return (await this.db.prepare("SELECT active_build_id AS id FROM book_publications WHERE book_id=?1").bind(book).first<{id:string|null}>())?.id??null;}
 async getActivePublication(book:string){return await this.db.prepare("SELECT active_build_id AS buildId,active_source_revision_id AS sourceRevisionId,active_manifest_etag AS etag,cache_version AS cacheVersion FROM book_publications WHERE book_id=?1").bind(book).first<{buildId:string;sourceRevisionId:string;etag:string;cacheVersion:number}>()}
 async publish(d:any){if(!this.db.batch)throw new Error("D1 transactional batch is required for publication");const publication=this.db.prepare("INSERT INTO book_publications (book_id,active_build_id,active_source_revision_id,active_manifest_etag,cache_version,record_version) SELECT book_id,?2,?3,?4,1,1 FROM book_builds WHERE id=?2 ON CONFLICT(book_id) DO UPDATE SET active_build_id=excluded.active_build_id,active_source_revision_id=excluded.active_source_revision_id,active_manifest_etag=excluded.active_manifest_etag,cache_version=book_publications.cache_version+1,record_version=book_publications.record_version+1 WHERE book_publications.active_build_id IS ?5").bind("unused",d.nextActiveBuildId,d.nextActiveSourceRevisionId,d.activeManifestEtag,d.expectedActiveBuildId),event=this.db.prepare("INSERT OR IGNORE INTO cache_invalidation_outbox(operation_id,book_id,build_id,manifest_etag) SELECT ?1,book_id,?2,?3 FROM book_builds WHERE id=?2").bind(d.invalidationOperationId,d.nextActiveBuildId,d.activeManifestEtag);const [p]=await this.db.batch([publication,event]);return changed(p!);}
}
type Row=Record<string,unknown>;function job(r:Row):BuildJob{return{jobId:String(r.id),buildId:String(r.build_id),bookId:String(r.book_id),sourceRevisionId:String(r.source_revision_id),kind:String(r.kind) as BuildJob["kind"],state:String(r.state) as BuildJob["state"],attempt:Number(r.attempt),nextAttemptAtMs:Number(r.next_attempt_at_ms),leaseId:r.lease_id===null?null:String(r.lease_id),leaseUntilMs:r.lease_until_ms===null?null:Number(r.lease_until_ms),recordVersion:Number(r.record_version),lastError:r.last_error===null?null:String(r.last_error)}}function changed(r:{success:boolean;meta?:{changes?:number}}){return r.success&&(r.meta?.changes??0)===1;}
