import{describe,expect,it}from"vitest";import{OidcJwksIdentityVerifier}from"./oidc-identity.js";
const enc=new TextEncoder(),now=2_000_000_000_000;
function base64(v:Uint8Array|string){const bytes=typeof v==="string"?enc.encode(v):v;return btoa(String.fromCharCode(...bytes)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
async function rsa(kid:string){const pair=await crypto.subtle.generateKey({name:"RSASSA-PKCS1-v1_5",modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:"SHA-256"},true,["sign","verify"]);return{kid,pair,jwk:{...await crypto.subtle.exportKey("jwk",pair.publicKey),kid,alg:"RS256",use:"sig"}}}
async function ec(kid:string){const pair=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);return{kid,pair,jwk:{...await crypto.subtle.exportKey("jwk",pair.publicKey),kid,alg:"ES256",use:"sig"}}}
async function token(key:Awaited<ReturnType<typeof rsa>>|Awaited<ReturnType<typeof ec>>,claims:Record<string,unknown>,alg:keyof never|"RS256"|"ES256"="RS256"){const h=base64(JSON.stringify({alg,kid:key.kid,typ:"JWT"})),p=base64(JSON.stringify(claims)),data=enc.encode(`${h}.${p}`),signature=await crypto.subtle.sign(alg==="RS256"?{name:"RSASSA-PKCS1-v1_5"}:{name:"ECDSA",hash:"SHA-256"},key.pair.privateKey,data);return`${h}.${p}.${base64(new Uint8Array(signature))}`}
function claims(extra:Record<string,unknown>={}){return{iss:"https://issuer.example",aud:"library",sub:"user-1",exp:now/1000+300,iat:now/1000-5,...extra}}
function verifier(keys:JsonWebKey[],fetcher?:typeof fetch){return new OidcJwksIdentityVerifier({issuer:"https://issuer.example",audience:"library",jwksUrl:"https://issuer.example/jwks",algorithms:["RS256","ES256"],clockSkewSeconds:30},{now:()=>now,fetch:fetcher??(async()=>new Response(JSON.stringify({keys}),{headers:{"cache-control":"public, max-age=300"}}))})}
describe("OIDC JWKS identity",()=>{
 it("verifies RS256 and ES256 accounts",async()=>{const r=await rsa("r"),e=await ec("e"),v=verifier([r.jwk,e.jwk]);await expect(v.verifyBearer(await token(r,claims()))).resolves.toEqual({kind:"account",userId:"user-1"});await expect(v.verifyBearer(await token(e,claims(),"ES256"))).resolves.toEqual({kind:"account",userId:"user-1"})});
 it("rejects expired, wrong issuer/audience, and alg none",async()=>{const r=await rsa("r"),v=verifier([r.jwk]);for(const c of [claims({exp:now/1000-31}),claims({iss:"https://evil"}),claims({aud:"other"})])expect(await v.verifyBearer(await token(r,c))).toEqual({kind:"invalid"});const unsigned=`${base64(JSON.stringify({alg:"none",kid:"r"}))}.${base64(JSON.stringify(claims()))}.`;expect(await v.verifyBearer(unsigned)).toEqual({kind:"invalid"})});
 it("refreshes once for a rotated kid and otherwise honors HTTP cache",async()=>{const a=await rsa("a"),b=await rsa("b");let calls=0;const f=async()=>new Response(JSON.stringify({keys:++calls===1?[a.jwk]:[a.jwk,b.jwk]}),{headers:{"cache-control":"max-age=300"}}),v=verifier([],f as typeof fetch);expect((await v.verifyBearer(await token(a,claims()))).kind).toBe("account");expect((await v.verifyBearer(await token(a,claims()))).kind).toBe("account");expect(calls).toBe(1);expect((await v.verifyBearer(await token(b,claims()))).kind).toBe("account");expect(calls).toBe(2)});
 it("returns invalid on network failure without accepting stale unknown keys",async()=>{const r=await rsa("r"),v=verifier([],async()=>{throw new Error("offline")});expect(await v.verifyBearer(await token(r,claims()))).toEqual({kind:"invalid"})});
 it("aborts a JWKS fetch at the configured timeout",async()=>{const r=await rsa("r"),v=new OidcJwksIdentityVerifier({issuer:"https://issuer.example",audience:"library",jwksUrl:"https://issuer.example/jwks",algorithms:["RS256"],fetchTimeoutMs:5},{now:()=>now,fetch:((_u,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError"))))) as typeof fetch});expect(await v.verifyBearer(await token(r,claims()))).toEqual({kind:"invalid"})});
 it("classifies a signed guest without granting account authority",async()=>{const r=await rsa("r"),v=verifier([r.jwk]);expect(await v.verifyBearer(await token(r,claims({is_guest:true})))).toEqual({kind:"guest"})});
});
