import { describe, expect, it } from "vitest";
import { decideEstimatedPaginationConsent, validatePublicDocxPublicationApproval, type EstimatedPaginationConsentIntent } from "./word-pagination-policy.js";

const hash="a".repeat(64),intent=(overrides:Partial<EstimatedPaginationConsentIntent>={}):EstimatedPaginationConsentIntent=>({schemaVersion:1,intentId:"intent-1",operationId:"op-1",principalId:"user-1",deviceId:"device-1",bookId:"book-1",sourceRevisionId:"revision-1",sourceFingerprint:hash,expectedConsentVersion:0,consentedAt:"2026-08-09T00:00:00Z",scope:"private-estimated-preview",...overrides});
describe("estimated pagination consent CAS",()=>{
 it("records private preview consent without making it authoritative",()=>{const result=decideEstimatedPaginationConsent({intent:intent(),current:null,currentSourceFingerprint:hash,authenticatedPrincipalId:"user-1",authenticatedDeviceId:"device-1",now:"2026-08-09T00:01:00Z"});expect(result).toMatchObject({kind:"record",next:{consentVersion:1,scope:"private-estimated-preview"}});expect(JSON.stringify(result)).not.toContain("authoritative")});
 it("is idempotent for the same operation and rejects operation reuse",()=>{const first=decideEstimatedPaginationConsent({intent:intent(),current:null,currentSourceFingerprint:hash,authenticatedPrincipalId:"user-1",authenticatedDeviceId:"device-1",now:"2026-08-09T00:01:00Z"});if(first.kind!=="record")throw Error("setup");expect(decideEstimatedPaginationConsent({intent:intent(),current:first.next,currentSourceFingerprint:hash,authenticatedPrincipalId:"user-1",authenticatedDeviceId:"device-1",now:"2026-08-09T00:02:00Z"}).kind).toBe("replay");expect(()=>decideEstimatedPaginationConsent({intent:intent({intentId:"other"}),current:first.next,currentSourceFingerprint:hash,authenticatedPrincipalId:"user-1",authenticatedDeviceId:"device-1",now:"2026-08-09T00:02:00Z"})).toThrow(/operation_reuse/)});
 it("fails stale fingerprints, CAS conflicts, and principal/device substitution",()=>{expect(decideEstimatedPaginationConsent({intent:intent(),current:null,currentSourceFingerprint:"b".repeat(64),authenticatedPrincipalId:"user-1",authenticatedDeviceId:"device-1",now:"2026-08-09T00:01:00Z"}).kind).toBe("stale-source");expect(decideEstimatedPaginationConsent({intent:intent({expectedConsentVersion:3}),current:null,currentSourceFingerprint:hash,authenticatedPrincipalId:"user-1",authenticatedDeviceId:"device-1",now:"2026-08-09T00:01:00Z"})).toEqual({kind:"conflict",currentVersion:0});expect(()=>decideEstimatedPaginationConsent({intent:intent(),current:null,currentSourceFingerprint:hash,authenticatedPrincipalId:"attacker",authenticatedDeviceId:"device-1",now:"2026-08-09T00:01:00Z"})).toThrow(/forbidden/)});
});
describe("public DOCX approval",()=>{it("requires a separate approval tied to the authoritative map and source",()=>{const approval={approvalId:"approval-1",operationId:"publish-1",principalId:"user-1",bookId:"book-1",sourceRevisionId:"revision-1",sourceFingerprint:hash,authoritativeWordPageMapFingerprint:hash,approvedAt:"2026-08-09T00:03:00Z",scope:"public-publish"as const};expect(()=>validatePublicDocxPublicationApproval(approval,{principalId:"user-1",bookId:"book-1",sourceRevisionId:"revision-1",sourceFingerprint:hash})).not.toThrow();expect(()=>validatePublicDocxPublicationApproval({...approval,authoritativeWordPageMapFingerprint:"b".repeat(64)},{principalId:"user-1",bookId:"book-1",sourceRevisionId:"revision-1",sourceFingerprint:hash})).toThrow(/mismatch/)})});
