import { describe,expect,it } from "vitest";
import { DurableBuildWorker, PermanentBuildError, type BuildJob, type BuildJobStore } from "./build-jobs.js";
import type { BookBuildManifest, DerivedArtifactKind } from "@library/source-sync";
const kinds:DerivedArtifactKind[]=["reader","pdf","search","toc","cover"];
class Store implements BuildJobStore { jobs=kinds.map((kind,i):BuildJob=>({jobId:`j${i}`,buildId:"b2",bookId:"book",sourceRevisionId:"r2",kind,state:"pending",attempt:0,nextAttemptAtMs:0,leaseId:null,leaseUntilMs:null,recordVersion:0,lastError:null})); active:string|null="b1"; artifacts:BookBuildManifest["artifacts"]=[];authorizePublicDocxPublication?:BuildJobStore["authorizePublicDocxPublication"];
 async ensureBuildJobs(){} async claim(now:number,lease:string,leaseMs:number,limit:number){return this.jobs.filter(j=>(["pending","retryable"].includes(j.state)&&j.nextAttemptAtMs<=now)||(j.state==="in-flight"&&(j.leaseUntilMs??Infinity)<=now)).slice(0,limit).map(j=>Object.assign(j,{state:"in-flight" as const,attempt:j.attempt+1,leaseId:lease,leaseUntilMs:now+leaseMs,recordVersion:j.recordVersion+1}));}
 async complete(j:BuildJob,a:BookBuildManifest["artifacts"][number]){j.state="succeeded";this.artifacts.push(a);return true;} async retry(j:BuildJob,n:number,c:string){Object.assign(j,{state:"retryable",nextAttemptAtMs:n,lastError:c,leaseId:null,leaseUntilMs:null});return true;} async fail(j:BuildJob,c:string){Object.assign(j,{state:"failed",lastError:c});return true;}
 async getManifest(){return {buildId:"b2",bookId:"book",sourceRevisionId:"r2",status:this.artifacts.length===5?"ready":"processing",artifacts:this.artifacts,createdAt:"2026-08-08"} as BookBuildManifest;} async getActiveBuildId(){return this.active;} async publish(d:any){if(this.active!==d.expectedActiveBuildId)return false;this.active=d.nextActiveBuildId;return true;}}
function artifact(kind:DerivedArtifactKind){return {artifactId:`a-${kind}`,kind,bookId:"book",sourceRevisionId:"r2",buildId:"b2",status:"ready" as const,fingerprint:{algorithm:"sha256" as const,hex:"a".repeat(64),byteLength:1},objectKey:`staging/b2/${kind}`,engineVersion:"1"};}
describe("DurableBuildWorker",()=>{it("publishes atomically only after every derivative completes",async()=>{const s=new Store();const builders=Object.fromEntries(kinds.map(k=>[k,{build:async()=>artifact(k)}])) as any;const w=new DurableBuildWorker(s,builders,{leaseMs:100,limit:5,baseRetryMs:10,maxRetryMs:100});expect((await w.runOnce(0,"l")).published).toBe(1);expect(s.active).toBe("b2");});
it("denies automatic public DOCX publication without a separate approval and permits an approved authoritative map",async()=>{const source="c".repeat(64),builders=Object.fromEntries(kinds.map(k=>[k,{build:async()=>artifact(k)}])) as any;const setup=(approved?:boolean)=>{const s=new Store();s.getManifest=async()=>{const value={buildId:"b2",bookId:"book",sourceRevisionId:"r2",status:s.artifacts.length===5?"ready":"processing",artifacts:s.artifacts,createdAt:"2026-08-08"}as BookBuildManifest;const reader=value.artifacts.find(item=>item.kind==="reader");if(reader){reader.sourceEdition={editionId:"edition",format:"docx",sha256:source};reader.wordPageMap={authoritative:true,engine:"microsoft-word-com",fingerprint:source,totalPages:2}}return value};if(approved!==undefined)s.authorizePublicDocxPublication=async required=>approved&&required.sourceFingerprint===source;return s};const denied=setup();expect((await new DurableBuildWorker(denied,builders,{leaseMs:100,limit:5,baseRetryMs:10,maxRetryMs:100}).runOnce(0,"l")).published).toBe(0);expect(denied.active).toBe("b1");const allowed=setup(true);expect((await new DurableBuildWorker(allowed,builders,{leaseMs:100,limit:5,baseRetryMs:10,maxRetryMs:100}).runOnce(0,"l")).published).toBe(1);expect(allowed.active).toBe("b2")});
it("keeps prior active on partial, retryable, and permanent failures and reclaims expired leases",async()=>{const s=new Store();s.jobs[0]!.state="in-flight";s.jobs[0]!.leaseUntilMs=-1;const builders=Object.fromEntries(kinds.map(k=>[k,{build:async()=>{if(k==="pdf")throw new Error("down");if(k==="cover")throw new PermanentBuildError("bad-cover");return artifact(k);}}])) as any;const r=await new DurableBuildWorker(s,builders,{leaseMs:100,limit:5,baseRetryMs:10,maxRetryMs:100}).runOnce(0,"l2");expect(r).toMatchObject({claimed:5,retried:1,failed:1,published:0});expect(s.active).toBe("b1");expect(s.jobs.find(j=>j.kind==="pdf")?.nextAttemptAtMs).toBe(10);});});
it("honors typed permanent failures and bounded Retry-After without publishing an incomplete build",async()=>{
 const s=new Store();const builders=Object.fromEntries(kinds.map(k=>[k,{build:async()=>{if(k==="pdf")throw Object.assign(new Error("throttled"),{code:"pdf_http_429",retryable:true,retryAfterMs:90});if(k==="cover")throw Object.assign(new Error("invalid"),{code:"invalid_cover",retryable:false});return artifact(k)}}])) as any;
 const result=await new DurableBuildWorker(s,builders,{leaseMs:100,limit:5,baseRetryMs:10,maxRetryMs:50}).runOnce(1_000,"lease");
 expect(result).toMatchObject({completed:3,retried:1,failed:1,published:0});
 expect(s.jobs.find(j=>j.kind==="pdf")).toMatchObject({state:"retryable",nextAttemptAtMs:1_050,lastError:"pdf_http_429"});
 expect(s.jobs.find(j=>j.kind==="cover")).toMatchObject({state:"failed",lastError:"invalid_cover"});
 expect(s.active).toBe("b1");
});
