import{describe,expect,it,vi}from"vitest";import{zipSync}from"fflate";import{QuranpediaClient,downloadQuranpediaPack,type QuranPackManifest,type QuranPackStorage}from"./quranpedia.js";
class MemoryStore implements QuranPackStorage{bytes=new Uint8Array();committed:QuranPackManifest|null=null;async size(){return this.bytes.length}async read(){return this.bytes}async append(_k:string,b:Uint8Array){const n=new Uint8Array(this.bytes.length+b.length);n.set(this.bytes);n.set(b,this.bytes.length);this.bytes=n}async reset(){this.bytes=new Uint8Array()}async commitAtomic(_t:string,_f:string,m:QuranPackManifest){this.committed=m}}
describe("Quranpedia read-only ingestion",()=>{
 it("fetches documented metadata with bounded provenance and no credentials",async()=>{const fetchImpl=vi.fn(async(_u,init)=>new Response(JSON.stringify([{id:1,name:"حفص"}]),{headers:{etag:'"v1"'}})),c=new QuranpediaClient(fetchImpl as typeof fetch,{maxResponseBytes:1000,maxRetries:0,baseBackoffMs:1,maxBackoffMs:1,requestTimeoutMs:1000},()=>new Date("2026-08-09T00:00:00Z"));const r=await c.metadata("mushafs");expect(r.provenance).toMatchObject({provider:"Quranpedia",sourceUrl:"https://api.quranpedia.net/v1/mushafs",etag:'"v1"',apiVersion:"v1"});expect((fetchImpl.mock.calls[0]![1]as RequestInit).headers).toEqual({accept:"application/json"})});
 it("rejects invalid ids and oversized responses",async()=>{const c=new QuranpediaClient(async()=>new Response("[]",{headers:{"content-length":"50"}})as never,{maxResponseBytes:10,maxRetries:0,baseBackoffMs:1,maxBackoffMs:1,requestTimeoutMs:10});expect(()=>c.ayahs(1,115)).toThrow("invalid_surah");await expect(c.metadata("topics")).rejects.toThrow("size_limit")});
 it("resumes a bounded official pack and atomically commits a checksum manifest",async()=>{const pack=zipSync({"timings/1.json":new TextEncoder().encode("[]")}),cut=5,s=new MemoryStore();s.bytes=pack.subarray(0,cut);const fetchImpl=vi.fn(async(_u,init)=>{expect((init!.headers as Record<string,string>)).toMatchObject({range:`bytes=${cut}-`,"if-range":'"pack"'});return new Response(pack.subarray(cut),{status:206,headers:{etag:'"pack"',"content-range":`bytes ${cut}-${pack.length-1}/${pack.length}`}})});const m=await downloadQuranpediaPack({url:"https://api.quranpedia.net/data/timings/1.zip",version:"fixture-v1",tempKey:"x.tmp",finalKey:"x",maxBytes:10000,maxEntries:10,maxExpandedBytes:1000,maxCompressionRatio:100,resumeEtag:'"pack"',storage:s,fetchImpl:fetchImpl as typeof fetch,now:()=>new Date("2026-08-09T00:00:00Z")});expect(m.byteLength).toBe(pack.length);expect(s.committed).toEqual(m)});
 it("clears partial bytes and fails closed when resume identity or range changed",async()=>{const pack=zipSync({"x.json":new TextEncoder().encode("[]")}),s=new MemoryStore();s.bytes=pack.subarray(0,5);const fetchImpl=vi.fn(async()=>new Response(pack.subarray(5),{status:206,headers:{etag:'"new"',"content-range":`bytes 6-${pack.length-1}/${pack.length}`}}));await expect(downloadQuranpediaPack({url:"https://api.quranpedia.net/data/x.zip",version:"v",tempKey:"t",finalKey:"f",maxBytes:10000,maxEntries:10,maxExpandedBytes:1000,maxCompressionRatio:100,resumeEtag:'"old"',storage:s,fetchImpl:fetchImpl as typeof fetch})).rejects.toThrow(/resume_mismatch/);expect(s.bytes).toHaveLength(0);expect(s.committed).toBeNull()});
 it("rejects an unsolicited partial response for a fresh download",async()=>{const pack=zipSync({"x.json":new TextEncoder().encode("[]")}),s=new MemoryStore();await expect(downloadQuranpediaPack({url:"https://api.quranpedia.net/data/x.zip",version:"v",tempKey:"t",finalKey:"f",maxBytes:10000,maxEntries:10,maxExpandedBytes:1000,maxCompressionRatio:100,storage:s,fetchImpl:async()=>new Response(pack,{status:206,headers:{etag:'"x"',"content-range":`bytes 0-${pack.length-1}/${pack.length}`}})})).rejects.toThrow(/http_206/);expect(s.bytes).toHaveLength(0);expect(s.committed).toBeNull()});
 it("discards completed bytes that fail structural or checksum verification",async()=>{for(const fixture of[{bytes:new TextEncoder().encode("not-a-zip"),expected:undefined},{bytes:zipSync({"x.json":new TextEncoder().encode("[]")}),expected:"0".repeat(64)}]){const s=new MemoryStore();await expect(downloadQuranpediaPack({url:"https://api.quranpedia.net/data/x.zip",version:"v",tempKey:"t",finalKey:"f",maxBytes:10000,maxEntries:10,maxExpandedBytes:1000,maxCompressionRatio:100,expectedSha256:fixture.expected,storage:s,fetchImpl:async()=>new Response(fixture.bytes,{status:200})})).rejects.toThrow();expect(s.bytes).toHaveLength(0);expect(s.committed).toBeNull()}});
 it("resets storage when append partially writes then fails",async()=>{const pack=zipSync({"x.json":new TextEncoder().encode("[]")});class PartialFailureStore extends MemoryStore{override async append(k:string,b:Uint8Array){await super.append(k,b.subarray(0,Math.min(3,b.length)));throw Error("disk_full")}}const s=new PartialFailureStore();await expect(downloadQuranpediaPack({url:"https://api.quranpedia.net/data/x.zip",version:"v",tempKey:"t",finalKey:"f",maxBytes:10000,maxEntries:10,maxExpandedBytes:1000,maxCompressionRatio:100,storage:s,fetchImpl:async()=>new Response(pack,{status:200})})).rejects.toThrow(/disk_full/);expect(s.bytes).toHaveLength(0);expect(s.committed).toBeNull()});
 it("rejects off-origin pack URLs before network or storage mutation",async()=>{const s=new MemoryStore(),f=vi.fn();await expect(downloadQuranpediaPack({url:"https://evil.example/a.zip",version:"x",tempKey:"t",finalKey:"f",maxBytes:10,maxEntries:1,maxExpandedBytes:10,maxCompressionRatio:10,storage:s,fetchImpl:f})).rejects.toThrow("origin_rejected");expect(f).not.toHaveBeenCalled()});
});
