import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { loadExecutableConfig, main } from "./cli-main.js";

const roots: string[] = [];
afterEach(async () => {vi.unstubAllGlobals();vi.unstubAllEnvs();await Promise.all(roots.splice(0).map(path => rm(path, { recursive: true, force: true })))});
async function fixture(requestTimeoutMs=1_000) {
  const root = await mkdtemp(join(tmpdir(), "source-sync-bin-")); roots.push(root);
  const path = join(root, "config.json");
  await writeFile(path, JSON.stringify({ managedDir: join(root, "books"), stateFile: join(root, "state.json"), lockFile: join(root, "daemon.lock"), healthFile: join(root, "health.json"), apiBase: "http://127.0.0.1:4101/", buildApiBase: "http://127.0.0.1:4101/build-service/", pdfEndpoint: "http://127.0.0.1:4102/convert", wordPageMapEndpoint:"http://127.0.0.1:4103/v1/word-page-map", deviceId: "test-device", engineVersion: "test", tokenSource: { kind: "env", name: "TEST_USER_TOKEN" }, serviceTokenSource: { kind: "env", name: "TEST_BUILD_TOKEN" }, reconcileIntervalMs: 100, outboxIntervalMs: 100, buildIntervalMs: 100, maxSourceBytes: 1_000_000, maxPdfBytes: 1_000_000, maxWordPageMapBytes:1_000_000,requestTimeoutMs }));
  return { root, path };
}
describe("executable CLI", () => {
  it("validates endpoint and token-source configuration without reading secret values", async () => { const f = await fixture(); const c = await loadExecutableConfig(f.path); expect(c.buildApiBase).toContain("build-service"); expect(await main(["config-check", "--config", f.path], {})).toBe(0); });
  it("uses stable exit codes for missing config and unavailable health", async () => { const f = await fixture(); expect(await main(["health", "--config", f.path], {})).toBe(3); expect(await main(["once"], {})).toBe(2); });
  it("keeps quarantine resolution dry-run until explicit confirmation",async()=>{const f=await fixture(),fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);expect(await main(["quarantine-resolve","--config",f.path,"--id","q","--lease","lease","--operation","resolution","--decision","allow","--reason","reviewed","--expected-version","0"],{})).toBe(0);expect(fetchMock).not.toHaveBeenCalled()});
  it("leases then resolves with the service token after confirmation",async()=>{const f=await fixture();vi.stubEnv("TEST_BUILD_TOKEN","service-secret");const fetchMock=vi.fn().mockResolvedValueOnce(Response.json({quarantineId:"q",leaseId:"lease",recordVersion:1})).mockResolvedValueOnce(Response.json({quarantineId:"q",status:"allowed",recordVersion:2}));vi.stubGlobal("fetch",fetchMock);expect(await main(["quarantine-resolve","--config",f.path,"--id","q","--lease","lease","--operation","resolution","--decision","allow","--reason","reviewed","--expected-version","0","--confirm"],{})).toBe(0);expect(fetchMock).toHaveBeenCalledTimes(2);expect((fetchMock.mock.calls[0]![1] as RequestInit).headers).toMatchObject({authorization:"Bearer service-secret","x-service-scopes":"quarantine:resolve"})});
  it("runs config/provision/remote preflight read-only against a local fetch harness",async()=>{const f=await fixture();vi.stubEnv("TEST_BUILD_TOKEN","service-secret");const calls:Array<{url:string;method:string}>=[],fetchMock=vi.fn(async(input:URL|RequestInfo,init?:RequestInit)=>{const url=String(input),method=init?.method??"GET";calls.push({url,method});if(url.endsWith("ready"))return Response.json({ready:true,bindings:[],missingTables:[]});if(url.endsWith("check")){expect(init?.headers).toMatchObject({authorization:"Bearer service-secret"});return Response.json({ok:true})}if(url.endsWith("convert")&&method==="OPTIONS")return new Response(null,{status:204});if(url.endsWith("word-page-map")&&method==="HEAD"){expect(init?.headers).toMatchObject({authorization:"Bearer service-secret"});return new Response(null,{status:204})}throw Error(`unexpected ${method} ${url}`)});vi.stubGlobal("fetch",fetchMock);expect(await main(["config-check","--config",f.path],{})).toBe(0);expect(await main(["provision-check","--config",f.path],{})).toBe(0);expect(await main(["remote-check","--config",f.path],{})).toBe(0);expect(calls.every(x=>x.method==="GET"||x.method==="OPTIONS"||x.method==="HEAD")).toBe(true)});
  it("fails preflight closed on readiness or missing service token",async()=>{const f=await fixture();vi.stubGlobal("fetch",vi.fn(async()=>new Response(null,{status:503})));expect(await main(["provision-check","--config",f.path],{})).toBe(5);vi.stubGlobal("fetch",vi.fn(async()=>Response.json({ready:true,bindings:[],missingTables:[]})));expect(await main(["provision-check","--config",f.path],{})).toBe(5)});
  it("rejects HTTP 200 readiness bodies that are false, incomplete, or malformed",async()=>{const f=await fixture();vi.stubEnv("TEST_BUILD_TOKEN","service-secret");for(const body of [{ready:false,bindings:[],missingTables:[]},{ready:true,bindings:["DB"],missingTables:[]},{ready:true,bindings:[],missingTables:["books"]},"not-json"]){vi.stubGlobal("fetch",vi.fn(async()=>typeof body==="string"?new Response(body):Response.json(body)));expect(await main(["provision-check","--config",f.path],{})).toBe(5)}});
  it("bounds a hung preflight and fails closed on a dropped connection without retrying",async()=>{const f=await fixture(5);vi.stubEnv("TEST_BUILD_TOKEN","service-secret");const hanging=vi.fn(async(_input:URL|RequestInfo,_init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>_init?.signal?.addEventListener("abort",()=>reject(_init.signal?.reason),{once:true})));vi.stubGlobal("fetch",hanging);expect(await main(["provision-check","--config",f.path],{})).toBe(5);expect(hanging).toHaveBeenCalledOnce();const dropped=vi.fn(async()=>{throw Error("ECONNRESET signed-secret")});vi.stubGlobal("fetch",dropped);expect(await main(["remote-check","--config",f.path],{})).toBe(5);expect(dropped).toHaveBeenCalledOnce()});
});
