import { createHash } from "node:crypto";
import { mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { buildQuranSearchPack } from "../packages/source-sync/dist/quran-search-pack.js";

const output=resolve(process.argv[2]??"generated/quranpedia-hafs-uthmani-v1"),checkpoint=join(output,".checkpoint"),base="https://api.quranpedia.net/v1/",retrievedAt=new Date().toISOString();
const sha=bytes=>createHash("sha256").update(bytes).digest("hex"),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function fetchBounded(url){for(let attempt=0;attempt<4;attempt++){try{const response=await fetch(url,{headers:{accept:"application/json"},redirect:"error"});if(response.ok){const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>512*1024)throw Error("response_size_limit");return{bytes,etag:response.headers.get("etag")}}if(response.status!==429&&response.status<500)throw Error(`http_${response.status}`)}catch(error){if(attempt===3)throw error}await sleep(250*2**attempt)}throw Error("unreachable")}
function validateSurah(value,surah){if(!Array.isArray(value)||!value.length)throw Error(`surah_empty:${surah}`);return value.map((entry,index)=>{if(Number(entry.surah)!==surah||Number(entry.number)!==index+1||typeof entry.text!=="string"||!entry.text)throw Error(`surah_identity:${surah}:${index+1}`);return{ayahId:`${surah}:${index+1}`,surah,ayah:index+1,sourceRecordId:entry.id,script:"uthmani",text:entry.text}})}
await mkdir(checkpoint,{recursive:true});const sources=[];let records=[];
for(let surah=1;surah<=114;surah++){const name=`${String(surah).padStart(3,"0")}.json`,path=join(checkpoint,name),url=`${base}mushafs/2/${surah}`;let bytes,etag=null,resumed=false;try{bytes=await readFile(path);validateSurah(JSON.parse(bytes.toString("utf8")),surah);resumed=true}catch{const response=await fetchBounded(url);bytes=response.bytes;etag=response.etag;const temp=`${path}.tmp`;await writeFile(temp,bytes);await rename(temp,path);await sleep(75)}const raw=JSON.parse(bytes.toString("utf8"));records=records.concat(validateSurah(raw,surah));sources.push({surah,url,etag,checksumSha256:sha(bytes),byteLength:bytes.length,resumed});}
if(records.length!==6236||new Set(records.map(item=>item.ayahId)).size!==6236)throw Error(`corpus_identity_count:${records.length}`);
const corpusBytes=Buffer.from(`${JSON.stringify({schemaVersion:1,datasetId:"quranpedia-hafs-uthmani-full",records})}\n`,`utf8`),searchBytes=Buffer.from(`${JSON.stringify(buildQuranSearchPack(records))}\n`,`utf8`);
const manifest={datasetId:"quranpedia-hafs-uthmani-full",kind:"ayah-text",schemaVersion:1,dataVersion:"1.0.0",checksumSha256:sha(corpusBytes),byteSize:corpusBytes.length,locale:"ar",script:"uthmani",qiraa:"عاصم",riwaya:"حفص",publicationStatus:"publishable-user-attested-waqf-reuse",search:{file:"search-index.json",checksumSha256:sha(searchBytes),byteSize:searchBytes.length,normalizationVersion:"arabic-broad-v1"},provenance:{sourceName:"الموسوعة القرآنية Quranpedia",sourceUrl:`${base}mushafs/2/{surah}`,licenseId:"USER-ATTESTED-WAQF-REUSE",attribution:"الموسوعة القرآنية Quranpedia — API v1؛ مصحف حفص النصي بالخط العثماني.",permissionBasis:"إقرار صاحب مشروع الخزانة بتاريخ 2026-08-09 بأن المصدر وقفي مصرح بالانتفاع والنشر في الخزانة الوقفية؛ لا يمثل معرف SPDX.",retrievedAt,sources}};
for(const[name,bytes]of[["ayah-text.json",corpusBytes],["search-index.json",searchBytes],["manifest.json",Buffer.from(`${JSON.stringify(manifest,null,2)}\n`)]]){const temp=join(output,`${name}.tmp`);await writeFile(temp,bytes);await rename(temp,join(output,name))}
console.log(JSON.stringify({output,records:records.length,corpusSha256:manifest.checksumSha256,searchSha256:manifest.search.checksumSha256,resumed:sources.filter(x=>x.resumed).length,downloaded:sources.filter(x=>!x.resumed).length}));
