import { NodeManagedSourceAdapter } from "./node-managed-source-adapter.js";import { JsonSourceSyncPersistence } from "./json-source-sync-persistence.js";import { SourceSyncScheduler } from "./source-sync-scheduler.js";
import { redactSchedulerNotice,redactWorkerDetail,safeErrorCode } from "./log-redaction.js";
export interface SourceSyncDaemonConfig{managedRoot:string;stateFile:string;reconcileIntervalMs:number;outboxIntervalMs:number;buildIntervalMs:number;shutdownTimeoutMs?:number}
export interface BoundedWorker{runOnce():Promise<unknown>}
export type DaemonEvent={kind:"started"|"stopped"|"tick-succeeded"|"tick-failed"|"scheduler";atMs:number;worker?:"reconcile"|"outbox"|"build";detail?:unknown};
export interface DaemonHealth{state:"idle"|"running"|"stopping"|"stopped";startedAtMs:number|null;lastSuccess:Partial<Record<"reconcile"|"outbox"|"build",number>>;lastError:Partial<Record<"reconcile"|"outbox"|"build",string>>;ticks:Record<"reconcile"|"outbox"|"build",number>}
export function validateDaemonConfig(c:SourceSyncDaemonConfig){if(!c.managedRoot.trim()||!c.stateFile.trim())throw Error("managedRoot and stateFile are required");for(const k of ["reconcileIntervalMs","outboxIntervalMs","buildIntervalMs"] as const)if(!Number.isSafeInteger(c[k])||c[k]<100)throw Error(`${k} must be at least 100ms`);const timeout=c.shutdownTimeoutMs??10_000;if(!Number.isSafeInteger(timeout)||timeout<1||timeout>120_000)throw Error("shutdownTimeoutMs must be an integer from 1 to 120000ms");return c}
export class SourceSyncDaemon{readonly #scheduler:SourceSyncScheduler;readonly #health:DaemonHealth={state:"idle",startedAtMs:null,lastSuccess:{},lastError:{},ticks:{reconcile:0,outbox:0,build:0}};#timers=new Set<ReturnType<typeof setTimeout>>();#controller:AbortController|null=null;readonly #active=new Map<"reconcile"|"outbox"|"build",Promise<unknown>>();
 constructor(readonly config:SourceSyncDaemonConfig,private readonly outbox:BoundedWorker,private readonly build:BoundedWorker,private readonly emit:(e:DaemonEvent)=>void=()=>{},scheduler?:SourceSyncScheduler,private readonly now:()=>number=Date.now){validateDaemonConfig(config);this.#scheduler=scheduler??new SourceSyncScheduler(new NodeManagedSourceAdapter(config.managedRoot),new JsonSourceSyncPersistence(config.stateFile),{onNotice:n=>this.emit({kind:"scheduler",atMs:this.now(),detail:redactSchedulerNotice(n)})})}
 health(){return structuredClone(this.#health)}async start(signal?:AbortSignal){if(this.#health.state==="running")return;if(signal?.aborted){this.#health.state="stopped";return}this.#controller=new AbortController();signal?.addEventListener("abort",()=>void this.stop(),{once:true});this.#health.state="running";this.#health.startedAtMs=this.now();await this.#scheduler.start();await this.#scheduler.idle();if(this.#health.state!=="running"||this.#controller.signal.aborted)return;this.emit({kind:"started",atMs:this.now()});this.#loop("reconcile",this.config.reconcileIntervalMs,()=>this.#scheduler.reconcileNow());this.#loop("outbox",this.config.outboxIntervalMs,()=>this.outbox.runOnce());this.#loop("build",this.config.buildIntervalMs,()=>this.build.runOnce())}
 async drainOnce(){await this.#runExclusive("reconcile",async()=>{await this.#scheduler.reconcileNow();await this.#scheduler.idle()});const outbox=await this.#runExclusive("outbox",()=>this.outbox.runOnce());const build=await this.#runExclusive("build",()=>this.build.runOnce());return{outbox,build}}
 async stop(){if(this.#health.state!=="running")return;this.#health.state="stopping";this.#controller?.abort();for(const t of this.#timers)clearTimeout(t);this.#timers.clear();this.#scheduler.stop();const settling=Promise.allSettled([...this.#active.values(),this.#scheduler.idle()]);const timeoutMs=this.config.shutdownTimeoutMs??10_000;let timer:ReturnType<typeof setTimeout>|undefined;const timedOut=await Promise.race([settling.then(()=>false),new Promise<true>(resolve=>{timer=setTimeout(()=>resolve(true),timeoutMs)})]);if(timer!==undefined)clearTimeout(timer);this.#health.state="stopped";this.emit({kind:"stopped",atMs:this.now(),...(timedOut?{detail:{code:"shutdown_timeout"}}:{})})}
 #runExclusive(name:"reconcile"|"outbox"|"build",work:()=>Promise<unknown>){const active=this.#active.get(name);if(active)return active;const run=work().finally(()=>{if(this.#active.get(name)===run)this.#active.delete(name)});this.#active.set(name,run);return run}
 #loop(name:"reconcile"|"outbox"|"build",interval:number,work:()=>Promise<unknown>){const run=async()=>{if(this.#controller?.signal.aborted)return;this.#health.ticks[name]++;try{const detail=redactWorkerDetail(await this.#runExclusive(name,work));if(this.#health.state==="stopped")return;this.#health.lastSuccess[name]=this.now();delete this.#health.lastError[name];this.emit({kind:"tick-succeeded",worker:name,atMs:this.now(),detail})}catch(e){if(this.#health.state==="stopped")return;const code=safeErrorCode(e,"worker_failed");this.#health.lastError[name]=code;this.emit({kind:"tick-failed",worker:name,atMs:this.now(),detail:{code}})}if(!this.#controller?.signal.aborted){const t=setTimeout(()=>{this.#timers.delete(t);void run()},interval);this.#timers.add(t)}};void run()}}
