import{describe,expect,it,vi}from"vitest";import{D1BuildJobStore}from"./d1-build-job-store.js";import type{D1DatabaseBinding}from"./bindings.js";
const job={jobId:"job",buildId:"build",bookId:"book",sourceRevisionId:"revision",kind:"reader"as const,state:"in-flight"as const,attempt:1,nextAttemptAtMs:0,leaseId:"lease",leaseUntilMs:10,recordVersion:3,lastError:null};
const artifact={artifactId:"artifact",kind:"reader"as const,bookId:"book",sourceRevisionId:"revision",buildId:"build",status:"ready"as const,fingerprint:{algorithm:"sha256"as const,hex:"a".repeat(64),byteLength:1},objectKey:"artifacts/a",engineVersion:"v1"};
describe("D1 build completion",()=>{
 it("claims build jobs with a per-book fair SQL rank before the bounded limit",async()=>{const sql:string[]=[],db:D1DatabaseBinding={prepare(s){sql.push(s);return{bind(){return this},first:async()=>null,all:async()=>({success:true,results:[]}),run:async()=>({success:true})}}};expect(await new D1BuildJobStore(db).claim(1,"lease",100,5)).toEqual([]);expect(sql[0]).toContain("ROW_NUMBER() OVER (PARTITION BY book_id");expect(sql[0]).toContain("ORDER BY fair_rank")});
 it("commits manifest and lease CAS in one D1 batch",async()=>{const batch=vi.fn(async()=>[{success:true,meta:{changes:1}},{success:true,meta:{changes:1}}]),db:D1DatabaseBinding={prepare(sql){const statement={bind(){return statement},first:async()=>sql.startsWith("SELECT")?{manifest_json:JSON.stringify({buildId:"build",bookId:"book",sourceRevisionId:"revision",status:"processing",artifacts:[],createdAt:"now"})}:null,all:async()=>({success:true,results:[]}),run:async()=>({success:true})};return statement},batch};expect(await new D1BuildJobStore(db).complete(job,artifact)).toBe(true);expect(batch).toHaveBeenCalledOnce();expect(batch.mock.calls[0]![0]).toHaveLength(2)});
 it("fails closed when a binding cannot provide a transactional batch",async()=>{const db:D1DatabaseBinding={prepare(sql){return{bind(){return this},first:async()=>sql.startsWith("SELECT")?{manifest_json:JSON.stringify({buildId:"build",bookId:"book",sourceRevisionId:"revision",status:"processing",artifacts:[],createdAt:"now"})}:null,all:async()=>({success:true,results:[]}),run:async()=>({success:true})}}};await expect(new D1BuildJobStore(db).complete(job,artifact)).rejects.toThrow(/transactional batch/)});
});
describe("D1 atomic publication cache contract",()=>{it("swaps active version and enqueues one replay-safe event in the same batch",async()=>{const batch=vi.fn(async()=>[{success:true,meta:{changes:1}},{success:true,meta:{changes:1}}]),sql:string[]=[],db:D1DatabaseBinding={prepare(s){sql.push(s);return{bind(){return this},first:async()=>null,all:async()=>({success:true,results:[]}),run:async()=>({success:true})}},batch};expect(await new D1BuildJobStore(db).publish({kind:"publish",expectedActiveBuildId:"old",nextActiveBuildId:"new",nextActiveSourceRevisionId:"revision",activeManifestEtag:'"build-new"',invalidationOperationId:"publication:book:new",artifactIds:{} as never})).toBe(true);expect(batch.mock.calls[0]![0]).toHaveLength(2);expect(sql.join(" ")).toContain("cache_version=book_publications.cache_version+1");expect(sql.join(" ")).toContain("INSERT OR IGNORE INTO cache_invalidation_outbox")})});
