import type { BookBuildManifest } from "@library/source-sync";
import type { D1DatabaseBinding,R2BucketBinding } from "./bindings.js";
import { D1BuildJobStore } from "./d1-build-job-store.js";
import { ServiceAuthError,type BuildServiceScope,type BuildServiceTokenVerifier } from "./service-auth.js";
export class BuildServiceRouter{
 readonly #store:D1BuildJobStore;
 constructor(private readonly db:D1DatabaseBinding,private readonly bucket:R2BucketBinding,private readonly auth:BuildServiceTokenVerifier){this.#store=new D1BuildJobStore(db)}
 async handle(r:Request):Promise<Response>{try{const p=new URL(r.url).pathname.replace(/\/+$/,'');
  if(r.method==='GET'&&p.endsWith('/build-service/check')){for(const scope of ['build:claim','build:write','revision:read','artifact:write','publish:write'] as const)await this.allow(r,scope);return json({ok:true,service:'source-sync-build',scopes:'verified'})}
  if(r.method==='POST'&&p.endsWith('/builds/ensure')){await this.allow(r,'build:write');await this.#store.ensureBuildJobs(await r.json() as BookBuildManifest);return json({ok:true})}
  if(r.method==='POST'&&p.endsWith('/build-jobs/claim')){await this.allow(r,'build:claim');const x=await r.json() as any;return json(await this.#store.claim(x.nowMs,x.leaseId,x.leaseMs,x.limit))}
  for(const a of['complete','retry','fail'] as const)if(r.method==='POST'&&p.endsWith(`/build-jobs/${a}`)){await this.allow(r,'build:write');const x=await r.json() as any;const committed=a==='complete'?await this.#store.complete(x.job,x.artifact):a==='retry'?await this.#store.retry(x.job,x.nextAttemptAtMs,x.code):await this.#store.fail(x.job,x.code);return json({committed})}
  if(r.method==='POST'&&p.endsWith('/build-jobs/publish')){await this.allow(r,'publish:write');return json({committed:await this.#store.publish(await r.json() as any)})}
  const m=p.match(/\/builds\/([^/]+)\/manifest$/);if(r.method==='GET'&&m?.[1]){await this.allow(r,'build:claim');return json(await this.#store.getManifest(decodeURIComponent(m[1])))}
  const a=p.match(/\/books\/([^/]+)\/active-build$/);if(r.method==='GET'&&a?.[1]){await this.allow(r,'build:claim');const active=await this.#store.getActivePublication(decodeURIComponent(a[1]));if(!active)return json({buildId:null});if(r.headers.get('if-none-match')===active.etag)return new Response(null,{status:304,headers:{etag:active.etag,'cache-control':'private, no-cache'}});return Response.json(active,{headers:{etag:active.etag,'cache-control':'private, no-cache','x-artifact-cache-policy':'public, max-age=31536000, immutable'}})}
  const v=p.match(/\/source-revisions\/([^/]+)\/bytes$/);if(r.method==='GET'&&v?.[1]){await this.allow(r,'revision:read');const id=decodeURIComponent(v[1]),row=await this.db.prepare("SELECT r.immutable_object_key AS key,r.sha256,e.id AS edition_id,COALESCE(e.format,'docx') AS format FROM book_source_revisions r LEFT JOIN source_editions e ON e.id=r.id AND e.work_id=r.book_id WHERE r.id=?1").bind(id).first<{key:string;sha256:string;edition_id:string|null;format:string}>();if(!row)return json({error:{code:'revision_not_found'}},404);const o=await this.bucket.get(row.key);return o?new Response(o.body,{headers:{'content-length':String(o.size),'content-type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','x-source-edition-id':row.edition_id??id,'x-source-format':row.format,'x-source-sha256':row.sha256,'cache-control':'no-store'}}):json({error:{code:'revision_bytes_missing'}},404)}
  if(r.method==='PUT'&&p.endsWith('/artifacts/immutable')){await this.allow(r,'artifact:write');const key=r.headers.get('x-artifact-key')??'',hex=r.headers.get('x-content-sha256')??'',size=Number(r.headers.get('x-content-length')),bytes=new Uint8Array(await r.arrayBuffer());if(!/^artifacts\/[\w.:/-]+$/.test(key)||!/^[0-9a-f]{64}$/.test(hex)||size!==bytes.byteLength||await sha(bytes)!==hex)return json({error:{code:'artifact_digest_mismatch'}},422);const put=await this.bucket.put(key,bytes,{onlyIf:{etagDoesNotMatch:'*'},customMetadata:{sha256:hex,byteLength:String(size)}});return json(put===null?{deduplicated:true}:{created:true})}
  return json({error:{code:'not_found'}},404)}catch(e){return e instanceof ServiceAuthError?json({error:{code:e.code}},e.status):json({error:{code:'build_service_error'}},500)}}
 private allow(r:Request,s:BuildServiceScope){return this.auth.verify(r,s)}
}
async function sha(b:Uint8Array){const copy=new Uint8Array(b);const h=await crypto.subtle.digest('SHA-256',copy.buffer);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function json(v:unknown,status=200){return Response.json(v,{status,headers:{'cache-control':'no-store'}})}
