import{describe,expect,it,vi}from"vitest";import{QuarantineResolutionAuthority,type QuarantineResolutionStore}from"../../source-sync-server/src/index.js";import{HmacBuildServiceTokenVerifier}from"./service-auth.js";import{QuarantineServiceRouter}from"./quarantine-router.js";
const record={quarantineId:"q",uploadId:"u",bookId:"b",operationId:"op",deviceId:"d",reasonCode:"external_relationship",status:"pending"as const,recordVersion:0,createdAt:"now",resolutionReason:null};
function fixture(overrides:Partial<QuarantineResolutionStore>={}){const store:QuarantineResolutionStore={list:async()=>[record],detail:async id=>id==="q"?record:null,lease:async()=>true,findResolution:async()=>null,resolve:async()=>true,...overrides};return new QuarantineServiceRouter(new QuarantineResolutionAuthority(store,()=>1000),new HmacBuildServiceTokenVerifier("secret",undefined,"quarantine-service"))}
function request(path:string,scope:string,init:RequestInit={}){return new Request(`https://sync.example/build-service/${path}`,{...init,headers:{authorization:"Bearer secret","x-service-scopes":scope,...init.headers}})}
describe("quarantine service router",()=>{
 it("keeps read and resolve scopes separate and rejects user bearer tokens",async()=>{const router=fixture();expect((await router.handle(request("quarantines","quarantine:read"))).status).toBe(200);expect((await router.handle(request("quarantines/q/lease","quarantine:read",{method:"POST",body:JSON.stringify({leaseId:"l",leaseMs:1000,expectedRecordVersion:0})}))).status).toBe(403);expect((await router.handle(new Request("https://sync.example/build-service/quarantines",{headers:{authorization:"Bearer user-oidc-token","x-service-scopes":"quarantine:read"}}))).status).toBe(401)});
 it("returns ID-scoped detail and not-found without leaking another record",async()=>{const router=fixture();expect((await router.handle(request("quarantines/q","quarantine:read"))).status).toBe(200);expect((await router.handle(request("quarantines/other","quarantine:read"))).status).toBe(404)});
 it("surfaces lost lease CAS and replays a resolution without mutation",async()=>{const resolve=vi.fn(async()=>true);let leased=false;const router=fixture({lease:async()=>{if(leased)return false;leased=true;return true},findResolution:async(_id,operation)=>operation==="same"?{status:"allowed",recordVersion:2}:null,resolve});const body={leaseId:"lease",leaseMs:1000,expectedRecordVersion:0};expect((await router.handle(request("quarantines/q/lease","quarantine:resolve",{method:"POST",body:JSON.stringify(body)}))).status).toBe(200);expect((await router.handle(request("quarantines/q/lease","quarantine:resolve",{method:"POST",body:JSON.stringify(body)}))).status).toBe(409);const replay=await router.handle(request("quarantines/q/resolve","quarantine:resolve",{method:"POST",body:JSON.stringify({resolutionId:"same",leaseId:"lease",decision:"allow",reason:"reviewed",expectedRecordVersion:1})}));expect(replay.status).toBe(200);expect(resolve).not.toHaveBeenCalled()});
});
