import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Store,LANGUAGES,prepareSource,normalize,validateResult} from '../core.mjs';
import worker,{LocalizationCoordinator,callProvider} from '../index.mjs';
const source=(id='book-1',text='شرح كتاب الطهارة',kind='book')=>({kind,id,source:text,public:true});
function fixture(languages=['en','fr']){
 const db=new DatabaseSync(':memory:');let now=Date.UTC(2026,9,2);
 const exec=(q,...p)=>db.prepare(q).all(...p),transaction=fn=>{db.exec('BEGIN');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};
 return {db,exec,transaction,store:new Store(exec,transaction,{languages,now:()=>now}),advance:ms=>now+=ms,close:()=>db.close()};
}
async function scenario(fn,languages){const f=fixture(languages);try{await fn(f);}finally{f.close();}}
test('36 distinct target languages',()=>assert.equal(new Set(LANGUAGES).size,36));
test('normalization removes harmless whitespace, preserves Arabic meaning distinctions',()=>{assert.equal(normalize('  عِلْم\n  إبراهيم  '),'عِلْم إبراهيم');assert.notEqual(normalize('علم'),normalize('عِلْم'));assert.notEqual(normalize('إن'),normalize('ان'));});
test('same normalized content shares unit without merging identities',async()=>{const a=await prepareSource(source('a','عنوان  الكتاب')),b=await prepareSource(source('b','عنوان\nالكتاب'));assert.equal(a.unit,b.unit);assert.notEqual(a.key,b.key);});
test('kind and context separate ambiguous units',async()=>{const a=await prepareSource(source('a','فتح','ui')),b=await prepareSource({...source('b','فتح','ui'),context:'noun'}),c=await prepareSource(source('c','فتح'));assert.notEqual(a.unit,b.unit);assert.notEqual(a.unit,c.unit);});
for(const [label,value]of [['null',null],['private',{...source(),public:false}],['body',{...source(),kind:'body'}],['empty',{...source(),source:''}],['too long',{...source(),source:'ا'.repeat(3001)}],['invalid active',{...source(),active:'false'}]])test('rejects '+label,async()=>assert.rejects(()=>prepareSource(value)));
test('repeated ingestion creates no duplicate tasks',()=>scenario(async f=>{const r=await prepareSource(source());assert.equal(f.store.ingest([r]).changed,1);assert.equal(f.store.ingest([r]).unchanged,1);assert.equal(f.store.one('SELECT COUNT(*) n FROM jobs').n,2);}));
test('one author identity reused by many books',()=>scenario(async f=>{for(let i=0;i<5;i++)f.store.ingest([await prepareSource(source('shamela:4','ابن تيمية','author')),await prepareSource(source('b'+i,'كتاب '+i))]);assert.equal(f.store.one("SELECT COUNT(*) n FROM sources WHERE kind='author'").n,1);}));
test('completion survives process restart and avoids provider re-use',()=>scenario(async f=>{const r=await prepareSource(source());f.store.ingest([r]);f.store.complete(f.store.claim().job,'Purification');const restarted=new Store(f.exec,f.transaction,{languages:['en']});restarted.ingest([r]);assert.equal(restarted.claim().job,null);assert.equal(restarted.publicationRows('en','book',r.shard)[0].translation,'Purification');},['en']));
test('another identity with same unit uses existing memory',()=>scenario(async f=>{const r=await prepareSource(source('a'));f.store.ingest([r]);f.store.complete(f.store.claim().job,'Purification');f.store.ingest([await prepareSource(source('b'))]);assert.equal(f.store.claim().job,null);assert.equal(f.store.one('SELECT COUNT(*) n FROM memory').n,1);},['en']));
test('late old result cannot appear under updated title',()=>scenario(async f=>{const a=await prepareSource(source()),b=await prepareSource(source('book-1','شرح كتاب الصلاة'));f.store.ingest([a]);const old=f.store.claim().job;f.store.ingest([b]);f.store.complete(old,'Old title');assert.equal(f.store.publicationRows('en','book',a.shard).length,0);f.store.complete(f.store.claim().job,'New title');assert.equal(f.store.publicationRows('en','book',b.shard)[0].translation,'New title');},['en']));
test('withdrawal removes public row but retains memory',()=>scenario(async f=>{const r=await prepareSource(source());f.store.ingest([r]);f.store.complete(f.store.claim().job,'Title');f.store.ingest([{...r,active:0}]);assert.equal(f.store.publicationRows('en','book',r.shard).length,0);assert.equal(f.store.one('SELECT COUNT(*) n FROM memory').n,1);},['en']));
test('active lease prevents another leader; stale token cannot win',()=>scenario(async f=>{f.store.ingest([await prepareSource(source())]);const a=f.store.claim().job;assert.equal(f.store.claim().job,null);f.advance(120001);const b=f.store.claim().job;assert.notEqual(a.token,b.token);assert.equal(f.store.complete(a,'Stale'),false);assert.equal(f.store.complete(b,'Current'),true);},['en']));
test('rate-limit failure delays retry, persists its reason',()=>scenario(async f=>{f.store.ingest([await prepareSource(source())]);f.store.fail(f.store.claim().job,'provider_http_429',{retryAfter:3600000});assert.equal(f.store.claim().job,null);f.advance(3600000);assert(f.store.claim().job);},['en']));
test('daily reservation limit resets next UTC day',()=>scenario(async f=>{f.store.ingest([await prepareSource(source())]);assert.equal(f.store.claim({dailyCalls:0}).reason,'budget');const j=f.store.claim({dailyCalls:1}).job;f.store.fail(j,'error');f.advance(61000);assert.equal(f.store.claim({dailyCalls:1}).reason,'budget');f.advance(86400000);assert(f.store.claim({dailyCalls:1}).job);},['en']));
test('monthly source-character budget separate from daily limit',()=>scenario(async f=>{f.store.ingest([await prepareSource(source())]);assert.equal(f.store.claim({monthlyCharacters:1}).reason,'budget');assert.equal(f.store.one('SELECT COUNT(*) n FROM budget').n,0);},['en']));
test('reviewed memory wins over late machine response',()=>scenario(async f=>{const r=await prepareSource(source());f.store.ingest([r]);const job=f.store.claim().job;f.store.seed(r.unit,'en','Reviewed',{reviewed:true});assert.equal(f.store.complete(job,'Automatic'),false);assert.equal(f.store.seed(r.unit,'en','Lower quality'),false);assert.equal(f.store.publicationRows('en','book',r.shard)[0].translation,'Reviewed');},['en']));
test('names pause until proper-name adapter configured',()=>scenario(async f=>{f.store.ingest([await prepareSource(source('author','عبد الله','author'))]);assert.equal(f.store.claim().job,null);assert(f.store.claim({allowNames:true}).job);},['en']));
test('placeholders retained exactly',()=>{assert.throws(()=>validateResult('نتائج {p0}','Results'));assert.throws(()=>validateResult('نتائج {p0}','{p0} {p0}'));assert.equal(validateResult('نتائج {p0}','Results {p0}'),'Results {p0}');});
test('empty, oversized and severely truncated results rejected',()=>{for(const s of ['', 'x'.repeat(16001),'\ufffd'])assert.throws(()=>validateResult('عنوان',s));assert.throws(()=>validateResult('أ'.repeat(200),'x'));});
test('publication cannot acknowledge a concurrent update',()=>scenario(async f=>{f.store.ingest([await prepareSource(source())]);const p=f.store.pendingPublications()[0];f.store.dirty(p.locale,p.kind,p.shard);f.store.published(p);assert(f.store.pendingPublications().length>0);},['en']));
test('missing language never publishes source pretending to be translation',()=>scenario(async f=>{const r=await prepareSource(source('ui','الإعدادات','ui'));f.store.ingest([r]);f.store.seed(r.unit,'en','Settings',{reviewed:true});assert.equal(f.store.publicationRows('fr','ui','0').length,0);assert.equal(f.store.publicationRows('en','ui','0')[0].translation,'Settings');}));
test('public dictionary read never touches jobs/provider',async()=>{let calls=0;const r=await worker.fetch(new Request('https://x/api/localization/v1/dict/en/ui/0.json'),{LOCALE_FILES:{get:async()=>({body:'{}',httpEtag:'"a"'})},LOCALIZATION_COORDINATOR:{get(){calls++;throw Error();}}});assert.equal(r.status,200);assert.equal(await r.text(),'{}');assert.equal(calls,0);});
test('missing pack does not enqueue translation',async()=>{const r=await worker.fetch(new Request('https://x/api/localization/v1/dict/en/ui/0.json'),{LOCALE_FILES:{get:async()=>null}});assert.equal(r.status,404);assert.equal(r.headers.get('cache-control'),'no-store');});
test('unauthorized mutations rejected',async()=>{const r=await worker.fetch(new Request('https://x/api/localization/admin/sources',{method:'POST',body:'{}'}),{LOCALIZATION_ADMIN_TOKEN:'a'.repeat(40)});assert.equal(r.status,401);});
test('malformed locale cannot read arbitrary R2 object',async()=>{assert.equal((await worker.fetch(new Request('https://x/v1/dict/xx/ui/0.json'),{})).status,404);});
test('generic translation adapter retains whole source title',async()=>{let sent;const p=await callProvider({source:'شرح كتاب الطهارة',locale:'en',kind:'book'},{TRANSLATOR:{fetch:async r=>{sent=await r.json();return Response.json({translation:'Book of Purification',engine:'test'});}}});assert.equal(sent.text,'شرح كتاب الطهارة');assert.equal(p.provider,'test');});
test('proper-name translation never falls through generic text API',async()=>assert.rejects(()=>callProvider({source:'عبد الله',locale:'en',kind:'author'},{}),/name_adapter_required/));
test('non-success provider response rejected',async()=>assert.rejects(()=>callProvider({source:'الكتاب',locale:'en',kind:'book'},{TRANSLATOR:{fetch:async()=>new Response('limit',{status:429})}}),/provider_http_429/));
test('production processing defaults to disabled',()=>scenario(f=>{assert.equal(f.store.status().enabled,false);assert.equal(f.store.status().budget.length,0);}));
test('failed R2 write retries without losing completed memory',()=>scenario(async f=>{let fail=true,out;const actor=new LocalizationCoordinator({storage:{sql:{exec:f.exec},transactionSync:f.transaction}},{LOCALE_FILES:{put:async(k,v)=>{if(fail)throw Error('r2_down');out={k,v:JSON.parse(v)};}}});actor.store=f.store;const r=await prepareSource(source());f.store.ingest([r]);f.store.seed(r.unit,'en','Title');await assert.rejects(()=>actor.publish());assert.equal(f.store.pendingPublications().length,1);fail=false;await actor.publish();assert.equal(out.v.rows[0][2],'Title');assert.equal(f.store.pendingPublications().length,0);},['en']));
test('source cap aborts complete ingest transaction',()=>scenario(async f=>{f.store.maxSources=1;await assert.rejects(async()=>f.store.ingest([await prepareSource(source('a')),await prepareSource(source('b'))]),/source_limit/);assert.equal(f.store.one('SELECT COUNT(*) n FROM sources').n,0);}));
test('two identical source IDs in one batch rejected',()=>scenario(async f=>{const r=await prepareSource(source());assert.throws(()=>f.store.ingest([r,r]),/invalid_batch/);}));
test('invalid JSON null is handled, not a runtime crash',()=>scenario(async f=>{const actor=new LocalizationCoordinator({storage:{sql:{exec:f.exec},transactionSync:f.transaction}},{});const r=await actor.fetch(new Request('https://internal/sources',{method:'POST',headers:{'content-type':'application/json'},body:'null'}));assert.equal(r.status,400);}));
test('proper-name prompt preserves full name and treats source as data',async()=>{
 const {nameProvider}=await import('../names.mjs');let sent;
 const r=await nameProvider({source:'عبد الله',locale:'en',context:''},{NAME_API_ENABLED:'true',MISTRAL_API_KEY:'test-not-secret',NAME_MODEL:'test'},async(u,o)=>{sent=JSON.parse(o.body);return Response.json({choices:[{finish_reason:'stop',message:{content:'{"name":"Abdullah"}'}}]});});
 assert.equal(r.translation,'Abdullah');assert.match(sent.messages[0].content,/Do not translate the literal meanings/);assert.equal(JSON.parse(sent.messages[1].content).source,'عبد الله');
});
test('proper-name network call is disabled without explicit opt-in',async()=>{
 const {nameProvider}=await import('../names.mjs');await assert.rejects(()=>nameProvider({source:'عبد الله',locale:'en'},{MISTRAL_API_KEY:'test',NAME_MODEL:'test'},()=>{throw Error('must_not_call');}),/name_adapter_required/);
});
