import {test} from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {readFileSync,readdirSync} from 'node:fs'
import {preparePublicBookSearch as stagePublicBookSearch,normalizePublicSearch,publicSearchOffsets} from '../functions/api/_public-book-search.js'
async function preparePublicBookSearch(...args){for(let n=0;n<5;n++){const result=await stagePublicBookSearch(...args);if(result!=='pending')return result}throw Error('staging_did_not_finish')}
import {queryPublicBooks,onRequest} from '../functions/api/search/public-books.js'
function fixture(){
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON')
 for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sql.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'))
 sql.exec("INSERT INTO accounts(subject,email,role) VALUES('owner','fixture@example.test','super-admin');INSERT INTO user_books(id,owner_subject,title,author,object_key,mime_type,byte_length,visibility,review_status) VALUES('book','owner','التوحيد','مؤلف','private/book','text/plain',10,'public','approved')")
 const now=Math.floor(Date.now()/1000)
 sql.prepare("UPDATE public_book_index_jobs SET state='running',lease_token='test_token_0000000',lease_until=? WHERE book_id='book'").run(now+300)
 const db={prepare(query){let args=[];return{bind(...v){args=v;return this},async first(){return sql.prepare(query).get(...args)??null},async all(){return{results:sql.prepare(query).all(...args)}},async run(){return{meta:{changes:Number(sql.prepare(query).run(...args).changes)}}}}},async batch(statements){return Promise.all(statements.map(s=>s.run()))}}
 const job=sql.prepare("SELECT * FROM public_book_index_jobs WHERE book_id='book'").get()
 const artifact={contract:'public-book-index/1',bookId:'book',generation:job.generation,title:'التوحيد',author:'مؤلف',coverageMode:'text-and-headings',rows:Array.from({length:1300},(_,i)=>({text:`توحيد الله فقرة ${i}`,paragraphIndex:i})),headings:[{value:'باب التوحيد',pageIndex:0}]}
 const ready=()=>sql.prepare("UPDATE public_book_index_jobs SET state='ready',manifest_sha256=?,source_sha256=?,artifact_key='public-book-index/test',parser_version='test',coverage_mode=?,checkpoint=2 WHERE book_id='book'").run('a'.repeat(64),'b'.repeat(64),artifact.coverageMode)
 return{sql,db,job,artifact,now,ready}
}
test('generation verified FTS returns all1300 paragraphs across13 pages, not just first40',async()=>{const f=fixture();try{
 assert.equal(await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now),true)
 let result=await (await queryPublicBooks(f.db,new URLSearchParams('q=توحيد'))).json();assert.equal(result.totalDocuments,0)
 f.ready();const seen=[];for(let offset=0;offset<1300;offset+=100){result=await(await queryPublicBooks(f.db,new URLSearchParams({q:'توحيد',offset:String(offset)}))).json();assert.equal(result.totalDocuments,1300);seen.push(...result.hits.map(h=>h.anchor.paragraphIndex))}assert.equal(new Set(seen).size,1300)
 }finally{f.sql.close()}})
for(const mutation of ["visibility='private'","review_status='rejected'","deleted_at='now'","title='changed'","object_key='private/new'"])test('immediate privacy/generation fence '+mutation,async()=>{const f=fixture();try{await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now);f.ready();const first=await(await queryPublicBooks(f.db,new URLSearchParams('q=توحيد'))).json();f.sql.exec('UPDATE user_books SET '+mutation);assert.equal((await queryPublicBooks(f.db,new URLSearchParams({q:'توحيد',snapshot:first.snapshot}))).status,409);assert.equal((await(await queryPublicBooks(f.db,new URLSearchParams('q=توحيد'))).json()).totalDocuments,0)}finally{f.sql.close()}})
test('PDF searches only bookmarks; corrupt binding and expired lease failclosed',async()=>{const f=fixture();try{f.artifact.coverageMode='pdf-bookmarks-only';await assert.rejects(()=>preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now),/pdf_body/);f.artifact.rows=[];assert.equal(await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now),true);f.ready();const data=await(await queryPublicBooks(f.db,new URLSearchParams('q=التوحيد'))).json();assert.equal(data.totalDocuments,1);assert.equal(data.hits[0].field,'heading');f.sql.exec("UPDATE public_book_search_receipts SET manifest_sha256='corrupt'");assert.equal((await(await queryPublicBooks(f.db,new URLSearchParams('q=التوحيد'))).json()).totalDocuments,0);f.sql.exec("UPDATE public_book_index_jobs SET state='running',lease_until=1");assert.equal(await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),1),false)}finally{f.sql.close()}})
test('query validation and disabled route make no DB request',async()=>{assert.equal((await onRequest({request:new Request('https://example.test/'),env:{}})).status,404);const f=fixture();try{assert.equal((await queryPublicBooks(f.db,new URLSearchParams('q=a&limit=101'))).status,400);assert.equal((await queryPublicBooks(f.db,new URLSearchParams('q=a&mode=fuzzy'))).status,422);assert.equal(normalizePublicSearch('إلى الْقُرْآن (١)'),'الي القران')}finally{f.sql.close()}})
test('staging resumes withoutreadyreceipt and withdrawal between stages fencescursor',async()=>{const f=fixture();try{assert.equal(await stagePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now),'pending');assert.equal(f.sql.prepare('SELECT next_row FROM public_book_search_staging').get().next_row,1000);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM public_book_search_receipts').get().n,0);f.sql.exec("UPDATE user_books SET visibility='private'");assert.equal(await stagePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now),false);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM public_book_search_receipts').get().n,0)}finally{f.sql.close()}})
test('far match snippet preserves original Arabic diacritics and omits internaloffsets',async()=>{const f=fixture();try{f.artifact.rows=[{text:'مُقَدِّمَةٌ '.repeat(1000)+'تَوْحِيدُ اللهِ خاتمة',paragraphIndex:0}];await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now);f.ready();const data=await(await queryPublicBooks(f.db,new URLSearchParams('q=توحيد'))).json();assert.equal(data.hits.length,1);assert.ok(data.hits[0].snippet.includes('تَوْحِيدُ اللهِ'));assert.ok(data.hits[0].snippet.length<1001);assert.equal(data.hits[0].anchor._searchOffsets,undefined);for(const value of ['  (١) إِلَى ﴿٢﴾ القرآن','𐐀abc İ ΣΟΣ','أَـبٌ،   ج'])assert.ok(publicSearchOffsets(value).length)}finally{f.sql.close()}})
for(const prefix of ['central-submission:','account-book:'])test('hidden legacy alias is excluded without staleFTS leakage '+prefix,async()=>{const f=fixture();try{await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now);f.ready();f.sql.prepare("INSERT INTO central_book_overrides(book_id,visibility,updated_by) VALUES(?,'hidden','owner')").run(prefix+'book');const result=await(await queryPublicBooks(f.db,new URLSearchParams('q=توحيد'))).json();assert.equal(result.totalDocuments,0);assert.equal(result.pendingBooks,0)}finally{f.sql.close()}})
test('privacy change between result read and response invalidates the entire snapshot',async()=>{const f=fixture();try{await preparePublicBookSearch(f.db,f.job,f.artifact,'a'.repeat(64),f.now);f.ready();const db={prepare(query){const statement=f.db.prepare(query),original=statement.all;statement.all=async()=>{const result=await original();f.sql.exec("UPDATE user_books SET visibility='private'");return result};return statement}};assert.equal((await queryPublicBooks(db,new URLSearchParams('q=توحيد'))).status,409)}finally{f.sql.close()}})
test('D1 inflated FTS trigger changes use RETURNING rows rather than meta.changes',async()=>{const f=fixture();try{const db={prepare(query){const statement=f.db.prepare(query),all=statement.all,run=statement.run;if(query.startsWith('INSERT INTO public_book_search_rows')){statement.run=async()=>{const result=await run();return{meta:{changes:result.meta.changes*11}}};statement.all=async()=>({...await all(),meta:{changes:999999}})}return statement}};assert.equal(await preparePublicBookSearch(db,f.job,f.artifact,'a'.repeat(64),f.now),true);assert.equal(f.sql.prepare('SELECT row_count FROM public_book_search_receipts').get().row_count,1303)}finally{f.sql.close()}})
