/** Inline-editor instructions. List values and biographies remain untouched. */
const labels=['الحياة والتاريخ','الصفات والتصنيفات','العلاقات العلمية','المؤلفات وكتب الخزانة','الاسم والتعريف','نص الترجمة','المؤلفات المعرّفة في الترجمة','هذا يحرر قائمة الترجمة، ولا يحذف الكتب المرتبطة بالمكتبة.'] as const
const row=(...values:string[])=>{if(values.length!==9)throw Error('Inline author locale length');return {labels:Object.fromEntries(labels.map((key,i)=>[key,values[i]!])),perLine:values[8]!}}
const rows={
en:row('Life and chronology','Attributes and categories','Scholarly relationships','Works and library books','Name and identity','Biography text','Works listed in the biography','This edits the biography’s list; it does not delete linked library books.','One entry per line'),
fr:row('Vie et chronologie','Attributs et catégories','Relations savantes','Œuvres et livres de la bibliothèque','Nom et identité','Texte de la biographie','Œuvres citées dans la biographie','Ceci modifie la liste de la biographie, sans supprimer les livres associés dans la bibliothèque.','Une entrée par ligne'),
ug:row('ھاياتى ۋە ۋاقىت تەرتىپى','سۈپەتلەر ۋە تۈرلەر','ئىلمىي مۇناسىۋەتلەر','ئەسەرلەر ۋە كۇتۇپخانا كىتابلىرى','ئىسمى ۋە سالاھىيىتى','تەرجىمىھال تېكىستى','تەرجىمىھالدا كۆرسىتىلگەن ئەسەرلەر','بۇ تەرجىمىھال تىزىملىكىنى تەھرىرلەيدۇ؛ باغلانغان كۇتۇپخانا كىتابلىرىنى ئۆچۈرمەيدۇ.','ھەر قۇرغا بىر تۈر'),
ckb:row('ژیان و مێژوو','تایبەتمەندی و پۆلەکان','پەیوەندییە زانستییەکان','بەرهەمەکان و کتێبەکانی کتێبخانە','ناو و ناسنامە','دەقی ژیاننامە','بەرهەمە ناسێنراوەکان لە ژیاننامە','ئەمە پێڕستی ژیاننامە دەستکاری دەکات؛ کتێبە بەستراوەکانی کتێبخانە ناسڕێتەوە.','هەر دانەیەک لە دێڕێک'),
ku:row('Jiyan û dîrok','Taybetmendî û kategorî','Têkiliyên zanistî','Berhem û pirtûkên pirtûkxaneyê','Nav û nasname','Nivîsa jiyannameyê','Berhemên di jiyannameyê de','Ev lîsteya jiyannameyê diguherîne; pirtûkên girêdayî yên pirtûkxaneyê jê nake.','Di her rêzekê de yek têketin'),
tr:row('Yaşam ve tarihler','Nitelikler ve kategoriler','İlmî ilişkiler','Eserler ve kütüphane kitapları','Ad ve kimlik','Biyografi metni','Biyografide belirtilen eserler','Bu işlem biyografideki listeyi düzenler; bağlantılı kütüphane kitaplarını silmez.','Her satıra bir kayıt'),
ur:row('زندگی اور تاریخیں','اوصاف اور زمرے','علمی تعلقات','تصانیف اور کتب خانے کی کتابیں','نام اور تعارف','سوانح کا متن','سوانح میں درج تصانیف','اس سے سوانح کی فہرست بدلتی ہے؛ کتب خانے کی منسلک کتابیں حذف نہیں ہوتیں۔','ہر سطر میں ایک اندراج'),
fa:row('زندگی و تاریخ‌ها','ویژگی‌ها و دسته‌بندی‌ها','روابط علمی','آثار و کتاب‌های کتابخانه','نام و هویت','متن زندگی‌نامه','آثار معرفی‌شده در زندگی‌نامه','این کار فهرست زندگی‌نامه را ویرایش می‌کند؛ کتاب‌های مرتبط کتابخانه را حذف نمی‌کند.','هر مورد در یک سطر'),
sw:row('Maisha na tarehe','Sifa na makundi','Mahusiano ya kielimu','Maandishi na vitabu vya maktaba','Jina na utambulisho','Maandishi ya wasifu','Maandishi yaliyotajwa katika wasifu','Hii hubadilisha orodha ya wasifu; haifuti vitabu vya maktaba vilivyounganishwa.','Ingizo moja kwa kila mstari'),
hi:row('जीवन और तिथियाँ','विशेषताएँ और श्रेणियाँ','विद्वत संबंध','कृतियाँ और पुस्तकालय की पुस्तकें','नाम और परिचय','जीवनी का पाठ','जीवनी में सूचीबद्ध कृतियाँ','यह जीवनी की सूची संपादित करता है; पुस्तकालय की जुड़ी पुस्तकें नहीं हटाता।','प्रति पंक्ति एक प्रविष्टि'),
hu:row('Élet és időrend','Jellemzők és kategóriák','Tudományos kapcsolatok','Művek és könyvtári könyvek','Név és személyazonosság','Életrajz szövege','Az életrajzban felsorolt művek','Ez az életrajz listáját szerkeszti; a kapcsolódó könyvtári könyveket nem törli.','Soronként egy bejegyzés'),
id:row('Kehidupan dan tanggal','Sifat dan kategori','Hubungan keilmuan','Karya dan buku perpustakaan','Nama dan identitas','Teks biografi','Karya yang tercantum dalam biografi','Ini mengubah daftar dalam biografi; tidak menghapus buku perpustakaan yang ditautkan.','Satu entri per baris'),
ms:row('Kehidupan dan tarikh','Sifat dan kategori','Hubungan keilmuan','Karya dan buku perpustakaan','Nama dan identiti','Teks biografi','Karya yang disenaraikan dalam biografi','Ini menyunting senarai biografi; tidak memadam buku perpustakaan yang dipautkan.','Satu entri setiap baris'),
bn:row('জীবন ও তারিখ','বৈশিষ্ট্য ও বিভাগ','জ্ঞানচর্চার সম্পর্ক','রচনাবলি ও গ্রন্থাগারের বই','নাম ও পরিচয়','জীবনীর পাঠ','জীবনীতে তালিকাভুক্ত রচনা','এটি জীবনীর তালিকা সম্পাদনা করে; গ্রন্থাগারের সংযুক্ত বই মুছে ফেলে না।','প্রতি লাইনে একটি তথ্য'),
ps:row('ژوند او نېټې','ځانګړنې او ډلې','علمي اړیکې','لیکنې او د کتابتون کتابونه','نوم او پېژندنه','د ژوندلیک متن','په ژوندلیک کې یادې شوې لیکنې','دا د ژوندلیک لړلیک سموي؛ د کتابتون تړلي کتابونه نه ړنګوي.','په هره کرښه کې یو توکی'),
so:row('Nolosha iyo taariikhaha','Sifooyin iyo qaybo','Xiriirrada aqooneed','Qoraallada iyo buugaagta maktabadda','Magaca iyo aqoonsiga','Qoraalka taariikh-nololeedka','Qoraallada ku qoran taariikh-nololeedka','Tani waxay beddeshaa liiska taariikh-nololeedka; ma tirtirto buugaagta maktabadda ee ku xiran.','Hal qodob sadar kasta'),
ha:row('Rayuwa da ranaku','Siffofi da rukuni','Alaƙar ilimi','Rubuce-rubuce da littattafan ɗakin karatu','Suna da ganewa','Rubutun tarihin rayuwa','Rubuce-rubucen da ke cikin tarihin rayuwa','Wannan yana gyara jerin tarihin rayuwa; ba ya goge littattafan ɗakin karatu da aka haɗa.','Abu ɗaya a kowane layi'),
ru:row('Жизнь и хронология','Характеристики и категории','Научные связи','Труды и книги библиотеки','Имя и сведения','Текст биографии','Труды, перечисленные в биографии','Это изменяет список в биографии, но не удаляет связанные книги библиотеки.','Одна запись в строке'),
uk:row('Життя та хронологія','Характеристики та категорії','Наукові зв’язки','Праці та книги бібліотеки','Ім’я та відомості','Текст біографії','Праці, перелічені в біографії','Це змінює список у біографії, але не видаляє пов’язані книги бібліотеки.','Один запис у рядку'),
de:row('Leben und Zeitangaben','Eigenschaften und Kategorien','Gelehrtenbeziehungen','Werke und Bibliotheksbücher','Name und Identität','Biografietext','In der Biografie aufgeführte Werke','Dies bearbeitet die Liste in der Biografie; verknüpfte Bibliotheksbücher werden nicht gelöscht.','Ein Eintrag pro Zeile'),
es:row('Vida y fechas','Atributos y categorías','Relaciones académicas','Obras y libros de la biblioteca','Nombre e identidad','Texto de la biografía','Obras enumeradas en la biografía','Esto modifica la lista de la biografía; no elimina los libros vinculados de la biblioteca.','Una entrada por línea'),
pt:row('Vida e datas','Atributos e categorias','Relações académicas','Obras e livros da biblioteca','Nome e identidade','Texto da biografia','Obras enumeradas na biografia','Isto edita a lista da biografia; não elimina os livros associados da biblioteca.','Uma entrada por linha'),
it:row('Vita e date','Caratteristiche e categorie','Relazioni accademiche','Opere e libri della biblioteca','Nome e identità','Testo della biografia','Opere elencate nella biografia','Questo modifica l’elenco della biografia; non elimina i libri collegati della biblioteca.','Una voce per riga'),
nl:row('Leven en tijdlijn','Eigenschappen en categorieën','Wetenschappelijke relaties','Werken en bibliotheekboeken','Naam en identiteit','Biografietekst','Werken vermeld in de biografie','Dit bewerkt de lijst in de biografie; gekoppelde bibliotheekboeken worden niet verwijderd.','Eén item per regel'),
sv:row('Liv och datum','Egenskaper och kategorier','Vetenskapliga relationer','Verk och biblioteksböcker','Namn och identitet','Biografitext','Verk som anges i biografin','Detta ändrar listan i biografin; länkade biblioteksböcker tas inte bort.','En post per rad'),
no:row('Liv og datoer','Egenskaper og kategorier','Faglige relasjoner','Verker og bibliotekbøker','Navn og identitet','Biografitekst','Verker oppført i biografien','Dette endrer listen i biografien; tilknyttede bibliotekbøker slettes ikke.','Én oppføring per linje'),
pl:row('Życie i daty','Cechy i kategorie','Relacje naukowe','Dzieła i książki biblioteki','Imię i tożsamość','Tekst biografii','Dzieła wymienione w biografii','To edytuje listę w biografii; nie usuwa powiązanych książek biblioteki.','Jeden wpis w wierszu'),
ro:row('Viață și date','Trăsături și categorii','Relații academice','Opere și cărți din bibliotecă','Nume și identitate','Textul biografiei','Opere enumerate în biografie','Aceasta editează lista biografiei; nu șterge cărțile asociate din bibliotecă.','O intrare pe rând'),
bs:row('Život i datumi','Osobine i kategorije','Naučne veze','Djela i knjige biblioteke','Ime i identitet','Tekst biografije','Djela navedena u biografiji','Ovo uređuje listu u biografiji; ne briše povezane knjige biblioteke.','Jedan unos po redu'),
sq:row('Jeta dhe datat','Tipare dhe kategori','Marrëdhëniet shkencore','Veprat dhe librat e bibliotekës','Emri dhe identiteti','Teksti i biografisë','Veprat e renditura në biografi','Kjo ndryshon listën e biografisë; nuk fshin librat e lidhur të bibliotekës.','Një hyrje për rresht'),
az:row('Həyat və tarixlər','Xüsusiyyətlər və kateqoriyalar','Elmi əlaqələr','Əsərlər və kitabxana kitabları','Ad və kimlik','Bioqrafiya mətni','Bioqrafiyada sadalanan əsərlər','Bu, bioqrafiyadakı siyahını dəyişir; əlaqəli kitabxana kitablarını silmir.','Hər sətirdə bir qeyd'),
uz:row('Hayot va sanalar','Sifatlar va turkumlar','Ilmiy aloqalar','Asarlar va kutubxona kitoblari','Ism va shaxsiyat','Tarjimai hol matni','Tarjimai holda ko‘rsatilgan asarlar','Bu tarjimai holdagi ro‘yxatni tahrirlaydi; bog‘langan kutubxona kitoblarini o‘chirmaydi.','Har bir qatorda bitta yozuv'),
kk:row('Өмірі мен даталары','Сипаттары мен санаттары','Ғылыми байланыстары','Еңбектері мен кітапхана кітаптары','Аты мен тұлғасы','Өмірбаян мәтіні','Өмірбаянда көрсетілген еңбектер','Бұл өмірбаяндағы тізімді өңдейді; байланыстырылған кітапхана кітаптарын жоймайды.','Әр жолда бір жазба'),
zh:row('生平与年代','特征与分类','学术关系','著作与馆藏图书','姓名与身份','传记正文','传记中列出的著作','这只编辑传记中的列表，不会删除关联的馆藏图书。','每行一项'),
ja:row('生涯と年代','特徴と分類','学問上の関係','著作と図書館の本','名前と人物情報','伝記の本文','伝記に記載された著作','伝記の一覧を編集します。関連付けられた図書館の本は削除しません。','1行につき1項目'),
ko:row('생애와 연대','특성과 분류','학문적 관계','저서와 도서관 도서','이름과 인물 정보','전기 본문','전기에 나열된 저서','전기의 목록을 편집하며 연결된 도서관 책은 삭제하지 않습니다.','한 줄에 항목 하나'),
} as const
export function addAuthorInlineTranslations(catalogs:Record<string,Record<string,string>>):void{
 const gregorian:Record<string,[string,string]>={en:['Birth (Gregorian)','Death (Gregorian)'],fr:['Naissance (grégorienne)','Décès (grégorien)'],ug:['تۇغۇلۇشى (مىلادىيە)','ۋاپاتى (مىلادىيە)'],ckb:['لەدایکبوون (زایینی)','کۆچی دوایی (زایینی)'],ku:['Jidayikbûn (Miladî)','Mirin (Miladî)'],tr:['Doğum (Miladi)','Ölüm (Miladi)'],ur:['پیدائش (عیسوی)','وفات (عیسوی)'],fa:['تولد میلادی','وفات میلادی'],sw:['Kuzaliwa (Gregori)','Kufariki (Gregori)'],hi:['जन्म (ग्रेगोरियन)','मृत्यु (ग्रेगोरियन)'],hu:['Születés (Gergely-naptár)','Halálozás (Gergely-naptár)'],id:['Lahir (Masehi)','Wafat (Masehi)'],ms:['Lahir (Masihi)','Wafat (Masihi)'],bn:['জন্ম (খ্রিষ্টীয়)','মৃত্যু (খ্রিষ্টীয়)'],ps:['زېږېدنه (میلادي)','مړینه (میلادي)'],so:['Dhalasho (Miilaadi)','Geeri (Miilaadi)'],ha:['Haihuwa (Miladiyya)','Rasuwa (Miladiyya)'],ru:['Рождение (григорианский календарь)','Смерть (григорианский календарь)'],uk:['Народження (григоріанський календар)','Смерть (григоріанський календар)'],de:['Geburt (gregorianisch)','Tod (gregorianisch)'],es:['Nacimiento (gregoriano)','Fallecimiento (gregoriano)'],pt:['Nascimento (gregoriano)','Falecimento (gregoriano)'],it:['Nascita (gregoriana)','Morte (gregoriana)'],nl:['Geboorte (Gregoriaans)','Overlijden (Gregoriaans)'],sv:['Födelse (gregoriansk)','Död (gregoriansk)'],no:['Fødsel (gregoriansk)','Død (gregoriansk)'],pl:['Narodziny (kalendarz gregoriański)','Śmierć (kalendarz gregoriański)'],ro:['Naștere (gregoriană)','Deces (gregorian)'],bs:['Rođenje (gregorijansko)','Smrt (gregorijanska)'],sq:['Lindja (gregoriane)','Vdekja (gregoriane)'],az:['Doğum (Miladi)','Ölüm (Miladi)'],uz:['Tug‘ilish (milodiy)','Vafot (milodiy)'],kk:['Туу (григориандық)','Қайтыс болу (григориандық)'],zh:['出生（公历）','去世（公历）'],ja:['出生（西暦）','死去（西暦）'],ko:['출생 (서력)','사망 (서력)']}
 for(const [code,[birth,death]]of Object.entries(gregorian)){const catalog=catalogs[code]??={};catalog['الميلاد الميلادي']??=birth;catalog['الوفاة الميلادية']??=death}
 const aliases={'الميلاد الهجري':'سنة الميلاد الهجرية','الوفاة الهجرية':'سنة الوفاة الهجرية','الترجمة المفصلة':'الترجمة التفصيلية'}
 const lists={'الأماكن — مكان في كل سطر':'الأماكن','الصفات — صفة في كل سطر':'الصفات','التصنيفات — تصنيف في كل سطر':'التصنيفات','الشيوخ — اسم في كل سطر':'الشيوخ','التلاميذ — اسم في كل سطر':'التلاميذ','المناصب — منصب في كل سطر':'المناصب','المؤلفات المعرّفة في الترجمة — عنوان في كل سطر':'المؤلفات المعرّفة في الترجمة','اشتهر باسم — اسم في كل سطر':'اشتهر باسم'}
 for(const [code,localized]of Object.entries(rows)){const catalog=catalogs[code]??={};for(const [key,value]of Object.entries(localized.labels))catalog[key]??=value;for(const [key,source]of Object.entries(aliases))if(catalog[source])catalog[key]??=catalog[source]!;for(const [key,source]of Object.entries(lists)){const value=catalog[source];if(!value)throw Error(`Missing author list label: ${code}/${source}`);catalog[key]??=`${value} - ${localized.perLine}`;catalog[key.replace('—','-')]??=catalog[key]!}}
}
