/** رأس مراجعة الاستيراد والحفظ؛ لا يتضمن قيم المسودات المستوردة. */
const keys=(required:string,cancel:string,saving:string)=>({'الحقول المعلّمة مطلوبة قبل حفظ أي كتاب.':required,'إلغاء':cancel,'جارٍ حفظ الكتب…':saving})
export const REVIEWED_BOOK_IMPORT_REVIEW_ACTIONS_ALL_UI={
en:keys('Marked fields are required before any book can be saved.','Cancel','Saving books…'),fr:keys('Les champs marqués sont requis avant d’enregistrer un livre.','Annuler','Enregistrement des livres…'),
ug:keys('ھەر قانداق كىتابنى ساقلاشتىن بۇرۇن بەلگىلەنگەن بۆلەكلەر زۆرۈر.','بىكار قىلىش','كىتابلار ساقلەۋاتىدۇ…'),ckb:keys('پێش پاشەکەوتکردنی هەر کتێبێک خانە نیشانکراوەکان پێویستن.','هەڵوەشاندنەوە','کتێبەکان پاشەکەوت دەکرێن…'),
ku:keys('Berî tomarkirina pirtûkekê qadên nîşankirî pêwîst in.','Betal bike','Pirtûk tên tomarkirin…'),tr:keys('Herhangi bir kitap kaydedilmeden önce işaretli alanlar gereklidir.','İptal','Kitaplar kaydediliyor…'),
ur:keys('کوئی کتاب محفوظ کرنے سے پہلے نشان زدہ خانے ضروری ہیں۔','منسوخ کریں','کتابیں محفوظ ہو رہی ہیں…'),fa:keys('پیش از ذخیرهٔ هر کتاب، فیلدهای علامت‌دار الزامی‌اند.','لغو','کتاب‌ها ذخیره می‌شوند…'),
sw:keys('Sehemu zilizowekwa alama zinahitajika kabla ya kuhifadhi kitabu chochote.','Ghairi','Vitabu vinahifadhiwa…'),hi:keys('किसी पुस्तक को सहेजने से पहले चिह्नित फ़ील्ड आवश्यक हैं।','रद्द करें','पुस्तकें सहेजी जा रही हैं…'),
hu:keys('A megjelölt mezők kitöltése szükséges bármely könyv mentése előtt.','Mégse','Könyvek mentése…'),id:keys('Kolom bertanda wajib diisi sebelum buku disimpan.','Batal','Menyimpan buku…'),
ms:keys('Medan bertanda diperlukan sebelum mana-mana buku disimpan.','Batal','Menyimpan buku…'),bn:keys('কোনো বই সংরক্ষণের আগে চিহ্নিত ঘরগুলো আবশ্যক।','বাতিল','বই সংরক্ষণ হচ্ছে…'),
ps:keys('د هر کتاب تر خوندي کولو مخکې نښه شوي ډګرونه اړین دي.','لغوه کول','کتابونه خوندي کېږي…'),so:keys('Goobaha calaamadaysan waa qasab ka hor kaydinta buug.','Jooji','Buugaagta waa la kaydinayaa…'),
ha:keys('Filayen da aka yiwa alama wajibi ne kafin ajiye kowane littafi.','Soke','Ana ajiye littattafai…'),ru:keys('Отмеченные поля обязательны перед сохранением любой книги.','Отмена','Сохранение книг…'),
uk:keys('Позначені поля обов’язкові перед збереженням будь-якої книги.','Скасувати','Збереження книг…'),de:keys('Markierte Felder sind erforderlich, bevor ein Buch gespeichert werden kann.','Abbrechen','Bücher werden gespeichert…'),
es:keys('Los campos marcados son obligatorios antes de guardar cualquier libro.','Cancelar','Guardando libros…'),pt:keys('Os campos assinalados são obrigatórios antes de guardar qualquer livro.','Cancelar','A guardar livros…'),
it:keys('I campi contrassegnati sono obbligatori prima di salvare qualsiasi libro.','Annulla','Salvataggio dei libri…'),nl:keys('Gemarkeerde velden zijn vereist voordat een boek kan worden opgeslagen.','Annuleren','Boeken opslaan…'),
sv:keys('Markerade fält krävs innan en bok kan sparas.','Avbryt','Sparar böcker…'),no:keys('Merkede felt kreves før en bok kan lagres.','Avbryt','Lagrer bøker…'),
pl:keys('Oznaczone pola są wymagane przed zapisaniem dowolnej książki.','Anuluj','Zapisywanie książek…'),ro:keys('Câmpurile marcate sunt obligatorii înainte de salvarea oricărei cărți.','Anulează','Se salvează cărțile…'),
bs:keys('Označena polja su obavezna prije spremanja bilo koje knjige.','Otkaži','Spremanje knjiga…'),sq:keys('Fushat e shënuara kërkohen para ruajtjes së çdo libri.','Anulo','Duke ruajtur librat…'),
az:keys('Hər hansı kitab saxlanmazdan əvvəl işarələnmiş sahələr doldurulmalıdır.','Ləğv et','Kitablar saxlanılır…'),uz:keys('Har qanday kitobni saqlashdan oldin belgilangan maydonlar to‘ldirilishi shart.','Bekor qilish','Kitoblar saqlanmoqda…'),
kk:keys('Кез келген кітапты сақтамас бұрын белгіленген өрістер міндетті.','Бас тарту','Кітаптар сақталуда…'),zh:keys('保存任何图书前，必须填写标记的字段。','取消','正在保存图书…'),
ja:keys('本を保存する前に、印の付いた項目への入力が必要です。','キャンセル','本を保存しています…'),ko:keys('책을 저장하기 전에 표시된 필드를 입력해야 합니다.','취소','책 저장 중…'),
} as const

const dynamic:Record<string,readonly[string,string]>={
en:['Review {n} books','Save {n} books'],fr:['Vérifier {n} livres','Enregistrer {n} livres'],ug:['{n} كىتابنى تەكشۈرۈش','{n} كىتابنى ساقلاش'],ckb:['پێداچوونەوەی {n} کتێب','پاشەکەوتکردنی {n} کتێب'],ku:['{n} pirtûkan kontrol bike','{n} pirtûkan tomar bike'],tr:['{n} kitabı gözden geçir','{n} kitabı kaydet'],ur:['{n} کتابوں کا جائزہ','{n} کتابیں محفوظ کریں'],fa:['بازبینی {n} کتاب','ذخیرهٔ {n} کتاب'],sw:['Kagua vitabu {n}','Hifadhi vitabu {n}'],hi:['{n} पुस्तकों की समीक्षा','{n} पुस्तकें सहेजें'],hu:['{n} könyv áttekintése','{n} könyv mentése'],id:['Tinjau {n} buku','Simpan {n} buku'],ms:['Semak {n} buku','Simpan {n} buku'],bn:['{n}টি বই পর্যালোচনা','{n}টি বই সংরক্ষণ'],ps:['{n} کتابونه وڅېړئ','{n} کتابونه خوندي کړئ'],so:['Dib u eeg {n} buug','Kaydi {n} buug'],ha:['Duba littattafai {n}','Ajiye littattafai {n}'],ru:['Проверить книг: {n}','Сохранить книг: {n}'],uk:['Перевірити книг: {n}','Зберегти книг: {n}'],de:['{n} Bücher prüfen','{n} Bücher speichern'],es:['Revisar {n} libros','Guardar {n} libros'],pt:['Rever {n} livros','Guardar {n} livros'],it:['Rivedi {n} libri','Salva {n} libri'],nl:['{n} boeken controleren','{n} boeken opslaan'],sv:['Granska {n} böcker','Spara {n} böcker'],no:['Gjennomgå {n} bøker','Lagre {n} bøker'],pl:['Przejrzyj {n} książek','Zapisz {n} książek'],ro:['Verifică {n} cărți','Salvează {n} cărți'],bs:['Pregledaj {n} knjiga','Spremi {n} knjiga'],sq:['Rishiko {n} libra','Ruaj {n} libra'],az:['{n} kitabı nəzərdən keçir','{n} kitabı saxla'],uz:['{n} kitobni ko‘rib chiqish','{n} kitobni saqlash'],kk:['{n} кітапты тексеру','{n} кітапты сақтау'],zh:['检查 {n} 本书','保存 {n} 本书'],ja:['{n} 冊を確認','{n} 冊を保存'],ko:['책 {n}권 검토','책 {n}권 저장'],
}
export function translateBookImportReviewDynamic(source:string,language:string):string|undefined{const t=dynamic[language];if(!t)return undefined;const review=source.match(/^مراجعة\s+([0-9٠-٩]+)\s+كتاب$/u)?.[1];if(review)return t[0].replace('{n}',review);const save=source.match(/^حفظ\s+([0-9٠-٩]+)\s+كتاب$/u)?.[1];return save?t[1].replace('{n}',save):undefined}
