/** مشغّل استيراد الكتب؛ لا يتضمن أسماء الملفات أو بيانات الكتب. */
const keys=(organized:string,heading:string,files:string,chooseFolder:string,fullFolder:string,folder:string)=>({'استيراد منظم':organized,'أضف كتبًا إلى الخِزانة':heading,'إضافة ملفات':files,'اختيار مجلد كامل':chooseFolder,'إضافة مجلد كامل':fullFolder,'إضافة مجلد':folder})
export const REVIEWED_BOOK_IMPORT_LAUNCHER_ALL_UI={
en:keys('Organized import','Add books to Al-Khezana','Add files','Choose an entire folder','Add an entire folder','Add folder'),fr:keys('Import organisé','Ajouter des livres à Al-Khezana','Ajouter des fichiers','Choisir un dossier entier','Ajouter un dossier entier','Ajouter un dossier'),
ug:keys('تەرتىپلىك ئەكىرىش','خەزىنىگە كىتاب قوشۇڭ','ھۆججەت قوشۇش','تولۇق قىسقۇچ تاللاش','تولۇق قىسقۇچ قوشۇش','قىسقۇچ قوشۇش'),ckb:keys('هاوردەکردنی ڕێکخراو','کتێب بۆ خەزانە زیاد بکە','فایل زیاد بکە','بوخچەیەکی تەواو هەڵبژێرە','بوخچەیەکی تەواو زیاد بکە','بوخچە زیاد بکە'),
ku:keys('Îthalata rêkûpêk','Pirtûkan li Xezaneyê zêde bike','Pelan zêde bike','Peldankek tam hilbijêre','Peldankek tam zêde bike','Peldank zêde bike'),tr:keys('Düzenli içe aktarma','Hazineye kitap ekle','Dosya ekle','Tüm klasörü seç','Tüm klasörü ekle','Klasör ekle'),
ur:keys('منظم درآمد','خزانہ میں کتابیں شامل کریں','فائلیں شامل کریں','پورا فولڈر منتخب کریں','پورا فولڈر شامل کریں','فولڈر شامل کریں'),fa:keys('درون‌ریزی سازمان‌یافته','کتاب‌ها را به خزانه بیفزایید','افزودن پرونده‌ها','انتخاب پوشهٔ کامل','افزودن پوشهٔ کامل','افزودن پوشه'),
sw:keys('Uingizaji uliopangwa','Ongeza vitabu Al-Khezana','Ongeza faili','Chagua folda nzima','Ongeza folda nzima','Ongeza folda'),hi:keys('व्यवस्थित आयात','अल-ख़ज़ाना में पुस्तकें जोड़ें','फ़ाइलें जोड़ें','पूरा फ़ोल्डर चुनें','पूरा फ़ोल्डर जोड़ें','फ़ोल्डर जोड़ें'),
hu:keys('Rendezett importálás','Könyvek hozzáadása az Al-Khezanához','Fájlok hozzáadása','Teljes mappa kiválasztása','Teljes mappa hozzáadása','Mappa hozzáadása'),id:keys('Impor teratur','Tambahkan buku ke Al-Khezana','Tambah file','Pilih seluruh folder','Tambahkan seluruh folder','Tambah folder'),
ms:keys('Import tersusun','Tambah buku ke Al-Khezana','Tambah fail','Pilih seluruh folder','Tambah seluruh folder','Tambah folder'),bn:keys('সুশৃঙ্খল আমদানি','আল-খাযানায় বই যোগ করুন','ফাইল যোগ করুন','সম্পূর্ণ ফোল্ডার বাছুন','সম্পূর্ণ ফোল্ডার যোগ করুন','ফোল্ডার যোগ করুন'),
ps:keys('منظم واردول','خزانې ته کتابونه زیات کړئ','فایلونه زیات کړئ','بشپړ پوښۍ وټاکئ','بشپړ پوښۍ زیاته کړئ','پوښۍ زیاته کړئ'),so:keys('Soo dejin habaysan','Buugaag ku dar Al-Khezana','Ku dar faylal','Dooro gal dhan','Ku dar gal dhan','Ku dar gal'),
ha:keys('Shigo mai tsari','Ƙara littattafai zuwa Al-Khezana','Ƙara fayiloli','Zaɓi babban fayil gaba ɗaya','Ƙara babban fayil gaba ɗaya','Ƙara babban fayil'),ru:keys('Организованный импорт','Добавить книги в Al-Khezana','Добавить файлы','Выбрать всю папку','Добавить всю папку','Добавить папку'),
uk:keys('Організований імпорт','Додати книги до Al-Khezana','Додати файли','Вибрати всю папку','Додати всю папку','Додати папку'),de:keys('Geordneter Import','Bücher zu Al-Khezana hinzufügen','Dateien hinzufügen','Ganzen Ordner auswählen','Ganzen Ordner hinzufügen','Ordner hinzufügen'),
es:keys('Importación organizada','Añadir libros a Al-Khezana','Añadir archivos','Elegir una carpeta completa','Añadir una carpeta completa','Añadir carpeta'),pt:keys('Importação organizada','Adicionar livros à Al-Khezana','Adicionar ficheiros','Escolher uma pasta inteira','Adicionar uma pasta inteira','Adicionar pasta'),
it:keys('Importazione organizzata','Aggiungi libri ad Al-Khezana','Aggiungi file','Scegli un’intera cartella','Aggiungi un’intera cartella','Aggiungi cartella'),nl:keys('Georganiseerde import','Boeken toevoegen aan Al-Khezana','Bestanden toevoegen','Hele map kiezen','Hele map toevoegen','Map toevoegen'),
sv:keys('Organiserad import','Lägg till böcker i Al-Khezana','Lägg till filer','Välj en hel mapp','Lägg till en hel mapp','Lägg till mapp'),no:keys('Organisert import','Legg til bøker i Al-Khezana','Legg til filer','Velg en hel mappe','Legg til en hel mappe','Legg til mappe'),
pl:keys('Uporządkowany import','Dodaj książki do Al-Khezana','Dodaj pliki','Wybierz cały folder','Dodaj cały folder','Dodaj folder'),ro:keys('Import organizat','Adaugă cărți în Al-Khezana','Adaugă fișiere','Alege un dosar întreg','Adaugă un dosar întreg','Adaugă dosar'),
bs:keys('Organizirani uvoz','Dodaj knjige u Al-Khezana','Dodaj datoteke','Odaberi cijelu mapu','Dodaj cijelu mapu','Dodaj mapu'),sq:keys('Import i organizuar','Shto libra në Al-Khezana','Shto skedarë','Zgjidh një dosje të plotë','Shto një dosje të plotë','Shto dosje'),
az:keys('Nizamlı idxal','Al-Khezanaya kitab əlavə et','Fayl əlavə et','Bütün qovluğu seç','Bütün qovluğu əlavə et','Qovluq əlavə et'),uz:keys('Tartibli import','Al-Khezanaga kitob qo‘shish','Fayllar qo‘shish','Butun jildni tanlash','Butun jildni qo‘shish','Jild qo‘shish'),
kk:keys('Реттелген импорт','Al-Khezana-ға кітаптар қосу','Файлдар қосу','Толық қалтаны таңдау','Толық қалтаны қосу','Қалта қосу'),zh:keys('有序导入','向 Al-Khezana 添加图书','添加文件','选择整个文件夹','添加整个文件夹','添加文件夹'),
ja:keys('整理されたインポート','Al-Khezana に本を追加','ファイルを追加','フォルダー全体を選択','フォルダー全体を追加','フォルダーを追加'),ko:keys('체계적 가져오기','Al-Khezana에 책 추가','파일 추가','전체 폴더 선택','전체 폴더 추가','폴더 추가'),
} as const
