/** حالات اختيار الملفات وقراءتها؛ لا تمرر أسماء الملفات أو بيانات الكتب. */
const keys=(none:string,reading:string,folder:string)=>({'لم يُعثر على ملفات كتب بصيغة مدعومة':none,'جارٍ قراءة بيانات الكتب':reading,'تعذّر فتح المجلد؛ استخدم اختيار المجلد البديل':folder})
export const REVIEWED_BOOK_IMPORT_INTAKE_ALL_UI={
en:keys('No supported book files were found','Reading book data','The folder could not be opened; use the alternate folder picker'),fr:keys('Aucun fichier de livre pris en charge trouvé','Lecture des données des livres','Impossible d’ouvrir le dossier ; utilisez l’autre sélecteur'),
ug:keys('قوللايدىغان كىتاب ھۆججىتى تېپىلمىدى','كىتاب ئۇچۇرى ئوقۇلۇۋاتىدۇ','قىسقۇچنى ئاچقىلى بولمىدى؛ باشقا تاللىغۇچنى ئىشلىتىڭ'),ckb:keys('هیچ فایلی کتێبی پشتگیریکراو نەدۆزرایەوە','داتای کتێبەکان دەخوێنرێتەوە','بوخچەکە نەکرایەوە؛ هەڵبژێری جێگرەوە بەکاربهێنە'),
ku:keys('Pelê pirtûkê yê piştgirîkirî nehat dîtin','Daneyên pirtûkan tên xwendin','Peldank nehat vekirin; hilbijêrê cîgir bi kar bîne'),tr:keys('Desteklenen kitap dosyası bulunamadı','Kitap verileri okunuyor','Klasör açılamadı; alternatif klasör seçiciyi kullanın'),
ur:keys('معاون کتاب فائل نہیں ملی','کتابوں کا ڈیٹا پڑھا جا رہا ہے','فولڈر نہیں کھل سکا؛ متبادل فولڈر انتخاب استعمال کریں'),fa:keys('پروندهٔ کتاب پشتیبانی‌شده‌ای یافت نشد','داده‌های کتاب‌ها خوانده می‌شود','پوشه باز نشد؛ از انتخابگر جایگزین استفاده کنید'),
sw:keys('Hakuna faili za vitabu zinazotumika','Data za vitabu zinasomwa','Folda haikufunguka; tumia kichagua mbadala'),hi:keys('कोई समर्थित पुस्तक फ़ाइल नहीं मिली','पुस्तक डेटा पढ़ा जा रहा है','फ़ोल्डर नहीं खुल सका; वैकल्पिक चयन का उपयोग करें'),
hu:keys('Nem található támogatott könyvfájl','Könyvadatok olvasása','A mappa nem nyitható meg; használja a másik választót'),id:keys('Tidak ditemukan file buku yang didukung','Membaca data buku','Folder tidak dapat dibuka; gunakan pemilih alternatif'),
ms:keys('Tiada fail buku yang disokong ditemui','Membaca data buku','Folder tidak dapat dibuka; gunakan pemilih alternatif'),bn:keys('সমর্থিত কোনো বইয়ের ফাইল পাওয়া যায়নি','বইয়ের তথ্য পড়া হচ্ছে','ফোল্ডার খোলা যায়নি; বিকল্প নির্বাচন ব্যবহার করুন'),
ps:keys('د ملاتړ شوي کتاب فایل ونه موندل شو','د کتابونو معلومات لوستل کېږي','پوښۍ پرانیستل نه شوه؛ بدیل ټاکونکی وکاروئ'),so:keys('Fayl buug oo la taageero lama helin','Xogta buugaagta waa la akhrinayaa','Galka lama furi karo; isticmaal dooriyaha kale'),
ha:keys('Ba a sami fayil ɗin littafi mai goyon baya ba','Ana karanta bayanan littattafai','Ba a buɗe babban fayil ba; yi amfani da madadin zaɓi'),ru:keys('Поддерживаемые файлы книг не найдены','Чтение данных книг','Не удалось открыть папку; используйте другой способ выбора'),
uk:keys('Підтримувані файли книг не знайдено','Читання даних книг','Не вдалося відкрити папку; скористайтеся іншим вибором'),de:keys('Keine unterstützten Buchdateien gefunden','Buchdaten werden gelesen','Ordner konnte nicht geöffnet werden; verwenden Sie die alternative Auswahl'),
es:keys('No se encontraron archivos de libro compatibles','Leyendo datos de libros','No se pudo abrir la carpeta; usa el selector alternativo'),pt:keys('Não foram encontrados ficheiros de livro compatíveis','A ler dados dos livros','Não foi possível abrir a pasta; use o seletor alternativo'),
it:keys('Nessun file di libro supportato trovato','Lettura dei dati dei libri','Impossibile aprire la cartella; usa il selettore alternativo'),nl:keys('Geen ondersteunde boekbestanden gevonden','Boekgegevens lezen','Map kon niet worden geopend; gebruik de alternatieve kiezer'),
sv:keys('Inga bokfiler som stöds hittades','Läser bokdata','Mappen kunde inte öppnas; använd det alternativa valet'),no:keys('Ingen støttede bokfiler ble funnet','Leser bokdata','Mappen kunne ikke åpnes; bruk det alternative valget'),
pl:keys('Nie znaleziono obsługiwanych plików książek','Odczytywanie danych książek','Nie udało się otworzyć folderu; użyj alternatywnego wyboru'),ro:keys('Nu s-au găsit fișiere de carte acceptate','Se citesc datele cărților','Dosarul nu a putut fi deschis; folosește selectorul alternativ'),
bs:keys('Nisu pronađene podržane datoteke knjiga','Čitanje podataka knjiga','Mapa se ne može otvoriti; koristite alternativni odabir'),sq:keys('Nuk u gjetën skedarë libri të mbështetur','Duke lexuar të dhënat e librave','Dosja nuk u hap; përdorni përzgjedhësin alternativ'),
az:keys('Dəstəklənən kitab faylı tapılmadı','Kitab məlumatları oxunur','Qovluq açıla bilmədi; alternativ seçicidən istifadə edin'),uz:keys('Qo‘llab-quvvatlanadigan kitob fayli topilmadi','Kitob ma’lumotlari o‘qilmoqda','Jild ochilmadi; muqobil tanlagichdan foydalaning'),
kk:keys('Қолдау көрсетілетін кітап файлы табылмады','Кітап деректері оқылуда','Қалта ашылмады; балама таңдауды пайдаланыңыз'),zh:keys('未找到受支持的图书文件','正在读取图书数据','无法打开文件夹；请使用备用选择器'),
ja:keys('対応する本のファイルが見つかりません','本のデータを読み取っています','フォルダーを開けません。別の選択方法を使用してください'),ko:keys('지원되는 책 파일을 찾을 수 없습니다','책 데이터 읽는 중','폴더를 열 수 없습니다. 대체 선택기를 사용하세요'),
} as const
const progress:Record<string,string>={en:'Checking {n} files and extracting data before review.',fr:'Vérification de {n} fichiers et extraction des données avant révision.',ug:'{n} ھۆججەت تەكشۈرۈلۈپ، كۆرۈپ چىقىشتىن بۇرۇن ئۇچۇرى چىقىرىلىۋاتىدۇ.',ckb:'{n} فایل پشکنین دەکرێت و پێش پێداچوونەوە داتاکانی دەردەهێنرێن.',ku:'{n} pel tên kontrolkirin û berî pêdaçûnê dane tên derxistin.',tr:'İnceleme öncesi {n} dosya kontrol edilip verileri çıkarılıyor.',ur:'جائزے سے پہلے {n} فائلوں کی جانچ اور ڈیٹا نکالا جا رہا ہے۔',fa:'پیش از بازبینی، {n} پرونده بررسی و داده‌ها استخراج می‌شود.',sw:'Faili {n} zinakaguliwa na data kutolewa kabla ya ukaguzi.',hi:'समीक्षा से पहले {n} फ़ाइलों की जाँच और डेटा निकाला जा रहा है।',hu:'{n} fájl ellenőrzése és adatainak kinyerése az áttekintés előtt.',id:'Memeriksa {n} file dan mengekstrak data sebelum peninjauan.',ms:'Memeriksa {n} fail dan mengekstrak data sebelum semakan.',bn:'পর্যালোচনার আগে {n}টি ফাইল পরীক্ষা ও তথ্য নেওয়া হচ্ছে।',ps:'له بیاکتنې مخکې {n} فایلونه کتل او معلومات ایستل کېږي.',so:'Waxaa la hubinayaa {n} fayl oo xogta laga soo saarayo ka hor dib-u-eegista.',ha:'Ana duba fayiloli {n} tare da fitar da bayanai kafin dubawa.',ru:'Проверяется файлов: {n}; данные извлекаются перед просмотром.',uk:'Перевіряється файлів: {n}; дані витягуються перед переглядом.',de:'{n} Dateien werden geprüft und Daten vor der Kontrolle extrahiert.',es:'Comprobando {n} archivos y extrayendo datos antes de revisarlos.',pt:'A verificar {n} ficheiros e a extrair dados antes da revisão.',it:'Controllo di {n} file ed estrazione dei dati prima della revisione.',nl:'{n} bestanden controleren en gegevens ophalen vóór beoordeling.',sv:'Kontrollerar {n} filer och hämtar data före granskning.',no:'Kontrollerer {n} filer og henter data før gjennomgang.',pl:'Sprawdzanie {n} plików i wyodrębnianie danych przed przeglądem.',ro:'Se verifică {n} fișiere și se extrag datele înainte de revizuire.',bs:'Provjera {n} datoteka i izdvajanje podataka prije pregleda.',sq:'Po kontrollohen {n} skedarë dhe po nxirren të dhënat para rishikimit.',az:'Baxışdan əvvəl {n} fayl yoxlanılır və məlumatlar çıxarılır.',uz:'Ko‘rib chiqishdan oldin {n} fayl tekshirilib, ma’lumotlar olinmoqda.',kk:'Тексеру алдында {n} файл қаралып, деректер шығарылуда.',zh:'正在检查 {n} 个文件并提取数据以供审核。',ja:'確認前に {n} 個のファイルを検査してデータを抽出しています。',ko:'검토 전에 파일 {n}개를 확인하고 데이터를 추출하고 있습니다.'}
export function translateBookImportProgress(source:string,language:string):string|undefined{const n=source.match(/^نفحص\s+([0-9٠-٩]+)\s+ملفًا ونستخرج بياناته قبل عرضها للمراجعة\.$/u)?.[1],t=progress[language];return n&&t?t.replace('{n}',n):undefined}
