/** أسماء حقول النشر والتنظيم فقط؛ لا تتضمن قيمها المستوردة. */
const keys=(publisher:string,edition:string,investigator:string,year:string,shelf:string,noShelf:string,cover:string,description:string)=>({'الناشر':publisher,'الطبعة':edition,'المحقق':investigator,'سنة النشر (هـ)':year,'الرف':shelf,'دون رف':noShelf,'استبدال الغلاف (اختياري)':cover,'الوصف':description})
export const REVIEWED_BOOK_IMPORT_PUBLICATION_FIELDS_ALL_UI={
en:keys('Publisher','Edition','Editor','Publication year (AH)','Shelf','No shelf','Replace cover (optional)','Description'),fr:keys('Éditeur','Édition','Éditeur scientifique','Année de publication (H)','Étagère','Sans étagère','Remplacer la couverture (facultatif)','Description'),
ug:keys('نەشر قىلغۇچى','نەشرى','تەھقىقلىغۇچى','نەشر يىلى (ھ)','تەكچە','تەكچىسىز','مۇقاۋىنى ئالماشتۇرۇش (ئىختىيارى)','چۈشەندۈرۈش'),ckb:keys('بڵاوکەرەوە','چاپ','لێکۆڵەر','ساڵی بڵاوکردنەوە (ک)','ڕەف','بێ ڕەف','گۆڕینی بەرگ (هەڵبژاردەیی)','وەسف'),
ku:keys('Weşanxane','Çap','Lêkolîner','Sala weşanê (H)','Ref','Bê ref','Bergê biguherîne (bijartî)','Danasîn'),tr:keys('Yayınevi','Baskı','Hazırlayan','Yayın yılı (H)','Raf','Rafsız','Kapağı değiştir (isteğe bağlı)','Açıklama'),
ur:keys('ناشر','اشاعت','محقق','سن اشاعت (ھ)','الماری','بلا الماری','سرورق بدلیں (اختیاری)','تفصیل'),fa:keys('ناشر','چاپ','محقق','سال نشر (هـ)','قفسه','بدون قفسه','جایگزینی جلد (اختیاری)','توضیح'),
sw:keys('Mchapishaji','Toleo','Mhariri','Mwaka wa uchapishaji (AH)','Rafu','Bila rafu','Badilisha jalada (hiari)','Maelezo'),hi:keys('प्रकाशक','संस्करण','संपादक','प्रकाशन वर्ष (हि.)','शेल्फ़','बिना शेल्फ़','आवरण बदलें (वैकल्पिक)','विवरण'),
hu:keys('Kiadó','Kiadás','Szerkesztő','Kiadás éve (AH)','Polc','Polc nélkül','Borító cseréje (opcionális)','Leírás'),id:keys('Penerbit','Edisi','Penyunting','Tahun terbit (H)','Rak','Tanpa rak','Ganti sampul (opsional)','Deskripsi'),
ms:keys('Penerbit','Edisi','Penyunting','Tahun terbit (H)','Rak','Tanpa rak','Ganti kulit (pilihan)','Penerangan'),bn:keys('প্রকাশক','সংস্করণ','সম্পাদক','প্রকাশ সাল (হি.)','তাক','তাক ছাড়া','প্রচ্ছদ বদলান (ঐচ্ছিক)','বিবরণ'),
ps:keys('خپرندوی','چاپ','څېړونکی','د خپرېدو کال (هـ)','المارۍ','بې المارۍ','پوښ بدل کړئ (اختیاري)','سپړنه'),so:keys('Daabacaha','Daabacaad','Tifaftire','Sannadka daabacaadda (H)','Khaanad','Khaanad la’aan','Beddel daboolka (ikhtiyaari)','Sharaxaad'),
ha:keys('Mawallafi','Bugu','Edita','Shekarar bugawa (H)','Shiryayye','Ba tare da shiryayye ba','Sauya murfi (na zaɓi)','Bayani'),ru:keys('Издатель','Издание','Редактор','Год издания (х.)','Полка','Без полки','Заменить обложку (необязательно)','Описание'),
uk:keys('Видавець','Видання','Редактор','Рік видання (г.)','Полиця','Без полиці','Замінити обкладинку (необов’язково)','Опис'),de:keys('Verlag','Ausgabe','Herausgeber','Erscheinungsjahr (AH)','Regal','Ohne Regal','Cover ersetzen (optional)','Beschreibung'),
es:keys('Editorial','Edición','Editor','Año de publicación (H)','Estante','Sin estante','Sustituir cubierta (opcional)','Descripción'),pt:keys('Editora','Edição','Editor','Ano de publicação (H)','Estante','Sem estante','Substituir capa (opcional)','Descrição'),
it:keys('Editore','Edizione','Curatore','Anno di pubblicazione (H)','Scaffale','Senza scaffale','Sostituisci copertina (facoltativo)','Descrizione'),nl:keys('Uitgever','Editie','Redacteur','Publicatiejaar (H)','Plank','Geen plank','Omslag vervangen (optioneel)','Beschrijving'),
sv:keys('Förlag','Utgåva','Redaktör','Utgivningsår (H)','Hylla','Ingen hylla','Byt omslag (valfritt)','Beskrivning'),no:keys('Forlag','Utgave','Redaktør','Utgivelsesår (H)','Hylle','Ingen hylle','Bytt omslag (valgfritt)','Beskrivelse'),
pl:keys('Wydawca','Wydanie','Redaktor','Rok wydania (H)','Półka','Bez półki','Zastąp okładkę (opcjonalnie)','Opis'),ro:keys('Editură','Ediție','Editor','Anul publicării (H)','Raft','Fără raft','Înlocuiește coperta (opțional)','Descriere'),
bs:keys('Izdavač','Izdanje','Urednik','Godina izdanja (H)','Polica','Bez police','Zamijeni korice (neobavezno)','Opis'),sq:keys('Botuesi','Botimi','Redaktori','Viti i botimit (H)','Rafti','Pa raft','Zëvendëso kopertinën (opsionale)','Përshkrimi'),
az:keys('Nəşriyyat','Nəşr','Redaktor','Nəşr ili (H)','Rəf','Rəfsiz','Üzü dəyiş (istəyə bağlı)','Təsvir'),uz:keys('Nashriyot','Nashr','Muharrir','Nashr yili (H)','Javon','Javonsiz','Muqovani almashtirish (ixtiyoriy)','Tavsif'),
kk:keys('Баспа','Басылым','Редактор','Жарияланған жыл (Һ)','Сөре','Сөресіз','Мұқабаны ауыстыру (міндетті емес)','Сипаттама'),zh:keys('出版者','版本','校订者','出版年（伊历）','书架','不放入书架','替换封面（可选）','描述'),
ja:keys('出版社','版','校訂者','出版年（ヒジュラ暦）','本棚','本棚なし','表紙を差し替え（任意）','説明'),ko:keys('출판사','판본','편집자','출판 연도(히즈라력)','책장','책장 없음','표지 교체(선택)','설명'),
} as const
