/** أسماء حقول هوية المسودة فقط؛ لا يحتوي القاموس أي قيمة كتاب أو مؤلف. */
const keys=(title:string,author:string,death:string,contemporary:string,category:string,tags:string)=>({'عنوان الكتاب *':title,'المؤلف *':author,'سنة الوفاة (هـ) *':death,'معاصر':contemporary,'التصنيف *':category,'الوسوم المقترحة من الفهرس (اختيارية)':tags})
export const REVIEWED_BOOK_IMPORT_IDENTITY_FIELDS_ALL_UI={
en:keys('Book title *','Author *','Death year (AH) *','Contemporary','Category *','Tags suggested from contents (optional)'),fr:keys('Titre du livre *','Auteur *','Année de décès (H) *','Contemporain','Catégorie *','Étiquettes suggérées par le sommaire (facultatif)'),
ug:keys('كىتاب ماۋزۇسى *','ئاپتور *','ۋاپات يىلى (ھ) *','ھازىرقى زامان','تۈر *','مۇندەرىجە تەۋسىيە قىلغان بەلگىلەر (ئىختىيارى)'),ckb:keys('ناونیشانی کتێب *','نووسەر *','ساڵی کۆچ (ک) *','هاوچەرخ','پۆل *','تاگە پێشنیارکراوەکانی پێڕست (هەڵبژاردەیی)'),
ku:keys('Sernavê pirtûkê *','Nivîskar *','Sala mirinê (H) *','Hevçax','Kategorî *','Etîketên pêşniyarkirî ji naverokê (bijartî)'),tr:keys('Kitap başlığı *','Yazar *','Ölüm yılı (H) *','Çağdaş','Kategori *','İçindekilerden önerilen etiketler (isteğe bağlı)'),
ur:keys('کتاب کا عنوان *','مصنف *','سن وفات (ھ) *','عصر حاضر','درجہ بندی *','فہرست سے تجویز کردہ ٹیگ (اختیاری)'),fa:keys('عنوان کتاب *','نویسنده *','سال وفات (هـ) *','هم‌روزگار','دسته *','برچسب‌های پیشنهادی فهرست (اختیاری)'),
sw:keys('Kichwa cha kitabu *','Mwandishi *','Mwaka wa kifo (AH) *','Wa kisasa','Aina *','Lebo zilizopendekezwa kutoka yaliyomo (hiari)'),hi:keys('पुस्तक शीर्षक *','लेखक *','मृत्यु वर्ष (हि.) *','समकालीन','श्रेणी *','विषय-सूची से सुझाए टैग (वैकल्पिक)'),
hu:keys('Könyv címe *','Szerző *','Halálozás éve (AH) *','Kortárs','Kategória *','Tartalomjegyzékből javasolt címkék (opcionális)'),id:keys('Judul buku *','Penulis *','Tahun wafat (H) *','Kontemporer','Kategori *','Tag yang disarankan dari daftar isi (opsional)'),
ms:keys('Tajuk buku *','Pengarang *','Tahun wafat (H) *','Kontemporari','Kategori *','Tag dicadangkan daripada kandungan (pilihan)'),bn:keys('বইয়ের শিরোনাম *','লেখক *','মৃত্যু সাল (হি.) *','সমকালীন','শ্রেণি *','সূচিপত্র থেকে প্রস্তাবিত ট্যাগ (ঐচ্ছিক)'),
ps:keys('د کتاب عنوان *','لیکوال *','د وفات کال (هـ) *','اوسنی','ډله *','له لړلیک څخه وړاندیز شوي نښانونه (اختیاري)'),so:keys('Cinwaanka buugga *','Qoraaga *','Sannadka geerida (H) *','Casri','Qaybta *','Calaamadaha laga soo jeediyay tusmada (ikhtiyaari)'),
ha:keys('Taken littafi *','Marubuci *','Shekarar mutuwa (H) *','Na zamani','Rukuni *','Tags da aka ba da shawara daga abubuwan ciki (na zaɓi)'),ru:keys('Название книги *','Автор *','Год смерти (х.) *','Современник','Категория *','Метки из оглавления (необязательно)'),
uk:keys('Назва книги *','Автор *','Рік смерті (г.) *','Сучасник','Категорія *','Мітки зі змісту (необов’язково)'),de:keys('Buchtitel *','Autor *','Todesjahr (AH) *','Zeitgenössisch','Kategorie *','Aus dem Inhaltsverzeichnis vorgeschlagene Tags (optional)'),
es:keys('Título del libro *','Autor *','Año de fallecimiento (H) *','Contemporáneo','Categoría *','Etiquetas sugeridas por el índice (opcional)'),pt:keys('Título do livro *','Autor *','Ano de falecimento (H) *','Contemporâneo','Categoria *','Etiquetas sugeridas pelo índice (opcional)'),
it:keys('Titolo del libro *','Autore *','Anno di morte (H) *','Contemporaneo','Categoria *','Tag suggeriti dall’indice (facoltativi)'),nl:keys('Boektitel *','Auteur *','Sterfjaar (H) *','Hedendaags','Categorie *','Tags voorgesteld uit de inhoud (optioneel)'),
sv:keys('Boktitel *','Författare *','Dödsår (H) *','Samtida','Kategori *','Taggar föreslagna från innehållet (valfritt)'),no:keys('Boktittel *','Forfatter *','Dødsår (H) *','Samtidig','Kategori *','Tagger foreslått fra innholdet (valgfritt)'),
pl:keys('Tytuł książki *','Autor *','Rok śmierci (H) *','Współczesny','Kategoria *','Tagi sugerowane ze spisu treści (opcjonalnie)'),ro:keys('Titlul cărții *','Autor *','Anul morții (H) *','Contemporan','Categorie *','Etichete sugerate din cuprins (opțional)'),
bs:keys('Naslov knjige *','Autor *','Godina smrti (H) *','Savremen','Kategorija *','Oznake predložene iz sadržaja (neobavezno)'),sq:keys('Titulli i librit *','Autori *','Viti i vdekjes (H) *','Bashkëkohor','Kategoria *','Etiketa të sugjeruara nga përmbajtja (opsionale)'),
az:keys('Kitabın adı *','Müəllif *','Vəfat ili (H) *','Müasir','Kateqoriya *','Mündəricatdan təklif edilən etiketlər (istəyə bağlı)'),uz:keys('Kitob nomi *','Muallif *','Vafot yili (H) *','Zamonaviy','Toifa *','Mundarijadan tavsiya etilgan teglar (ixtiyoriy)'),
kk:keys('Кітап атауы *','Автор *','Қайтыс болған жыл (Һ) *','Замандас','Санат *','Мазмұннан ұсынылған тегтер (міндетті емес)'),zh:keys('书名 *','作者 *','卒年（伊历）*','当代','分类 *','目录建议的标签（可选）'),
ja:keys('書名 *','著者 *','没年（ヒジュラ暦）*','現代','分類 *','目次から提案されたタグ（任意）'),ko:keys('책 제목 *','저자 *','사망 연도(히즈라력) *','현대','분류 *','목차에서 제안된 태그(선택)'),
} as const
