/** عناصر المؤلف المشارك والغلاف؛ لا تتضمن أسماء الأشخاص أو الصور. */
const keys=(add:string,name:string,remove:string,replace:string,first:string)=>({'إضافة مؤلف مشارك':add,'اسم المؤلف المشارك':name,'حذف المؤلف المشارك':remove,'استبدال الغلاف':replace,'اعتماد الصفحة الأولى غلافًا':first})
export const REVIEWED_BOOK_IMPORT_PEOPLE_COVER_FIELDS_ALL_UI={
en:keys('Add co-author','Co-author name','Remove co-author','Replace cover','Use first page as cover'),fr:keys('Ajouter un coauteur','Nom du coauteur','Supprimer le coauteur','Remplacer la couverture','Utiliser la première page comme couverture'),
ug:keys('ھەمكار ئاپتور قوشۇش','ھەمكار ئاپتور نامى','ھەمكار ئاپتورنى ئۆچۈرۈش','مۇقاۋىنى ئالماشتۇرۇش','بىرىنچى بەتنى مۇقاۋا قىلىش'),ckb:keys('هاونووسەر زیاد بکە','ناوی هاونووسەر','هاونووسەر بسڕەوە','بەرگ بگۆڕە','پەڕەی یەکەم بکە بە بەرگ'),
ku:keys('Hev-nivîskar zêde bike','Navê hev-nivîskar','Hev-nivîskar jê bibe','Bergê biguherîne','Rûpela yekem wek berg bi kar bîne'),tr:keys('Ortak yazar ekle','Ortak yazarın adı','Ortak yazarı kaldır','Kapağı değiştir','İlk sayfayı kapak olarak kullan'),
ur:keys('شریک مصنف شامل کریں','شریک مصنف کا نام','شریک مصنف حذف کریں','سرورق بدلیں','پہلا صفحہ سرورق بنائیں'),fa:keys('افزودن هم‌نویسنده','نام هم‌نویسنده','حذف هم‌نویسنده','جایگزینی جلد','استفاده از صفحهٔ نخست به‌عنوان جلد'),
sw:keys('Ongeza mwandishi mwenza','Jina la mwandishi mwenza','Ondoa mwandishi mwenza','Badilisha jalada','Tumia ukurasa wa kwanza kama jalada'),hi:keys('सह-लेखक जोड़ें','सह-लेखक का नाम','सह-लेखक हटाएँ','आवरण बदलें','पहले पृष्ठ को आवरण बनाएँ'),
hu:keys('Társszerző hozzáadása','Társszerző neve','Társszerző eltávolítása','Borító cseréje','Első oldal használata borítóként'),id:keys('Tambah penulis bersama','Nama penulis bersama','Hapus penulis bersama','Ganti sampul','Gunakan halaman pertama sebagai sampul'),
ms:keys('Tambah pengarang bersama','Nama pengarang bersama','Buang pengarang bersama','Ganti kulit','Gunakan halaman pertama sebagai kulit'),bn:keys('সহলেখক যোগ করুন','সহলেখকের নাম','সহলেখক সরান','প্রচ্ছদ বদলান','প্রথম পৃষ্ঠাকে প্রচ্ছদ করুন'),
ps:keys('شریک لیکوال زیات کړئ','د شریک لیکوال نوم','شریک لیکوال حذف کړئ','پوښ بدل کړئ','لومړۍ پاڼه د پوښ په توګه وکاروئ'),so:keys('Ku dar qoraa wadaag','Magaca qoraaga wadaag','Ka saar qoraaga wadaag','Beddel daboolka','Bogga koowaad ka dhig dabool'),
ha:keys('Ƙara marubuci tare','Sunan marubuci tare','Cire marubuci tare','Sauya murfi','Yi amfani da shafi na farko a matsayin murfi'),ru:keys('Добавить соавтора','Имя соавтора','Удалить соавтора','Заменить обложку','Использовать первую страницу как обложку'),
uk:keys('Додати співавтора','Ім’я співавтора','Видалити співавтора','Замінити обкладинку','Використати першу сторінку як обкладинку'),de:keys('Mitautor hinzufügen','Name des Mitautors','Mitautor entfernen','Cover ersetzen','Erste Seite als Cover verwenden'),
es:keys('Añadir coautor','Nombre del coautor','Eliminar coautor','Sustituir cubierta','Usar la primera página como cubierta'),pt:keys('Adicionar coautor','Nome do coautor','Remover coautor','Substituir capa','Usar a primeira página como capa'),
it:keys('Aggiungi coautore','Nome del coautore','Rimuovi coautore','Sostituisci copertina','Usa la prima pagina come copertina'),nl:keys('Medeauteur toevoegen','Naam medeauteur','Medeauteur verwijderen','Omslag vervangen','Eerste pagina als omslag gebruiken'),
sv:keys('Lägg till medförfattare','Medförfattarens namn','Ta bort medförfattare','Byt omslag','Använd första sidan som omslag'),no:keys('Legg til medforfatter','Navn på medforfatter','Fjern medforfatter','Bytt omslag','Bruk første side som omslag'),
pl:keys('Dodaj współautora','Nazwa współautora','Usuń współautora','Zastąp okładkę','Użyj pierwszej strony jako okładki'),ro:keys('Adaugă coautor','Numele coautorului','Elimină coautorul','Înlocuiește coperta','Folosește prima pagină drept copertă'),
bs:keys('Dodaj koautora','Ime koautora','Ukloni koautora','Zamijeni korice','Koristi prvu stranicu kao korice'),sq:keys('Shto bashkautor','Emri i bashkautorit','Hiq bashkautorin','Zëvendëso kopertinën','Përdor faqen e parë si kopertinë'),
az:keys('Həmmüəllif əlavə et','Həmmüəllifin adı','Həmmüəllifi sil','Üzü dəyiş','İlk səhifəni üz kimi istifadə et'),uz:keys('Hammuallif qo‘shish','Hammuallif nomi','Hammuallifni o‘chirish','Muqovani almashtirish','Birinchi sahifani muqova qilish'),
kk:keys('Бірлескен автор қосу','Бірлескен автор аты','Бірлескен авторды жою','Мұқабаны ауыстыру','Бірінші бетті мұқаба ретінде пайдалану'),zh:keys('添加合著者','合著者姓名','移除合著者','替换封面','将第一页用作封面'),
ja:keys('共著者を追加','共著者名','共著者を削除','表紙を差し替え','最初のページを表紙に使用'),ko:keys('공동 저자 추가','공동 저자 이름','공동 저자 삭제','표지 교체','첫 페이지를 표지로 사용'),
} as const
