/** Interface labels only: no catalog titles, author names, or book text. */
const keys=['العناوين الفهرسية','لغات الترجمة المتاحة','تحديث الإحصاءات','عن هذه الأعداد وتحديثها','إحصاءات المكتبة','اكتشف ما في الخزانة','الخزانة في أرقام','غير متاح','تعذر التحديث؛ أعد المحاولة'] as const
const row=(...values:string[])=>{if(values.length!==keys.length)throw Error('Statistics locale row length');return Object.fromEntries(keys.map((key,i)=>[key,values[i]!]))}
export const REVIEWED_HOME_STATISTICS_ALL_UI={
en:row('Indexed headings','Available translation languages','Refresh statistics','About these figures and updates','Library statistics','Discover the library','The library in numbers','Unavailable','Update failed; try again'),
fr:row('Titres indexés','Langues de traduction disponibles','Actualiser les statistiques','À propos des chiffres et mises à jour','Statistiques de la bibliothèque','Découvrez la bibliothèque','La bibliothèque en chiffres','Indisponible','Échec de la mise à jour ; réessayez'),
ug:row('مۇندەرىجە ماۋزۇلىرى','ئىشلەتكىلى بولىدىغان تەرجىمە تىللىرى','ئىستاتىستىكىنى يېڭىلاش','بۇ سانلار ۋە يېڭىلاش ھەققىدە','كۇتۇپخانا ئىستاتىستىكىسى','كۇتۇپخانىنى بايقاڭ','كۇتۇپخانا سانلاردا','ئىشلەتكىلى بولمايدۇ','يېڭىلاش مەغلۇپ بولدى؛ قايتا سىناڭ'),
ckb:row('ناونیشانە پێڕستکراوەکان','زمانە بەردەستەکانی وەرگێڕان','نوێکردنەوەی ئامارەکان','دەربارەی ئەم ژمارانە و نوێکردنەوەیان','ئامارەکانی کتێبخانە','کتێبخانەکە بناسە','کتێبخانە بە ژمارە','بەردەست نییە','نوێکردنەوە سەرکەوتوو نەبوو؛ دووبارە هەوڵ بدەوە'),
ku:row('Sernavên îndekskirî','Zimanên wergerê yên berdest','Amaran nû bike','Derbarê van hejmaran û nûkirinê de','Amarên pirtûkxaneyê','Pirtûkxaneyê keşf bike','Pirtûkxane bi hejmaran','Ne berdest e','Nûkirin bi ser neket; dîsa biceribîne'),
tr:row('Dizin başlıkları','Kullanılabilir çeviri dilleri','İstatistikleri yenile','Bu sayılar ve güncellemeler hakkında','Kütüphane istatistikleri','Kütüphaneyi keşfedin','Rakamlarla kütüphane','Kullanılamıyor','Güncelleme başarısız; tekrar deneyin'),
ur:row('فہرست شدہ عنوانات','ترجمے کی دستیاب زبانیں','اعداد و شمار تازہ کریں','ان اعداد اور تازہ کاری کے بارے میں','کتب خانے کے اعداد و شمار','کتب خانہ دریافت کریں','کتب خانہ اعداد میں','دستیاب نہیں','تازہ کاری ناکام؛ دوبارہ کوشش کریں'),
fa:row('عنوان‌های نمایه‌شده','زبان‌های ترجمهٔ در دسترس','به‌روزرسانی آمار','دربارهٔ این اعداد و به‌روزرسانی آن‌ها','آمار کتابخانه','کتابخانه را کشف کنید','کتابخانه به روایت اعداد','در دسترس نیست','به‌روزرسانی ناموفق بود؛ دوباره تلاش کنید'),
sw:row('Vichwa vilivyoorodheshwa','Lugha za tafsiri zinazopatikana','Sasisha takwimu','Kuhusu takwimu hizi na masasisho','Takwimu za maktaba','Gundua maktaba','Maktaba kwa nambari','Haipatikani','Usasishaji umeshindwa; jaribu tena'),
hi:row('अनुक्रमित शीर्षक','उपलब्ध अनुवाद भाषाएँ','आँकड़े ताज़ा करें','इन आँकड़ों और अपडेट के बारे में','पुस्तकालय के आँकड़े','पुस्तकालय खोजें','आँकड़ों में पुस्तकालय','उपलब्ध नहीं','अपडेट विफल; फिर कोशिश करें'),
hu:row('Indexelt címsorok','Elérhető fordítási nyelvek','Statisztikák frissítése','Az adatokról és frissítésükről','Könyvtári statisztikák','Fedezze fel a könyvtárat','A könyvtár számokban','Nem érhető el','A frissítés sikertelen; próbálja újra'),
id:row('Judul bagian terindeks','Bahasa terjemahan tersedia','Perbarui statistik','Tentang angka dan pembaruannya','Statistik perpustakaan','Jelajahi perpustakaan','Perpustakaan dalam angka','Tidak tersedia','Pembaruan gagal; coba lagi'),
ms:row('Tajuk bahagian berindeks','Bahasa terjemahan tersedia','Kemas kini statistik','Tentang angka dan kemas kininya','Statistik perpustakaan','Terokai perpustakaan','Perpustakaan dalam angka','Tidak tersedia','Kemas kini gagal; cuba lagi'),
bn:row('সূচিবদ্ধ শিরোনাম','উপলব্ধ অনুবাদের ভাষা','পরিসংখ্যান হালনাগাদ করুন','এই সংখ্যা ও হালনাগাদ সম্পর্কে','গ্রন্থাগারের পরিসংখ্যান','গ্রন্থাগার আবিষ্কার করুন','সংখ্যায় গ্রন্থাগার','উপলব্ধ নয়','হালনাগাদ ব্যর্থ; আবার চেষ্টা করুন'),
ps:row('لړلیک شوي سرلیکونه','د ژباړې شته ژبې','شمېرې تازه کړئ','د دې شمېرو او تازه کولو په اړه','د کتابتون شمېرې','کتابتون وپلټئ','کتابتون په شمېرو کې','نشته','تازه کول ناکام شول؛ بیا هڅه وکړئ'),
so:row('Cinwaannada la tusmeeyay','Luqadaha tarjumaadda ee la heli karo','Cusboonaysii tirakoobka','Ku saabsan tirooyinkan iyo cusboonaysiintooda','Tirakoobka maktabadda','Sahami maktabadda','Maktabadda oo tirooyin ah','Lama heli karo','Cusboonaysiintu way fashilantay; mar kale isku day'),
ha:row('Kanun da aka sanya a fihirisa','Harsunan fassara da ake da su','Sabunta ƙididdiga','Game da waɗannan lambobi da sabunta su','Ƙididdigar ɗakin karatu','Gano ɗakin karatu','Ɗakin karatu a lambobi','Babu shi','Sabuntawa ta gaza; sake gwadawa'),
ru:row('Заголовки в указателе','Доступные языки перевода','Обновить статистику','Об этих данных и их обновлении','Статистика библиотеки','Откройте библиотеку','Библиотека в цифрах','Недоступно','Обновление не удалось; повторите попытку'),
uk:row('Заголовки в покажчику','Доступні мови перекладу','Оновити статистику','Про ці дані та їх оновлення','Статистика бібліотеки','Відкрийте бібліотеку','Бібліотека в цифрах','Недоступно','Оновлення не вдалося; спробуйте ще раз'),
de:row('Indexierte Überschriften','Verfügbare Übersetzungssprachen','Statistik aktualisieren','Über diese Zahlen und ihre Aktualisierung','Bibliotheksstatistik','Entdecken Sie die Bibliothek','Die Bibliothek in Zahlen','Nicht verfügbar','Aktualisierung fehlgeschlagen; erneut versuchen'),
es:row('Encabezados indexados','Idiomas de traducción disponibles','Actualizar estadísticas','Sobre estas cifras y su actualización','Estadísticas de la biblioteca','Descubre la biblioteca','La biblioteca en cifras','No disponible','Error al actualizar; inténtalo de nuevo'),
pt:row('Cabeçalhos indexados','Idiomas de tradução disponíveis','Atualizar estatísticas','Sobre estes números e a sua atualização','Estatísticas da biblioteca','Explore a biblioteca','A biblioteca em números','Indisponível','Falha na atualização; tente novamente'),
it:row('Intestazioni indicizzate','Lingue di traduzione disponibili','Aggiorna statistiche','Informazioni sui dati e sul loro aggiornamento','Statistiche della biblioteca','Esplora la biblioteca','La biblioteca in numeri','Non disponibile','Aggiornamento non riuscito; riprova'),
nl:row('Geïndexeerde koppen','Beschikbare vertaaltalen','Statistieken vernieuwen','Over deze cijfers en updates','Bibliotheekstatistieken','Ontdek de bibliotheek','De bibliotheek in cijfers','Niet beschikbaar','Bijwerken mislukt; probeer opnieuw'),
sv:row('Indexerade rubriker','Tillgängliga översättningsspråk','Uppdatera statistik','Om dessa siffror och uppdateringar','Biblioteksstatistik','Upptäck biblioteket','Biblioteket i siffror','Inte tillgängligt','Uppdateringen misslyckades; försök igen'),
no:row('Indekserte overskrifter','Tilgjengelige oversettelsesspråk','Oppdater statistikk','Om disse tallene og oppdateringer','Bibliotekstatistikk','Oppdag biblioteket','Biblioteket i tall','Ikke tilgjengelig','Oppdateringen mislyktes; prøv igjen'),
pl:row('Indeksowane nagłówki','Dostępne języki tłumaczenia','Odśwież statystyki','O tych liczbach i ich aktualizacji','Statystyki biblioteki','Odkryj bibliotekę','Biblioteka w liczbach','Niedostępne','Aktualizacja nie powiodła się; spróbuj ponownie'),
ro:row('Titluri indexate','Limbi de traducere disponibile','Actualizează statisticile','Despre aceste cifre și actualizarea lor','Statisticile bibliotecii','Descoperă biblioteca','Biblioteca în cifre','Indisponibil','Actualizarea a eșuat; încearcă din nou'),
bs:row('Indeksirani naslovi','Dostupni jezici prijevoda','Osvježi statistiku','O ovim brojevima i ažuriranjima','Statistika biblioteke','Istražite biblioteku','Biblioteka u brojevima','Nedostupno','Ažuriranje nije uspjelo; pokušajte ponovo'),
sq:row('Tituj të indeksuar','Gjuhët e disponueshme të përkthimit','Përditëso statistikat','Rreth këtyre shifrave dhe përditësimit','Statistikat e bibliotekës','Zbulo bibliotekën','Biblioteka në shifra','Nuk disponohet','Përditësimi dështoi; provo përsëri'),
az:row('İndekslənmiş başlıqlar','Mövcud tərcümə dilləri','Statistikanı yenilə','Bu rəqəmlər və yenilənmələri haqqında','Kitabxana statistikası','Kitabxananı kəşf edin','Rəqəmlərlə kitabxana','Mövcud deyil','Yeniləmə alınmadı; yenidən cəhd edin'),
uz:row('Indekslangan sarlavhalar','Mavjud tarjima tillari','Statistikani yangilash','Bu raqamlar va yangilanishlar haqida','Kutubxona statistikasi','Kutubxonani kashf eting','Kutubxona raqamlarda','Mavjud emas','Yangilash bajarilmadi; qayta urinib ko‘ring'),
kk:row('Индекстелген тақырыптар','Қолжетімді аударма тілдері','Статистиканы жаңарту','Осы сандар және олардың жаңартылуы туралы','Кітапхана статистикасы','Кітапханамен танысыңыз','Кітапхана сандармен','Қолжетімсіз','Жаңарту сәтсіз аяқталды; қайталап көріңіз'),
zh:row('已索引的标题','可用翻译语言','刷新统计','关于这些数字及其更新','图书馆统计','探索图书馆','数字中的图书馆','不可用','更新失败，请重试'),
ja:row('索引登録された見出し','利用可能な翻訳言語','統計を更新','数値と更新について','図書館の統計','図書館を探索','数字で見る図書館','利用不可','更新に失敗しました。再試行してください'),
ko:row('색인된 제목','사용 가능한 번역 언어','통계 새로고침','수치 및 업데이트 안내','도서관 통계','도서관 둘러보기','숫자로 보는 도서관','사용할 수 없음','업데이트 실패; 다시 시도하세요'),
} as const

const detailKeys=['الصفحات','الأماكن','تُراجع اللقطة تلقائيًا كل خمس دقائق أثناء عرض الصفحة.','إحصاءات الفهرس المنشور؛ لا تشمل الكتب الخاصة أو الإضافات العامة الأحدث من إصدار الفهرس. الأماكن تشمل غير المرتبطة بخريطة، واللغات خيارات متاحة وليست ترجمة مكتملة لكل الكتب.'] as const
const detail=(pages:string,places:string,refresh:string,scope:string)=>Object.fromEntries(detailKeys.map((key,i)=>[key,[pages,places,refresh,scope][i]!]))
const details={
en:detail('Pages','Places','The snapshot is checked automatically every five minutes while this page is open.','Published catalog statistics exclude private books and public additions newer than the catalog release. Places include those without maps. Languages are available options, not completed translations of every book.'),
fr:detail('Pages','Lieux','L’instantané est vérifié automatiquement toutes les cinq minutes pendant l’affichage de cette page.','Les statistiques du catalogue publié excluent les livres privés et les ajouts publics postérieurs à sa version. Les lieux sans carte sont inclus. Les langues sont des options disponibles, et non des traductions complètes de tous les livres.'),
ug:detail('بەتلەر','جايلار','بۇ بەت ئېچىلغاندا سانلىق مەلۇمات ھەر بەش مىنۇتتا ئاپتوماتىك تەكشۈرۈلىدۇ.','ئېلان قىلىنغان مۇندەرىجە ئىستاتىستىكىسى شەخسىي كىتابلارنى ۋە مۇندەرىجە نەشرىدىن كېيىنكى ئاممىۋى قوشۇمچىلارنى ئۆز ئىچىگە ئالمايدۇ. خەرىتىسى يوق جايلارمۇ سانىلىدۇ. تىللار بار تاللاشلار بولۇپ، ھەممە كىتاب تولۇق تەرجىمە قىلىنغان دېگەنلىك ئەمەس.'),
ckb:detail('لاپەڕەکان','شوێنەکان','لە کاتی پیشاندانی ئەم پەڕەیەدا، وێنەی داتاکان هەر پێنج خولەک بە خۆکار دەپشکنرێت.','ئامارەکانی پێڕستی بڵاوکراوە کتێبە تایبەتەکان و زیادکراوە گشتییە نوێترەکان لە وەشانی پێڕست ناگرنەوە. شوێنە بێ‌نەخشەکانیش دەژمێردرێن. زمانەکان هەڵبژاردەی بەردەستن، نەک وەرگێڕانی تەواوی هەموو کتێبەکان.'),
ku:detail('Rûpel','Cih','Dema ev rûpel vekirî ye, wêneya daneyan her pênc deqeyan bixweber tê kontrolkirin.','Amarên kataloga weşandî pirtûkên taybet û zêdekirinên giştî yên piştî guhertoya katalogê nagirin. Cihên bê nexşe jî têne jimartin. Ziman vebijêrkên berdest in, ne wergerên qediyayî yên hemû pirtûkan.'),
tr:detail('Sayfalar','Yerler','Bu sayfa açıkken veri anlık görüntüsü her beş dakikada bir otomatik kontrol edilir.','Yayımlanmış katalog istatistiklerine özel kitaplar ve katalog sürümünden sonraki genel eklemeler dahil değildir. Haritası olmayan yerler de sayılır. Diller kullanılabilir seçeneklerdir; tüm kitapların eksiksiz çevrildiği anlamına gelmez.'),
ur:detail('صفحات','مقامات','یہ صفحہ کھلا ہو تو معلومات کے محفوظ عکس کو ہر پانچ منٹ بعد خودکار طور پر جانچا جاتا ہے۔','شائع شدہ فہرست کے اعداد میں نجی کتابیں اور فہرست کے اجرا کے بعد کی عوامی اضافے شامل نہیں۔ نقشے کے بغیر مقامات بھی شمار ہوتے ہیں۔ زبانیں دستیاب اختیارات ہیں، ہر کتاب کے مکمل ترجمے نہیں۔'),
fa:detail('صفحات','مکان‌ها','هنگام نمایش این صفحه، تصویر آماری هر پنج دقیقه به‌طور خودکار بررسی می‌شود.','آمار فهرست منتشرشده شامل کتاب‌های خصوصی و افزوده‌های عمومی پس از انتشار فهرست نیست. مکان‌های بدون نقشه نیز شمرده می‌شوند. زبان‌ها گزینه‌های موجودند، نه ترجمهٔ کامل همهٔ کتاب‌ها.'),
sw:detail('Kurasa','Maeneo','Picha ya data hukaguliwa kiotomatiki kila dakika tano wakati ukurasa huu uko wazi.','Takwimu za katalogi iliyochapishwa hazijumuishi vitabu binafsi au nyongeza za umma za baada ya toleo la katalogi. Maeneo yasiyo na ramani pia yanahesabiwa. Lugha ni chaguo zinazopatikana, si tafsiri kamili za kila kitabu.'),
hi:detail('पृष्ठ','स्थान','यह पृष्ठ खुला रहने पर आँकड़ों का स्नैपशॉट हर पाँच मिनट में अपने आप जाँचा जाता है।','प्रकाशित सूची के आँकड़ों में निजी पुस्तकें और सूची जारी होने के बाद जोड़ी गई सार्वजनिक पुस्तकें शामिल नहीं हैं। बिना मानचित्र वाले स्थान भी गिने जाते हैं। भाषाएँ उपलब्ध विकल्प हैं, हर पुस्तक का पूर्ण अनुवाद नहीं।'),
hu:detail('Oldalak','Helyek','Az adatok pillanatképe ötpercenként automatikusan ellenőrzésre kerül, amíg ez az oldal nyitva van.','A közzétett katalógus statisztikái nem tartalmazzák a magánkönyveket és a katalógus kiadása utáni nyilvános bővítéseket. A térkép nélküli helyek is szerepelnek. A nyelvek elérhető lehetőségek, nem minden könyv elkészült fordításai.'),
id:detail('Halaman','Tempat','Cuplikan data diperiksa otomatis setiap lima menit selama halaman ini terbuka.','Statistik katalog terbit tidak mencakup buku pribadi atau tambahan publik setelah rilis katalog. Tempat tanpa peta juga dihitung. Bahasa adalah pilihan yang tersedia, bukan terjemahan lengkap setiap buku.'),
ms:detail('Halaman','Tempat','Petikan data disemak secara automatik setiap lima minit semasa halaman ini dibuka.','Statistik katalog terbit tidak merangkumi buku peribadi atau tambahan awam selepas keluaran katalog. Tempat tanpa peta turut dikira. Bahasa ialah pilihan yang tersedia, bukan terjemahan lengkap setiap buku.'),
bn:detail('পৃষ্ঠা','স্থান','এই পৃষ্ঠা খোলা থাকলে তথ্যের স্ন্যাপশট প্রতি পাঁচ মিনিটে স্বয়ংক্রিয়ভাবে পরীক্ষা করা হয়।','প্রকাশিত তালিকার পরিসংখ্যানে ব্যক্তিগত বই এবং তালিকা প্রকাশের পরে যোগ করা সর্বজনীন বই অন্তর্ভুক্ত নয়। মানচিত্রহীন স্থানও গণনা করা হয়। ভাষাগুলো উপলব্ধ বিকল্প, প্রতিটি বইয়ের সম্পূর্ণ অনুবাদ নয়।'),
ps:detail('پاڼې','ځایونه','تر څو چې دا پاڼه پرانیستې وي، د معلوماتو انځور په هرو پنځو دقیقو کې په اوتومات ډول کتل کېږي.','د خپاره شوي لړلیک شمېرې شخصي کتابونه او د لړلیک له خپرېدو وروسته عامې زیاتونې نه رانغاړي. بې نقشې ځایونه هم شمېرل کېږي. ژبې شته انتخابونه دي، نه د هر کتاب بشپړې ژباړې.'),
so:detail('Bogag','Goobo','Sawirka xogta si toos ah ayaa loo hubiyaa shantii daqiiqoba inta boggani furan yahay.','Tirakoobka tusmada la daabacay kuma jiraan buugaagta gaarka ah iyo ku-darrooyinka dadweynaha ee ka dambeeya sii-daynta tusmada. Goobaha aan khariidadda lahayn waa la tiriyaa. Luqaduhu waa xulashooyin la heli karo, ma aha tarjumaad dhammaystiran oo buug kasta ah.'),
ha:detail('Shafuka','Wurare','Ana duba hoton bayanan ta atomatik kowane minti biyar yayin da wannan shafi yake buɗe.','Ƙididdigar kundin da aka wallafa ba ta haɗa littattafan sirri ko ƙarin littattafan jama’a bayan fitar kundin ba. Ana ƙirga wuraren da ba su da taswira ma. Harsuna zaɓuɓɓuka ne da ake da su, ba cikakkun fassarorin kowane littafi ba.'),
ru:detail('Страницы','Места','Снимок данных автоматически проверяется каждые пять минут, пока эта страница открыта.','Статистика опубликованного каталога не включает личные книги и общедоступные добавления после его выпуска. Учитываются и места без карт. Языки обозначают доступные варианты, а не готовые переводы всех книг.'),
uk:detail('Сторінки','Місця','Знімок даних автоматично перевіряється кожні п’ять хвилин, доки ця сторінка відкрита.','Статистика опублікованого каталогу не охоплює приватні книги та загальнодоступні додавання після його випуску. Місця без карт також враховано. Мови — це доступні варіанти, а не готові переклади всіх книг.'),
de:detail('Seiten','Orte','Der Datenstand wird alle fünf Minuten automatisch geprüft, solange diese Seite geöffnet ist.','Die Statistik des veröffentlichten Katalogs enthält keine privaten Bücher und keine öffentlichen Ergänzungen nach dessen Veröffentlichung. Auch Orte ohne Karte werden gezählt. Die Sprachen sind verfügbare Optionen, keine vollständigen Übersetzungen aller Bücher.'),
es:detail('Páginas','Lugares','La instantánea de datos se comprueba automáticamente cada cinco minutos mientras esta página está abierta.','Las estadísticas del catálogo publicado excluyen los libros privados y las adiciones públicas posteriores a su publicación. Se incluyen los lugares sin mapa. Los idiomas son opciones disponibles, no traducciones completas de todos los libros.'),
pt:detail('Páginas','Lugares','O retrato dos dados é verificado automaticamente a cada cinco minutos enquanto esta página está aberta.','As estatísticas do catálogo publicado excluem livros privados e adições públicas posteriores à sua versão. Incluem-se os lugares sem mapa. Os idiomas são opções disponíveis, não traduções completas de todos os livros.'),
it:detail('Pagine','Luoghi','L’istantanea dei dati viene controllata automaticamente ogni cinque minuti mentre questa pagina è aperta.','Le statistiche del catalogo pubblicato escludono i libri privati e le aggiunte pubbliche successive alla sua edizione. Sono inclusi i luoghi senza mappa. Le lingue sono opzioni disponibili, non traduzioni complete di tutti i libri.'),
nl:detail('Pagina’s','Plaatsen','De gegevensmomentopname wordt elke vijf minuten automatisch gecontroleerd zolang deze pagina open is.','De statistieken van de gepubliceerde catalogus sluiten privéboeken en openbare toevoegingen na de catalogusuitgave uit. Plaatsen zonder kaart tellen ook mee. Talen zijn beschikbare opties, geen voltooide vertalingen van alle boeken.'),
sv:detail('Sidor','Platser','Databilden kontrolleras automatiskt var femte minut medan sidan är öppen.','Statistiken för den publicerade katalogen omfattar inte privata böcker eller offentliga tillägg efter katalogutgåvan. Platser utan karta räknas också. Språken är tillgängliga alternativ, inte färdiga översättningar av alla böcker.'),
no:detail('Sider','Steder','Databildet kontrolleres automatisk hvert femte minutt mens denne siden er åpen.','Statistikken for den publiserte katalogen inkluderer ikke private bøker eller offentlige tillegg etter katalogutgaven. Steder uten kart telles også. Språkene er tilgjengelige alternativer, ikke fullstendige oversettelser av alle bøker.'),
pl:detail('Strony','Miejsca','Migawka danych jest automatycznie sprawdzana co pięć minut, gdy ta strona jest otwarta.','Statystyki opublikowanego katalogu nie obejmują książek prywatnych ani publicznych dodatków po jego wydaniu. Uwzględniono też miejsca bez map. Języki to dostępne opcje, a nie gotowe tłumaczenia wszystkich książek.'),
ro:detail('Pagini','Locuri','Instantaneul datelor este verificat automat la fiecare cinci minute cât timp pagina este deschisă.','Statisticile catalogului publicat exclud cărțile private și adăugările publice ulterioare ediției catalogului. Sunt incluse și locurile fără hartă. Limbile sunt opțiuni disponibile, nu traduceri complete ale tuturor cărților.'),
bs:detail('Stranice','Mjesta','Snimak podataka se automatski provjerava svakih pet minuta dok je ova stranica otvorena.','Statistika objavljenog kataloga ne uključuje privatne knjige ni javne dodatke nakon izdanja kataloga. Broje se i mjesta bez karte. Jezici su dostupne opcije, a ne potpuni prijevodi svih knjiga.'),
sq:detail('Faqe','Vende','Pamja e të dhënave kontrollohet automatikisht çdo pesë minuta ndërsa kjo faqe është e hapur.','Statistikat e katalogut të publikuar përjashtojnë librat privatë dhe shtesat publike pas botimit të katalogut. Përfshihen edhe vendet pa hartë. Gjuhët janë mundësi të disponueshme, jo përkthime të plota të çdo libri.'),
az:detail('Səhifələr','Yerlər','Bu səhifə açıq olduğu müddətdə məlumat görüntüsü hər beş dəqiqədən bir avtomatik yoxlanılır.','Dərc olunmuş kataloqun statistikasına şəxsi kitablar və kataloq buraxılışından sonrakı ictimai əlavələr daxil deyil. Xəritəsiz yerlər də sayılır. Dillər mövcud seçimlərdir, bütün kitabların tam tərcümələri deyil.'),
uz:detail('Sahifalar','Joylar','Bu sahifa ochiq turganda ma’lumotlar nusxasi har besh daqiqada avtomatik tekshiriladi.','Nashr qilingan katalog statistikasi shaxsiy kitoblar va katalog chiqarilganidan keyingi ommaviy qo‘shimchalarni hisobga olmaydi. Xaritasiz joylar ham sanaladi. Tillar mavjud variantlardir, barcha kitoblarning to‘liq tarjimalari emas.'),
kk:detail('Беттер','Орындар','Бұл бет ашық тұрғанда деректер көшірмесі әр бес минут сайын автоматты түрде тексеріледі.','Жарияланған каталог статистикасына жеке кітаптар және каталог шыққаннан кейінгі жалпыға қолжетімді толықтырулар кірмейді. Картасыз орындар да есептеледі. Тілдер — қолжетімді нұсқалар, барлық кітаптардың толық аудармалары емес.'),
zh:detail('页数','地点','此页面打开期间，数据快照每五分钟自动检查一次。','已发布目录的统计不包括私人图书或目录版本发布后的公共新增内容。地点数量包含尚无地图的地点。语言是可用选项，并不代表每本书都已完整翻译。'),
ja:detail('ページ','場所','このページを表示している間、データのスナップショットを5分ごとに自動確認します。','公開済み目録の統計には、非公開の本や目録公開後の追加公開分は含まれません。地図のない場所も集計します。言語は利用可能な選択肢であり、すべての本の翻訳完了を意味しません。'),
ko:detail('페이지','장소','이 페이지가 열려 있는 동안 데이터 스냅샷을 5분마다 자동으로 확인합니다.','발행된 목록의 통계에는 비공개 도서와 목록 발행 이후 공개 추가분이 포함되지 않습니다. 지도가 없는 장소도 집계합니다. 언어는 사용 가능한 선택지이며 모든 책의 번역 완료를 뜻하지 않습니다.'),
} as const
for(const code of Object.keys(details) as (keyof typeof details)[])Object.assign(REVIEWED_HOME_STATISTICS_ALL_UI[code],details[code])
const snapshotLabels:Record<string,string>={en:'Release snapshot',fr:'Instantané de la version',ug:'نەشر سانلىق مەلۇماتى',ckb:'وێنەی داتای وەشان',ku:'Wêneya daneyên guhertoyê',tr:'Sürüm anlık görüntüsü',ur:'اجرا کا محفوظ عکس',fa:'تصویر آماری نسخه',sw:'Picha ya toleo',hi:'संस्करण स्नैपशॉट',hu:'Kiadási pillanatkép',id:'Cuplikan rilis',ms:'Petikan keluaran',bn:'সংস্করণের স্ন্যাপশট',ps:'د خپرونې انځور',so:'Sawirka sii-daynta',ha:'Hoton bayanan fitarwa',ru:'Снимок выпуска',uk:'Знімок випуску',de:'Stand der Veröffentlichung',es:'Instantánea de la versión',pt:'Retrato da versão',it:'Istantanea della versione',nl:'Momentopname van de uitgave',sv:'Versionsbild',no:'Versjonsbilde',pl:'Migawka wydania',ro:'Instantaneul ediției',bs:'Snimak izdanja',sq:'Pamja e botimit',az:'Buraxılış görüntüsü',uz:'Nashr nusxasi',kk:'Шығарылым көшірмесі',zh:'版本快照',ja:'公開版スナップショット',ko:'배포 스냅샷'}
export function translateStatisticsSnapshot(source:string,language:string):string|undefined{
 const date=source.match(/^لقطة إصدار (.+)؛ تُراجع تلقائيًا كل خمس دقائق أثناء عرض الصفحة\.$/u)?.[1]
 const label=snapshotLabels[language],catalog=details[language as keyof typeof details]
 return date&&label&&catalog?`${label}: ${date}. ${catalog[detailKeys[2]]}`:undefined
}
