type LibraryBulkDynamicTemplates = {
  selected: (count: string) => string
  apply: (count: string) => string
  applied: (count: string) => string
  undone: (count: string) => string
  confirmDelete: (count: string, sample: string) => string
  deletedWithFailures: (deleted: string, failed: string) => string
  deleted: (count: string) => string
}

/** إدارة المكتبة الجماعية؛ sample عينة عناوين منشورات تحفظ حرفيًا. */
export const REVIEWED_LIBRARY_BULK_DYNAMIC_TEMPLATES: Readonly<Record<string, LibraryBulkDynamicTemplates>> = {
  en:{selected:c=>`You selected ${c} books; only the fields specified here will change`,apply:c=>`Apply changes to ${c} books`,applied:c=>`Selected data applied to ${c} books`,undone:c=>`Undid the last bulk update on ${c} books`,confirmDelete:(c,s)=>`Delete ${c} books? ${s} This deletion cannot be undone.`,deletedWithFailures:(a,b)=>`${a} deleted; ${b} could not be deleted`,deleted:c=>`${c} books deleted`},
  fr:{selected:c=>`${c} livres sélectionnés ; seuls les champs indiqués ici changeront`,apply:c=>`Appliquer les modifications à ${c} livres`,applied:c=>`Données sélectionnées appliquées à ${c} livres`,undone:c=>`Dernière modification groupée annulée pour ${c} livres`,confirmDelete:(c,s)=>`Supprimer ${c} livres ? ${s} Cette suppression est irréversible.`,deletedWithFailures:(a,b)=>`${a} supprimés ; échec pour ${b}`,deleted:c=>`${c} livres supprimés`},
  ug:{selected:c=>`${c} كىتاب تاللاندى؛ پەقەت بۇ يەردە بەلگىلەنگەن بۆلەكلەر ئۆزگىرىدۇ`,apply:c=>`${c} كىتابقا ئۆزگەرتىش قوللىنىش`,applied:c=>`تاللانغان سانلىق مەلۇمات ${c} كىتابقا قوللىنىلدى`,undone:c=>`${c} كىتابتىكى ئاخىرقى توپ ئۆزگەرتىش قايتۇرۇلدى`,confirmDelete:(c,s)=>`${c} كىتاب ئۆچۈرۈلسۇنمۇ؟ ${s} بۇنى قايتۇرغىلى بولمايدۇ.`,deletedWithFailures:(a,b)=>`${a} ئۆچۈرۈلدى، ${b} ئۆچۈرۈلمىدى`,deleted:c=>`${c} كىتاب ئۆچۈرۈلدى`},
  ckb:{
    selected:count=>`${count} کتێبت هەڵبژاردووە؛ تەنها ئەو خانانە دەگۆڕێن کە لێرە دیاریت کردوون`,apply:count=>`جێبەجێکردنی گۆڕانکارییەکان لە ${count} کتێب`,applied:count=>`داتای دیاریکراو لە ${count} کتێب جێبەجێ کرا`,undone:count=>`دوایین جێبەجێکردنی کۆمەڵی لە ${count} کتێب پاشگەز کرایەوە`,confirmDelete:(count,sample)=>`سڕینەوەی ${count} کتێب؟ ${sample} ئەم سڕینەوەیە ناگەڕێتەوە.`,deletedWithFailures:(deleted,failed)=>`${deleted} سڕایەوە و سڕینەوەی ${failed} سەرکەوتوو نەبوو`,deleted:count=>`${count} کتێب سڕایەوە`,
  },
  ku:{
    selected:count=>`Te ${count} pirtûk hilbijartin; tenê qadên ku li vir diyarkirine diguherin`,apply:count=>`Guherînan li ${count} pirtûkan bisepîne`,applied:count=>`Daneyên diyarkirî li ${count} pirtûkan hatin sepandin`,undone:count=>`Sepandina komî ya dawî li ${count} pirtûkan hate paşvebirin`,confirmDelete:(count,sample)=>`${count} pirtûk werin jêbirin? ${sample} Ev jêbirin nayê vegerandin.`,deletedWithFailures:(deleted,failed)=>`${deleted} hatin jêbirin û ${failed} nehatin jêbirin`,deleted:count=>`${count} pirtûk hatin jêbirin`,
  },
  tr:{
    selected:count=>`${count} kitap seçtiniz; yalnızca burada belirttiğiniz alanlar değişir`,apply:count=>`Değişiklikleri ${count} kitaba uygula`,applied:count=>`Seçilen veriler ${count} kitaba uygulandı`,undone:count=>`${count} kitaptaki son toplu uygulama geri alındı`,confirmDelete:(count,sample)=>`${count} kitap silinsin mi? ${sample} Bu silme geri alınamaz.`,deletedWithFailures:(deleted,failed)=>`${deleted} silindi, ${failed} silinemedi`,deleted:count=>`${count} kitap silindi`,
  },
  ur:{
    selected:count=>`آپ نے ${count} کتابیں منتخب کیں؛ صرف یہاں متعین خانے بدلیں گے`,apply:count=>`${count} کتابوں پر تبدیلیاں نافذ کریں`,applied:count=>`منتخب ڈیٹا ${count} کتابوں پر نافذ ہوگیا`,undone:count=>`${count} کتابوں پر آخری اجتماعی نفاذ واپس ہوگیا`,confirmDelete:(count,sample)=>`${count} کتابیں حذف کریں؟ ${sample} یہ حذف واپس نہیں ہوسکتا۔`,deletedWithFailures:(deleted,failed)=>`${deleted} حذف ہوئیں اور ${failed} حذف نہ ہوسکیں`,deleted:count=>`${count} کتابیں حذف ہوئیں`,
  },
  fa:{
    selected:count=>`${count} کتاب انتخاب کردید؛ فقط فیلدهایی که اینجا تعیین کرده‌اید تغییر می‌کنند`,apply:count=>`اعمال تغییرات روی ${count} کتاب`,applied:count=>`داده‌های تعیین‌شده روی ${count} کتاب اعمال شد`,undone:count=>`آخرین اعمال گروهی روی ${count} کتاب برگردانده شد`,confirmDelete:(count,sample)=>`${count} کتاب حذف شود؟ ${sample} این حذف بازگشت‌پذیر نیست.`,deletedWithFailures:(deleted,failed)=>`${deleted} مورد حذف شد و حذف ${failed} مورد ممکن نشد`,deleted:count=>`${count} کتاب حذف شد`,
  },
  sw:{selected:c=>`Umechagua vitabu ${c}; ni sehemu ulizobainisha hapa tu zitabadilika`,apply:c=>`Tumia mabadiliko kwa vitabu ${c}`,applied:c=>`Data iliyochaguliwa imetumika kwa vitabu ${c}`,undone:c=>`Umetengua badiliko la mwisho la pamoja kwa vitabu ${c}`,confirmDelete:(c,s)=>`Ufute vitabu ${c}? ${s} Ufutaji huu hauwezi kutenduliwa.`,deletedWithFailures:(a,b)=>`${a} vimefutwa; ${b} havikuweza kufutwa`,deleted:c=>`Vitabu ${c} vimefutwa`},
  hi:{selected:c=>`आपने ${c} पुस्तकें चुनीं; केवल यहाँ बताए क्षेत्र बदलेंगे`,apply:c=>`${c} पुस्तकों पर बदलाव लागू करें`,applied:c=>`चुना डेटा ${c} पुस्तकों पर लागू हुआ`,undone:c=>`${c} पुस्तकों का पिछला सामूहिक बदलाव वापस लिया`,confirmDelete:(c,s)=>`${c} पुस्तकें हटाएँ? ${s} इसे वापस नहीं लिया जा सकता।`,deletedWithFailures:(a,b)=>`${a} हटाई गईं; ${b} नहीं हट सकीं`,deleted:c=>`${c} पुस्तकें हटाई गईं`},
  hu:{selected:c=>`${c} könyvet választott; csak az itt megadott mezők változnak`,apply:c=>`Módosítások alkalmazása ${c} könyvre`,applied:c=>`A kijelölt adatok ${c} könyvre alkalmazva`,undone:c=>`${c} könyv utolsó tömeges módosítása visszavonva`,confirmDelete:(c,s)=>`Töröl ${c} könyvet? ${s} A törlés nem vonható vissza.`,deletedWithFailures:(a,b)=>`${a} törölve; ${b} nem törölhető`,deleted:c=>`${c} könyv törölve`},
  id:{selected:c=>`Anda memilih ${c} buku; hanya bidang yang ditentukan di sini yang berubah`,apply:c=>`Terapkan perubahan ke ${c} buku`,applied:c=>`Data terpilih diterapkan ke ${c} buku`,undone:c=>`Pembaruan massal terakhir pada ${c} buku dibatalkan`,confirmDelete:(c,s)=>`Hapus ${c} buku? ${s} Penghapusan ini tidak dapat dibatalkan.`,deletedWithFailures:(a,b)=>`${a} dihapus; ${b} gagal dihapus`,deleted:c=>`${c} buku dihapus`},
  ms:{selected:c=>`Anda memilih ${c} buku; hanya medan yang dinyatakan di sini berubah`,apply:c=>`Gunakan perubahan pada ${c} buku`,applied:c=>`Data terpilih digunakan pada ${c} buku`,undone:c=>`Kemas kini pukal terakhir pada ${c} buku dibatalkan`,confirmDelete:(c,s)=>`Padam ${c} buku? ${s} Pemadaman ini tidak boleh dibuat asal.`,deletedWithFailures:(a,b)=>`${a} dipadam; ${b} gagal dipadam`,deleted:c=>`${c} buku dipadam`},
  bn:{selected:c=>`আপনি ${c}টি বই বেছেছেন; এখানে নির্ধারিত ক্ষেত্রই শুধু বদলাবে`,apply:c=>`${c}টি বইয়ে পরিবর্তন প্রয়োগ করুন`,applied:c=>`নির্বাচিত তথ্য ${c}টি বইয়ে প্রয়োগ হয়েছে`,undone:c=>`${c}টি বইয়ের শেষ সম্মিলিত পরিবর্তন বাতিল হয়েছে`,confirmDelete:(c,s)=>`${c}টি বই মুছবেন? ${s} এটি ফিরিয়ে নেওয়া যাবে না।`,deletedWithFailures:(a,b)=>`${a}টি মুছে গেছে; ${b}টি মোছা যায়নি`,deleted:c=>`${c}টি বই মুছে গেছে`},
  ps:{selected:c=>`تاسو ${c} کتابونه ټاکلي؛ یوازې دلته ټاکل شوې برخې بدلېږي`,apply:c=>`په ${c} کتابونو بدلونونه پلي کړئ`,applied:c=>`ټاکل شوي معلومات په ${c} کتابونو پلي شول`,undone:c=>`د ${c} کتابونو وروستی ډله‌ییز بدلون بېرته واخیستل شو`,confirmDelete:(c,s)=>`${c} کتابونه ړنګ کړئ؟ ${s} دا ړنګول بېرته نه اخیستل کېږي.`,deletedWithFailures:(a,b)=>`${a} ړنګ شول؛ ${b} ونه ړنګېدل`,deleted:c=>`${c} کتابونه ړنګ شول`},
  so:{selected:c=>`Waxaad dooratay ${c} buug; keliya meelaha halkan lagu sheegay ayaa isbeddelaya`,apply:c=>`Ku dabaq isbeddelka ${c} buug`,applied:c=>`Xogta la doortay waxaa lagu dabaqay ${c} buug`,undone:c=>`Isbeddelkii guud ee ugu dambeeyey ee ${c} buug waa la celiyey`,confirmDelete:(c,s)=>`Ma tirtirtaa ${c} buug? ${s} Tirtiriddan lama celin karo.`,deletedWithFailures:(a,b)=>`${a} waa la tirtiray; ${b} lama tirtiri karin`,deleted:c=>`${c} buug waa la tirtiray`},
  ha:{selected:c=>`Ka zaɓi littattafai ${c}; filayen da ka ayyana a nan kaɗai za su canza`,apply:c=>`Aiwatar da canje-canje ga littattafai ${c}`,applied:c=>`An aiwatar da bayanan da aka zaɓa ga littattafai ${c}`,undone:c=>`An soke sabuntawar taro na ƙarshe ga littattafai ${c}`,confirmDelete:(c,s)=>`A goge littattafai ${c}? ${s} Ba za a iya dawo da wannan gogewar ba.`,deletedWithFailures:(a,b)=>`${a} an goge; ${b} ba a iya gogewa ba`,deleted:c=>`An goge littattafai ${c}`},
  ru:{selected:c=>`Выбрано книг: ${c}; изменятся только указанные здесь поля`,apply:c=>`Применить изменения к ${c} книгам`,applied:c=>`Выбранные данные применены к ${c} книгам`,undone:c=>`Последнее массовое изменение ${c} книг отменено`,confirmDelete:(c,s)=>`Удалить ${c} книг? ${s} Это действие нельзя отменить.`,deletedWithFailures:(a,b)=>`${a} удалено; ${b} удалить не удалось`,deleted:c=>`Удалено книг: ${c}`},
  uk:{selected:c=>`Вибрано книг: ${c}; зміняться лише вказані тут поля`,apply:c=>`Застосувати зміни до ${c} книг`,applied:c=>`Вибрані дані застосовано до ${c} книг`,undone:c=>`Останню масову зміну ${c} книг скасовано`,confirmDelete:(c,s)=>`Видалити ${c} книг? ${s} Цю дію неможливо скасувати.`,deletedWithFailures:(a,b)=>`${a} видалено; ${b} не вдалося видалити`,deleted:c=>`Видалено книг: ${c}`},
  de:{selected:c=>`${c} Bücher ausgewählt; nur die hier angegebenen Felder ändern sich`,apply:c=>`Änderungen auf ${c} Bücher anwenden`,applied:c=>`Ausgewählte Daten auf ${c} Bücher angewendet`,undone:c=>`Letzte Sammeländerung an ${c} Büchern rückgängig gemacht`,confirmDelete:(c,s)=>`${c} Bücher löschen? ${s} Dies kann nicht rückgängig gemacht werden.`,deletedWithFailures:(a,b)=>`${a} gelöscht; ${b} konnten nicht gelöscht werden`,deleted:c=>`${c} Bücher gelöscht`},
  es:{selected:c=>`Has seleccionado ${c} libros; solo cambiarán los campos indicados aquí`,apply:c=>`Aplicar cambios a ${c} libros`,applied:c=>`Datos seleccionados aplicados a ${c} libros`,undone:c=>`Se deshizo el último cambio masivo en ${c} libros`,confirmDelete:(c,s)=>`¿Eliminar ${c} libros? ${s} Esta acción no se puede deshacer.`,deletedWithFailures:(a,b)=>`${a} eliminados; no se pudieron eliminar ${b}`,deleted:c=>`${c} libros eliminados`},
  pt:{selected:c=>`Selecionou ${c} livros; apenas os campos indicados aqui serão alterados`,apply:c=>`Aplicar alterações a ${c} livros`,applied:c=>`Dados selecionados aplicados a ${c} livros`,undone:c=>`Desfeita a última alteração em massa de ${c} livros`,confirmDelete:(c,s)=>`Eliminar ${c} livros? ${s} Esta ação não pode ser anulada.`,deletedWithFailures:(a,b)=>`${a} eliminados; não foi possível eliminar ${b}`,deleted:c=>`${c} livros eliminados`},
  it:{selected:c=>`Hai selezionato ${c} libri; cambieranno solo i campi indicati qui`,apply:c=>`Applica le modifiche a ${c} libri`,applied:c=>`Dati selezionati applicati a ${c} libri`,undone:c=>`Annullata l'ultima modifica collettiva su ${c} libri`,confirmDelete:(c,s)=>`Eliminare ${c} libri? ${s} L'eliminazione non può essere annullata.`,deletedWithFailures:(a,b)=>`${a} eliminati; ${b} non eliminati`,deleted:c=>`${c} libri eliminati`},
  nl:{selected:c=>`${c} boeken geselecteerd; alleen de hier opgegeven velden veranderen`,apply:c=>`Wijzigingen toepassen op ${c} boeken`,applied:c=>`Geselecteerde gegevens toegepast op ${c} boeken`,undone:c=>`Laatste bulkwijziging van ${c} boeken ongedaan gemaakt`,confirmDelete:(c,s)=>`${c} boeken verwijderen? ${s} Dit kan niet ongedaan worden gemaakt.`,deletedWithFailures:(a,b)=>`${a} verwijderd; ${b} konden niet worden verwijderd`,deleted:c=>`${c} boeken verwijderd`},
  sv:{selected:c=>`${c} böcker valda; bara fälten som anges här ändras`,apply:c=>`Tillämpa ändringar på ${c} böcker`,applied:c=>`Valda data tillämpades på ${c} böcker`,undone:c=>`Senaste massändringen av ${c} böcker ångrades`,confirmDelete:(c,s)=>`Ta bort ${c} böcker? ${s} Detta kan inte ångras.`,deletedWithFailures:(a,b)=>`${a} borttagna; ${b} kunde inte tas bort`,deleted:c=>`${c} böcker borttagna`},
  no:{selected:c=>`${c} bøker valgt; bare feltene som er angitt her endres`,apply:c=>`Bruk endringer på ${c} bøker`,applied:c=>`Valgte data brukt på ${c} bøker`,undone:c=>`Siste masseendring av ${c} bøker ble angret`,confirmDelete:(c,s)=>`Slette ${c} bøker? ${s} Dette kan ikke angres.`,deletedWithFailures:(a,b)=>`${a} slettet; ${b} kunne ikke slettes`,deleted:c=>`${c} bøker slettet`},
  pl:{selected:c=>`Wybrano ${c} książek; zmienią się tylko wskazane tutaj pola`,apply:c=>`Zastosuj zmiany do ${c} książek`,applied:c=>`Wybrane dane zastosowano do ${c} książek`,undone:c=>`Cofnięto ostatnią zmianę zbiorczą ${c} książek`,confirmDelete:(c,s)=>`Usunąć ${c} książek? ${s} Tej operacji nie można cofnąć.`,deletedWithFailures:(a,b)=>`${a} usunięto; ${b} nie udało się usunąć`,deleted:c=>`Usunięto książek: ${c}`},
  ro:{selected:c=>`Ați selectat ${c} cărți; se modifică doar câmpurile indicate aici`,apply:c=>`Aplicați modificările la ${c} cărți`,applied:c=>`Datele selectate au fost aplicate la ${c} cărți`,undone:c=>`Ultima modificare în masă a ${c} cărți a fost anulată`,confirmDelete:(c,s)=>`Ștergeți ${c} cărți? ${s} Ștergerea nu poate fi anulată.`,deletedWithFailures:(a,b)=>`${a} șterse; ${b} nu au putut fi șterse`,deleted:c=>`${c} cărți șterse`},
  bs:{selected:c=>`Odabrali ste ${c} knjiga; mijenjaju se samo ovdje navedena polja`,apply:c=>`Primijeni izmjene na ${c} knjiga`,applied:c=>`Odabrani podaci primijenjeni na ${c} knjiga`,undone:c=>`Poništena posljednja grupna izmjena ${c} knjiga`,confirmDelete:(c,s)=>`Izbrisati ${c} knjiga? ${s} Brisanje se ne može poništiti.`,deletedWithFailures:(a,b)=>`${a} izbrisano; ${b} nije moguće izbrisati`,deleted:c=>`${c} knjiga izbrisano`},
  sq:{selected:c=>`Keni zgjedhur ${c} libra; ndryshojnë vetëm fushat e përcaktuara këtu`,apply:c=>`Zbatoni ndryshimet në ${c} libra`,applied:c=>`Të dhënat e zgjedhura u zbatuan në ${c} libra`,undone:c=>`U anulua ndryshimi i fundit në grup për ${c} libra`,confirmDelete:(c,s)=>`Të fshihen ${c} libra? ${s} Fshirja nuk mund të zhbëhet.`,deletedWithFailures:(a,b)=>`${a} u fshinë; ${b} nuk u fshinë`,deleted:c=>`${c} libra u fshinë`},
  az:{selected:c=>`${c} kitab seçdiniz; yalnız burada göstərilən sahələr dəyişəcək`,apply:c=>`Dəyişiklikləri ${c} kitaba tətbiq edin`,applied:c=>`Seçilmiş məlumatlar ${c} kitaba tətbiq edildi`,undone:c=>`${c} kitabdakı son toplu dəyişiklik geri alındı`,confirmDelete:(c,s)=>`${c} kitab silinsin? ${s} Bu əməliyyat geri qaytarılmır.`,deletedWithFailures:(a,b)=>`${a} silindi; ${b} silinmədi`,deleted:c=>`${c} kitab silindi`},
  uz:{selected:c=>`${c} ta kitob tanlandi; faqat shu yerda ko‘rsatilgan maydonlar o‘zgaradi`,apply:c=>`O‘zgarishlarni ${c} ta kitobga qo‘llang`,applied:c=>`Tanlangan maʼlumotlar ${c} ta kitobga qo‘llandi`,undone:c=>`${c} ta kitobdagi so‘nggi ommaviy o‘zgarish bekor qilindi`,confirmDelete:(c,s)=>`${c} ta kitob o‘chirilsinmi? ${s} Buni bekor qilib bo‘lmaydi.`,deletedWithFailures:(a,b)=>`${a} o‘chirildi; ${b} o‘chirilmadi`,deleted:c=>`${c} ta kitob o‘chirildi`},
  kk:{selected:c=>`${c} кітап таңдалды; мұнда көрсетілген өрістер ғана өзгереді`,apply:c=>`Өзгерістерді ${c} кітапқа қолдану`,applied:c=>`Таңдалған деректер ${c} кітапқа қолданылды`,undone:c=>`${c} кітаптағы соңғы топтық өзгеріс қайтарылды`,confirmDelete:(c,s)=>`${c} кітап жойылсын ба? ${s} Мұны қайтару мүмкін емес.`,deletedWithFailures:(a,b)=>`${a} жойылды; ${b} жойылмады`,deleted:c=>`${c} кітап жойылды`},
  zh:{selected:c=>`已选择 ${c} 本书；仅更改此处指定的字段`,apply:c=>`将更改应用到 ${c} 本书`,applied:c=>`已将所选数据应用到 ${c} 本书`,undone:c=>`已撤销 ${c} 本书的上次批量更改`,confirmDelete:(c,s)=>`删除 ${c} 本书？${s} 此操作无法撤销。`,deletedWithFailures:(a,b)=>`已删除 ${a}；${b} 删除失败`,deleted:c=>`已删除 ${c} 本书`},
  ja:{selected:c=>`${c} 冊を選択しました。ここで指定した項目のみ変更されます`,apply:c=>`${c} 冊に変更を適用`,applied:c=>`選択したデータを ${c} 冊に適用しました`,undone:c=>`${c} 冊への直前の一括変更を元に戻しました`,confirmDelete:(c,s)=>`${c} 冊を削除しますか？ ${s} この操作は元に戻せません。`,deletedWithFailures:(a,b)=>`${a} 件削除、${b} 件は削除できませんでした`,deleted:c=>`${c} 冊を削除しました`},
  ko:{selected:c=>`책 ${c}권을 선택했습니다. 여기서 지정한 필드만 변경됩니다`,apply:c=>`책 ${c}권에 변경 사항 적용`,applied:c=>`선택한 데이터를 책 ${c}권에 적용했습니다`,undone:c=>`책 ${c}권의 마지막 일괄 변경을 취소했습니다`,confirmDelete:(c,s)=>`책 ${c}권을 삭제할까요? ${s} 이 작업은 되돌릴 수 없습니다.`,deletedWithFailures:(a,b)=>`${a}개 삭제됨, ${b}개 삭제 실패`,deleted:c=>`책 ${c}권 삭제됨`},
}
