type ReaderStatusDynamicTemplates = {
  diagnostic: (code: string) => string
  preservedWithDiagnostic: (code: string) => string
  copyFailed: (detail: string) => string
  pdfFailed: (detail: string) => string
  partsDownload: (count: string) => string
  localRequired: (label: string) => string
}

/** حالات القارئ؛ code/detail/label قيم تشغيلية تحفظ حرفيًا ولا تُترجم كبيانات. */
export const REVIEWED_READER_STATUS_DYNAMIC_TEMPLATES: Readonly<Record<string, ReaderStatusDynamicTemplates>> = {
  en:{diagnostic:code=>`Diagnostic code: ${code}`,preservedWithDiagnostic:code=>`The book's original data is preserved and was not deleted. Diagnostic code: ${code}`,copyFailed:detail=>`Copy failed: ${detail}`,pdfFailed:detail=>`Could not create PDF: ${detail}`,partsDownload:count=>`Started downloading ${count} parts in their original formats`,localRequired:label=>`${label} — requires the local app`},
  fr:{diagnostic:code=>`Code de diagnostic : ${code}`,preservedWithDiagnostic:code=>`Les données originales du livre sont conservées et n'ont pas été supprimées. Code de diagnostic : ${code}`,copyFailed:detail=>`Échec de la copie : ${detail}`,pdfFailed:detail=>`Création du PDF impossible : ${detail}`,partsDownload:count=>`Téléchargement de ${count} parties dans leurs formats originaux démarré`,localRequired:label=>`${label} — nécessite l'application locale`},
  ug:{diagnostic:code=>`دىئاگنوز كودى: ${code}`,preservedWithDiagnostic:code=>`كىتابنىڭ ئەسلى سانلىق مەلۇماتى ساقلانغان، ئۆچۈرۈلمىگەن. دىئاگنوز كودى: ${code}`,copyFailed:detail=>`كۆچۈرۈش مەغلۇپ بولدى: ${detail}`,pdfFailed:detail=>`PDF قۇرالمىدى: ${detail}`,partsDownload:count=>`${count} بۆلەكنى ئەسلى فورماتتا چۈشۈرۈش باشلاندى`,localRequired:label=>`${label} — يەرلىك ئەپ كېرەك`},
  ckb:{diagnostic:code=>`کۆدی پشکنین: ${code}`,preservedWithDiagnostic:code=>`داتای ڕەسەنی کتێبەکە پاشەکەوت کراوە و نەسڕاوەتەوە. کۆدی پشکنین: ${code}`,copyFailed:detail=>`لەبەرگرتنەوە سەرکەوتوو نەبوو: ${detail}`,pdfFailed:detail=>`دروستکردنی PDF سەرکەوتوو نەبوو: ${detail}`,partsDownload:count=>`داگرتنی ${count} بەش بە فۆرماتە ڕەسەنەکانیان دەستی پێکرد`,localRequired:label=>`${label} — پێویستی بە ئەپی ناوخۆیی هەیە`},
  ku:{diagnostic:code=>`Koda teşhîsê: ${code}`,preservedWithDiagnostic:code=>`Daneyên resen ên pirtûkê parastî ne û nehatine jêbirin. Koda teşhîsê: ${code}`,copyFailed:detail=>`Kopîkirin bi ser neket: ${detail}`,pdfFailed:detail=>`PDF nehat afirandin: ${detail}`,partsDownload:count=>`Daxistina ${count} beşan bi formatên wan ên resen dest pê kir`,localRequired:label=>`${label} — sepana herêmî pêwîst e`},
  tr:{diagnostic:code=>`Tanı kodu: ${code}`,preservedWithDiagnostic:code=>`Kitabın özgün verileri korundu ve silinmedi. Tanı kodu: ${code}`,copyFailed:detail=>`Kopyalanamadı: ${detail}`,pdfFailed:detail=>`PDF oluşturulamadı: ${detail}`,partsDownload:count=>`${count} bölüm özgün biçimleriyle indirilmeye başladı`,localRequired:label=>`${label} — yerel uygulama gerekir`},
  ur:{diagnostic:code=>`تشخیصی رمز: ${code}`,preservedWithDiagnostic:code=>`کتاب کا اصل ڈیٹا محفوظ ہے اور حذف نہیں ہوا۔ تشخیصی رمز: ${code}`,copyFailed:detail=>`نقل نہ ہو سکا: ${detail}`,pdfFailed:detail=>`PDF نہ بن سکا: ${detail}`,partsDownload:count=>`${count} اجزاء کا اصل صیغوں میں ڈاؤن لوڈ شروع ہوا`,localRequired:label=>`${label} — مقامی ایپ درکار ہے`},
  fa:{diagnostic:code=>`کد عیب‌یابی: ${code}`,preservedWithDiagnostic:code=>`داده‌های اصلی کتاب محفوظ است و حذف نشده. کد عیب‌یابی: ${code}`,copyFailed:detail=>`کپی ممکن نشد: ${detail}`,pdfFailed:detail=>`ساخت PDF ممکن نشد: ${detail}`,partsDownload:count=>`بارگیری ${count} بخش با قالب‌های اصلی آغاز شد`,localRequired:label=>`${label} — به برنامهٔ محلی نیاز دارد`},
  sw:{diagnostic:code=>`Msimbo wa uchunguzi: ${code}`,preservedWithDiagnostic:code=>`Data asili ya kitabu imehifadhiwa na haikufutwa. Msimbo wa uchunguzi: ${code}`,copyFailed:detail=>`Kunakili kumeshindikana: ${detail}`,pdfFailed:detail=>`PDF haikuundwa: ${detail}`,partsDownload:count=>`Upakuaji wa sehemu ${count} katika miundo yake asili umeanza`,localRequired:label=>`${label} — inahitaji programu ya ndani`},
  hi:{diagnostic:code=>`निदान कोड: ${code}`,preservedWithDiagnostic:code=>`पुस्तक का मूल डेटा सुरक्षित है और हटाया नहीं गया। निदान कोड: ${code}`,copyFailed:detail=>`कॉपी नहीं हो सकी: ${detail}`,pdfFailed:detail=>`PDF नहीं बन सका: ${detail}`,partsDownload:count=>`${count} भागों का मूल प्रारूप में डाउनलोड शुरू हुआ`,localRequired:label=>`${label} — स्थानीय ऐप आवश्यक है`},
  hu:{diagnostic:code=>`Diagnosztikai kód: ${code}`,preservedWithDiagnostic:code=>`A könyv eredeti adatai megmaradtak, nem törlődtek. Diagnosztikai kód: ${code}`,copyFailed:detail=>`A másolás sikertelen: ${detail}`,pdfFailed:detail=>`A PDF nem hozható létre: ${detail}`,partsDownload:count=>`${count} rész letöltése elindult eredeti formátumban`,localRequired:label=>`${label} — helyi alkalmazás szükséges`},
  id:{diagnostic:code=>`Kode diagnostik: ${code}`,preservedWithDiagnostic:code=>`Data asli buku tetap tersimpan dan tidak dihapus. Kode diagnostik: ${code}`,copyFailed:detail=>`Gagal menyalin: ${detail}`,pdfFailed:detail=>`PDF tidak dapat dibuat: ${detail}`,partsDownload:count=>`Unduhan ${count} bagian dalam format aslinya dimulai`,localRequired:label=>`${label} — memerlukan aplikasi lokal`},
  ms:{diagnostic:code=>`Kod diagnostik: ${code}`,preservedWithDiagnostic:code=>`Data asal buku kekal tersimpan dan tidak dipadam. Kod diagnostik: ${code}`,copyFailed:detail=>`Salinan gagal: ${detail}`,pdfFailed:detail=>`PDF tidak dapat dicipta: ${detail}`,partsDownload:count=>`Muat turun ${count} bahagian dalam format asal bermula`,localRequired:label=>`${label} — memerlukan aplikasi setempat`},
  bn:{diagnostic:code=>`নির্ণয় কোড: ${code}`,preservedWithDiagnostic:code=>`বইয়ের মূল তথ্য সংরক্ষিত আছে এবং মুছে যায়নি। নির্ণয় কোড: ${code}`,copyFailed:detail=>`অনুলিপি ব্যর্থ: ${detail}`,pdfFailed:detail=>`PDF তৈরি করা যায়নি: ${detail}`,partsDownload:count=>`${count}টি অংশের মূল বিন্যাসে ডাউনলোড শুরু হয়েছে`,localRequired:label=>`${label} — স্থানীয় অ্যাপ প্রয়োজন`},
  ps:{diagnostic:code=>`تشخیصي کوډ: ${code}`,preservedWithDiagnostic:code=>`د کتاب اصلي معلومات خوندي دي او نه دي حذف شوي. تشخیصي کوډ: ${code}`,copyFailed:detail=>`کاپي ناکامه شوه: ${detail}`,pdfFailed:detail=>`PDF جوړ نه شو: ${detail}`,partsDownload:count=>`د ${count} برخو کښته کول په اصلي بڼو پیل شول`,localRequired:label=>`${label} — ځايي اپ ته اړتیا لري`},
  so:{diagnostic:code=>`Koodhka ogaanshaha: ${code}`,preservedWithDiagnostic:code=>`Xogta asalka ah ee buugga waa la dhowray mana tirtirmin. Koodhka ogaanshaha: ${code}`,copyFailed:detail=>`Nuqulku wuu fashilmay: ${detail}`,pdfFailed:detail=>`PDF lama samayn karin: ${detail}`,partsDownload:count=>`Soo dejinta ${count} qaybood ee qaababkoodii asalka ahaa way bilaabatay`,localRequired:label=>`${label} — wuxuu u baahan yahay abka maxalliga ah`},
  ha:{diagnostic:code=>`Lambar bincike: ${code}`,preservedWithDiagnostic:code=>`An adana ainihin bayanan littafin kuma ba a share su ba. Lambar bincike: ${code}`,copyFailed:detail=>`Kwafi ya gaza: ${detail}`,pdfFailed:detail=>`Ba a iya ƙirƙirar PDF ba: ${detail}`,partsDownload:count=>`An fara sauke sassa ${count} a tsarin asalinsu`,localRequired:label=>`${label} — yana buƙatar manhajar gida`},
  ru:{diagnostic:code=>`Код диагностики: ${code}`,preservedWithDiagnostic:code=>`Исходные данные книги сохранены и не удалены. Код диагностики: ${code}`,copyFailed:detail=>`Не удалось скопировать: ${detail}`,pdfFailed:detail=>`Не удалось создать PDF: ${detail}`,partsDownload:count=>`Начато скачивание ${count} частей в исходных форматах`,localRequired:label=>`${label} — требуется локальное приложение`},
  uk:{diagnostic:code=>`Код діагностики: ${code}`,preservedWithDiagnostic:code=>`Оригінальні дані книги збережені й не видалені. Код діагностики: ${code}`,copyFailed:detail=>`Не вдалося скопіювати: ${detail}`,pdfFailed:detail=>`Не вдалося створити PDF: ${detail}`,partsDownload:count=>`Розпочато завантаження ${count} частин в оригінальних форматах`,localRequired:label=>`${label} — потрібна локальна програма`},
  de:{diagnostic:code=>`Diagnosecode: ${code}`,preservedWithDiagnostic:code=>`Die Originaldaten des Buchs sind erhalten und wurden nicht gelöscht. Diagnosecode: ${code}`,copyFailed:detail=>`Kopieren fehlgeschlagen: ${detail}`,pdfFailed:detail=>`PDF konnte nicht erstellt werden: ${detail}`,partsDownload:count=>`Download von ${count} Teilen in ihren Originalformaten gestartet`,localRequired:label=>`${label} — lokale App erforderlich`},
  es:{diagnostic:code=>`Código de diagnóstico: ${code}`,preservedWithDiagnostic:code=>`Los datos originales del libro se conservaron y no se eliminaron. Código de diagnóstico: ${code}`,copyFailed:detail=>`No se pudo copiar: ${detail}`,pdfFailed:detail=>`No se pudo crear el PDF: ${detail}`,partsDownload:count=>`Se inició la descarga de ${count} partes en sus formatos originales`,localRequired:label=>`${label} — requiere la aplicación local`},
  pt:{diagnostic:code=>`Código de diagnóstico: ${code}`,preservedWithDiagnostic:code=>`Os dados originais do livro foram preservados e não eliminados. Código de diagnóstico: ${code}`,copyFailed:detail=>`Não foi possível copiar: ${detail}`,pdfFailed:detail=>`Não foi possível criar o PDF: ${detail}`,partsDownload:count=>`Iniciada a transferência de ${count} partes nos formatos originais`,localRequired:label=>`${label} — requer a aplicação local`},
  it:{diagnostic:code=>`Codice diagnostico: ${code}`,preservedWithDiagnostic:code=>`I dati originali del libro sono conservati e non sono stati eliminati. Codice diagnostico: ${code}`,copyFailed:detail=>`Copia non riuscita: ${detail}`,pdfFailed:detail=>`Impossibile creare il PDF: ${detail}`,partsDownload:count=>`Avviato il download di ${count} parti nei formati originali`,localRequired:label=>`${label} — richiede l'app locale`},
  nl:{diagnostic:code=>`Diagnosecode: ${code}`,preservedWithDiagnostic:code=>`De oorspronkelijke boekgegevens zijn bewaard en niet verwijderd. Diagnosecode: ${code}`,copyFailed:detail=>`Kopiëren mislukt: ${detail}`,pdfFailed:detail=>`PDF kon niet worden gemaakt: ${detail}`,partsDownload:count=>`Download van ${count} delen in hun oorspronkelijke indeling gestart`,localRequired:label=>`${label} — lokale app vereist`},
  sv:{diagnostic:code=>`Diagnoskod: ${code}`,preservedWithDiagnostic:code=>`Bokens originaldata är bevarade och har inte raderats. Diagnoskod: ${code}`,copyFailed:detail=>`Kopiering misslyckades: ${detail}`,pdfFailed:detail=>`PDF kunde inte skapas: ${detail}`,partsDownload:count=>`Hämtning av ${count} delar i originalformat har startat`,localRequired:label=>`${label} — kräver den lokala appen`},
  no:{diagnostic:code=>`Diagnosekode: ${code}`,preservedWithDiagnostic:code=>`Bokens originaldata er bevart og ikke slettet. Diagnosekode: ${code}`,copyFailed:detail=>`Kopiering mislyktes: ${detail}`,pdfFailed:detail=>`PDF kunne ikke opprettes: ${detail}`,partsDownload:count=>`Nedlasting av ${count} deler i originalformat startet`,localRequired:label=>`${label} — krever lokalappen`},
  pl:{diagnostic:code=>`Kod diagnostyczny: ${code}`,preservedWithDiagnostic:code=>`Oryginalne dane książki zachowano i nie usunięto. Kod diagnostyczny: ${code}`,copyFailed:detail=>`Kopiowanie nie powiodło się: ${detail}`,pdfFailed:detail=>`Nie udało się utworzyć PDF: ${detail}`,partsDownload:count=>`Rozpoczęto pobieranie ${count} części w oryginalnych formatach`,localRequired:label=>`${label} — wymaga aplikacji lokalnej`},
  ro:{diagnostic:code=>`Cod de diagnostic: ${code}`,preservedWithDiagnostic:code=>`Datele originale ale cărții sunt păstrate și nu au fost șterse. Cod de diagnostic: ${code}`,copyFailed:detail=>`Copierea a eșuat: ${detail}`,pdfFailed:detail=>`PDF-ul nu a putut fi creat: ${detail}`,partsDownload:count=>`A început descărcarea a ${count} părți în formatele originale`,localRequired:label=>`${label} — necesită aplicația locală`},
  bs:{diagnostic:code=>`Dijagnostički kod: ${code}`,preservedWithDiagnostic:code=>`Izvorni podaci knjige su sačuvani i nisu izbrisani. Dijagnostički kod: ${code}`,copyFailed:detail=>`Kopiranje nije uspjelo: ${detail}`,pdfFailed:detail=>`PDF nije moguće napraviti: ${detail}`,partsDownload:count=>`Počelo je preuzimanje ${count} dijelova u izvornim formatima`,localRequired:label=>`${label} — zahtijeva lokalnu aplikaciju`},
  sq:{diagnostic:code=>`Kodi diagnostik: ${code}`,preservedWithDiagnostic:code=>`Të dhënat origjinale të librit janë ruajtur dhe nuk janë fshirë. Kodi diagnostik: ${code}`,copyFailed:detail=>`Kopjimi dështoi: ${detail}`,pdfFailed:detail=>`PDF-ja nuk u krijua: ${detail}`,partsDownload:count=>`Filloi shkarkimi i ${count} pjesëve në formatet origjinale`,localRequired:label=>`${label} — kërkon aplikacionin lokal`},
  az:{diagnostic:code=>`Diaqnostika kodu: ${code}`,preservedWithDiagnostic:code=>`Kitabın orijinal məlumatları qorunub və silinməyib. Diaqnostika kodu: ${code}`,copyFailed:detail=>`Kopyalama alınmadı: ${detail}`,pdfFailed:detail=>`PDF yaradıla bilmədi: ${detail}`,partsDownload:count=>`${count} hissənin orijinal formatlarda endirilməsi başladı`,localRequired:label=>`${label} — yerli tətbiq tələb olunur`},
  uz:{diagnostic:code=>`Tashxis kodi: ${code}`,preservedWithDiagnostic:code=>`Kitobning asl maʼlumotlari saqlandi va o‘chirilmadi. Tashxis kodi: ${code}`,copyFailed:detail=>`Nusxalash amalga oshmadi: ${detail}`,pdfFailed:detail=>`PDF yaratilmadi: ${detail}`,partsDownload:count=>`${count} qismni asl formatlarda yuklab olish boshlandi`,localRequired:label=>`${label} — mahalliy ilova talab qilinadi`},
  kk:{diagnostic:code=>`Диагностика коды: ${code}`,preservedWithDiagnostic:code=>`Кітаптың бастапқы деректері сақталды және жойылмады. Диагностика коды: ${code}`,copyFailed:detail=>`Көшіру сәтсіз: ${detail}`,pdfFailed:detail=>`PDF жасалмады: ${detail}`,partsDownload:count=>`${count} бөлікті бастапқы пішімдерде жүктеу басталды`,localRequired:label=>`${label} — жергілікті қолданба қажет`},
  zh:{diagnostic:code=>`诊断代码：${code}`,preservedWithDiagnostic:code=>`图书原始数据已保留，未被删除。诊断代码：${code}`,copyFailed:detail=>`复制失败：${detail}`,pdfFailed:detail=>`无法创建 PDF：${detail}`,partsDownload:count=>`已开始以原始格式下载 ${count} 个部分`,localRequired:label=>`${label} — 需要本地应用`},
  ja:{diagnostic:code=>`診断コード: ${code}`,preservedWithDiagnostic:code=>`書籍の元データは保持され、削除されていません。診断コード: ${code}`,copyFailed:detail=>`コピーできませんでした: ${detail}`,pdfFailed:detail=>`PDF を作成できませんでした: ${detail}`,partsDownload:count=>`${count} 部分の元形式でのダウンロードを開始しました`,localRequired:label=>`${label} — ローカルアプリが必要です`},
  ko:{diagnostic:code=>`진단 코드: ${code}`,preservedWithDiagnostic:code=>`책의 원본 데이터는 보존되었으며 삭제되지 않았습니다. 진단 코드: ${code}`,copyFailed:detail=>`복사 실패: ${detail}`,pdfFailed:detail=>`PDF를 만들 수 없습니다: ${detail}`,partsDownload:count=>`${count}개 부분을 원본 형식으로 다운로드하기 시작했습니다`,localRequired:label=>`${label} — 로컬 앱 필요`},
}
