const KEYS = ['تعذّر فتح خطط القراءة','الخطط محفوظة على جهازك؛ أعد المحاولة.'] as const
const labels = (values: readonly string[]): Readonly<Record<string, string>> => Object.fromEntries(KEYS.map((key, index) => [key, values[index]!]))

/** تعافي شاشة الخطط؛ رسائل نظامية ثابتة بلا بيانات مستخدم أو كتاب. */
export const REVIEWED_READING_PLANS_RECOVERY_ALL_UI: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  en: labels(['Could not open reading plans','Your plans are saved on this device; try again.']), fr: labels(['Impossible d’ouvrir les plans de lecture','Vos plans sont enregistrés sur cet appareil ; réessayez.']), ug: labels(['ئوقۇش پىلانلىرىنى ئاچقىلى بولمىدى','پىلانلىرىڭىز بۇ ئۈسكۈنىدە ساقلانغان؛ قايتا سىناڭ.']),
  sw: labels(['Imeshindikana kufungua mipango ya kusoma','Mipango yako imehifadhiwa kwenye kifaa hiki; jaribu tena.']), hi: labels(['पठन योजनाएँ नहीं खुल सकीं','आपकी योजनाएँ इस उपकरण पर सुरक्षित हैं; फिर प्रयास करें।']), hu: labels(['Az olvasási tervek nem nyithatók meg','Tervei ezen az eszközön vannak mentve; próbálja újra.']),
  id: labels(['Rencana membaca tidak dapat dibuka','Rencana Anda tersimpan di perangkat ini; coba lagi.']), ms: labels(['Pelan bacaan tidak dapat dibuka','Pelan anda disimpan pada peranti ini; cuba lagi.']), bn: labels(['পাঠ পরিকল্পনা খোলা যায়নি','আপনার পরিকল্পনাগুলো এই যন্ত্রে সংরক্ষিত আছে; আবার চেষ্টা করুন।']),
  ps: labels(['د لوستلو پلانونه پرانیستل نه شول','ستاسو پلانونه په دې وسیله خوندي دي؛ بیا هڅه وکړئ.']), so: labels(['Qorshayaasha akhriska lama furi karin','Qorshayaashaadu waxay ku kaydsan yihiin qalabkan; mar kale isku day.']), ha: labels(['Ba a iya buɗe tsare-tsaren karatu ba','An adana tsare-tsarenku a wannan na’ura; sake gwadawa.']),
  ru: labels(['Не удалось открыть планы чтения','Ваши планы сохранены на этом устройстве; попробуйте снова.']), uk: labels(['Не вдалося відкрити плани читання','Ваші плани збережені на цьому пристрої; спробуйте ще раз.']), de: labels(['Lesepläne konnten nicht geöffnet werden','Ihre Pläne sind auf diesem Gerät gespeichert; versuchen Sie es erneut.']),
  es: labels(['No se pudieron abrir los planes de lectura','Tus planes están guardados en este dispositivo; inténtalo de nuevo.']), pt: labels(['Não foi possível abrir os planos de leitura','Seus planos estão salvos neste dispositivo; tente novamente.']), it: labels(['Impossibile aprire i piani di lettura','I tuoi piani sono salvati su questo dispositivo; riprova.']),
  nl: labels(['Leesplannen konden niet worden geopend','Uw plannen zijn op dit apparaat opgeslagen; probeer het opnieuw.']), sv: labels(['Läsplanerna kunde inte öppnas','Dina planer är sparade på den här enheten; försök igen.']), no: labels(['Leseplanene kunne ikke åpnes','Planene dine er lagret på denne enheten; prøv igjen.']),
  pl: labels(['Nie udało się otworzyć planów czytania','Twoje plany są zapisane na tym urządzeniu; spróbuj ponownie.']), ro: labels(['Planurile de lectură nu au putut fi deschise','Planurile tale sunt salvate pe acest dispozitiv; încearcă din nou.']), bs: labels(['Planovi čitanja se nisu mogli otvoriti','Vaši planovi su sačuvani na ovom uređaju; pokušajte ponovo.']),
  sq: labels(['Planet e leximit nuk u hapën','Planet e tua ruhen në këtë pajisje; provo përsëri.']), az: labels(['Oxu planlarını açmaq mümkün olmadı','Planlarınız bu cihazda saxlanılıb; yenidən cəhd edin.']), uz: labels(['O‘qish rejalarini ochib bo‘lmadi','Rejalaringiz ushbu qurilmada saqlangan; qayta urinib ko‘ring.']),
  kk: labels(['Оқу жоспарларын ашу мүмкін болмады','Жоспарларыңыз осы құрылғыда сақталған; қайталап көріңіз.']), zh: labels(['无法打开阅读计划','您的计划已保存在此设备上；请重试。']), ja: labels(['読書計画を開けませんでした','計画はこの端末に保存されています。もう一度お試しください。']), ko: labels(['독서 계획을 열 수 없습니다','계획은 이 기기에 저장되어 있습니다. 다시 시도하세요.']),
}
