const KEYS = ['رحلات القراءة','تابع ورد اليوم، واعرف ما أنجزت وما بقي من كل كتاب.','افتح صفحة كتاب وحدد الوقت المتاح يوميًا لتبدأ رحلة واضحة.','الخطة متوقفة مؤقتًا ولا يتراكم الورد'] as const
const labels = (values: readonly string[]): Readonly<Record<string, string>> => Object.fromEntries(KEYS.map((key, index) => [key, values[index]!]))

/** وصف وإرشاد خطط القراءة؛ نصوص ثابتة لا تحمل عنوان كتاب أو قيمة تقدم. */
export const REVIEWED_READING_PLANS_GUIDANCE_ALL_UI: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  en: labels(['Reading journeys','Follow today’s reading and see what you completed and what remains in each book.','Open a book page and set your daily available time to begin a clear journey.','The plan is paused; daily reading will not accumulate']), fr: labels(['Parcours de lecture','Suivez la lecture du jour et voyez ce qui est terminé ou restant dans chaque livre.','Ouvrez la page d’un livre et indiquez votre temps quotidien disponible pour commencer un parcours clair.','Le plan est en pause ; la lecture quotidienne ne s’accumule pas']), ug: labels(['ئوقۇش سەپەرلىرى','بۈگۈنكى ئوقۇشىڭىزنى كۆزىتىپ، ھەر كىتابتا تاماملانغان ۋە قالغان قىسمىنى بىلىڭ.','كىتاب بېتىنى ئېچىپ، كۈندىلىك بوش ۋاقتىڭىزنى بەلگىلەپ ئېنىق سەپەرنى باشلاڭ.','پىلان ۋاقىتلىق توختىتىلدى؛ كۈندىلىك ئوقۇش يىغىلمايدۇ']),
  sw: labels(['Safari za kusoma','Fuatilia usomaji wa leo na ujue kilichokamilika na kilichobaki katika kila kitabu.','Fungua ukurasa wa kitabu na weka muda unaopatikana kila siku ili kuanza safari iliyo wazi.','Mpango umesitishwa; usomaji wa kila siku hautajikusanya']), hi: labels(['पठन यात्राएँ','आज का पठन देखें और जानें कि हर पुस्तक में क्या पूरा हुआ और क्या शेष है।','किसी पुस्तक का पृष्ठ खोलें और स्पष्ट यात्रा शुरू करने के लिए प्रतिदिन उपलब्ध समय तय करें।','योजना रुकी हुई है; दैनिक पठन जमा नहीं होगा']), hu: labels(['Olvasási utak','Kövesse a mai olvasást, és lássa, mi készült el és mi maradt az egyes könyvekből.','Nyisson meg egy könyvoldalt, és adja meg a napi idejét egy világos út megkezdéséhez.','A terv szünetel; a napi olvasás nem halmozódik']),
  id: labels(['Perjalanan membaca','Ikuti bacaan hari ini dan lihat yang telah selesai serta yang tersisa di setiap buku.','Buka halaman buku dan atur waktu harian yang tersedia untuk memulai perjalanan yang jelas.','Rencana dijeda; bacaan harian tidak akan menumpuk']), ms: labels(['Perjalanan membaca','Ikuti bacaan hari ini dan lihat yang selesai serta yang masih berbaki dalam setiap buku.','Buka halaman buku dan tetapkan masa harian yang tersedia untuk memulakan perjalanan yang jelas.','Pelan dijeda; bacaan harian tidak akan terkumpul']), bn: labels(['পাঠযাত্রা','আজকের পাঠ অনুসরণ করুন এবং প্রতিটি বইয়ে কী শেষ হয়েছে ও কী বাকি আছে দেখুন।','একটি বইয়ের পৃষ্ঠা খুলে স্পষ্ট যাত্রা শুরু করতে প্রতিদিনের সময় নির্ধারণ করুন।','পরিকল্পনা বিরত আছে; দৈনিক পাঠ জমবে না']),
  ps: labels(['د لوستلو سفرونه','د نن ورځې لوستل تعقیب کړئ او په هر کتاب کې بشپړ او پاتې شوي برخې وپېژنئ.','د کتاب پاڼه پرانیزئ او د روښانه سفر لپاره ورځنی وخت وټاکئ.','پلان درول شوی؛ ورځنی لوستل نه راټولېږي']), so: labels(['Safarrada akhriska','La soco akhriska maanta oo ogow waxa laga dhammeeyey iyo waxa ka haray buug kasta.','Fur bogga buug oo deji waqtiga maalinlaha ah si aad u bilowdo safar cad.','Qorshuhu wuu hakad galay; akhriska maalinlaha ahi isma ururinayo']), ha: labels(['Tafiyar karatu','Bi diddigin karatun yau kuma ga abin da aka kammala da abin da ya rage a kowane littafi.','Buɗe shafin littafi ka saita lokacin yau da kullum domin fara tafiya mai bayyana.','An dakatar da tsarin; karatun kullum ba zai taru ba']),
  ru: labels(['Маршруты чтения','Следите за чтением сегодня и смотрите, что завершено и что осталось в каждой книге.','Откройте страницу книги и задайте доступное ежедневное время, чтобы начать понятный маршрут.','План приостановлен; ежедневное чтение не накапливается']), uk: labels(['Маршрути читання','Стежте за сьогоднішнім читанням і бачте, що завершено та що лишилося в кожній книзі.','Відкрийте сторінку книги й задайте доступний щоденний час, щоб почати зрозумілий маршрут.','План призупинено; щоденне читання не накопичується']), de: labels(['Lesereisen','Verfolgen Sie die heutige Lektüre und sehen Sie, was in jedem Buch geschafft wurde und noch fehlt.','Öffnen Sie eine Buchseite und legen Sie Ihre täglich verfügbare Zeit fest, um einen klaren Weg zu beginnen.','Der Plan ist pausiert; tägliche Lektüre sammelt sich nicht an']),
  es: labels(['Recorridos de lectura','Sigue la lectura de hoy y consulta lo completado y lo pendiente en cada libro.','Abre la página de un libro y fija tu tiempo diario disponible para iniciar un recorrido claro.','El plan está en pausa; la lectura diaria no se acumula']), pt: labels(['Jornadas de leitura','Acompanhe a leitura de hoje e veja o que foi concluído e o que resta em cada livro.','Abra a página de um livro e defina seu tempo diário disponível para iniciar uma jornada clara.','O plano está pausado; a leitura diária não se acumula']), it: labels(['Percorsi di lettura','Segui la lettura di oggi e scopri cosa hai completato e cosa resta in ogni libro.','Apri la pagina di un libro e imposta il tempo quotidiano disponibile per iniziare un percorso chiaro.','Il piano è in pausa; la lettura quotidiana non si accumula']),
  nl: labels(['Leesreizen','Volg de lezing van vandaag en zie wat in elk boek voltooid is en nog resteert.','Open een boekpagina en stel uw beschikbare dagelijkse tijd in om een duidelijk traject te beginnen.','Het plan is gepauzeerd; dagelijkse lezing stapelt niet op']), sv: labels(['Läsresor','Följ dagens läsning och se vad som är klart och vad som återstår i varje bok.','Öppna en boksida och ange din tillgängliga tid per dag för att börja en tydlig resa.','Planen är pausad; den dagliga läsningen samlas inte på hög']), no: labels(['Lesereiser','Følg dagens lesing og se hva som er fullført og hva som gjenstår i hver bok.','Åpne en bokside og angi tilgjengelig tid per dag for å starte en tydelig reise.','Planen er satt på pause; daglig lesing hoper seg ikke opp']),
  pl: labels(['Ścieżki czytania','Śledź dzisiejszą lekturę i sprawdź, co ukończono, a co zostało w każdej książce.','Otwórz stronę książki i ustaw dostępny czas dzienny, aby rozpocząć przejrzystą ścieżkę.','Plan jest wstrzymany; dzienna lektura nie kumuluje się']), ro: labels(['Parcursuri de lectură','Urmărește lectura de azi și vezi ce ai terminat și ce a rămas din fiecare carte.','Deschide pagina unei cărți și stabilește timpul zilnic disponibil pentru a începe un parcurs clar.','Planul este întrerupt; lectura zilnică nu se acumulează']), bs: labels(['Putovanja kroz čitanje','Pratite današnje čitanje i vidite šta je završeno, a šta je ostalo u svakoj knjizi.','Otvorite stranicu knjige i odredite dnevno vrijeme da započnete jasan put.','Plan je pauziran; dnevno čitanje se ne gomila']),
  sq: labels(['Udhëtime leximi','Ndiq leximin e sotëm dhe shih çfarë përfundove e çfarë mbetet në çdo libër.','Hap faqen e një libri dhe cakto kohën ditore për të nisur një udhëtim të qartë.','Plani është pezulluar; leximi ditor nuk grumbullohet']), az: labels(['Oxu səyahətləri','Bugünkü oxunu izləyin və hər kitabda tamamlananla qalanı görün.','Kitab səhifəsini açın və aydın səyahətə başlamaq üçün gündəlik vaxtınızı təyin edin.','Plan dayandırılıb; gündəlik oxu yığılmır']), uz: labels(['O‘qish sayohatlari','Bugungi o‘qishni kuzating va har bir kitobda tugagan hamda qolgan qismlarni ko‘ring.','Kitob sahifasini oching va aniq sayohatni boshlash uchun kunlik vaqtingizni belgilang.','Reja to‘xtatilgan; kunlik o‘qish yig‘ilmaydi']),
  kk: labels(['Оқу сапарлары','Бүгінгі оқуды бақылап, әр кітапта аяқталған және қалған бөлікті көріңіз.','Кітап бетін ашып, айқын сапарды бастау үшін күнделікті уақытыңызды белгілеңіз.','Жоспар кідіртілді; күнделікті оқу жиналмайды']), zh: labels(['阅读旅程','跟进今日阅读，查看每本书已完成和剩余的内容。','打开图书页面并设定每日可用时间，以开始清晰的阅读旅程。','计划已暂停；每日阅读不会累积']), ja: labels(['読書の旅','今日の読書を追跡し、各書籍で完了した部分と残りを確認します。','書籍ページを開き、毎日使える時間を設定して明確な読書の旅を始めます。','計画は一時停止中です。日々の読書量は累積しません']), ko: labels(['독서 여정','오늘의 독서를 추적하고 각 책에서 완료한 부분과 남은 부분을 확인하세요.','책 페이지를 열고 매일 가능한 시간을 정해 명확한 여정을 시작하세요.','계획이 일시 중지되었습니다. 일일 독서량은 누적되지 않습니다']),
}
