/** غلاف بطاقة معلومات الكتاب؛ القيم الوصفية نفسها تبقى من المصدر. */
const keys=(panel:string,pending:string,close:string,card:string,edit:string)=>({'معلومات الكتاب ومعاينة PDF':panel,'تظهر بيانات الكتاب هنا بعد تحميله.':pending,'إغلاق بطاقة الكتاب':close,'بطاقة الكتاب':card,'تعديل الكتاب':edit})
export const REVIEWED_READER_BOOK_CARD_ALL_UI={
en:keys('Book details and PDF preview','Book details appear here after loading.','Close book card','Book card','Edit book'),fr:keys('Informations du livre et aperçu PDF','Les informations du livre apparaissent ici après chargement.','Fermer la fiche du livre','Fiche du livre','Modifier le livre'),
ug:keys('كىتاب ئۇچۇرى ۋە PDF ئالدىن كۆرۈش','كىتاب يۈكلەنگەندىن كېيىن ئۇچۇرى بۇ يەردە كۆرۈنىدۇ.','كىتاب كارتىسىنى تاقاش','كىتاب كارتىسى','كىتابنى تەھرىرلەش'),ckb:keys('زانیاریی کتێب و پێشبینینی PDF','دوای بارکردن زانیاریی کتێب لێرە دەردەکەوێت.','کارتی کتێب دابخە','کارتی کتێب','دەستکاری کتێب'),
ku:keys('Agahiyên pirtûkê û pêşdîtina PDF','Piştî barkirinê agahiyên pirtûkê li vir xuya dibin.','Karta pirtûkê bigire','Karta pirtûkê','Pirtûkê sererast bike'),tr:keys('Kitap bilgileri ve PDF önizlemesi','Kitap bilgileri yüklendikten sonra burada görünür.','Kitap kartını kapat','Kitap kartı','Kitabı düzenle'),
ur:keys('کتاب کی معلومات اور PDF پیش منظر','کتاب لوڈ ہونے کے بعد اس کی معلومات یہاں ظاہر ہوں گی۔','کتاب کارڈ بند کریں','کتاب کارڈ','کتاب میں ترمیم'),fa:keys('اطلاعات کتاب و پیش‌نمایش PDF','پس از بارگذاری، اطلاعات کتاب اینجا نمایش داده می‌شود.','بستن کارت کتاب','کارت کتاب','ویرایش کتاب'),
sw:keys('Maelezo ya kitabu na hakikisho la PDF','Maelezo ya kitabu huonekana hapa baada ya kupakiwa.','Funga kadi ya kitabu','Kadi ya kitabu','Hariri kitabu'),hi:keys('पुस्तक विवरण और PDF पूर्वावलोकन','लोड होने के बाद पुस्तक विवरण यहाँ दिखाई देगा।','पुस्तक कार्ड बंद करें','पुस्तक कार्ड','पुस्तक संपादित करें'),
hu:keys('Könyvadatok és PDF-előnézet','A könyv adatai betöltés után itt jelennek meg.','Könyvkártya bezárása','Könyvkártya','Könyv szerkesztése'),id:keys('Informasi buku dan pratinjau PDF','Informasi buku muncul di sini setelah dimuat.','Tutup kartu buku','Kartu buku','Edit buku'),
ms:keys('Maklumat buku dan pratonton PDF','Maklumat buku muncul di sini selepas dimuatkan.','Tutup kad buku','Kad buku','Sunting buku'),bn:keys('বইয়ের তথ্য ও PDF পূর্বরূপ','লোড হওয়ার পর বইয়ের তথ্য এখানে দেখা যাবে।','বইয়ের কার্ড বন্ধ করুন','বইয়ের কার্ড','বই সম্পাদনা করুন'),
ps:keys('د کتاب معلومات او PDF مخکتنه','د کتاب معلومات تر پورته کېدو وروسته دلته ښکاري.','د کتاب کارت وتړئ','د کتاب کارت','کتاب سمول'),so:keys('Macluumaadka buugga iyo hordhaca PDF','Macluumaadka buuggu halkan ayuu ka muuqdaa marka la raro.','Xir kaarka buugga','Kaarka buugga','Tafatir buugga'),
ha:keys('Bayanan littafi da samfotin PDF','Bayanan littafin zai bayyana a nan bayan lodawa.','Rufe katin littafi','Katin littafi','Gyara littafi'),ru:keys('Сведения о книге и просмотр PDF','Сведения о книге появятся здесь после загрузки.','Закрыть карточку книги','Карточка книги','Изменить книгу'),
uk:keys('Відомості про книгу та перегляд PDF','Відомості про книгу з’являться тут після завантаження.','Закрити картку книги','Картка книги','Редагувати книгу'),de:keys('Buchdetails und PDF-Vorschau','Buchdetails erscheinen hier nach dem Laden.','Buchkarte schließen','Buchkarte','Buch bearbeiten'),
es:keys('Información del libro y vista previa PDF','La información del libro aparecerá aquí tras cargarlo.','Cerrar ficha del libro','Ficha del libro','Editar libro'),pt:keys('Informações do livro e pré-visualização PDF','As informações do livro aparecem aqui após o carregamento.','Fechar cartão do livro','Cartão do livro','Editar livro'),
it:keys('Informazioni sul libro e anteprima PDF','Le informazioni sul libro appariranno qui dopo il caricamento.','Chiudi scheda del libro','Scheda del libro','Modifica libro'),nl:keys('Boekgegevens en PDF-voorbeeld','Boekgegevens verschijnen hier na het laden.','Boekkaart sluiten','Boekkaart','Boek bewerken'),
sv:keys('Bokinformation och PDF-förhandsvisning','Bokinformationen visas här efter inläsning.','Stäng bokkort','Bokkort','Redigera bok'),no:keys('Bokinformasjon og PDF-forhåndsvisning','Bokinformasjonen vises her etter lasting.','Lukk bokkort','Bokkort','Rediger bok'),
pl:keys('Informacje o książce i podgląd PDF','Informacje o książce pojawią się tutaj po wczytaniu.','Zamknij kartę książki','Karta książki','Edytuj książkę'),ro:keys('Informații despre carte și previzualizare PDF','Informațiile despre carte apar aici după încărcare.','Închide fișa cărții','Fișa cărții','Editează cartea'),
bs:keys('Podaci o knjizi i PDF pregled','Podaci o knjizi pojavit će se ovdje nakon učitavanja.','Zatvori karticu knjige','Kartica knjige','Uredi knjigu'),sq:keys('Informacioni i librit dhe pamja PDF','Informacioni i librit shfaqet këtu pas ngarkimit.','Mbyll kartën e librit','Karta e librit','Ndrysho librin'),
az:keys('Kitab məlumatları və PDF önizləməsi','Kitab məlumatları yükləndikdən sonra burada görünür.','Kitab kartını bağla','Kitab kartı','Kitabı redaktə et'),uz:keys('Kitob ma’lumotlari va PDF ko‘rinishi','Kitob ma’lumotlari yuklangach shu yerda ko‘rinadi.','Kitob kartini yopish','Kitob karti','Kitobni tahrirlash'),
kk:keys('Кітап ақпараты және PDF алдын ала қарау','Кітап ақпараты жүктелгеннен кейін осында көрінеді.','Кітап картасын жабу','Кітап картасы','Кітапты өңдеу'),zh:keys('图书信息和 PDF 预览','加载后，图书信息将显示在此处。','关闭图书卡片','图书卡片','编辑图书'),
ja:keys('本の情報と PDF プレビュー','読み込み後、本の情報がここに表示されます。','本のカードを閉じる','本のカード','本を編集'),ko:keys('책 정보 및 PDF 미리보기','불러온 뒤 책 정보가 여기에 표시됩니다.','책 카드 닫기','책 카드','책 편집'),
} as const
