const KEYS = ['أنت على هدف اليوم أو أمامه','أتممت الكتاب بحمد الله','الخطة مكتملة','اقرأ الآن'] as const
const labels = (values: readonly string[]): Readonly<Record<string, string>> => Object.fromEntries(KEYS.map((key, index) => [key, values[index]!]))

/** حالات إتمام خطة القراءة وإجراؤها؛ لا تشمل هوية الكتاب أو قيم التقدم. */
export const REVIEWED_READING_PLANS_COMPLETION_ALL_UI: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  en: labels(['You are on or ahead of today’s target','You completed the book, praise be to God','Plan completed','Read now']), fr: labels(['Vous avez atteint ou dépassé l’objectif du jour','Vous avez terminé le livre, louange à Dieu','Plan terminé','Lire maintenant']), ug: labels(['بۈگۈنكى نىشانغا يەتتىڭىز ياكى ئۇنىڭ ئالدىدىسىز','ئاللاھقا ھەمدۇسانا، كىتابنى تاماملىدىڭىز','پىلان تاماملاندى','ھازىر ئوقۇڭ']),
  sw: labels(['Umefikia au umepita lengo la leo','Umekamilisha kitabu, sifa njema ni za Mungu','Mpango umekamilika','Soma sasa']), hi: labels(['आप आज के लक्ष्य पर या उससे आगे हैं','ईश्वर की कृपा से आपने पुस्तक पूरी कर ली','योजना पूरी हुई','अभी पढ़ें']), hu: labels(['Elérte vagy megelőzte a mai célt','Istennek hála befejezte a könyvet','A terv elkészült','Olvasás most']),
  id: labels(['Anda mencapai atau melampaui target hari ini','Anda telah menyelesaikan buku, segala puji bagi Allah','Rencana selesai','Baca sekarang']), ms: labels(['Anda mencapai atau melepasi sasaran hari ini','Anda telah menamatkan buku, segala puji bagi Allah','Pelan selesai','Baca sekarang']), bn: labels(['আপনি আজকের লক্ষ্যে বা তার চেয়ে এগিয়ে আছেন','আল্লাহর প্রশংসা, আপনি বইটি শেষ করেছেন','পরিকল্পনা সম্পূর্ণ','এখন পড়ুন']),
  ps: labels(['تاسو د نن ورځې هدف ته رسېدلي یا ترې مخکې یاست','الحمد لله، تاسو کتاب بشپړ کړ','پلان بشپړ شو','اوس یې ولولئ']), so: labels(['Waxaad joogtaa ama ka horraysaa yoolka maanta','Mahad Ilaahay, buugga waad dhammaysay','Qorshuhu wuu dhammaaday','Hadda akhri']), ha: labels(['Kana kan burin yau ko ka wuce shi','Godiya ta tabbata ga Allah, ka kammala littafin','An kammala tsarin','Karanta yanzu']),
  ru: labels(['Вы достигли или опережаете цель на сегодня','Вы завершили книгу, хвала Богу','План завершён','Читать сейчас']), uk: labels(['Ви досягли або випереджаєте сьогоднішню ціль','Ви завершили книгу, хвала Богові','План завершено','Читати зараз']), de: labels(['Sie haben das heutige Ziel erreicht oder übertroffen','Sie haben das Buch abgeschlossen, Gott sei Dank','Plan abgeschlossen','Jetzt lesen']),
  es: labels(['Has alcanzado o superado el objetivo de hoy','Has terminado el libro, gracias a Dios','Plan completado','Leer ahora']), pt: labels(['Você atingiu ou superou a meta de hoje','Você concluiu o livro, graças a Deus','Plano concluído','Ler agora']), it: labels(['Hai raggiunto o superato l’obiettivo di oggi','Hai completato il libro, grazie a Dio','Piano completato','Leggi ora']),
  nl: labels(['U hebt het doel van vandaag bereikt of loopt voor','U hebt het boek voltooid, God zij dank','Plan voltooid','Nu lezen']), sv: labels(['Du har nått eller ligger före dagens mål','Du har slutfört boken, Gud vare lov','Planen är klar','Läs nu']), no: labels(['Du har nådd eller ligger foran dagens mål','Du har fullført boken, Gud være lovet','Planen er fullført','Les nå']),
  pl: labels(['Osiągnięto lub wyprzedzono dzisiejszy cel','Książka została ukończona, dzięki Bogu','Plan ukończony','Czytaj teraz']), ro: labels(['Ai atins sau ai depășit obiectivul de azi','Ai terminat cartea, slavă lui Dumnezeu','Plan finalizat','Citește acum']), bs: labels(['Dostigli ste ili premašili današnji cilj','Završili ste knjigu, hvala Bogu','Plan je završen','Čitaj sada']),
  sq: labels(['E ke arritur ose tejkaluar synimin e sotëm','E ke përfunduar librin, falë Zotit','Plani u përfundua','Lexo tani']), az: labels(['Bugünkü hədəfə çatmısınız və ya onu qabaqlamısınız','Allaha həmd olsun, kitabı bitirdiniz','Plan tamamlandı','İndi oxu']), uz: labels(['Bugungi maqsadga yetdingiz yoki undan oldindasiz','Allohga hamd, kitobni tugatdingiz','Reja tugallandi','Hozir o‘qing']),
  kk: labels(['Бүгінгі мақсатқа жеттіңіз немесе одан алдасыз','Аллаға шүкір, кітапты аяқтадыңыз','Жоспар аяқталды','Қазір оқу']), zh: labels(['您已达到或超过今日目标','感谢真主，您已读完本书','计划已完成','立即阅读']), ja: labels(['今日の目標に到達、または先行しています','神に感謝し、本を読み終えました','計画は完了しました','今すぐ読む']), ko: labels(['오늘 목표에 도달했거나 앞서 있습니다','하나님께 감사드리며 책을 완독했습니다','계획 완료','지금 읽기']),
}
