type SettingsDynamicTemplates = {
  archiveReady: (count: string) => string
  restoreReport: (imported: string, skipped: string, failed: string) => string
  inspectingFile: (fileName: string) => string
  mergeReport: (notes: string, highlights: string, shelves: string) => string
  accountUsage: (used: string, maximum: string) => string
  offlineOnline: (available: string) => string
  offlineUnavailable: (available: string, unavailable: string) => string
}

/** قوالب حالات الإعدادات الديناميكية؛ القيم وأسماء الملفات تبقى كما أدخلها المستخدم. */
export const REVIEWED_SETTINGS_DYNAMIC_TEMPLATES: Readonly<Record<string, SettingsDynamicTemplates>> = {
  en: { archiveReady:c=>`Archive of ${c} books is ready`,restoreReport:(a,b,c)=>`${a} restored · ${b} skipped · ${c} failed`,inspectingFile:f=>`Inspecting ${f}…`,mergeReport:(a,b,c)=>`Merge complete: ${a} notes, ${b} highlights, ${c} shelves.`,accountUsage:(a,b)=>`Usage: ${a} bytes of ${b} bytes`,offlineOnline:a=>`${a} local services ready; connection available.`,offlineUnavailable:(a,b)=>`${a} services ready; ${b} require a connection or device tool.`},
  fr: { archiveReady:c=>`Archive de ${c} livres prête`,restoreReport:(a,b,c)=>`${a} restaurés · ${b} ignorés · ${c} échoués`,inspectingFile:f=>`Analyse de ${f}…`,mergeReport:(a,b,c)=>`Fusion terminée : ${a} notes, ${b} surlignages, ${c} étagères.`,accountUsage:(a,b)=>`Utilisation : ${a} octets sur ${b}`,offlineOnline:a=>`${a} services locaux prêts ; connexion disponible.`,offlineUnavailable:(a,b)=>`${a} services prêts ; ${b} nécessitent une connexion ou un outil local.`},
  ug: { archiveReady:c=>`${c} كىتاب ئارخىپى تەييار`,restoreReport:(a,b,c)=>`${a} ئەسلىگە كەلدى · ${b} ئاتلاندى · ${c} مەغلۇپ`,inspectingFile:f=>`${f} تەكشۈرۈلۈۋاتىدۇ…`,mergeReport:(a,b,c)=>`بىرلەشتۈرۈش تامام: ${a} ئىزاھ، ${b} بەلگە، ${c} جازا.`,accountUsage:(a,b)=>`ئىشلىتىش: ${b} بايتتىن ${a} بايت`,offlineOnline:a=>`${a} يەرلىك مۇلازىمەت تەييار؛ ئۇلىنىش بار.`,offlineUnavailable:(a,b)=>`${a} مۇلازىمەت تەييار، ${b} ئۇلىنىش ياكى ئۈسكۈنە قورالىغا موھتاج.`},
  ckb: {
    archiveReady: count => `ئەرشیفی ${count} کتێب ئامادە کرا`,
    restoreReport: (imported, skipped, failed) => `${imported} گەڕێندرایەوە · ${skipped} تێپەڕێنرا · ${failed} شکستی هێنا`,
    inspectingFile: fileName => `پشکنینی ${fileName}…`,
    mergeReport: (notes, highlights, shelves) => `تێکەڵکردن تەواو بوو: ${notes} تێبینی، ${highlights} دیاریکردن، ${shelves} ڕەف.`,
    accountUsage: (used, maximum) => `بەکارهێنان: ${used} بایت لە ${maximum} بایت`,
    offlineOnline: available => `${available} خزمەتگوزاری ناوخۆیی ئامادەن؛ پەیوەندی بەردەستە.`,
    offlineUnavailable: (available, unavailable) => `${available} خزمەتگوزاری ئێستا ئامادەن و ${unavailable} پێویستیان بە پەیوەندی یان ئامرازی ئامێر هەیە.`,
  },
  ku: {
    archiveReady: count => `Arşîva ${count} pirtûkan amade bû`,
    restoreReport: (imported, skipped, failed) => `${imported} vegeriyan · ${skipped} derbas bûn · ${failed} bi ser neketin`,
    inspectingFile: fileName => `${fileName} tê kontrolkirin…`,
    mergeReport: (notes, highlights, shelves) => `Yek kirin qediya: ${notes} not, ${highlights} nîşankirin, ${shelves} ref.`,
    accountUsage: (used, maximum) => `Bikaranîn: ${used} bayt ji ${maximum} baytan`,
    offlineOnline: available => `${available} xizmetên herêmî amade ne; girêdan heye.`,
    offlineUnavailable: (available, unavailable) => `${available} xizmet niha amade ne û ${unavailable} girêdan an amûreke cihazê dixwazin.`,
  },
  tr: {
    archiveReady: count => `${count} kitaplık arşiv hazırlandı`,
    restoreReport: (imported, skipped, failed) => `${imported} geri yüklendi · ${skipped} atlandı · ${failed} başarısız`,
    inspectingFile: fileName => `${fileName} inceleniyor…`,
    mergeReport: (notes, highlights, shelves) => `Birleştirme tamamlandı: ${notes} not, ${highlights} vurgu, ${shelves} raf.`,
    accountUsage: (used, maximum) => `Kullanım: ${maximum} bayttan ${used} bayt`,
    offlineOnline: available => `${available} yerel hizmet hazır; bağlantı kullanılabilir.`,
    offlineUnavailable: (available, unavailable) => `${available} hizmet hazır, ${unavailable} hizmet bağlantı veya cihaz aracı gerektiriyor.`,
  },
  ur: {
    archiveReady: count => `${count} کتابوں کا آرکائیو تیار ہوگیا`,
    restoreReport: (imported, skipped, failed) => `${imported} بحال · ${skipped} چھوڑ دی گئیں · ${failed} ناکام`,
    inspectingFile: fileName => `${fileName} کی جانچ جاری ہے…`,
    mergeReport: (notes, highlights, shelves) => `انضمام مکمل: ${notes} نوٹس، ${highlights} نمایاں متن، ${shelves} شیلف۔`,
    accountUsage: (used, maximum) => `استعمال: ${maximum} بائٹ میں سے ${used} بائٹ`,
    offlineOnline: available => `${available} مقامی خدمات تیار ہیں؛ رابطہ دستیاب ہے۔`,
    offlineUnavailable: (available, unavailable) => `${available} خدمات تیار ہیں اور ${unavailable} کو رابطہ یا آلے کا ٹول درکار ہے۔`,
  },
  fa: {
    archiveReady: count => `آرشیو ${count} کتاب آماده شد`,
    restoreReport: (imported, skipped, failed) => `${imported} بازیابی شد · ${skipped} نادیده گرفته شد · ${failed} ناموفق`,
    inspectingFile: fileName => `در حال بررسی ${fileName}…`,
    mergeReport: (notes, highlights, shelves) => `ادغام انجام شد: ${notes} یادداشت، ${highlights} برجسته‌سازی، ${shelves} قفسه.`,
    accountUsage: (used, maximum) => `مصرف: ${used} بایت از ${maximum} بایت`,
    offlineOnline: available => `${available} خدمت محلی آماده است؛ اتصال برقرار است.`,
    offlineUnavailable: (available, unavailable) => `${available} خدمت آماده است و ${unavailable} مورد به اتصال یا ابزار دستگاه نیاز دارد.`,
  },
  sw: { archiveReady:c=>`Kumbukumbu ya vitabu ${c} iko tayari`,restoreReport:(a,b,c)=>`${a} vimerejeshwa · ${b} vimerukwa · ${c} vimeshindwa`,inspectingFile:f=>`Inakagua ${f}…`,mergeReport:(a,b,c)=>`Uunganishaji umekamilika: madokezo ${a}, uangaziaji ${b}, rafu ${c}.`,accountUsage:(a,b)=>`Matumizi: baiti ${a} kati ya ${b}`,offlineOnline:a=>`Huduma ${a} za ndani ziko tayari; muunganisho upo.`,offlineUnavailable:(a,b)=>`Huduma ${a} ziko tayari; ${b} zinahitaji muunganisho au zana ya kifaa.`},
  hi: { archiveReady:c=>`${c} पुस्तकों का संग्रह तैयार है`,restoreReport:(a,b,c)=>`${a} पुनर्स्थापित · ${b} छोड़े · ${c} विफल`,inspectingFile:f=>`${f} की जाँच हो रही है…`,mergeReport:(a,b,c)=>`विलय पूरा: ${a} नोट, ${b} हाइलाइट, ${c} शेल्फ़।`,accountUsage:(a,b)=>`उपयोग: ${b} में से ${a} बाइट`,offlineOnline:a=>`${a} स्थानीय सेवाएँ तैयार; कनेक्शन उपलब्ध।`,offlineUnavailable:(a,b)=>`${a} सेवाएँ तैयार; ${b} को कनेक्शन या डिवाइस टूल चाहिए।`},
  hu: { archiveReady:c=>`${c} könyv archívuma elkészült`,restoreReport:(a,b,c)=>`${a} visszaállítva · ${b} kihagyva · ${c} sikertelen`,inspectingFile:f=>`${f} ellenőrzése…`,mergeReport:(a,b,c)=>`Egyesítés kész: ${a} jegyzet, ${b} kiemelés, ${c} polc.`,accountUsage:(a,b)=>`Használat: ${a} bájt / ${b} bájt`,offlineOnline:a=>`${a} helyi szolgáltatás kész; van kapcsolat.`,offlineUnavailable:(a,b)=>`${a} szolgáltatás kész; ${b} kapcsolódást vagy eszközt igényel.`},
  id: { archiveReady:c=>`Arsip ${c} buku siap`,restoreReport:(a,b,c)=>`${a} dipulihkan · ${b} dilewati · ${c} gagal`,inspectingFile:f=>`Memeriksa ${f}…`,mergeReport:(a,b,c)=>`Penggabungan selesai: ${a} catatan, ${b} sorotan, ${c} rak.`,accountUsage:(a,b)=>`Penggunaan: ${a} bita dari ${b} bita`,offlineOnline:a=>`${a} layanan lokal siap; koneksi tersedia.`,offlineUnavailable:(a,b)=>`${a} layanan siap; ${b} memerlukan koneksi atau alat perangkat.`},
  ms: { archiveReady:c=>`Arkib ${c} buku sedia`,restoreReport:(a,b,c)=>`${a} dipulihkan · ${b} dilangkau · ${c} gagal`,inspectingFile:f=>`Memeriksa ${f}…`,mergeReport:(a,b,c)=>`Gabungan selesai: ${a} nota, ${b} sorotan, ${c} rak.`,accountUsage:(a,b)=>`Penggunaan: ${a} bait daripada ${b} bait`,offlineOnline:a=>`${a} perkhidmatan setempat sedia; sambungan tersedia.`,offlineUnavailable:(a,b)=>`${a} perkhidmatan sedia; ${b} memerlukan sambungan atau alat peranti.`},
  bn: { archiveReady:c=>`${c}টি বইয়ের আর্কাইভ প্রস্তুত`,restoreReport:(a,b,c)=>`${a} পুনরুদ্ধার · ${b} এড়ানো · ${c} ব্যর্থ`,inspectingFile:f=>`${f} পরীক্ষা করা হচ্ছে…`,mergeReport:(a,b,c)=>`একত্রীকরণ সম্পন্ন: ${a} নোট, ${b} হাইলাইট, ${c} তাক।`,accountUsage:(a,b)=>`ব্যবহার: ${b} বাইটের মধ্যে ${a} বাইট`,offlineOnline:a=>`${a}টি স্থানীয় সেবা প্রস্তুত; সংযোগ আছে।`,offlineUnavailable:(a,b)=>`${a}টি সেবা প্রস্তুত; ${b}টির সংযোগ বা ডিভাইস টুল দরকার।`},
  ps: { archiveReady:c=>`د ${c} کتابونو زېرمه چمتو ده`,restoreReport:(a,b,c)=>`${a} بېرته راوړل · ${b} تېر شول · ${c} ناکام`,inspectingFile:f=>`${f} کتل کېږي…`,mergeReport:(a,b,c)=>`یوځای کول بشپړ شول: ${a} یادښتونه، ${b} روښانه برخې، ${c} المارۍ.`,accountUsage:(a,b)=>`کارونه: له ${b} بایټو ${a} بایټه`,offlineOnline:a=>`${a} سیمه‌ییز خدمتونه چمتو دي؛ اړیکه شته.`,offlineUnavailable:(a,b)=>`${a} خدمتونه چمتو دي؛ ${b} اړیکې یا د وسیلې اوزار ته اړتیا لري.`},
  so: { archiveReady:c=>`Kaydka ${c} buug waa diyaar`,restoreReport:(a,b,c)=>`${a} la soo celiyey · ${b} laga booday · ${c} fashilmay`,inspectingFile:f=>`La baarayo ${f}…`,mergeReport:(a,b,c)=>`Isku-darka waa dhammaaday: ${a} qoraal, ${b} calaamad, ${c} shelf.`,accountUsage:(a,b)=>`Isticmaal: ${a} bayt oo ka mid ah ${b}`,offlineOnline:a=>`${a} adeeg oo maxalli ah waa diyaar; xiriirku wuu jiraa.`,offlineUnavailable:(a,b)=>`${a} adeeg waa diyaar; ${b} waxay u baahan yihiin xiriir ama qalab.`},
  ha: { archiveReady:c=>`Rumbun littattafai ${c} ya shirya`,restoreReport:(a,b,c)=>`${a} an dawo · ${b} an tsallake · ${c} sun gaza`,inspectingFile:f=>`Ana duba ${f}…`,mergeReport:(a,b,c)=>`Haɗawa ta cika: bayanai ${a}, haskakawa ${b}, shiryayyu ${c}.`,accountUsage:(a,b)=>`Amfani: baiti ${a} cikin ${b}`,offlineOnline:a=>`Ayyukan gida ${a} sun shirya; haɗi yana nan.`,offlineUnavailable:(a,b)=>`Ayyuka ${a} sun shirya; ${b} suna buƙatar haɗi ko kayan na’ura.`},
  ru: { archiveReady:c=>`Архив из ${c} книг готов`,restoreReport:(a,b,c)=>`${a} восстановлено · ${b} пропущено · ${c} с ошибкой`,inspectingFile:f=>`Проверка ${f}…`,mergeReport:(a,b,c)=>`Объединение завершено: ${a} заметок, ${b} выделений, ${c} полок.`,accountUsage:(a,b)=>`Использовано: ${a} из ${b} байт`,offlineOnline:a=>`${a} локальных служб готовы; подключение доступно.`,offlineUnavailable:(a,b)=>`${a} служб готовы; ${b} требуют подключения или средства устройства.`},
  uk: { archiveReady:c=>`Архів із ${c} книг готовий`,restoreReport:(a,b,c)=>`${a} відновлено · ${b} пропущено · ${c} з помилкою`,inspectingFile:f=>`Перевірка ${f}…`,mergeReport:(a,b,c)=>`Об’єднання завершено: ${a} нотаток, ${b} виділень, ${c} полиць.`,accountUsage:(a,b)=>`Використано: ${a} із ${b} байт`,offlineOnline:a=>`${a} локальних служб готові; з’єднання доступне.`,offlineUnavailable:(a,b)=>`${a} служб готові; ${b} потребують з’єднання або засобу пристрою.`},
  de: { archiveReady:c=>`Archiv mit ${c} Büchern ist bereit`,restoreReport:(a,b,c)=>`${a} wiederhergestellt · ${b} übersprungen · ${c} fehlgeschlagen`,inspectingFile:f=>`${f} wird geprüft…`,mergeReport:(a,b,c)=>`Zusammenführung abgeschlossen: ${a} Notizen, ${b} Markierungen, ${c} Regale.`,accountUsage:(a,b)=>`Nutzung: ${a} von ${b} Byte`,offlineOnline:a=>`${a} lokale Dienste bereit; Verbindung verfügbar.`,offlineUnavailable:(a,b)=>`${a} Dienste bereit; ${b} benötigen Verbindung oder Gerätewerkzeug.`},
  es: { archiveReady:c=>`Archivo de ${c} libros preparado`,restoreReport:(a,b,c)=>`${a} restaurados · ${b} omitidos · ${c} fallidos`,inspectingFile:f=>`Inspeccionando ${f}…`,mergeReport:(a,b,c)=>`Fusión completada: ${a} notas, ${b} resaltados, ${c} estanterías.`,accountUsage:(a,b)=>`Uso: ${a} de ${b} bytes`,offlineOnline:a=>`${a} servicios locales listos; conexión disponible.`,offlineUnavailable:(a,b)=>`${a} servicios listos; ${b} requieren conexión o herramienta del dispositivo.`},
  pt: { archiveReady:c=>`Arquivo de ${c} livros preparado`,restoreReport:(a,b,c)=>`${a} restaurados · ${b} ignorados · ${c} falharam`,inspectingFile:f=>`A inspecionar ${f}…`,mergeReport:(a,b,c)=>`Fusão concluída: ${a} notas, ${b} destaques, ${c} estantes.`,accountUsage:(a,b)=>`Utilização: ${a} de ${b} bytes`,offlineOnline:a=>`${a} serviços locais prontos; ligação disponível.`,offlineUnavailable:(a,b)=>`${a} serviços prontos; ${b} requerem ligação ou ferramenta do dispositivo.`},
  it: { archiveReady:c=>`Archivio di ${c} libri pronto`,restoreReport:(a,b,c)=>`${a} ripristinati · ${b} ignorati · ${c} non riusciti`,inspectingFile:f=>`Analisi di ${f}…`,mergeReport:(a,b,c)=>`Unione completata: ${a} note, ${b} evidenziazioni, ${c} scaffali.`,accountUsage:(a,b)=>`Utilizzo: ${a} di ${b} byte`,offlineOnline:a=>`${a} servizi locali pronti; connessione disponibile.`,offlineUnavailable:(a,b)=>`${a} servizi pronti; ${b} richiedono connessione o strumento del dispositivo.`},
  nl: { archiveReady:c=>`Archief van ${c} boeken is gereed`,restoreReport:(a,b,c)=>`${a} hersteld · ${b} overgeslagen · ${c} mislukt`,inspectingFile:f=>`${f} controleren…`,mergeReport:(a,b,c)=>`Samenvoegen voltooid: ${a} notities, ${b} markeringen, ${c} planken.`,accountUsage:(a,b)=>`Gebruik: ${a} van ${b} bytes`,offlineOnline:a=>`${a} lokale diensten gereed; verbinding beschikbaar.`,offlineUnavailable:(a,b)=>`${a} diensten gereed; ${b} vereisen verbinding of apparaathulpmiddel.`},
  sv: { archiveReady:c=>`Arkiv med ${c} böcker är klart`,restoreReport:(a,b,c)=>`${a} återställda · ${b} överhoppade · ${c} misslyckades`,inspectingFile:f=>`Kontrollerar ${f}…`,mergeReport:(a,b,c)=>`Sammanslagning klar: ${a} anteckningar, ${b} markeringar, ${c} hyllor.`,accountUsage:(a,b)=>`Användning: ${a} av ${b} byte`,offlineOnline:a=>`${a} lokala tjänster klara; anslutning tillgänglig.`,offlineUnavailable:(a,b)=>`${a} tjänster klara; ${b} kräver anslutning eller enhetsverktyg.`},
  no: { archiveReady:c=>`Arkiv med ${c} bøker er klart`,restoreReport:(a,b,c)=>`${a} gjenopprettet · ${b} hoppet over · ${c} mislyktes`,inspectingFile:f=>`Kontrollerer ${f}…`,mergeReport:(a,b,c)=>`Sammenslåing fullført: ${a} notater, ${b} markeringer, ${c} hyller.`,accountUsage:(a,b)=>`Bruk: ${a} av ${b} byte`,offlineOnline:a=>`${a} lokale tjenester klare; tilkobling tilgjengelig.`,offlineUnavailable:(a,b)=>`${a} tjenester klare; ${b} krever tilkobling eller enhetsverktøy.`},
  pl: { archiveReady:c=>`Archiwum ${c} książek jest gotowe`,restoreReport:(a,b,c)=>`${a} przywrócono · ${b} pominięto · ${c} nie powiodło się`,inspectingFile:f=>`Sprawdzanie ${f}…`,mergeReport:(a,b,c)=>`Scalanie zakończone: ${a} notatek, ${b} wyróżnień, ${c} półek.`,accountUsage:(a,b)=>`Użycie: ${a} z ${b} bajtów`,offlineOnline:a=>`${a} usług lokalnych gotowych; połączenie dostępne.`,offlineUnavailable:(a,b)=>`${a} usług gotowych; ${b} wymaga połączenia lub narzędzia urządzenia.`},
  ro: { archiveReady:c=>`Arhiva cu ${c} cărți este gata`,restoreReport:(a,b,c)=>`${a} restaurate · ${b} omise · ${c} eșuate`,inspectingFile:f=>`Se verifică ${f}…`,mergeReport:(a,b,c)=>`Combinare finalizată: ${a} notițe, ${b} evidențieri, ${c} rafturi.`,accountUsage:(a,b)=>`Utilizare: ${a} din ${b} octeți`,offlineOnline:a=>`${a} servicii locale gata; conexiune disponibilă.`,offlineUnavailable:(a,b)=>`${a} servicii gata; ${b} necesită conexiune sau instrument al dispozitivului.`},
  bs: { archiveReady:c=>`Arhiva od ${c} knjiga je spremna`,restoreReport:(a,b,c)=>`${a} vraćeno · ${b} preskočeno · ${c} neuspjelo`,inspectingFile:f=>`Provjera ${f}…`,mergeReport:(a,b,c)=>`Spajanje završeno: ${a} bilješki, ${b} isticanja, ${c} polica.`,accountUsage:(a,b)=>`Upotreba: ${a} od ${b} bajtova`,offlineOnline:a=>`${a} lokalnih usluga spremno; veza dostupna.`,offlineUnavailable:(a,b)=>`${a} usluga spremno; ${b} zahtijeva vezu ili alat uređaja.`},
  sq: { archiveReady:c=>`Arkivi me ${c} libra është gati`,restoreReport:(a,b,c)=>`${a} u rikthyen · ${b} u anashkaluan · ${c} dështuan`,inspectingFile:f=>`Po kontrollohet ${f}…`,mergeReport:(a,b,c)=>`Bashkimi përfundoi: ${a} shënime, ${b} theksime, ${c} rafte.`,accountUsage:(a,b)=>`Përdorimi: ${a} nga ${b} bajte`,offlineOnline:a=>`${a} shërbime lokale gati; lidhja është e disponueshme.`,offlineUnavailable:(a,b)=>`${a} shërbime gati; ${b} kërkojnë lidhje ose mjet pajisjeje.`},
  az: { archiveReady:c=>`${c} kitablıq arxiv hazırdır`,restoreReport:(a,b,c)=>`${a} bərpa edildi · ${b} ötürüldü · ${c} alınmadı`,inspectingFile:f=>`${f} yoxlanılır…`,mergeReport:(a,b,c)=>`Birləşdirmə tamamlandı: ${a} qeyd, ${b} vurğulama, ${c} rəf.`,accountUsage:(a,b)=>`İstifadə: ${b} baytdan ${a} bayt`,offlineOnline:a=>`${a} yerli xidmət hazırdır; bağlantı mövcuddur.`,offlineUnavailable:(a,b)=>`${a} xidmət hazırdır; ${b} bağlantı və ya cihaz aləti tələb edir.`},
  uz: { archiveReady:c=>`${c} ta kitob arxivi tayyor`,restoreReport:(a,b,c)=>`${a} tiklandi · ${b} o‘tkazildi · ${c} muvaffaqiyatsiz`,inspectingFile:f=>`${f} tekshirilmoqda…`,mergeReport:(a,b,c)=>`Birlashtirish tugadi: ${a} qayd, ${b} belgilash, ${c} javon.`,accountUsage:(a,b)=>`Foydalanish: ${b} baytdan ${a} bayt`,offlineOnline:a=>`${a} mahalliy xizmat tayyor; ulanish mavjud.`,offlineUnavailable:(a,b)=>`${a} xizmat tayyor; ${b} ulanish yoki qurilma vositasini talab qiladi.`},
  kk: { archiveReady:c=>`${c} кітап мұрағаты дайын`,restoreReport:(a,b,c)=>`${a} қалпына келді · ${b} өткізіліп жіберілді · ${c} сәтсіз`,inspectingFile:f=>`${f} тексерілуде…`,mergeReport:(a,b,c)=>`Біріктіру аяқталды: ${a} жазба, ${b} ерекшелеу, ${c} сөре.`,accountUsage:(a,b)=>`Пайдалану: ${b} байттың ${a} байты`,offlineOnline:a=>`${a} жергілікті қызмет дайын; байланыс бар.`,offlineUnavailable:(a,b)=>`${a} қызмет дайын; ${b} байланыс не құрылғы құралын қажет етеді.`},
  zh: { archiveReady:c=>`${c} 本书的归档已就绪`,restoreReport:(a,b,c)=>`已恢复 ${a} · 已跳过 ${b} · 失败 ${c}`,inspectingFile:f=>`正在检查 ${f}…`,mergeReport:(a,b,c)=>`合并完成：${a} 条笔记、${b} 条高亮、${c} 个书架。`,accountUsage:(a,b)=>`用量：${a} / ${b} 字节`,offlineOnline:a=>`${a} 项本地服务已就绪；连接可用。`,offlineUnavailable:(a,b)=>`${a} 项服务已就绪；${b} 项需要连接或设备工具。`},
  ja: { archiveReady:c=>`${c} 冊のアーカイブを準備しました`,restoreReport:(a,b,c)=>`${a} 件復元 · ${b} 件スキップ · ${c} 件失敗`,inspectingFile:f=>`${f} を確認中…`,mergeReport:(a,b,c)=>`統合完了: メモ ${a} 件、ハイライト ${b} 件、本棚 ${c} 件。`,accountUsage:(a,b)=>`使用量: ${b} バイト中 ${a} バイト`,offlineOnline:a=>`${a} 件のローカルサービスが準備完了。接続可能です。`,offlineUnavailable:(a,b)=>`${a} 件のサービスが準備完了。${b} 件は接続または端末ツールが必要です。`},
  ko: { archiveReady:c=>`책 ${c}권의 보관 파일 준비 완료`,restoreReport:(a,b,c)=>`${a}개 복원 · ${b}개 건너뜀 · ${c}개 실패`,inspectingFile:f=>`${f} 검사 중…`,mergeReport:(a,b,c)=>`병합 완료: 메모 ${a}개, 강조 ${b}개, 서가 ${c}개.`,accountUsage:(a,b)=>`사용량: ${b}바이트 중 ${a}바이트`,offlineOnline:a=>`로컬 서비스 ${a}개 준비됨. 연결 사용 가능.`,offlineUnavailable:(a,b)=>`서비스 ${a}개 준비됨. ${b}개는 연결 또는 기기 도구가 필요함.`},
}
