import{describe,expect,it,vi}from"vitest";import{QuarantineResolutionAuthority,type QuarantineResolutionStore}from"./quarantine.js";
const record={quarantineId:"q",uploadId:"u",bookId:"b",operationId:"op",deviceId:"d",reasonCode:"external_relationship",status:"pending"as const,recordVersion:0,createdAt:"now",resolutionReason:null};
function store(overrides:Partial<QuarantineResolutionStore>={}):QuarantineResolutionStore{return{list:async()=>[record],detail:async id=>id==="q"?record:null,lease:async()=>true,findResolution:async()=>null,resolve:async()=>true,...overrides}}
describe("quarantine resolution authority",()=>{
 it("bounds listing and hides absent records",async()=>{const list=vi.fn(async()=>[record]),a=new QuarantineResolutionAuthority(store({list}));await a.list(999);expect(list).toHaveBeenCalledWith(100);await expect(a.detail("other")).rejects.toMatchObject({status:404})});
 it("leases with CAS then resolves with explicit admin and operation id",async()=>{const lease=vi.fn(async()=>true),resolve=vi.fn(async()=>true),a=new QuarantineResolutionAuthority(store({lease,resolve}),()=>1000);expect(await a.lease("q","lease",1000,0)).toMatchObject({recordVersion:1});const input={quarantineId:"q",resolutionId:"resolution",leaseId:"lease",decision:"allow"as const,reason:"reviewed",expectedRecordVersion:1};expect(await a.resolve({adminId:"admin"},input)).toMatchObject({status:"allowed",recordVersion:2});expect(resolve).toHaveBeenCalledWith({...input,adminId:"admin"})});
 it("returns an idempotent replay without a second mutation",async()=>{const resolve=vi.fn(async()=>true),a=new QuarantineResolutionAuthority(store({findResolution:async()=>({status:"rejected",recordVersion:4}),resolve}));await expect(a.resolve({adminId:"admin"},{quarantineId:"q",resolutionId:"same",leaseId:"lease",decision:"reject",reason:"unsafe",expectedRecordVersion:3})).resolves.toMatchObject({status:"rejected",recordVersion:4});expect(resolve).not.toHaveBeenCalled()});
 it("rejects lost leases/CAS and bounded notes",async()=>{const a=new QuarantineResolutionAuthority(store({lease:async()=>false,resolve:async()=>false}));await expect(a.lease("q","lease",1000,0)).rejects.toMatchObject({status:409});await expect(a.resolve({adminId:"admin"},{quarantineId:"q",resolutionId:"r",leaseId:"l",decision:"reject",reason:"x".repeat(501),expectedRecordVersion:1})).rejects.toMatchObject({status:400})});
});
