CREATE TABLE subject_categories(category_id TEXT PRIMARY KEY,name TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,updated_by TEXT REFERENCES accounts(subject),updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subject_category_aliases(alias TEXT PRIMARY KEY,category_id TEXT NOT NULL REFERENCES subject_categories(category_id));
CREATE INDEX subject_alias_category ON subject_category_aliases(category_id);
INSERT INTO subject_categories(category_id,name) VALUES('subject:1','العقيدة');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('العقيدة','subject:1');
INSERT INTO subject_categories(category_id,name) VALUES('subject:2','الفرق والردود');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفرق والردود','subject:2');
INSERT INTO subject_categories(category_id,name) VALUES('subject:3','التفسير');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('التفسير','subject:3');
INSERT INTO subject_categories(category_id,name) VALUES('subject:4','علوم القرآن وأصول التفسير');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('علوم القرآن وأصول التفسير','subject:4');
INSERT INTO subject_categories(category_id,name) VALUES('subject:5','التجويد والقراءات');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('التجويد والقراءات','subject:5');
INSERT INTO subject_categories(category_id,name) VALUES('subject:6','كتب السنة');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('كتب السنة','subject:6');
INSERT INTO subject_categories(category_id,name) VALUES('subject:7','شروح الحديث');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('شروح الحديث','subject:7');
INSERT INTO subject_categories(category_id,name) VALUES('subject:8','التخريج والأطراف');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('التخريج والأطراف','subject:8');
INSERT INTO subject_categories(category_id,name) VALUES('subject:9','العلل والسؤلات الحديثية');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('العلل والسؤلات الحديثية','subject:9');
INSERT INTO subject_categories(category_id,name) VALUES('subject:10','علوم الحديث');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('علوم الحديث','subject:10');
INSERT INTO subject_categories(category_id,name) VALUES('subject:11','أصول الفقه');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('أصول الفقه','subject:11');
INSERT INTO subject_categories(category_id,name) VALUES('subject:12','علوم الفقه والقواعد الفقهية');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('علوم الفقه والقواعد الفقهية','subject:12');
INSERT INTO subject_categories(category_id,name) VALUES('subject:13','المنطق');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('المنطق','subject:13');
INSERT INTO subject_categories(category_id,name) VALUES('subject:14','الفقه الحنفي');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفقه الحنفي','subject:14');
INSERT INTO subject_categories(category_id,name) VALUES('subject:15','الفقه المالكي');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفقه المالكي','subject:15');
INSERT INTO subject_categories(category_id,name) VALUES('subject:16','الفقه الشافعي');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفقه الشافعي','subject:16');
INSERT INTO subject_categories(category_id,name) VALUES('subject:17','الفقه الحنبلي');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفقه الحنبلي','subject:17');
INSERT INTO subject_categories(category_id,name) VALUES('subject:18','الفقه العام');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفقه العام','subject:18');
INSERT INTO subject_categories(category_id,name) VALUES('subject:19','مسائل فقهية');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('مسائل فقهية','subject:19');
INSERT INTO subject_categories(category_id,name) VALUES('subject:20','السياسة الشرعية والقضاء');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('السياسة الشرعية والقضاء','subject:20');
INSERT INTO subject_categories(category_id,name) VALUES('subject:21','الفرائض والوصايا');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفرائض والوصايا','subject:21');
INSERT INTO subject_categories(category_id,name) VALUES('subject:22','الفتاوى');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الفتاوى','subject:22');
INSERT INTO subject_categories(category_id,name) VALUES('subject:23','الرقائق والآداب والأذكار');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الرقائق والآداب والأذكار','subject:23');
INSERT INTO subject_categories(category_id,name) VALUES('subject:24','السيرة النبوية');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('السيرة النبوية','subject:24');
INSERT INTO subject_categories(category_id,name) VALUES('subject:25','التاريخ');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('التاريخ','subject:25');
INSERT INTO subject_categories(category_id,name) VALUES('subject:26','التراجم والطبقات');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('التراجم والطبقات','subject:26');
INSERT INTO subject_categories(category_id,name) VALUES('subject:27','الأنساب');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الأنساب','subject:27');
INSERT INTO subject_categories(category_id,name) VALUES('subject:28','البلدان والرحلات');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('البلدان والرحلات','subject:28');
INSERT INTO subject_categories(category_id,name) VALUES('subject:29','كتب اللغة');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('كتب اللغة','subject:29');
INSERT INTO subject_categories(category_id,name) VALUES('subject:30','الغريب والمعاجم');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الغريب والمعاجم','subject:30');
INSERT INTO subject_categories(category_id,name) VALUES('subject:31','النحو والصرف');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('النحو والصرف','subject:31');
INSERT INTO subject_categories(category_id,name) VALUES('subject:32','الأدب');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الأدب','subject:32');
INSERT INTO subject_categories(category_id,name) VALUES('subject:33','العروض والقوافي');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('العروض والقوافي','subject:33');
INSERT INTO subject_categories(category_id,name) VALUES('subject:34','الشعر ودواوينه');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الشعر ودواوينه','subject:34');
INSERT INTO subject_categories(category_id,name) VALUES('subject:35','البلاغة');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('البلاغة','subject:35');
INSERT INTO subject_categories(category_id,name) VALUES('subject:36','الجوامع');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الجوامع','subject:36');
INSERT INTO subject_categories(category_id,name) VALUES('subject:37','فهارس الكتب والأدلة');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('فهارس الكتب والأدلة','subject:37');
INSERT INTO subject_categories(category_id,name) VALUES('subject:38','الطب');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('الطب','subject:38');
INSERT INTO subject_categories(category_id,name) VALUES('subject:39','كتب عامة');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('كتب عامة','subject:39');
INSERT INTO subject_categories(category_id,name) VALUES('subject:40','علوم أخرى');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('علوم أخرى','subject:40');
INSERT INTO subject_category_aliases(alias,category_id) VALUES('التفاسير','subject:3');
CREATE TRIGGER subject_category_alias_insert AFTER INSERT ON subject_categories WHEN NEW.updated_by IS NOT NULL BEGIN
 INSERT INTO subject_category_aliases(alias,category_id) VALUES(NEW.name,NEW.category_id);
 INSERT INTO oversight_events(entity_type,entity_id,actor_subject,action,before_json,after_json,before_revision,revision) VALUES('subject-category',NEW.category_id,NEW.updated_by,'create',NULL,json_object('name',NEW.name),0,NEW.revision);
 SELECT (CASE WHEN NOT EXISTS(SELECT 1 FROM oversight_events WHERE entity_type='subject-category' AND entity_id=NEW.category_id AND revision=NEW.revision AND actor_subject=NEW.updated_by AND after_json=json_object('name',NEW.name)) OR NOT EXISTS(SELECT 1 FROM subject_category_aliases WHERE alias=NEW.name AND category_id=NEW.category_id) THEN RAISE(ABORT,'category_audit_missing') END);
END;
CREATE TRIGGER subject_category_alias_update AFTER UPDATE ON subject_categories WHEN NEW.revision<>OLD.revision BEGIN
 SELECT (CASE WHEN EXISTS(SELECT 1 FROM subject_category_aliases WHERE alias=NEW.name AND category_id<>NEW.category_id) THEN RAISE(ABORT,'category_name_reserved') END);
 INSERT OR IGNORE INTO subject_category_aliases(alias,category_id) VALUES(NEW.name,NEW.category_id);
 INSERT INTO oversight_events(entity_type,entity_id,actor_subject,action,before_json,after_json,before_revision,revision) VALUES('subject-category',NEW.category_id,NEW.updated_by,'update',json_object('name',OLD.name),json_object('name',NEW.name),OLD.revision,NEW.revision);
 SELECT (CASE WHEN NOT EXISTS(SELECT 1 FROM oversight_events WHERE entity_type='subject-category' AND entity_id=NEW.category_id AND revision=NEW.revision AND actor_subject=NEW.updated_by AND after_json=json_object('name',NEW.name)) OR NOT EXISTS(SELECT 1 FROM subject_category_aliases WHERE alias=NEW.name AND category_id=NEW.category_id) THEN RAISE(ABORT,'category_audit_missing') END);
END;

