import { createServer, type Server } from "node:http";import { once } from "node:events";import { afterEach,describe,expect,it } from "vitest";import { createPdfServiceBuilder, PdfServiceBuildError } from "./pdf-service-builder.js";import type { BuildJob } from "../../source-sync-server/src/index.js";
const servers:Server[]=[];afterEach(async()=>Promise.all(servers.splice(0).map(async s=>{s.close();await once(s,"close")})));
async function endpoint(handler:Parameters<typeof createServer>[0]){const s=createServer(handler);servers.push(s);s.listen(0,"127.0.0.1");await once(s,"listening");const a=s.address();if(!a||typeof a==="string")throw Error();return `http://127.0.0.1:${a.port}/convert`;}
function job():BuildJob{return{jobId:"j",buildId:"b",bookId:"book",sourceRevisionId:"rev",kind:"pdf",state:"in-flight",attempt:1,nextAttemptAtMs:0,leaseId:"l",leaseUntilMs:1,recordVersion:1,lastError:null}}
function builder(url:string,timeoutMs=500){const writes:any[]=[];return{writes,b:createPdfServiceBuilder({readRevisionBytes:async()=>new Uint8Array([0x50,0x4b,1])},{putImmutable:async x=>{writes.push(x)}},{endpoint:url,accessToken:async()=>"token",timeoutMs,maxSourceBytes:100,maxPdfBytes:100,engineVersion:"fallback"})}}
describe("PDF service builder",()=>{
 it("sends multipart auth and stores a validated immutable PDF",async()=>{const url=await endpoint((req,res)=>{expect(req.headers.authorization).toBe("Bearer token");expect(req.headers["content-type"]).toMatch(/^multipart\/form-data; boundary=/);res.writeHead(200,{"content-type":"application/pdf","x-pdf-engine":"word-com"});res.end("%PDF-1.7\n")});const {b,writes}=builder(url);const a=await b.build({job:job()});expect(a).toMatchObject({kind:"pdf",engineVersion:"word-com",fingerprint:{byteLength:9}});expect(writes[0].objectKey).toMatch(/\/pdf\/[0-9a-f]{64}\.pdf$/)});
 it("classifies 500 as retryable",async()=>{const {b}=builder(await endpoint((_q,r)=>{r.writeHead(500);r.end()}));await expect(b.build({job:job()})).rejects.toMatchObject({code:"pdf_http_500",retryable:true})});
 it("rejects invalid content permanently",async()=>{const {b}=builder(await endpoint((_q,r)=>{r.writeHead(200,{"content-type":"application/pdf"});r.end("not-pdf")}));await expect(b.build({job:job()})).rejects.toMatchObject({code:"invalid_pdf_signature",retryable:false})});
 it("aborts timeout as retryable",async()=>{const {b}=builder(await endpoint(()=>{}),20);const error=await b.build({job:job()}).catch(e=>e);expect(error).toBeInstanceOf(PdfServiceBuildError);expect(error).toMatchObject({code:"pdf_timeout",retryable:true})});
});
