import type { BookBuildManifest } from "@library/source-sync";import type { BuildJob,BuildJobStore } from "../../source-sync-server/src/index.js";import type { DerivedArtifactSink,SourceEditionRevisionSource } from "./node-derived-builders.js";
export class RemoteBuildError extends Error{constructor(readonly code:string,readonly retryable:boolean,readonly status:number|null=null,readonly retryAfterMs:number|null=null){super(code);this.name="RemoteBuildError"}}
export class RemoteBuildPorts implements BuildJobStore,SourceEditionRevisionSource,DerivedArtifactSink{constructor(private readonly base:URL|string,private readonly serviceToken:()=>Promise<string>,private readonly fetchImpl:typeof fetch=fetch,private readonly requestTimeoutMs?:number){}
 async #request(path:string,init:RequestInit={}){const token=(await this.serviceToken()).trim();if(!token)throw new RemoteBuildError("service_token_unavailable",false);const r=await this.fetchImpl(new URL(path,this.base),{...init,headers:{authorization:`Bearer ${token}`,"x-service-scopes":"build:claim build:write revision:read artifact:write publish:write",...init.headers},...(this.requestTimeoutMs===undefined?{}:{signal:AbortSignal.timeout(this.requestTimeoutMs)})});if(!r.ok&&r.status!==304)throw new RemoteBuildError(`build_service_${r.status}`,r.status===408||r.status===429||r.status>=500,r.status,parseRetryAfter(r.headers.get("retry-after")));return r}
 async ensureBuildJobs(m:BookBuildManifest){await this.#request("builds/ensure",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(m)})}
 async claim(nowMs:number,leaseId:string,leaseMs:number,limit:number){return await (await this.#request("build-jobs/claim",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nowMs,leaseId,leaseMs,limit})})).json() as BuildJob[]}
 async complete(job:BuildJob,artifact:BookBuildManifest["artifacts"][number]){return (await this.transition("complete",{job,artifact})).committed}async retry(job:BuildJob,nextAttemptAtMs:number,code:string){return (await this.transition("retry",{job,nextAttemptAtMs,code})).committed}async fail(job:BuildJob,code:string){return (await this.transition("fail",{job,code})).committed}
 async transition(action:string,body:unknown){return await (await this.#request(`build-jobs/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)})).json() as {committed:boolean}}
 async getManifest(id:string){return await (await this.#request(`builds/${encodeURIComponent(id)}/manifest`)).json() as BookBuildManifest}async getActiveBuildId(book:string){return (await (await this.#request(`books/${encodeURIComponent(book)}/active-build`)).json() as {buildId:string|null}).buildId}async publish(decision:any){return(await this.transition("publish",decision)).committed}
 async revalidateActivePublication(book:string,etag?:string){const response=await this.#request(`books/${encodeURIComponent(book)}/active-build`,{headers:{...(etag?{"if-none-match":etag}:{})}});if(response.status===304)return{status:"not-modified" as const,etag:etag!};return{status:"modified" as const,etag:response.headers.get("etag"),publication:await response.json() as {buildId:string|null;sourceRevisionId?:string;cacheVersion?:number}}}
 async readRevisionSource(id:string){const response=await this.#request(`source-revisions/${encodeURIComponent(id)}/bytes`),bytes=new Uint8Array(await response.arrayBuffer()),editionId=response.headers.get("x-source-edition-id")??"",format=response.headers.get("x-source-format"),sha256=response.headers.get("x-source-sha256")??"";if(!editionId||format!=="docx"||!/^[a-f0-9]{64}$/.test(sha256))throw new RemoteBuildError("source_edition_headers_invalid",false);return{bytes,editionId,format:"docx"as const,sha256}}
 async readRevisionBytes(id:string){return(await this.readRevisionSource(id)).bytes}
 async putImmutable(input:{objectKey:string;bytes:Uint8Array;contentType:string}){const hash=await crypto.subtle.digest("SHA-256",input.bytes);const hex=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");await this.#request("artifacts/immutable",{method:"PUT",headers:{"content-type":input.contentType,"x-artifact-key":input.objectKey,"x-content-sha256":hex,"x-content-length":String(input.bytes.byteLength)},body:input.bytes})}}
export interface CachedActivePublication{buildId:string|null;sourceRevisionId?:string;cacheVersion?:number}
export class ActivePublicationRevalidator{private readonly cache=new Map<string,{etag:string|null;publication:CachedActivePublication}>();constructor(private readonly remote:Pick<RemoteBuildPorts,"revalidateActivePublication">){}async get(bookId:string){const cached=this.cache.get(bookId);try{const next=await this.remote.revalidateActivePublication(bookId,cached?.etag??undefined);if(next.status==="not-modified"&&cached)return{status:"fresh"as const,...cached};if(next.status==="modified"){const value={etag:next.etag,publication:next.publication};this.cache.set(bookId,value);return{status:"fresh"as const,...value}}throw Error("not_modified_without_cached_value")}catch(error){if(cached)return{status:"stale"as const,...cached};throw error}}}
function parseRetryAfter(value:string|null){if(value===null)return null;const seconds=Number(value);if(Number.isFinite(seconds)&&seconds>=0)return Math.round(seconds*1000);const at=Date.parse(value);return Number.isFinite(at)?Math.max(0,at-Date.now()):null}
