import type{StoredBook,BookIntakeFields}from'./engine/library_store';
export interface AdminLocalWordInput{remoteId:string;ownerScope:string;file:File;title:string;author:string;category?:string}
interface Dependencies{scope:()=>string;storage:Pick<Storage,'getItem'|'setItem'>;getBook:(id:string)=>Promise<Pick<StoredBook,'id'|'ownerScope'|'originalSha256'>|undefined>;save:(book:BookIntakeFields&{fileName:string;data:Uint8Array;sourceFormat:'word';mimeType:string},options:{expectedOwnerScope:string})=>Promise<string>;enqueue:(id:string,title:string,scope:string,options:{revision:string;recheck:true})=>void;hash:(data:Uint8Array)=>Promise<string>}
const flights=new Map<string,Promise<{localId:string;reused:boolean;checkpointSaved:boolean}>>(),sessionLinks=new Map<string,string>();
/** Called only after the server accepted this exact file. Never uploads or publishes. */
export async function linkAdminWordLocally(input:AdminLocalWordInput,deps:Dependencies):Promise<{localId:string;reused:boolean;checkpointSaved:boolean}>{
 const active=()=>{if(deps.scope()!==input.ownerScope||input.ownerScope.startsWith('guest:'))throw Error('local_book_identity_changed')};active();if(!/^[A-Za-z0-9_-]{1,200}$/.test(input.remoteId)||!input.file.name.toLowerCase().endsWith('.docx'))throw Error('admin_local_word_input');
 const key='alkhizana:admin-word-link:v1:'+encodeURIComponent(input.ownerScope)+':'+input.remoteId;
 const previous=flights.get(key);if(previous)return previous;
 const work=(async()=>{const data=new Uint8Array(await input.file.arrayBuffer());active();const revision=await deps.hash(data);active();let prior=sessionLinks.get(key);try{prior??=deps.storage.getItem(key)??undefined}catch{}
 if(prior){const book=await deps.getBook(prior);active();if(book?.ownerScope===input.ownerScope&&book.originalSha256===revision){deps.enqueue(book.id,input.title,input.ownerScope,{revision,recheck:true});return{localId:book.id,reused:true,checkpointSaved:true}}}
 const localId=await deps.save({title:input.title,author:input.author,...(input.category?{category:input.category}:{}),fileName:input.file.name,data,sourceFormat:'word',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'},{expectedOwnerScope:input.ownerScope});active();sessionLinks.set(key,localId);let checkpointSaved=true;try{deps.storage.setItem(key,localId)}catch{checkpointSaved=false}deps.enqueue(localId,input.title,input.ownerScope,{revision,recheck:true});return{localId,reused:false,checkpointSaved};})().finally(()=>flights.delete(key));flights.set(key,work);return work;
}
export async function indexAcceptedAdminWord(input:AdminLocalWordInput){const[{currentLibraryIdentityScope,getBook,saveBook},{localBookIndexJobs}]=await Promise.all([import('./engine/library_store'),import('./local_index_status')]);return linkAdminWordLocally(input,{scope:currentLibraryIdentityScope,getBook,save:saveBook,storage:localStorage,enqueue:(...args)=>localBookIndexJobs.enqueue(...args),hash:async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(bytes).buffer))].map(v=>v.toString(16).padStart(2,'0')).join('')})}
