import type { StoredBook } from './engine/library_store'
const marks=/[\u064B-\u065F\u0670\u0640]/gu,punctuation=/[()[\]{}«»"'،,:؛.!؟/_-]+/gu
export function canonicalBookText(value:string):string{return value.normalize('NFKC').replace(marks,'').replace(/[أإآٱ]/gu,'ا').replace(/ى/gu,'ي').replace(/ة/gu,'ه').replace(punctuation,' ').replace(/\s+/gu,' ').trim().toLocaleLowerCase('ar')}
export function canonicalBookFingerprint(book:Pick<StoredBook,'title'|'author'>):string{return `${canonicalBookText(book.title)}\u0000${canonicalBookText(book.author)}`}
const validYear=(year:number|undefined)=>Number.isInteger(year)&&year!>0&&year!<2000
function editionEvidence(book:StoredBook):string|undefined {const values=[book.edition?.trim(),book.publisher?.trim(),validYear(book.publicationYearHijri)?String(book.publicationYearHijri):undefined].filter((x):x is string=>Boolean(x));return values.length?values.map(canonicalBookText).join('\u0000'):undefined}
function score(book:StoredBook):number{return (book.managedSource==='published'?100:0)+(book.sourceKind==='shamela4.1'&&book.sourceBookId?80:0)+(book.bokTextVersion===4?60:0)+(book.bokPages?.length?40:0)+(book.data.byteLength?25:0)+(validYear(book.publicationYearHijri)?8:0)+(book.publisher?3:0)+(book.edition?3:0)}
export interface CanonicalBookSet { books:StoredBook[]; aliases:Map<string,string> }
export function canonicalVisibleBooks(input:StoredBook[]):CanonicalBookSet {const groups=new Map<string,StoredBook[]>();for(const book of input){const key=canonicalBookFingerprint(book);groups.set(key,[...(groups.get(key)??[]),book])}const books:StoredBook[]=[],aliases=new Map<string,string>();for(const group of groups.values()){if(group.length===1){books.push(group[0]!);continue}const evidence=group.map(editionEvidence),allDistinct=evidence.every(Boolean)&&new Set(evidence).size===group.length;if(allDistinct){books.push(...group);continue}const ordered=[...group].sort((a,b)=>score(b)-score(a)||b.addedAt-a.addedAt||a.id.localeCompare(b.id)),winner=ordered[0]!;books.push(winner);for(const duplicate of ordered.slice(1))aliases.set(duplicate.id,winner.id)}return{books,aliases}}
