import { beforeEach,describe,expect,it,vi } from 'vitest'
import { createHash } from 'node:crypto'
import { fetchPagesDataAsset,pagesReleaseAllowedOnHost,resetPagesDataReleaseForTests } from './pages_data_release'
const sha=(x:Uint8Array)=>createHash('sha256').update(x).digest('hex')
beforeEach(()=>resetPagesDataReleaseForTests())
it('aborts promptly while release discovery is stalled',async()=>{
 const controller=new AbortController()
 const fetcher=vi.fn(()=>new Promise<Response>(()=>undefined)) as typeof fetch
 const pending=fetchPagesDataAsset('corpus','book.json','local',fetcher,{signal:controller.signal})
 const assertion=expect(pending).rejects.toMatchObject({name:'AbortError'})
 controller.abort()
 await assertion
})
it('keeps production release URLs out of localhost while allowing an explicit local harness',()=>{const config=(baseUrl:string)=>({contract:'alkhizana-pages-client/1' as const,releaseId:'a'.repeat(24),projects:[{name:'corpus-01',group:'corpus' as const,baseUrl}]});expect(pagesReleaseAllowedOnHost(config('https://khezana-corpus-01.pages.dev'),'localhost')).toBe(false);expect(pagesReleaseAllowedOnHost(config('http://127.0.0.1:4200'),'127.0.0.1')).toBe(true);expect(pagesReleaseAllowedOnHost(config('https://khezana-corpus-01.pages.dev'),'alkhizana.pages.dev')).toBe(true)})
describe('Pages multi-project data release',()=>{it('reassembles an immutable cross-origin book and verifies every SHA',async()=>{const whole=new TextEncoder().encode('{"book":"كتاب"}'),a=whole.slice(0,7),b=whole.slice(7),fetcher=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);if(url.endsWith('shamela-pages-release.json'))return new Response(JSON.stringify({contract:'alkhizana-pages-client/1',releaseId:'a'.repeat(24),projects:[{name:'corpus-01',group:'corpus',baseUrl:'https://corpus.example'}]}));if(url.endsWith('project-manifest.json'))return new Response(JSON.stringify({contract:'alkhizana-pages-project/1',releaseId:'a'.repeat(24),project:'corpus-01',group:'corpus',assets:[{group:'corpus',path:'batch/books/1.json',bytes:whole.length,sha256:sha(whole),project:'corpus-01',parts:[{path:'releases/x/a.bin',bytes:a.length,sha256:sha(a)},{path:'releases/x/b.bin',bytes:b.length,sha256:sha(b)}]}]}));if(url.endsWith('a.bin'))return new Response(a);if(url.endsWith('b.bin'))return new Response(b);return new Response(null,{status:404})}) as typeof fetch;const response=await fetchPagesDataAsset('corpus','batch/books/1.json','./local.json',fetcher);expect(new Uint8Array(await response.arrayBuffer())).toEqual(whole);expect(response.headers.get('x-alkhizana-project')).toBe('corpus-01');expect(fetcher).not.toHaveBeenCalledWith('./local.json',expect.anything())});it('falls back locally when no release config exists',async()=>{const fetcher=vi.fn(async(input:RequestInfo|URL)=>String(input).endsWith('shamela-pages-release.json')?new Response(null,{status:404}):new Response('local')) as typeof fetch;expect(await (await fetchPagesDataAsset('search','manifest.json','./library/shamela-search/manifest.json',fetcher)).text()).toBe('local')});it('fails closed when a chunk is corrupt',async()=>{const bytes=new TextEncoder().encode('x'),fetcher=vi.fn(async(input:RequestInfo|URL)=>String(input).endsWith('shamela-pages-release.json')?new Response(JSON.stringify({contract:'alkhizana-pages-client/1',releaseId:'b'.repeat(24),projects:[{name:'search-01',group:'search',baseUrl:'https://search.example'}]})):String(input).endsWith('project-manifest.json')?new Response(JSON.stringify({contract:'alkhizana-pages-project/1',releaseId:'b'.repeat(24),project:'search-01',group:'search',assets:[{group:'search',path:'manifest.json',bytes:1,sha256:sha(bytes),project:'search-01',parts:[{path:'bad',bytes:1,sha256:'0'.repeat(64)}]}]})):new Response(bytes)) as typeof fetch;await expect(fetchPagesDataAsset('search','manifest.json','local',fetcher)).rejects.toThrow('pages_asset_part_integrity')})})
