import {withPagesFetchRetry} from './pages_fetch_retry'
export interface PagesReleaseConfig { contract:'alkhizana-pages-client/1'; releaseId:string; projects:Array<{name:string;group:'corpus'|'search';baseUrl:string}> }
interface AssetPart { path:string;bytes:number;sha256:string }
interface ProjectAsset { group:string;path:string;bytes:number;sha256:string;project:string;parts:AssetPart[] }
interface ProjectManifest { contract:'alkhizana-pages-project/1';releaseId:string;project:string;group:string;assets:ProjectAsset[] }

const CONFIG='./data/shamela-pages-release.json', manifests=new Map<string,Promise<ProjectManifest>>()
const hash=async(bytes:Uint8Array)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(bytes).buffer))].map(x=>x.toString(16).padStart(2,'0')).join('')
const cleanBase=(value:string)=>value.replace(/\/+$/u,'')
const joinUrl=(base:string,path:string)=>`${cleanBase(base)}/${path.replace(/^\/+/, '')}`
let configured:Promise<PagesReleaseConfig|undefined>|undefined

export function isLocalRuntimeHost(host=globalThis.location?.hostname):boolean {return host==='localhost'||host==='127.0.0.1'||host==='[::1]'}
export function pagesReleaseAllowedOnHost(config:PagesReleaseConfig,host=globalThis.location?.hostname):boolean{return !isLocalRuntimeHost(host)||config.projects.every(project=>!/^https?:\/\/(?!localhost(?::|\/)|127\.0\.0\.1(?::|\/)|\[::1\](?::|\/))/u.test(project.baseUrl))}

export function resetPagesDataReleaseForTests(){configured=undefined;manifests.clear()}
export async function loadPagesReleaseConfig(fetcher:typeof fetch=globalThis.fetch):Promise<PagesReleaseConfig|undefined>{configured??=(async()=>{try{const response=await fetcher(CONFIG,{cache:'no-cache'});if(response.status===404)return undefined;if(!response.ok)throw new Error(`pages_release_config_http_${response.status}`);const value=await response.json() as PagesReleaseConfig;if(value.contract!=='alkhizana-pages-client/1'||!/^[a-f0-9]{24}$/u.test(value.releaseId)||!Array.isArray(value.projects))throw new Error('pages_release_config_invalid');if(!pagesReleaseAllowedOnHost(value))return undefined;return value}catch(error){configured=undefined;throw error}})();return configured}
async function projectManifest(project:PagesReleaseConfig['projects'][number],releaseId:string,fetcher:typeof fetch){let pending=manifests.get(project.name);if(!pending){pending=(async()=>{const response=await fetcher(joinUrl(project.baseUrl,'project-manifest.json'),{cache:'no-cache',mode:'cors'});if(!response.ok)throw new Error(`pages_project_manifest_http_${response.status}`);const value=await response.json() as ProjectManifest;if(value.contract!=='alkhizana-pages-project/1'||value.releaseId!==releaseId||value.project!==project.name)throw new Error('pages_project_manifest_invalid');return value})();pending=pending.catch(error=>{manifests.delete(project.name);throw error});manifests.set(project.name,pending)}return pending}

export async function fetchPagesDataAsset(group:'corpus'|'search',path:string,fallbackUrl:string,fetcher:typeof fetch=globalThis.fetch):Promise<Response>{fetcher=withPagesFetchRetry(fetcher);const config=await loadPagesReleaseConfig(fetcher);if(!config)return fetcher(fallbackUrl,{cache:'force-cache',credentials:'same-origin'});const projects=config.projects.filter(x=>x.group===group&&x.baseUrl);for(const project of projects){const manifest=await projectManifest(project,config.releaseId,fetcher),asset=manifest.assets.find(x=>x.path===path);if(!asset)continue;const chunks=await Promise.all(asset.parts.map(async part=>{const response=await fetcher(joinUrl(project.baseUrl,part.path),{cache:'force-cache',mode:'cors'});if(!response.ok)throw new Error(`pages_asset_part_http_${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength!==part.bytes||await hash(bytes)!==part.sha256)throw new Error(`pages_asset_part_integrity:${path}`);return bytes})),joined=new Uint8Array(asset.bytes);let offset=0;for(const chunk of chunks){joined.set(chunk,offset);offset+=chunk.byteLength}if(offset!==asset.bytes||await hash(joined)!==asset.sha256)throw new Error(`pages_asset_reassembly_integrity:${path}`);return new Response(joined,{status:200,headers:{'content-type':'application/json','x-alkhizana-release':config.releaseId,'x-alkhizana-project':project.name}})}throw new Error(`pages_asset_not_mapped:${group}:${path}`)}
