import coverage from './quran_mujahid_coverage.json'
import {loadReadyBokReading} from './quran_ready_bok_reading'
const keys=new Set(coverage.keys)
interface Page {sourceRowId:string;sequence:number;part:string|null;page:number|null;body:string;foot:string|null}
interface Verse {contract:'khizana-ready-bok-verse/1';readerId:410012810;surah:number;ayah:number;pages:Page[];segments:{pageRef:number;sequence:number;tokenStart:number;tokenLength:number}[]}
const countTokens=(s:string)=>(s.normalize('NFKC').replace(/ﷺ/g,'صلى الله عليه وسلم').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/[\u064b-\u065f\u0670\u06d6-\u06ed]/g,'').match(/[\p{L}\p{N}]+/gu)||[]).length
export const mujahidCoverage=(s:number,a:number)=>keys.has(`${s}:${a}`)?'confirmed':'unmapped'
export function validMujahidVerse(value:unknown,s:number,a:number):value is Verse{
 const d=value as Verse|null;if(!d||d.contract!=='khizana-ready-bok-verse/1'||d.readerId!==410012810||d.surah!==s||d.ayah!==a||!Array.isArray(d.pages)||!d.pages.length||d.pages.length>40||!Array.isArray(d.segments)||!d.segments.length||d.segments.length>40)return false
 if(!d.pages.every(p=>!!p&&typeof p.sourceRowId==='string'&&/^\d+$/.test(p.sourceRowId)&&Number.isInteger(p.sequence)&&p.sequence>=0&&typeof p.body==='string'&&!!p.body.trim()&&(p.foot===null||typeof p.foot==='string')&&(p.part===null||typeof p.part==='string')&&(p.page===null||(Number.isInteger(p.page)&&p.page>0))))return false
 if(new Set(d.pages.map(p=>p.sourceRowId)).size!==d.pages.length)return false
 const used=new Set<number>();return d.segments.every((x,i)=>{if(!x||!Number.isInteger(x.pageRef)||x.pageRef<0||!d.pages[x.pageRef])return false;const p=d.pages[x.pageRef]!;used.add(x.pageRef);return x.sequence===p.sequence&&x.tokenStart===0&&Number.isInteger(x.tokenLength)&&x.tokenLength>0&&x.tokenLength===countTokens(p.body)&&(i===0||x.sequence>=d.segments[i-1]!.sequence)})&&used.size===d.pages.length
}
export async function loadMujahidVerse(s:number,a:number,signal:AbortSignal):Promise<Verse>{if(mujahidCoverage(s,a)!=='confirmed')throw Error('unmapped');const response=await fetch(`./quran/resources/mujahid-ready/${s}-${a}.json`,{credentials:'same-origin',signal:AbortSignal.any([signal,AbortSignal.timeout(6000)])});if(!response.ok||!response.body)throw Error('unavailable');const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>32768)throw Error('oversize');chunks.push(value)}}finally{await reader.cancel();reader.releaseLock()}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const d:unknown=JSON.parse(new TextDecoder().decode(bytes));if(!validMujahidVerse(d,s,a))throw Error('invalid_or_partial');return d}
export function loadMujahidReading(s:number,a:number,root:HTMLElement,tools:HTMLElement,current:()=>boolean){return loadReadyBokReading({readerId:'410012810',confirmed:(s,a)=>mujahidCoverage(s,a)==='confirmed',load:async(s,a,signal)=>{const data=await loadMujahidVerse(s,a,signal);return{segments:data.segments.map(x=>data.pages[x.pageRef]!)}}},s,a,root,tools,current)}
