import { getAnnotations } from './annotation_store'
import { arabicNum } from './ui'

type ReaderPanelTab='toc'|'bookmarks'|'highlights'
export interface ReaderUnifiedPanel {element:HTMLElement;open(tab?:ReaderPanelTab):void;close():void;refresh():void}

export function createReaderUnifiedPanel(bookId:string,tocRoot:()=>HTMLElement|null,onPage:(index:number)=>void,onClose?:()=>void):ReaderUnifiedPanel {
  const panel=document.createElement('section');panel.className='reader__unified-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','لوحة التنقل والتعليقات')
  const head=document.createElement('header'),title=document.createElement('h2'),closeButton=document.createElement('button');title.textContent='لوحة الكتاب';closeButton.type='button';closeButton.className='reader__unified-close';closeButton.textContent='إغلاق';closeButton.setAttribute('aria-label','إغلاق لوحة الكتاب');head.append(title,closeButton)
  const tabs=document.createElement('div');tabs.className='reader__unified-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','أقسام لوحة الكتاب')
  const panels=new Map<ReaderPanelTab,HTMLElement>(),buttons=new Map<ReaderPanelTab,HTMLButtonElement>();let active:ReaderPanelTab='toc',restoreFocus:HTMLElement|null=null
  for(const [key,label] of [['toc','الفهرس'],['bookmarks','الفواصل'],['highlights','التظليلات']] as const){const button=document.createElement('button'),content=document.createElement('div');button.type='button';button.id=`reader-panel-tab-${key}`;button.setAttribute('role','tab');button.setAttribute('aria-controls',`reader-panel-${key}`);button.textContent=label;content.id=`reader-panel-${key}`;content.className='reader__unified-content';content.setAttribute('role','tabpanel');content.setAttribute('aria-labelledby',button.id);tabs.append(button);panel.append(content);buttons.set(key,button);panels.set(key,content);button.addEventListener('click',()=>activate(key))}
  panel.prepend(head,tabs)
  const activate=(tab:ReaderPanelTab)=>{active=tab;for(const [key,button] of buttons){const selected=key===tab;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;panels.get(key)!.hidden=!selected}refresh()}
  const item=(label:string,page:number)=>{const button=document.createElement('button');button.type='button';button.className='reader__unified-item';button.textContent=label;button.addEventListener('click',()=>{onPage(page);close()});return button}
  const refresh=()=>{const state=getAnnotations(),bookmarks=state.bookmarks[bookId]??[],highlights=state.highlights.filter(x=>x.bookId===bookId),tocItems=[...(tocRoot()?.querySelectorAll<HTMLButtonElement>('.reader__toc-item')??[])];buttons.get('toc')!.textContent=`الفهرس (${arabicNum(tocItems.length)})`;buttons.get('bookmarks')!.textContent=`الفواصل (${arabicNum(bookmarks.length)})`;buttons.get('highlights')!.textContent=`التظليلات (${arabicNum(highlights.length)})`;const tocPanel=panels.get('toc')!,bookmarkPanel=panels.get('bookmarks')!,highlightPanel=panels.get('highlights')!;tocPanel.replaceChildren(...tocItems.map((source,index)=>{const clone=document.createElement('button');clone.type='button';clone.className='reader__unified-item';clone.textContent=source.textContent?.trim()||`عنوان ${index+1}`;clone.addEventListener('click',()=>{source.click();close()});return clone}));bookmarkPanel.replaceChildren(...bookmarks.map(page=>item(`فاصل الصفحة ${arabicNum(page+1)}`,page)));highlightPanel.replaceChildren(...highlights.map(value=>item(`${value.text} — الصفحة ${arabicNum(value.pageIndex+1)}`,value.pageIndex)));for(const content of [tocPanel,bookmarkPanel,highlightPanel])if(!content.children.length){const empty=document.createElement('p');empty.className='reader__unified-empty';empty.textContent='لا توجد عناصر بعد';content.append(empty)}}
  const close=()=>{panel.hidden=true;document.body.classList.remove('reader-unified-panel-open');restoreFocus?.focus();restoreFocus=null;onClose?.()}
  const open=(tab:ReaderPanelTab='toc')=>{restoreFocus=document.activeElement as HTMLElement|null;panel.hidden=false;document.body.classList.add('reader-unified-panel-open');activate(tab);buttons.get(tab)?.focus()}
  closeButton.addEventListener('click',close);panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close();return}if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const order:[ReaderPanelTab,ReaderPanelTab,ReaderPanelTab]=['toc','bookmarks','highlights'],current=order.indexOf(active);const next=event.key==='Home'?0:event.key==='End'?2:event.key==='ArrowLeft'?(current+1)%3:(current+2)%3;event.preventDefault();activate(order[next]!);buttons.get(order[next]!)?.focus()})
  activate('toc');return{element:panel,open,close,refresh}
}
