import { readingStorageKey } from './reading_identity_scope'
export interface ResearchProject { id: string; title: string; description: string; annotationIds: string[]; createdAt: number; updatedAt: number }
const KEY = 'alkhizana:research-projects:v1'
export function listResearchProjects(): ResearchProject[] { try { const value = JSON.parse(localStorage.getItem(readingStorageKey(KEY)) ?? '[]'); return Array.isArray(value) ? value.filter(valid).map(item => ({ ...item, description: typeof item.description === 'string' ? item.description : '', annotationIds: [...new Set(item.annotationIds)] })).sort((a, b) => b.updatedAt - a.updatedAt) : [] } catch { return [] } }
export function createResearchProject(title: string, description = '', now = Date.now()): ResearchProject { const clean = title.trim(); if (!clean) throw new Error('اكتب عنوان المشروع'); const project = { id: `${now}-${Math.random().toString(36).slice(2, 8)}`, title: clean, description: description.trim(), annotationIds: [], createdAt: now, updatedAt: now }; save([project, ...listResearchProjects()]); return project }
export function updateResearchProject(id: string, annotationIds: readonly string[], now = Date.now()): ResearchProject { const projects = listResearchProjects(), project = projects.find(item => item.id === id); if (!project) throw new Error('المشروع غير موجود'); const updated = { ...project, annotationIds: [...new Set(annotationIds.filter(Boolean))], updatedAt: now }; save(projects.map(item => item.id === id ? updated : item)); return updated }
export function deleteResearchProject(id: string): void { save(listResearchProjects().filter(item => item.id !== id)) }
export function removeAnnotationFromProjects(annotationId: string): void { save(listResearchProjects().map(item => ({ ...item, annotationIds: item.annotationIds.filter(id => id !== annotationId) }))) }
export function saveResearchProjects(projects: readonly ResearchProject[]): void { if (projects.length) localStorage.setItem(readingStorageKey(KEY), JSON.stringify(projects)); else localStorage.removeItem(readingStorageKey(KEY)) }
const save = saveResearchProjects
function valid(item: any): item is ResearchProject { return item && typeof item.id === 'string' && typeof item.title === 'string' && Array.isArray(item.annotationIds) && Number.isFinite(item.createdAt) && Number.isFinite(item.updatedAt) }
