import {it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {SearchFieldBoundaryProvider,phraseWithinField,type FieldBoundaryDescriptor} from './search_field_boundary_provider';
const sha=(x:string)=>createHash('sha256').update(x).digest('hex'),identity={packedReleaseId:'test',packedManifestSha256:'a'.repeat(64),normalizerSha256:'b'.repeat(64),policy:'positions+death-2'};
function fixture(rows:any[]=[['12:0',2,5,8]]){
 const files=new Map<string,string>();const part=JSON.stringify({contract:'khizana-search-field-boundary-part/1',packedReleaseId:'test',bookId:'12',rows});files.set('books/12/0000.json',part);
 const bucket=sha('12').slice(0,2);const indexFiles=Array.from({length:256},(_,i)=>{const id=i.toString(16).padStart(2,'0'),path=`indexes/${id}.json`,raw=JSON.stringify({contract:'khizana-search-field-boundary-index/1',...identity,entries:id===bucket?[['12',[{path:'books/12/0000.json',byteLength:Buffer.byteLength(part),sha256:sha(part),firstSequence:0,lastSequence:0}]]]:[]});files.set(path,raw);return{id,path,byteLength:Buffer.byteLength(raw),sha256:sha(raw)}});
 const descriptor:FieldBoundaryDescriptor={contract:'khizana-search-field-boundaries/1',...identity,complete:true,counts:{segments:860,books:8594,documents:7626594,emptyDocuments:3},indexBucketCount:256,indexFiles};
 const fetcher=vi.fn(async(url:any)=>new Response(files.get(new URL(url).pathname.slice(1))??'',{status:200}));
 return{descriptor,fetcher,files,client:new SearchFieldBoundaryProvider({descriptor,expected:identity,baseUrl:'https://test.invalid',fetch:fetcher})};
}
it('verified boundaries distinguish title/body/foot and forbid phrase crossings',async()=>{const {client,fetcher}=fixture();const row=await client.lookup('12:0','body');expect(row).toEqual(['12:0',2,5,8]);expect(phraseWithinField(row!,4,2,'body')).toBe(false);expect(phraseWithinField(row!,3,2,'body')).toBe(true);expect(phraseWithinField(row!,5,3,'foot')).toBe(true);expect(await client.lookup('12:0','both')).toBeUndefined();expect(fetcher).toHaveBeenCalledTimes(2);client.dispose()});
it('partial descriptor and mismatched identity reject before reads',()=>{const f=fixture();expect(()=>new SearchFieldBoundaryProvider({descriptor:{...f.descriptor,complete:false},expected:identity,baseUrl:'https://test.invalid'})).toThrow();expect(()=>new SearchFieldBoundaryProvider({descriptor:f.descriptor,expected:{...identity,packedReleaseId:'wrong'},baseUrl:'https://test.invalid'})).toThrow();f.client.dispose()});
it('corrupt bytes and authenticated invalid rows fail, never return absence',async()=>{const f=fixture();f.files.set('books/12/0000.json','broken');await expect(f.client.lookup('12:0','foot')).rejects.toThrow();f.client.dispose();for(const row of [['13:0',0,1,2],['12:0',3,2,4],['12:1',0,1,2]]){const g=fixture([row]);await expect(g.client.lookup('12:0','body')).rejects.toThrow();g.client.dispose()}});
it('timeout rejects and independent consumers retain a shared flight',async()=>{
 const f=fixture();const delayed=vi.fn(async(...args:any[])=>{await new Promise(r=>setTimeout(r,10));return f.fetcher(args[0])});const client=new SearchFieldBoundaryProvider({descriptor:f.descriptor,expected:identity,baseUrl:'https://test.invalid',fetch:delayed});const c=new AbortController();const a=client.lookup('12:0','body',c.signal),b=client.lookup('12:0','foot');c.abort();await expect(a).rejects.toThrow();expect(await b).toEqual(['12:0',2,5,8]);client.dispose();f.client.dispose();
 const blocked=new SearchFieldBoundaryProvider({descriptor:f.descriptor,expected:identity,baseUrl:'https://test.invalid',fetch:async(_u,opts)=>new Promise((_r,reject)=>opts?.signal?.addEventListener('abort',()=>reject(opts.signal?.reason)))});try{await expect(blocked.lookup('12:0','body')).rejects.toThrow('timeout')}finally{blocked.dispose()}
},15000);
