// Generated by tools/build-shamela-catalog-snapshot.mjs; do not edit by hand.
export const SHAMELA_CATALOG_SNAPSHOT={"path":"./data/shamela-catalog.snapshot.json","bytes":4874153,"sha256":"157b8a546eabb127d3627268851c0cc0a091f4d32c58018c2cdd8565173ea05d","bookCount":8594,"batchCount":86,"sourceSha256":"99e60f552cbac1853b365fbfe418d8da6e093c637cee8f4145ade89a7e25d593"} as const
