import type { SearchHit, SearchPage, SearchWorkerRequest, SearchWorkerResponse, SerializedSearchShard } from '../../packages/search/src/index'
import { shamelaSourceBookId } from './shamela_public_identity'
import { fetchPagesDataAsset } from './pages_data_release'
import { ShamelaSearchV2Client, type SeparatedV2SearchBinding } from './shamela_search_v2'

export interface ShamelaSearchManifest { contract:string; source?:{booksDigestSha256?:string}; counts?:{books:number;documents:number;postings:number}; routing?:{manifest:string}; shards:Array<{id:string;bookId:string;batch?:string;file:string;byteLength:number;sha256:string}> }
interface RoutingManifest { contract:string; bucketCount:number; globalPattern:string; batchPattern:string; batches:string[] }
export interface ShamelaSearchPage extends SearchPage { unavailableBookIds:string[]; pendingBookIds:string[]; coverageComplete:boolean }
export interface WorkerPort { postMessage(value:SearchWorkerRequest):void; addEventListener(type:'message',listener:(event:MessageEvent<SearchWorkerResponse>)=>void):void; terminate?():void }
type WorkerCommand<T=SearchWorkerRequest> = T extends {requestId:string} ? Omit<T,'requestId'> : never
const ROOT='./library/shamela-search/'
const digest=async(bytes:Uint8Array)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(bytes).buffer))].map(x=>x.toString(16).padStart(2,'0')).join('')
const folded=(value:string)=>value.toLocaleLowerCase('ar').replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/\u0640/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/\s+/gu,' ').trim()
/**
 * عدة مفاتيح متباعدة (حتى ثمانية) تضيق المسار قبل تنزيل أي shard.
 * استعمال مفتاح واحد كان يحوّل العبارات الشائعة إلى مئات الكتب المرشحة،
 * فيرتفع استهلاك المعالج والشبكة كأنه مسح كامل للكتب.
 */
const queryGrams=(value:string)=>{const text=folded(value),all=[...new Set(Array.from({length:Math.max(0,text.length-2)},(_,i)=>({gram:text.slice(i,i+3),index:i})))],rare='ظطضصثغعخحجشذزقف',limit=8;if(all.length<=limit)return all.map(x=>x.gram);const ranked=[...all].sort((a,b)=>[...b.gram].filter(x=>rare.includes(x)).length-[...a.gram].filter(x=>rare.includes(x)).length||new Set(b.gram).size-new Set(a.gram).size||a.index-b.index),picked:typeof all=[];for(const candidate of ranked){if(picked.every(item=>Math.abs(item.index-candidate.index)>=2))picked.push(candidate);if(picked.length===limit)break}for(const candidate of ranked){if(picked.length===limit)break;if(!picked.some(item=>item.gram===candidate.gram))picked.push(candidate)}return picked.sort((a,b)=>a.index-b.index).map(x=>x.gram)}
const bucketFor=(gram:string,count:number)=>{let hash=2166136261;for(let i=0;i<gram.length;i++){hash^=gram.charCodeAt(i);hash=Math.imul(hash,16777619)}return String((hash>>>0)%count).padStart(4,'0')}
const intersectSets=(sets:Array<Set<string>>)=>{if(!sets.length)return new Set<string>();const ordered=[...sets].sort((a,b)=>a.size-b.size),out=new Set(ordered[0]);for(const value of out)if(ordered.some(set=>!set.has(value)))out.delete(value);return out}
const abortableSearch=<T>(promise:Promise<T>,signal?:AbortSignal):Promise<T>=>{if(!signal)return promise;if(signal.aborted)return Promise.reject(new DOMException('Search superseded','AbortError'));return new Promise<T>((resolve,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(new DOMException('Search superseded','AbortError'))};signal.addEventListener('abort',abort,{once:true});promise.then(value=>{signal.removeEventListener('abort',abort);resolve(value)},error=>{signal.removeEventListener('abort',abort);reject(error)})})}
const workerFailure=(error:unknown)=>error instanceof Error&&/^shamela_search_worker_/.test(error.message)
const localSearchHost=()=>globalThis.location?.hostname==='localhost'||globalThis.location?.hostname==='127.0.0.1'||globalThis.location?.hostname==='[::1]'
// أول تشغيل محلي يقرأ manifest وpostings من القرص وقد يحتاج بضع ثوانٍ، لكنه
// يظل أسرع كثيرًا من الرجوع المبكر إلى فهرس V1 الكامل. كانت مهلة 900ms
// تقطع V2 بعد أن يكاد ينتهي ثم تجعل الواجهة تنتظر مهلة البحث كلها.
const withLocalV2Deadline=<T>(promise:Promise<T>,signal?:AbortSignal):Promise<T>=>{const active=abortableSearch(promise,signal);if(!localSearchHost())return active;let timer:ReturnType<typeof setTimeout>;const deadline=new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('shamela_search_v2_cold_deadline')),5000)});return Promise.race([active,deadline]).finally(()=>clearTimeout(timer))}

export class ShamelaSearchClient {
  async searchSeparatedV2(query:string,scope:'body'|'foot',binding:SeparatedV2SearchBinding,offset=0,limit=100,bookIds?:string[],signal?:AbortSignal){
    signal?.throwIfAborted()
    const sourceIds=bookIds?.map(shamelaSourceBookId)
    if(sourceIds?.some(id=>!id))throw Error('search_field_scope_contains_local_books')
    // No legacy fallback: an unsplit index cannot answer a field-scoped query.
    const page=await abortableSearch(this.v2.searchSeparated(query,scope,binding,offset,limit,sourceIds as string[]|undefined,signal),signal)
    signal?.throwIfAborted()
    return{...page,offset,limit,unavailableBookIds:[],pendingBookIds:[]}
  }
  private manifest?:Promise<ShamelaSearchManifest>; private v2ScopeIds=new WeakMap<string[],{sourceIds:string[];invalid:string[]}>(); private routing?:Promise<RoutingManifest>; private routeBuckets=new Map<string,Promise<Map<string,string[]>>>(); private loaded=new Set<string>(); private pending=new Map<string,(r:SearchWorkerResponse)=>void>(); private serial=0;private readonly v2:ShamelaSearchV2Client
  constructor(private readonly worker:WorkerPort,private readonly fetcher:typeof fetch=(input,init)=>globalThis.fetch(input,init),v2Fetcher:typeof fetch=fetcher){this.v2=new ShamelaSearchV2Client(v2Fetcher);worker.addEventListener('message',e=>{const done=this.pending.get(e.data.requestId);if(done){this.pending.delete(e.data.requestId);done(e.data)}})}
    async searchCompleteV2(query:string,offset=0,limit=40,bookIds?:string[],signal?:AbortSignal):Promise<ShamelaSearchPage>{if(signal?.aborted)throw new DOMException('Search superseded','AbortError');let compiled=bookIds?this.v2ScopeIds.get(bookIds):undefined;if(bookIds&&!compiled){const mapped=bookIds.map(shamelaSourceBookId);compiled={sourceIds:mapped.filter((x):x is string=>Boolean(x)),invalid:bookIds.filter((_,index)=>!mapped[index])};this.v2ScopeIds.set(bookIds,compiled)}const invalid=compiled?.invalid??[],sourceIds=compiled?.sourceIds;try{const page=await withLocalV2Deadline(this.v2.search(query,offset,limit,sourceIds),signal);if(signal?.aborted)throw new DOMException('Search superseded','AbortError');return{total:page.total,offset,limit,hits:page.hits,unavailableBookIds:invalid,pendingBookIds:[],coverageComplete:page.coverageComplete&&invalid.length===0&&page.indexedBooks===8594}}catch(error){if(this.v2.hasSourceRecovery||signal?.aborted||error instanceof DOMException&&error.name==='AbortError')throw error;return this.search(query,offset,limit,bookIds,signal,true)}}
    async searchExhaustiveV2(query:string,offset=0,limit=40,bookIds?:string[],signal?:AbortSignal):Promise<ShamelaSearchPage>{if(signal?.aborted)throw new DOMException('Search superseded','AbortError');let compiled=bookIds?this.v2ScopeIds.get(bookIds):undefined;if(bookIds&&!compiled){const mapped=bookIds.map(shamelaSourceBookId);compiled={sourceIds:mapped.filter((x):x is string=>Boolean(x)),invalid:bookIds.filter((_,index)=>!mapped[index])};this.v2ScopeIds.set(bookIds,compiled)}const invalid=compiled?.invalid??[],sourceIds=compiled?.sourceIds;try{const page=await withLocalV2Deadline(this.v2.searchComplete(query,offset,limit,sourceIds),signal);if(signal?.aborted)throw new DOMException('Search superseded','AbortError');return{total:page.total,offset,limit,hits:page.hits,unavailableBookIds:invalid,pendingBookIds:[],coverageComplete:page.coverageComplete&&invalid.length===0&&page.indexedBooks===8594}}catch(error){if(this.v2.hasSourceRecovery||signal?.aborted||error instanceof DOMException&&error.name==='AbortError')throw error;return this.search(query,offset,limit,bookIds,signal,true)}}
  private request(request:WorkerCommand,signal?:AbortSignal):Promise<SearchWorkerResponse>{
    if(signal?.aborted)return Promise.reject(new DOMException('Search superseded','AbortError'))
    const requestId=`shamela-search-${++this.serial}`
    return new Promise((resolve,reject)=>{
      const cleanup=()=>{clearTimeout(timer);signal?.removeEventListener('abort',abort);this.pending.delete(requestId)}
      const abort=()=>{cleanup();reject(new DOMException('Search superseded','AbortError'))}
      const timer=setTimeout(()=>{cleanup();reject(new Error('shamela_search_worker_timeout'))},10_000)
      signal?.addEventListener('abort',abort,{once:true})
      this.pending.set(requestId,response=>{cleanup();resolve(response)})
      try{this.worker.postMessage({...request,requestId} as SearchWorkerRequest)}catch(error){cleanup();reject(new Error('shamela_search_worker_post_failed',{cause:error}))}
    })
  }
  private async getManifest(){this.manifest??=(async()=>{const r=await this.fetcher(`${ROOT}manifest.json`);if(!r.ok)throw new Error('shamela_search_manifest_unavailable');return r.json() as Promise<ShamelaSearchManifest>})();const pending=this.manifest;try{return await pending}catch(error){if(this.manifest===pending)delete this.manifest;throw error}}
  private async getRouting(manifest:ShamelaSearchManifest){if(!manifest.routing)return undefined;this.routing??=(async()=>{const r=await this.fetcher(`${ROOT}${manifest.routing!.manifest}`);if(!r.ok)throw new Error('shamela_search_routing_unavailable');return r.json() as Promise<RoutingManifest>})();return this.routing}
  private routeBucket(path:string){let cached=this.routeBuckets.get(path);if(!cached){cached=(async()=>{const r=await this.fetcher(`${ROOT}${path}`);if(!r.ok)throw new Error('shamela_search_route_bucket_unavailable');const value=await r.json() as {entries:Array<[string,string[]]>};return new Map(value.entries)})();this.routeBuckets.set(path,cached)}return cached}
  private async routedEntries(query:string,manifest:ShamelaSearchManifest){const routing=await this.getRouting(manifest);if(!routing)return undefined;const grams=queryGrams(query);if(!grams.length)return undefined;const global=await Promise.all(grams.map(async gram=>({gram,map:await this.routeBucket(routing.globalPattern.replace('{bucket}',bucketFor(gram,routing.bucketCount)))})));const batches=intersectSets(global.map(({gram,map})=>new Set(map.get(gram)??[]))),ids=new Set<string>();for(const batch of batches){const maps=await Promise.all(grams.map(gram=>this.routeBucket(routing.batchPattern.replace('{batch}',batch).replace('{bucket}',bucketFor(gram,routing.bucketCount)))));for(const id of intersectSets(maps.map((map,index)=>new Set(map.get(grams[index]!)??[]))))ids.add(id)}return manifest.shards.filter(entry=>ids.has(entry.id)).sort((a,b)=>a.byteLength-b.byteLength||a.id.localeCompare(b.id))}
  private async load(entry:ShamelaSearchManifest['shards'][number],signal:AbortSignal){if(this.loaded.has(entry.id))return;const r=await this.fetcher(`${ROOT}${entry.file}`,{signal});if(!r.ok)throw new Error('shamela_search_shard_unavailable');const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.byteLength!==entry.byteLength||await digest(bytes)!==entry.sha256)throw new Error('shamela_search_shard_integrity');const response=await this.request({type:'restore',shard:JSON.parse(new TextDecoder().decode(bytes)) as SerializedSearchShard},signal);if(!response.ok)throw new Error(response.error);this.loaded.add(entry.id)}
  async search(query:string,offset=0,limit=40,bookIds?:string[],signal?:AbortSignal,skipV2=false):Promise<ShamelaSearchPage>{
    if(signal?.aborted)throw new DOMException('Search superseded','AbortError')
    if(!skipV2&&!bookIds?.length){try{const page=await abortableSearch(this.v2.search(query,offset,limit),signal);return{total:page.total,offset,limit,hits:page.hits,unavailableBookIds:[],pendingBookIds:[],coverageComplete:page.coverageComplete}}catch(error){if(this.v2.hasSourceRecovery||signal?.aborted)throw error}}
    const controller=new AbortController(),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true})
    let timedOut=false
    const timer=setTimeout(()=>{timedOut=true;controller.abort()},30_000)
    try{return await abortableSearch(this.searchFallback(query,offset,limit,bookIds,controller.signal),controller.signal)}
    catch(error){if(timedOut){delete this.manifest;delete this.routing;this.routeBuckets.clear();throw new Error('shamela_search_fallback_timeout',{cause:error})}throw error}
    finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);controller.abort()}
  }
  private async searchFallback(query:string,offset:number,limit:number,bookIds:string[]|undefined,signal:AbortSignal):Promise<ShamelaSearchPage>{const active=()=>{if(signal.aborted)throw new DOMException('Search superseded','AbortError')};active();const manifest=await this.getManifest();active();const wanted=bookIds?.length?new Set(bookIds.map(shamelaSourceBookId).filter((x):x is string=>Boolean(x))):undefined;let routed:ShamelaSearchManifest['shards']|undefined;try{if(!wanted||wanted.size>64)routed=await this.routedEntries(query,manifest)}catch(error){if(signal.aborted)throw error;if(wanted&&wanted.size>64)throw new Error('shamela_search_routing_failed',{cause:error});routed=undefined}active();const entries=(routed??manifest.shards).filter(x=>!wanted||wanted.has(x.bookId)),manifestIds=new Set(manifest.shards.map(x=>x.bookId)),unavailableBookIds=new Set<string>(wanted?[...wanted].filter(id=>!manifestIds.has(id)):[]),summaries:Array<{entry:ShamelaSearchManifest['shards'][number];total:number}>=[];let cursor=0;
    // لا نحجب أول نتيجة بتنزيل آلاف الشاردات. نفحص أفواجًا صغيرة مرتبة، ثم
    // نصرّح بالتغطية المتبقية بدل إظهار «لا نتائج» كاذبة. الاستدعاء المقيد
    // بكتاب واحد يبقى كاملاً، وصفحات لاحقة تتابع من الشاردات المحملة.
    const target=Math.max(1,offset+limit),bounded=(routed===undefined&&(!wanted||wanted.size>64))||Boolean(wanted&&wanted.size>64);
    while(cursor<entries.length){active();const cohort=entries.slice(cursor,cursor+(bounded?1:64)),settled=await Promise.allSettled(cohort.map(async entry=>{active();await this.load(entry,signal);active();const response=await this.request({type:'search',shardId:entry.id,query,offset:0,limit:1},signal);if(!response.ok)throw new Error(response.error);return{entry,total:(response.value as SearchPage).total}}));active();settled.forEach((result,index)=>{if(result.status==='fulfilled')summaries.push(result.value);else{if(workerFailure(result.reason))throw result.reason;unavailableBookIds.add(cohort[index]!.bookId)}});cursor+=cohort.length;const found=summaries.reduce((n,x)=>n+x.total,0);if(bounded&&found>=target)break}
    if(!summaries.length&&unavailableBookIds.size)throw new Error('shamela_search_fallback_unavailable')
    const total=summaries.reduce((n,x)=>n+x.total,0),hits:SearchHit[]=[];let skipped=0,remaining=Math.max(0,limit);for(const summary of summaries){if(remaining===0)break;if(offset>=skipped+summary.total){skipped+=summary.total;continue}let local=Math.max(0,offset-skipped);while(local<summary.total&&remaining>0){const take=Math.min(500,remaining);try{const response=await this.request({type:'search',shardId:summary.entry.id,query,offset:local,limit:take},signal);if(!response.ok)throw new Error(response.error);const page=response.value as SearchPage;hits.push(...page.hits);local+=page.hits.length;remaining-=page.hits.length;if(!page.hits.length)break}catch(error){active();if(workerFailure(error))throw error;unavailableBookIds.add(summary.entry.bookId);break}}skipped+=summary.total}const pendingBookIds=[...new Set(entries.slice(cursor).map(x=>x.bookId))];return{total,offset,limit,hits,unavailableBookIds:[...unavailableBookIds],pendingBookIds,coverageComplete:pendingBookIds.length===0&&unavailableBookIds.size===0}}
}
let singleton:ShamelaSearchClient|undefined
export function shamelaSearchClient(){singleton??=new ShamelaSearchClient(new Worker(new URL('./shamela_search.worker.ts',import.meta.url),{type:'module'}),((input)=>{const url=String(input),path=url.startsWith(ROOT)?url.slice(ROOT.length):url;return fetchPagesDataAsset('search',path,url)}) as typeof fetch,((input,init)=>globalThis.fetch(input,init)) as typeof fetch);return singleton}
