import{unzipSync}from"fflate";
export interface ArchiveIntakeLimits{maxBytes:number;maxEntries:number;maxExpandedBytes:number;maxCompressionRatio:number}
export interface PdfIntakePolicy{maxBytes:number;maxObjects:number;maxDeclaredStreamBytes:number}
export interface BokIntakePolicy extends ArchiveIntakeLimits{maxDatabaseBytes:number}
export interface EpubIntakePolicy extends ArchiveIntakeLimits{maxMarkupBytes:number}
export interface TextIntakePolicy{maxBytes:number;maxCodePoints:number;maxLineCodePoints:number}
export type MultiFormatIntakeReason="size_limit"|"invalid_signature"|"truncated_pdf"|"pdf_object_limit"|"pdf_stream_limit"|"pdf_active_content"|"pdf_embedded_file"|"pdf_external_action"|"invalid_zip"|"unsafe_entry_path"|"encrypted_entry"|"entry_limit"|"expanded_size_limit"|"compression_ratio_limit"|"missing_epub_part"|"invalid_epub_mimetype"|"epub_active_content"|"epub_external_reference"|"bok_active_content"|"bok_payload_missing"|"invalid_text_encoding"|"nul_character"|"text_codepoint_limit"|"text_line_limit";
export type MultiFormatIntakeResult={kind:"allow";encoding?:"utf-8"|"utf-16le"|"utf-16be";container?:"database"|"archive"}|{kind:"quarantine"|"reject";reason:MultiFormatIntakeReason};
const ascii=new TextDecoder("latin1");
function isStandardJet(bytes:Uint8Array){return starts(bytes,[0,1,0,0])&&ascii.decode(bytes.subarray(4,32)).startsWith("Standard Jet DB")}
export function validatePdfIntake(bytes:Uint8Array,p:PdfIntakePolicy):MultiFormatIntakeResult{positive(p);if(bytes.byteLength>p.maxBytes)return reject("size_limit");const s=ascii.decode(bytes);if(!s.startsWith("%PDF-"))return reject("invalid_signature");if(!/%%EOF\s*$/.test(s))return reject("truncated_pdf");if((s.match(/\b\d+\s+\d+\s+obj\b/g)??[]).length>p.maxObjects)return reject("pdf_object_limit");for(const m of s.matchAll(/\/Length\s+(\d+)/g))if(Number(m[1])>p.maxDeclaredStreamBytes)return reject("pdf_stream_limit");const structure=s.replace(/\bstream\r?\n[\s\S]*?\bendstream\b/g,"stream endstream");if(/\/(JavaScript|JS|Launch)\b/i.test(structure))return quarantine("pdf_active_content");if(/\/(EmbeddedFile|Filespec)\b/i.test(structure))return quarantine("pdf_embedded_file");if(/\/(URI|GoToR|SubmitForm|ImportData)\b/i.test(structure))return quarantine("pdf_external_action");return{kind:"allow"}}
export function validateBokIntake(bytes:Uint8Array,p:BokIntakePolicy):MultiFormatIntakeResult{archivePolicy(p);if(bytes.byteLength>Math.min(p.maxBytes,p.maxDatabaseBytes))return reject("size_limit");if(starts(bytes,[0x53,0x51,0x4c,0x69,0x74,0x65,0x20,0x66,0x6f,0x72,0x6d,0x61,0x74,0x20,0x33,0]))return suspiciousDatabase(bytes)?quarantine("bok_active_content"):{kind:"allow",container:"database"};if(starts(bytes,[0xd0,0xcf,0x11,0xe0,0xa1,0xb1,0x1a,0xe1])||isStandardJet(bytes))return suspiciousDatabase(bytes)?quarantine("bok_active_content"):{kind:"allow",container:"database"};const meta=zipCentral(bytes,p);if("kind"in meta)return meta;let files:Record<string,Uint8Array>;try{files=unzipSync(bytes)}catch{return reject("invalid_zip")}const names=Object.keys(files);if(!names.some(n=>/\.(bok|db|sqlite|mdb)$/i.test(n)))return reject("bok_payload_missing");if(Object.values(files).some(suspiciousDatabase))return quarantine("bok_active_content");return{kind:"allow",container:"archive"}}
export function validateEpubIntake(bytes:Uint8Array,p:EpubIntakePolicy):MultiFormatIntakeResult{archivePolicy(p);if(bytes.byteLength>p.maxBytes)return reject("size_limit");const meta=zipCentral(bytes,p);if("kind"in meta)return meta;let files:Record<string,Uint8Array>;try{files=unzipSync(bytes)}catch{return reject("invalid_zip")}if(!files.mimetype||!files["META-INF/container.xml"])return reject("missing_epub_part");if(new TextDecoder().decode(files.mimetype).trim()!=="application/epub+zip")return reject("invalid_epub_mimetype");for(const[name,value]of Object.entries(files)){if(!/\.(xhtml|html|htm|svg|xml|css)$/i.test(name))continue;if(value.byteLength>p.maxMarkupBytes)return reject("expanded_size_limit");const text=new TextDecoder().decode(value);if(/<\s*(script|form|iframe|object|embed)\b|\son\w+\s*=/i.test(text))return quarantine("epub_active_content");if(/(?:src|href|url)\s*[:=(]\s*["']?\s*(?:https?:|\/\/)/i.test(text))return quarantine("epub_external_reference")}return{kind:"allow",container:"archive"}}
export function validateTextIntake(bytes:Uint8Array,p:TextIntakePolicy):MultiFormatIntakeResult{positive(p);if(bytes.byteLength>p.maxBytes)return reject("size_limit");let encoding:"utf-8"|"utf-16le"|"utf-16be"="utf-8",offset=0;if(starts(bytes,[0xef,0xbb,0xbf]))offset=3;else if(starts(bytes,[0xff,0xfe])){encoding="utf-16le";offset=2}else if(starts(bytes,[0xfe,0xff])){encoding="utf-16be";offset=2}if(encoding!=="utf-8"&&(bytes.byteLength-offset)%2!==0)return reject("invalid_text_encoding");let text:string;try{const body=encoding==="utf-16be"?swap16(bytes.subarray(offset)):bytes.subarray(offset);text=new TextDecoder(encoding==="utf-16be"?"utf-16le":encoding,{fatal:true}).decode(body)}catch{return reject("invalid_text_encoding")}if(text.includes("\0"))return reject("nul_character");if([...text].length>p.maxCodePoints)return reject("text_codepoint_limit");if(text.split(/\r?\n/).some(line=>[...line].length>p.maxLineCodePoints))return reject("text_line_limit");return{kind:"allow",encoding}}
function zipCentral(bytes:Uint8Array,p:ArchiveIntakeLimits):{}|MultiFormatIntakeResult{const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),e=find(v);if(e<0||e+22>v.byteLength)return reject("invalid_zip");const comment=v.getUint16(e+20,true);if(e+22+comment!==v.byteLength||v.getUint16(e+4,true)!==0||v.getUint16(e+6,true)!==0)return reject("invalid_zip");const diskCount=v.getUint16(e+8,true),count=v.getUint16(e+10,true),size=v.getUint32(e+12,true),start=v.getUint32(e+16,true);if(diskCount!==count||start+size!==e)return reject("invalid_zip");if(count>p.maxEntries)return reject("entry_limit");let o=start,total=0;for(let i=0;i<count;i++){if(o+46>e||v.getUint32(o,true)!==0x02014b50)return reject("invalid_zip");const flags=v.getUint16(o+8,true),compressed=v.getUint32(o+20,true),raw=v.getUint32(o+24,true),nl=v.getUint16(o+28,true),xl=v.getUint16(o+30,true),cl=v.getUint16(o+32,true),next=o+46+nl+xl+cl;if(flags&1)return reject("encrypted_entry");if(next>e)return reject("invalid_zip");let name="";try{name=new TextDecoder("utf-8",{fatal:true}).decode(bytes.subarray(o+46,o+46+nl))}catch{return reject("invalid_zip")}if(!safe(name))return reject("unsafe_entry_path");total+=raw;if(total>p.maxExpandedBytes)return reject("expanded_size_limit");if(raw>0&&(compressed===0||raw/compressed>p.maxCompressionRatio))return reject("compression_ratio_limit");o=next}return o===e?{}:reject("invalid_zip")}
function suspiciousDatabase(bytes:Uint8Array){const s=ascii.decode(bytes);return isStandardJet(bytes)?false:/(?:vba|macro|load_extension|attach\s+database|shell\s*\()/i.test(s)}function starts(bytes:Uint8Array,sig:number[]){return sig.every((x,i)=>bytes[i]===x)}function find(v:DataView){for(let o=v.byteLength-22;o>=Math.max(0,v.byteLength-65557);o--)if(v.getUint32(o,true)===0x06054b50)return o;return-1}function safe(n:string){return!!n&&!n.includes("\\")&&!n.startsWith("/")&&!/^[A-Za-z]:/.test(n)&&!n.split("/").includes("..")}function reject(reason:MultiFormatIntakeReason){return{kind:"reject"as const,reason}}function quarantine(reason:MultiFormatIntakeReason){return{kind:"quarantine"as const,reason}}function positive<T extends object>(p:T){for(const[k,v]of Object.entries(p))if(typeof v!=="number"||!Number.isFinite(v)||v<=0)throw Error(`invalid ${k}`)}function archivePolicy(p:ArchiveIntakeLimits){positive(p)}function swap16(bytes:Uint8Array){const out=bytes.slice();for(let i=0;i<out.length;i+=2){const x=out[i]!;out[i]=out[i+1]!;out[i+1]=x}return out}
