import type{QuarantineRecord,RevisionHistorySnapshot,SyncAccountUsage,SyncDevice}from"./remote-api.js";import type{Etagged,SourceSyncHttpClient}from"./http-client.js";
export type SourceSyncIdentity={kind:"signedOut"}|{kind:"guest"}|{kind:"authenticated";userId:string};
export type SourceSyncPhase="signedOut"|"guest"|"localOnly"|"connecting"|"synced"|"offline"|"pending"|"conflict"|"quarantined"|"error";
export interface SourceSyncViewState{phase:SourceSyncPhase;uploadAllowed:boolean;activeDevice:SyncDevice|null;revision:RevisionHistorySnapshot|null;usage:SyncAccountUsage|null;pendingCount:number;conflictCount:number;quarantineCount:number;stale:boolean;errorCode:string|null}
type Snapshot={devices:SyncDevice[];revision:RevisionHistorySnapshot;usage:SyncAccountUsage;quarantine:QuarantineRecord[]};
export class SourceSyncSession{private snapshot:Snapshot|null=null;private etags:Partial<Record<keyof Snapshot,string|null>>={};constructor(private readonly api:Pick<SourceSyncHttpClient,"devices"|"revisions"|"usage"|"quarantineStatus">,private readonly bookId:string,private readonly deviceId:string,private readonly emit:(s:SourceSyncViewState)=>void=()=>{}){}start(identity:SourceSyncIdentity,signal?:AbortSignal){if(identity.kind==="signedOut")return this.out("signedOut",false);if(identity.kind==="guest")return this.out("guest",false);return this.connect(signal)}localOnly(){return this.out("localOnly",false)}async connect(signal?:AbortSignal){this.emit(this.view("connecting",false));try{const [devices,revision,usage,quarantine]=await Promise.all([this.api.devices(this.etags.devices??undefined,signal),this.api.revisions(this.bookId,this.etags.revision??undefined,signal),this.api.usage(this.etags.usage??undefined,signal),this.api.quarantineStatus(this.bookId,this.etags.quarantine??undefined,signal)]);this.snapshot={devices:this.merge("devices",devices),revision:this.merge("revision",revision),usage:this.merge("usage",usage),quarantine:this.merge("quarantine",quarantine)};const state=this.classify(false);this.emit(state);return state}catch(e){if(this.snapshot){const state=this.classify(true);this.emit(state);return state}const state=this.view("error",false,e instanceof Error?e.message:"sync_error");this.emit(state);return state}}
 private merge<K extends keyof Snapshot>(key:K,next:Etagged<Snapshot[K]>){if(next.notModified){if(!this.snapshot)throw Error("not_modified_without_cache");return this.snapshot[key]}this.etags[key]=next.etag;return next.value}
 private classify(stale:boolean){const s=this.snapshot!,conflictCount=s.revision.revisions.filter(r=>r.status==="conflicted").length,quarantineCount=s.quarantine.filter(q=>q.status==="pending").length,pendingCount=(s.revision.desiredRevisionId?1:0)+s.revision.revisions.filter(r=>["pending","stabilizing","ready-for-upload","uploaded","building"].includes(r.status)).length,activeDevice=s.devices.find(d=>d.deviceId===this.deviceId&&d.revokedAt===null)??null,phase:SourceSyncPhase=stale?"offline":quarantineCount?"quarantined":conflictCount?"conflict":pendingCount?"pending":"synced";return{phase,uploadAllowed:activeDevice!==null,activeDevice,revision:s.revision,usage:s.usage,pendingCount,conflictCount,quarantineCount,stale,errorCode:null}}
 private view(phase:SourceSyncPhase,uploadAllowed:boolean,errorCode:string|null=null):SourceSyncViewState{return{phase,uploadAllowed,activeDevice:null,revision:null,usage:null,pendingCount:0,conflictCount:0,quarantineCount:0,stale:false,errorCode}}
 private out(phase:SourceSyncPhase,uploadAllowed:boolean){const state=this.view(phase,uploadAllowed);this.emit(state);return state}
}
