import { writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import type { AlignmentReport } from "./types.js";
import { reportHash } from "./report.js";
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export async function writeReviewHtml(path: string, report: AlignmentReport): Promise<void> {
  const pdfUrl = pathToFileURL(report.inputs.pdf.path).href;
  const rows = report.matches.map(m => `<article class="card ${m.status}"><header>صفحة PDF ${m.pdfPage} ← فقرة ${m.paragraphIndex ?? "؟"} <b>${Math.round(m.confidence*100)}%</b></header><div class="cols"><section><h3>الأصل المطبوع</h3><iframe loading="lazy" src="${esc(pdfUrl)}#page=${m.pdfPage}&view=FitH"></iframe><details><summary>النص المستخرج</summary><p>${esc(m.pdfStart)}</p><hr><p>${esc(m.pdfEnd)}</p></details></section><section><h3>موضع Word المرشح</h3><p>${esc(m.docxText)}</p><label><input type="radio" name="p${m.pdfPage}" value="accept"> قبول</label><label><input type="radio" name="p${m.pdfPage}" value="reject"> رفض</label><label>فقرة بديلة <input class="idx" type="number" data-page="${m.pdfPage}" value="${m.paragraphIndex ?? ""}"></label></section></div></article>`).join("\n");
  const html = `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>مراجعة محاذاة الكتاب</title><style>body{font-family:Tahoma,Arial;background:#f4f1ea;color:#201b16;margin:0}main{max-width:1400px;margin:auto;padding:24px}.summary,.card{background:white;border:1px solid #d8d0c5;border-radius:12px;padding:16px;margin:12px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card.needs_review{border-right:7px solid #d58b16}.card.auto{border-right:7px solid #22845a}header{font-size:18px}p{line-height:1.9}iframe{width:100%;height:620px;border:1px solid #ddd}label{margin:8px;display:inline-block}button{padding:10px 18px}@media(max-width:750px){.cols{grid-template-columns:1fr}iframe{height:450px}}</style><main><div class="summary"><h1>مراجعة محاذاة PDF مع Word</h1><p>تغطية مقاسة ${Math.round(report.metrics.measuredCoverage*100)}% — تلقائي ${report.metrics.auto} — يحتاج مراجعة ${report.metrics.needsReview}. لا يعني ذلك تطابقًا كاملًا.</p><button id="save">تنزيل ملف الاعتمادات</button></div>${rows}</main><script>document.querySelector('#save').onclick=()=>{const decisions=[];document.querySelectorAll('.card').forEach((c,i)=>{const page=i+1,a=c.querySelector('input[type=radio]:checked'),idx=c.querySelector('.idx');if(a)decisions.push({pdfPage:page,action:a.value,paragraphIndex:Number(idx.value)})});const data={reportSha256:${JSON.stringify(reportHash(report))},decisions};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='approvals.json';a.click()};</script></html>`;
  await writeFile(path, html, "utf8");
}
